objects/Affiliation__c.object
<CustomObject>
    <description>&lt;AFF&gt; - Provide account to account relationship</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Affiliations</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Solicitor</fullName>
                </value>
                <value>
                    <fullName>Franchisee</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Leasing Agent</fullName>
                </value>
                <value>
                    <fullName>Leases Sent To</fullName>
                </value>
                <value>
                    <fullName>Company with Personal Guarantees</fullName>
                </value>
                <value>
                    <fullName>Company with Parent Guarantees</fullName>
                </value>
                <value>
                    <fullName>Personal Guarantees by Franchisee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AFF-{0000}</displayFormat>
        <label>Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>At Risk</fullName>
                </value>
                <value>
                    <fullName>Held</fullName>
                </value>
                <value>
                    <fullName>Trading</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SpaceType</valueSetName>
        </valueSet>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/SpaceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Shop</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Kiosk</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Office Suite</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Store Room</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Seating</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sundry Property</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Garage / Parking</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sundry</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Space Bank</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Common Mall</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>Re-design</label>
    </customValue>
    <customValue>
        <fullName>Seating License</fullName>
        <isActive>false</isActive>
        <label>Seating License</label>
    </customValue>
    <customValue>
        <fullName>Sundry Site</fullName>
        <isActive>false</isActive>
        <label>Sundry Site</label>
    </customValue>
    <masterLabel>Space Type</masterLabel>
</GlobalValueSet>

classes/AffiliationBLTest.cls
/**
 * @author:			Kyle Tan
 * @desc:			test class for AffiliationBL
 **/
@isTest
private class AffiliationBLTest {

    @testSetup
    private static void testSetup() {
        Map<String, Schema.RecordTypeInfo> accountRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(Constants.ACCOUNT);

        //Create Price Book
        List<Pricebook2> priceBookList = new List<Pricebook2>();
        priceBookList = TestDataFactory.createPricebook(1);
        database.insert(priceBookList);
        
        //Create Property
        List<Property__c> propertyList = new List<Property__c>();
        propertyList = TestDataFactory.createProperty(1, priceBookList[0]);
        database.insert(propertyList);
        
        //Create Space
        List<Space__c> spaceList = new List<Space__c>();
        spaceList = TestDataFactory.createSpace(1, propertyList[0]);
        database.insert(spaceList);
        
        //Create Account
        List<Account> accountList = new List<Account>();
        accountList = TestDataFactory.createAccountBulk(5, propertyList[0].Id, accountRecordTypeMapByName.get(Constants.PROPERTY_BASED).getRecordTypeId());
        database.insert(accountList);
        
        //Create Contact
        List<Contact> contactList = new List<Contact>();
        contactList.add(TestDataFactory.createContact('Test Name', accountList[0]));
        database.insert(contactList);
        
        //Create Affiliation
        List<Affiliation__c> affiliationList = new List<Affiliation__c>();
        affiliationList.add(TestDataFactory.createAffiliation(accountList[0], 
                                                              accountList[1], 
                                                              contactList[0], 
                                                              Constants.COMP_PERSONAL_GUARANTEES, 
                                                              Constants.CURRENT));
        database.insert(affiliationList);
        
        //Create Opportunity
        List<Opportunity> opportunityList = new List<Opportunity>();
        opportunityList = TestDataFactory.createOpportunity(5, accountList[0], propertyList[0], spaceList[0]);
        database.insert(opportunityList);
        
        //Create Opportunity Contact Role
        List<OpportunityContactRole> oppContactRoleList = new List<OpportunityContactRole>();
        oppContactRoleList.add(TestDataFactory.createOpportunityContactRole(opportunityList[0], contactList[0], 'Influencer'));
        database.insert(oppContactRoleList);
    }
    
    /**
     * @author:			Kyle Tan
     **/
    @isTest
    private static void createOpportunityConRolesTest() {
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SCG_SYS_ADM LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        List<OpportunityContactRole> oppContactRoleList  = new List<OpportunityContactRole>();
        List<Affiliation__c> affiliationList = new List<Affiliation__c>([SELECT Id, Contact__c, Status__c, Type__c FROM Affiliation__c]);
        List<Opportunity> opportunityList = new List<Opportunity>([SELECT Id FROM Opportunity]);
        system.runAs(testUser) {
            test.startTest();
            oppContactRoleList = AffiliationBL.createOpportunityConRoles(affiliationList[0], opportunityList);
            test.stopTest();
        }
        system.assertEquals(5, oppContactRoleList.size());
    }
    
    /**
     * @author:			Kyle Tan
     **/
    @isTest
    private static void updateNumberofGuarantorsTest() {
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SCG_SYS_ADM LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        List<Opportunity> returnOppList = new List<Opportunity>();
        List<Affiliation__c> affiliationList = new List<Affiliation__c>([SELECT Id, Contact__c, Status__c, Type__c FROM Affiliation__c]);
        List<Opportunity> opportunityList = new List<Opportunity>([SELECT Id, NumberofGuarantors__c FROM Opportunity]);
        system.runAs(testUser) {
            test.startTest();
            opportunityList[0].NumberofGuarantors__c = 0;
            returnOppList = AffiliationBL.updateNumberofGuarantors(affiliationList[0], opportunityList);
            test.stopTest();
        }
        for(Opportunity oppRec :returnOppList) {
            if(oppRec.Id == opportunityList[0].Id) {
                system.assertEquals(1, oppRec.NumberofGuarantors__c);
            } else {
                system.assertEquals(2, oppRec.NumberofGuarantors__c);
            }
        }
    }
    
    /**
     * @author:			Kyle Tan
     **/
    @isTest
    private static void deleteContactRoleTest() {
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SCG_SYS_ADM LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        List<OpportunityContactRole> returnOppContactRoleList  = new List<OpportunityContactRole>();
        List<Affiliation__c> affiliationList = new List<Affiliation__c>([SELECT Id, Contact__c, Status__c, Type__c FROM Affiliation__c]);
        List<OpportunityContactRole> oppContactRoleList  = new List<OpportunityContactRole>([SELECT Id, ContactId FROM OpportunityContactRole]);
        system.runAs(testUser) {
            test.startTest();
            returnOppContactRoleList = AffiliationBL.deleteContactRole(affiliationList[0], oppContactRoleList);
            test.stopTest();
        }
        system.assertEquals(6, returnOppContactRoleList.size());
    }
    
    /**
     * @author:			Kyle Tan
     **/
    @isTest
    private static void reduceNumberOfGuarantorsTest() {
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SCG_SYS_ADM LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        List<Opportunity> returnOppList = new List<Opportunity>();
        List<Affiliation__c> affiliationList = new List<Affiliation__c>([SELECT Id, Contact__c, Status__c, Type__c FROM Affiliation__c]);
        List<OpportunityContactRole> oppContactRoleList  = new List<OpportunityContactRole>([SELECT Id, OpportunityId FROM OpportunityContactRole]);
        List<Opportunity> opportunityList = new List<Opportunity>([SELECT Id, NumberofGuarantors__c FROM Opportunity]);
        system.runAs(testUser) {
            test.startTest();
            returnOppList = AffiliationBL.reduceNumberOfGuarantors(affiliationList[0], oppContactRoleList, opportunityList);
            test.stopTest();
        }
        for(Opportunity oppRec :returnOppList) {
            system.assertEquals(0, oppRec.NumberofGuarantors__c);
        }
    }
}