objects/BillCode__c.object
<CustomObject>
    <description>&lt;BIC&gt;Bill Codes from JDE for product mapping</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BillCodeDescription__c</fullName>
        <label>Bill Code Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>BillCode__c</fullName>
        <description>JDE Bill code</description>
        <externalId>true</externalId>
        <inlineHelpText>JDE Bill code</inlineHelpText>
        <label>Bill Code</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Bill Code</label>
    <nameField>
        <displayFormat>BC-{000000}</displayFormat>
        <label>Bill Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bill Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>JDEPropertyNumber__c</fullName>
        <externalId>true</externalId>
        <label>JDE Property Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BillingCategory__c</fullName>
        <description>Billing category to identify the bill code.</description>
        <inlineHelpText>For Finance Use Only.</inlineHelpText>
        <label>Billing Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SpaceBillingCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Neel 03042018: Added</description>
        <label>Description</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DevelopmentType__c</fullName>
        <label>Development Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>DevelopmentImpacted__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Operational</fullName>
                    <default>true</default>
                    <label>Operational</label>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Mini Project</fullName>
                </value>
                <value>
                    <fullName>None Project</fullName>
                    <isActive>false</isActive>
                    <label>None Project</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LatestBudget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Latest Budget</label>
        <referenceTo>SpaceBudgetAndForecast__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Spaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LatestForecast__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Latest Forecast</label>
        <referenceTo>SpaceBudgetAndForecast__c</referenceTo>
        <relationshipLabel>Spaces (Latest Forecast)</relationshipLabel>
        <relationshipName>Spaces2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LatestJVBudget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Latest JV Budget</label>
        <referenceTo>SpaceBudgetAndForecast__c</referenceTo>
        <relationshipLabel>Spaces (Latest JV Budget)</relationshipLabel>
        <relationshipName>Spaces1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ReasonForChange__c</fullName>
        <inlineHelpText>This is applicable for reconfiguration area changes.</inlineHelpText>
        <label>Reason For Change</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ReconfiguredCurrentRentSemiGross__c</fullName>
        <label>Reconfigured Current Rent (Semi Gross)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ReconfiguredCurrentRent__c</fullName>
        <description>This field will hold the pro-rata rent based on Space Reconfiguration process</description>
        <label>Reconfigured Current Rent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RentableArea__c</fullName>
        <label>Rentable Area</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SpaceType</valueSetName>
        </valueSet>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SpaceBudgetAndForecast__c.object
<CustomObject>
    <description>&lt;SBF&gt; - Represents approved annualised amount for budget for CY and JV FY and forecast periods</description>
    <fields>
        <fullName>AnnualisedPVRentGross__c</fullName>
        <label>Annualised PV Rent (Gross)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AnnualisedPVRentNet__c</fullName>
        <label>Annualised PV Rent (Net)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AnnualisedPVRentSemiGross__c</fullName>
        <label>Annualised PV Rent (Semi Gross)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AnnualisedRentDecNet__c</fullName>
        <label>Annualised Rent (Dec) (Net)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AnnualisedRentDecSemiGross__c</fullName>
        <label>Annualised Rent (Dec) (Semi Gross)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AnnualisedRentJanNet__c</fullName>
        <label>Annualised Rent (Jan) (Net)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AnnualisedRentJanSemiGross__c</fullName>
        <label>Annualised Rent (Jan) (Semi Gross)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CapitalSiteEstablishment__c</fullName>
        <label>Capital (Site Establishment)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ModelType__c</fullName>
        <label>Model Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Budget</fullName>
                </value>
                <value>
                    <fullName>JV Budget</fullName>
                </value>
                <value>
                    <fullName>Forecast</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PromotionalAllowance__c</fullName>
        <label>Promotional Allowance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <formula>Space__r.Property__r.Name</formula>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipLabel>Space Budget and Forecast</relationshipLabel>
        <relationshipName>Space_Budget_and_Forecast</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Space Budget and Forecast</label>
    <nameField>
        <label>Space Budget and Forecast Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Space Budget and Forecast</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SpaceProduct__c.object
<CustomObject>
    <description>&lt;SPP&gt; - Represents a products delated to the Space where Space product values is different to property. This caters for space level outgoings eg. Council rates, Air Con</description>
    <fields>
        <fullName>Active__c</fullName>
        <description>Confirms that the Space Product can currently be used. This field is driven by the effective dates defined for this space product.</description>
        <formula>IF(ISBLANK(EffectiveToDate__c), 
IF(EffectiveFromDate__c &lt;= TODAY(),TRUE,FALSE), 
(AND(EffectiveFromDate__c &lt;= TODAY(), 
TODAY() &lt;= EffectiveToDate__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Confirms that the Space Product can currently be used. This field is driven by the effective dates defined for this space product.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CalculationMethod__c</fullName>
        <description>Drives the price calculation.</description>
        <label>Calculation Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>Percentage</fullName>
                </value>
                <value>
                    <fullName>PSM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Describes the product / service.</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EffectiveFromDate__c</fullName>
        <description>The Date from which this Product becomes or became available for use for any Opportunity related to the Space.</description>
        <label>Effective From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EffectiveToDate__c</fullName>
        <description>The Date until which this Product was or will remain available for use for any Opportunity related to the Space.</description>
        <label>Effective To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Percentage__c</fullName>
        <description>Store the applicable percentage value if the price is calculated based on a percentage (based on the selected &quot;Calculation Method&quot;)</description>
        <inlineHelpText>Provide a percentage if the calculation method is percentage.</inlineHelpText>
        <label>Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Product used for this Space Product.</description>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You can select only recoveries product.</errorMessage>
            <filterItems>
                <field>Product2.BillCode__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Product2.Family</field>
                <operation>equals</operation>
                <value>Recoveries</value>
            </filterItems>
            <filterItems>
                <field>Product2.EffectiveFromDate__c</field>
                <operation>notEqual</operation>
                <value>1/1/2018</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Space Products</relationshipLabel>
        <relationshipName>Space_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <description>The Property to which this Space Product applies. This field is defaulted based on the selected Space.</description>
        <formula>Space__r.Property__r.Name</formula>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <description>The Space to which the Space Product applies.</description>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipLabel>Space Products</relationshipLabel>
        <relationshipName>SpaceProducts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Space Product</label>
    <nameField>
        <displayFormat>SPP - {0000}</displayFormat>
        <label>Space Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Space Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/SpaceBillingCategory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>NR</fullName>
        <label>Non Retail</label>
    </customValue>
    <customValue>
        <fullName>PE</fullName>
        <label>External Precinct</label>
    </customValue>
    <customValue>
        <fullName>ATM</fullName>
    </customValue>
    <customValue>
        <fullName>EX</fullName>
        <label>Car Park - External</label>
    </customValue>
    <customValue>
        <fullName>PM</fullName>
        <label>Car Park - Permanent</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Car Park - Internal</label>
    </customValue>
    <customValue>
        <fullName>VL</fullName>
        <label>Car Park - Valet</label>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
        <default>true</default>
        <label>Not Applicable</label>
    </customValue>
    <description>Space Billing Category</description>
    <masterLabel>Space Billing Category</masterLabel>
</GlobalValueSet>

globalValueSets/SpaceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Shop</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Kiosk</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Office Suite</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Store Room</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Seating</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sundry Property</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Garage / Parking</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sundry</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Space Bank</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Common Mall</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>Re-design</label>
    </customValue>
    <customValue>
        <fullName>Seating License</fullName>
        <isActive>false</isActive>
        <label>Seating License</label>
    </customValue>
    <customValue>
        <fullName>Sundry Site</fullName>
        <isActive>false</isActive>
        <label>Sundry Site</label>
    </customValue>
    <masterLabel>Space Type</masterLabel>
</GlobalValueSet>

classes/SpaceManagementControllerTest.cls
@isTest
private class SpaceManagementControllerTest {
    @TestSetup private static void testSetup(){
        Map<String, Schema.RecordTypeInfo> spaceRecordTypeMap = RecordTypeUtil.getAllRecordTypesByName(Constants.SPACE);
        List<Pricebook2> priceBookList = new List<Pricebook2>();
		
        //Create Price Book
        priceBookList = TestDataFactory.createPricebook(1);
        database.insert(priceBookList);
        
        Property__c property = TestDataFactory.createProperty(1, priceBookList[0])[0];
        Database.insert(property);

        List<Space__c> spaceList = TestDataFactory.createSpace(5, property);
        Map<Id, Space__c> spaceMap = new Map<Id, Space__c>();
        for(Space__c space : spaceList){
            space.RentableArea__c = 40;
            space.DevelopmentType__c = null;
            space.ReconfiguredCurrentRent__c = 100000;
            space.ReconfiguredCurrentRentSemiGross__c = 50000;
            space.RecordTypeId = spaceRecordTypeMap.get(Constants.PROSPECTIVE_SPACE).getRecordTypeId();
            space.CurrencyIsoCode = 'AUD';
        }
        spaceList[4].billingCategory__c = Constants.SPACEBILLINGCATEGORY_NON_RETAIL; // --- additional code coverage; else statement is unreachable due to validation rule
        Database.insert(spaceList);

        spaceMap.putAll(spaceList);

        SpaceBudgetAndForecast__c spaceBudgetTemp;
        List<SpaceBudgetAndForecast__c> spaceBudgetList = new List<SpaceBudgetAndForecast__c>();

        Set<String> modelTypeSet = new Set<String>{
            Constants.BUDGET,
            Constants.JV_BUDGET,
            Constants.FORECAST
        };

        for(Space__c space : spaceList){
            for(String modelType : modelTypeSet){
                spaceBudgetTemp = TestDataFactory.createSpaceBudget(1, space)[0];
                spaceBudgetTemp.ModelType__c = modelType;
                spaceBudgetTemp.AnnualisedRentDecSemiGross__c = 250000;
                spaceBudgetTemp.AnnualisedRentDecNet__c = 250000;
                spaceBudgetTemp.AnnualisedRentJanSemiGross__c = 350000;
                spaceBudgetTemp.AnnualisedRentJanNet__c = 350000;
                spaceBudgetTemp.AnnualisedPVRentSemiGross__c = 150000;
                spaceBudgetTemp.AnnualisedPVRentNet__c = 150000;
                spaceBudgetTemp.AnnualisedPVRentGross__c = 150000;
                spaceBudgetTemp.PromotionalAllowance__c = 250000;
                spaceBudgetTemp.CapitalSiteEstablishment__c = 250000;

                spaceBudgetList.add(spaceBudgetTemp);
            }
        }

        Database.insert(spaceBudgetList);

        Space__c spaceTemp;
        for(SpaceBudgetAndForecast__c sBudget : spaceBudgetList){
            if(spaceMap.containsKey(sBudget.Space__c)){
                spaceTemp = spaceMap.get(sBudget.Space__c);
                if(Constants.BUDGET.equalsIgnoreCase(sBudget.ModelType__c)){
                    spaceTemp.LatestBudget__c = sBudget.Id;
                } else if(Constants.JV_BUDGET.equalsIgnoreCase(sBudget.ModelType__c)){
                    spaceTemp.LatestJVBudget__c = sBudget.Id;
                } else if(Constants.FORECAST.equalsIgnoreCase(sBudget.ModelType__c)){
                    spaceTemp.LatestForecast__c = sBudget.Id;
                }
            }
        }
		Billcode__c abc = new Billcode__c();
        abc.Active__c = true;
        abc.BillCode__c = 'ABC';
        abc.BillCodeDescription__c = 'abc';
        Database.insert(abc);
        Database.update(spaceMap.values());
        Product2 prodRec = new Product2();
        prodRec = TestDataFactory.createProduct('Test Name', 'Fam');
        prodRec.Family = 'Recoveries';
        prodRec.Billcode__c = abc.Id;
        prodRec.OutgoingsCategory__c = 'Land Tax';			// --- code coverage: 'Cleaning' is not included in Label.SpaceReconfig_OutgoingCategory
        prodRec.EffectiveFromDate__c = Date.today();
        database.insert(prodRec);
        
        List<SpaceProduct__c> spaceProdList = new List<SpaceProduct__c>();
        spaceProdList = TestDataFactory.createSpaceProduct(1, spaceTemp, '', prodRec);
        spaceProdList[0].CalculationMethod__c = 'Fixed';
        spaceProdList[0].CurrencyIsoCode = 'AUD';
        database.insert(spaceProdList);
    }

    public static testMethod void testGetSpaces(){
        SpaceManagementController.Response res;
        SpaceManagementController.SpaceWrapper spaceWrap;
        Property__c property = [SELECT Id, Name FROM Property__c];

        Test.startTest();
            res = SpaceManagementController.getSpaces(property.Id);
        Test.stopTest();

        system.assertEquals(res.status, 'SUCCESS');
        spaceWrap = (SpaceManagementController.SpaceWrapper) JSON.deserialize(res.returnValue, SpaceManagementController.SpaceWrapper.class);
        system.assertEquals(5, spaceWrap.spaceList.size());
    }

    public static testMethod void testCreateSpacesMerge(){
        Property__c property = [SELECT Id,Property__c.JDEPropertyNumber__c,  Name FROM Property__c];
        String sourceSpaceListJSON;
        String newSpaceListJSON;

        SpaceManagementController.Response res;
        res = SpaceManagementController.getSpaces(property.Id);
        SpaceManagementController.SpaceWrapper spaceWrap = (SpaceManagementController.SpaceWrapper) JSON.deserialize(res.returnValue, SpaceManagementController.SpaceWrapper.class);
        sourceSpaceListJSON = JSON.serialize(spaceWrap.spaceList);

        Space__c space = new Space__c();
        List<Space__c> newSpaceList = new List<Space__c>();

        space.Type__c = '2';
        space.Name = 'SP0001';
        space.RentableArea__c = 100;
        newSpaceList.add(space);

        space = new Space__c();
        space.Type__c = '2';
        space.Name = 'SP0002';
        space.RentableArea__c = 40;
        newSpaceList.add(space);

        space = new Space__c();
        space.Type__c = '20';
        space.Name = 'SP0003';
        space.RentableArea__c = 60;
        space.ReasonForChange__c = 'Lost Space';
        newSpaceList.add(space);

        newSpaceListJSON = JSON.serialize(newSpaceList);

        Test.startTest();
            SpaceManagementController.createSpaces(property, sourceSpaceListJSON, newSpaceListJSON, 'merge');
        Test.stopTest();
    }

    public static testMethod void testCreateSpacesSplit(){
        Property__c property = [SELECT Id, Name, Property__c.JDEPropertyNumber__c FROM Property__c];
        String sourceSpaceListJSON;
        String newSpaceListJSON;

        SpaceManagementController.Response res;
        res = SpaceManagementController.getSpaces(property.Id);
        SpaceManagementController.SpaceWrapper spaceWrap = (SpaceManagementController.SpaceWrapper) JSON.deserialize(res.returnValue, SpaceManagementController.SpaceWrapper.class);
        sourceSpaceListJSON = JSON.serialize(spaceWrap.spaceList);

        Space__c space = new Space__c();
        List<Space__c> newSpaceList = new List<Space__c>();

        space.Type__c = '2';
        space.Name = 'SP0001';
        space.RentableArea__c = 100;
        newSpaceList.add(space);

        space = new Space__c();
        space.Type__c = '2';
        space.Name = 'SP0002';
        space.RentableArea__c = 40;
        newSpaceList.add(space);

        space = new Space__c();
        space.Type__c = '20';
        space.Name = 'SP0003';
        space.RentableArea__c = 60;
        space.ReasonForChange__c = 'Lost Space';
        newSpaceList.add(space);

        newSpaceListJSON = JSON.serialize(newSpaceList);

        Test.startTest();
            SpaceManagementController.createSpaces(property, sourceSpaceListJSON, newSpaceListJSON, 'split');
        Test.stopTest();
    }

    public static testMethod void testCreateSpacesError(){
        Property__c property = [SELECT Id, Name, Property__c.JDEPropertyNumber__c FROM Property__c];
        String sourceSpaceListJSON;
        String newSpaceListJSON;

        SpaceManagementController.Response res;
        res = SpaceManagementController.getSpaces(property.Id);
        SpaceManagementController.SpaceWrapper spaceWrap = (SpaceManagementController.SpaceWrapper) JSON.deserialize(res.returnValue, SpaceManagementController.SpaceWrapper.class);
        sourceSpaceListJSON = JSON.serialize(spaceWrap.spaceList);

        Space__c space = new Space__c();
        List<Space__c> newSpaceList = new List<Space__c>();

        space.Type__c = '2';
        space.Name = 'SP00016';
        space.RentableArea__c = 100;
        newSpaceList.add(space);

        space = new Space__c();
        space.Type__c = '2';
        space.Name = 'SP000*';
        space.RentableArea__c = 100;
        newSpaceList.add(space);

        newSpaceListJSON = JSON.serialize(newSpaceList);

        Test.startTest();
            SpaceManagementController.createSpaces(property, sourceSpaceListJSON, newSpaceListJSON, 'split');
        Test.stopTest();
    }
    
    private static testMethod void createSpaceProductTest() {
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SCG_SYS_ADM LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        SpaceProduct__c spaceProdRec = new SpaceProduct__c();
        List<SpaceProduct__c> spaceProdList = new List<SpaceProduct__c>([SELECT Id, Description__c, CalculationMethod__c, 
                                                                         EffectiveFromDate__c, EffectiveToDate__c,CurrencyIsoCode, 
                                                                         Percentage__c, Product__c, ProductFamily__c, 
                                                                         SalesPrice__c 
                                                                         FROM SpaceProduct__c]);
        List<Space__c> spaceList = new List<Space__c>([SELECT Id FROM Space__c]);
        system.runAs(testUser) {
            test.startTest();
            spaceProdRec = SpaceManagementController.createSpaceProduct(spaceProdList[0], spaceList[0]);
            test.stopTest();
        }
    }
    
    private static testMethod void testHasUserAccess() {
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SCG_SYS_ADM LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        Boolean hasUserAccess;
        system.runAs(testUser) {
            test.startTest();
            hasUserAccess = SpaceManagementController.hasUserAccess();
            test.stopTest();
        }
        System.assert(hasUserAccess);
    }
    
    private static testMethod void testCreateChildSpaceProduct() {
        Property__c property = [SELECT Id,Property__c.JDEPropertyNumber__c,  Name FROM Property__c];

        List<Space__c> sourceSpaceList = new List<Space__c>();
        List<Space__c> newSpaceList = new List<Space__c>();
        Set<Id> sourceSpaceIdSet = new Set<Id>();

        SpaceManagementController.Response res;
        res = SpaceManagementController.getSpaces(property.Id);
        SpaceManagementController.SpaceWrapper spaceWrap = (SpaceManagementController.SpaceWrapper) JSON.deserialize(res.returnValue, SpaceManagementController.SpaceWrapper.class);
        sourceSpaceList = spaceWrap.spaceList;

        
        for(Space__c sourceSpace : sourceSpaceList){
            sourceSpaceIdSet.add(sourceSpace.Id);
        }
        
        Space__c space = new Space__c();
        
        space.Type__c = '2';
        space.Name = 'SP0001';
        space.RentableArea__c = 100;
        newSpaceList.add(space);

        space = new Space__c();
        space.Type__c = '2';
        space.Name = 'SP0002';
        space.RentableArea__c = 40;
        newSpaceList.add(space);

        space = new Space__c();
        space.Type__c = '20';
        space.Name = 'SP0003';
        space.RentableArea__c = 60;
        space.ReasonForChange__c = 'Lost Space';
        newSpaceList.add(space);

        Test.startTest();
            SpaceManagementController.createChildSpaceProduct(sourceSpaceIdSet, newSpaceList);
        Test.stopTest();
    }
    
    private static testMethod void testGenerateChildSpaceProductsForOutgoings(){
        Property__c property = [SELECT Id,Property__c.JDEPropertyNumber__c,  Name FROM Property__c];

        List<Space__c> sourceSpaceList = new List<Space__c>();
        List<Space__c> newSpaceList = new List<Space__c>();
        Set<Id> sourceSpaceIdSet = new Set<Id>();

        SpaceManagementController.Response res;
        res = SpaceManagementController.getSpaces(property.Id);
        SpaceManagementController.SpaceWrapper spaceWrap = (SpaceManagementController.SpaceWrapper) JSON.deserialize(res.returnValue, SpaceManagementController.SpaceWrapper.class);
        sourceSpaceList = spaceWrap.spaceList;

        
        for(Space__c sourceSpace : sourceSpaceList){
            sourceSpaceIdSet.add(sourceSpace.Id);
        }
        
        Space__c space = new Space__c();
        
        space.Type__c = '2';
        space.Name = 'SP0001';
        space.RentableArea__c = 100;
        space.CurrencyIsoCode = 'AUD';
        newSpaceList.add(space);

        space = new Space__c();
        space.Type__c = '2';
        space.Name = 'SP0002';
        space.RentableArea__c = 40;
        space.CurrencyIsoCode = 'AUD';
        newSpaceList.add(space);

        space = new Space__c();
        space.Type__c = '20';
        space.Name = 'SP0003';
        space.RentableArea__c = 60;
        space.ReasonForChange__c = 'Lost Space';
        space.CurrencyIsoCode = 'AUD';
        newSpaceList.add(space);

        Test.startTest();
            SpaceManagementController.generateChildSpaceProductsForOutgoings(9999,sourceSpaceIdSet, newSpaceList);
        Test.stopTest();
    }
    
    private static testMethod void testCalculateCurrenRent() {
        Property__c property = [SELECT Id,Property__c.JDEPropertyNumber__c,  Name FROM Property__c];

        List<Space__c> sourceSpaceList = new List<Space__c>();
        List<Space__c> newSpaceList = new List<Space__c>();

        SpaceManagementController.Response res;
        res = SpaceManagementController.getSpaces(property.Id);
        SpaceManagementController.SpaceWrapper spaceWrap = (SpaceManagementController.SpaceWrapper) JSON.deserialize(res.returnValue, SpaceManagementController.SpaceWrapper.class);
        sourceSpaceList = spaceWrap.spaceList;

        Space__c space = new Space__c();
        

        space.Type__c = '2';
        space.Name = 'SP0001';
        space.RentableArea__c = 100;
        newSpaceList.add(space);

        space = new Space__c();
        space.Type__c = '2';
        space.Name = 'SP0002';
        space.RentableArea__c = 40;
        newSpaceList.add(space);

        space = new Space__c();
        space.Type__c = '20';
        space.Name = 'SP0003';
        space.RentableArea__c = 60;
        space.ReasonForChange__c = 'Lost Space';
        newSpaceList.add(space);

        Test.startTest();
            SpaceManagementController.calculateCurrenRent(sourceSpaceList, newSpaceList);
        Test.stopTest();
    } 
    
    private static testMethod void testcreateSpaceBudget() {
        Property__c property = [SELECT Id,Property__c.JDEPropertyNumber__c,  Name FROM Property__c];

        List<Space__c> sourceSpaceList = new List<Space__c>();
        List<Space__c> newSpaceList = new List<Space__c>();

        SpaceManagementController.Response res;
        res = SpaceManagementController.getSpaces(property.Id);
        SpaceManagementController.SpaceWrapper spaceWrap = (SpaceManagementController.SpaceWrapper) JSON.deserialize(res.returnValue, SpaceManagementController.SpaceWrapper.class);
        sourceSpaceList = spaceWrap.spaceList;

        Space__c space = new Space__c();
        

        space.Type__c = '2';
        space.Name = 'SP0001';
        space.RentableArea__c = 100;
        newSpaceList.add(space);

        space = new Space__c();
        space.Type__c = '2';
        space.Name = 'SP0002';
        space.RentableArea__c = 40;
        newSpaceList.add(space);

        space = new Space__c();
        space.Type__c = '20';
        space.Name = 'SP0003';
        space.RentableArea__c = 60;
        space.ReasonForChange__c = 'Lost Space';
        newSpaceList.add(space);
		
        SpaceManagementController.SpaceBudgetWrapper sbWrapper = new SpaceManagementController.SpaceBudgetWrapper();
        sbWrapper.childSpaces.putAll(newSpaceList);
        sbWrapper.parentSpaces.putAll(sourceSpaceList);
        sbWrapper.property = property;
        sbWrapper.spaceBudgetMap = DatabaseSOQLBank.getSpaceBudget(SpaceManagementController.getLatestBudgetIds(sourceSpaceList));
        
        Test.startTest();
            SpaceManagementController.createSpaceBudget(sbWrapper);
        Test.stopTest();
    }
    
}