objects/BillCode__c.object
<CustomObject>
    <description>&lt;BIC&gt;Bill Codes from JDE for product mapping</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BillCodeDescription__c</fullName>
        <label>Bill Code Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>BillCode__c</fullName>
        <description>JDE Bill code</description>
        <externalId>true</externalId>
        <inlineHelpText>JDE Bill code</inlineHelpText>
        <label>Bill Code</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Bill Code</label>
    <nameField>
        <displayFormat>BC-{000000}</displayFormat>
        <label>Bill Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bill Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BillingCategory__c</fullName>
        <description>Billing category to identify the bill code.</description>
        <inlineHelpText>For Finance Use Only.</inlineHelpText>
        <label>Billing Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SpaceBillingCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DevelopmentType__c</fullName>
        <label>Development Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>DevelopmentImpacted__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Operational</fullName>
                    <default>true</default>
                    <label>Operational</label>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Mini Project</fullName>
                </value>
                <value>
                    <fullName>None Project</fullName>
                    <isActive>false</isActive>
                    <label>None Project</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LatestBudget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Latest Budget</label>
        <referenceTo>SpaceBudgetAndForecast__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Spaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LatestForecast__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Latest Forecast</label>
        <referenceTo>SpaceBudgetAndForecast__c</referenceTo>
        <relationshipLabel>Spaces (Latest Forecast)</relationshipLabel>
        <relationshipName>Spaces2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LatestJVBudget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Latest JV Budget</label>
        <referenceTo>SpaceBudgetAndForecast__c</referenceTo>
        <relationshipLabel>Spaces (Latest JV Budget)</relationshipLabel>
        <relationshipName>Spaces1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MainFloor__c</fullName>
        <label>Main Floor</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Floor</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ReasonForChange__c</fullName>
        <inlineHelpText>This is applicable for reconfiguration area changes.</inlineHelpText>
        <label>Reason For Change</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ReconfiguredCurrentRentSemiGross__c</fullName>
        <label>Reconfigured Current Rent (Semi Gross)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ReconfiguredCurrentRent__c</fullName>
        <description>This field will hold the pro-rata rent based on Space Reconfiguration process</description>
        <label>Reconfigured Current Rent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <description>Parent
Child</description>
        <label>Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Relationship</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RentableArea__c</fullName>
        <label>Rentable Area</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SpaceType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>UsableArea__c</fullName>
        <inlineHelpText>Equals the rentable area.</inlineHelpText>
        <label>Usable Area</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SpaceBudgetAndForecast__c.object
<CustomObject>
    <description>&lt;SBF&gt; - Represents approved annualised amount for budget for CY and JV FY and forecast periods</description>
    <fields>
        <fullName>AnnualisedPVRentGross__c</fullName>
        <label>Annualised PV Rent (Gross)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AnnualisedPVRentNet__c</fullName>
        <label>Annualised PV Rent (Net)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AnnualisedPVRentSemiGross__c</fullName>
        <label>Annualised PV Rent (Semi Gross)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AnnualisedRentDecNet__c</fullName>
        <label>Annualised Rent (Dec) (Net)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AnnualisedRentDecSemiGross__c</fullName>
        <label>Annualised Rent (Dec) (Semi Gross)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AnnualisedRentJanNet__c</fullName>
        <label>Annualised Rent (Jan) (Net)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AnnualisedRentJanSemiGross__c</fullName>
        <label>Annualised Rent (Jan) (Semi Gross)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CapitalSiteEstablishment__c</fullName>
        <label>Capital (Site Establishment)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ModelType__c</fullName>
        <label>Model Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Budget</fullName>
                </value>
                <value>
                    <fullName>JV Budget</fullName>
                </value>
                <value>
                    <fullName>Forecast</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PromotionalAllowance__c</fullName>
        <label>Promotional Allowance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <formula>Space__r.Property__r.Name</formula>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipLabel>Space Budget and Forecast</relationshipLabel>
        <relationshipName>Space_Budget_and_Forecast</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Space Budget and Forecast</label>
    <nameField>
        <label>Space Budget and Forecast Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Space Budget and Forecast</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SpaceGroup__c.object
<CustomObject>
    <description>&lt;SPG&gt; - Represents a grouping of spaces eg. Sales Precinct, Development Project</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ChildSpace__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Child Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipLabel>Space Groups (Child Space)</relationshipLabel>
        <relationshipName>Space_Groups2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <formula>ChildSpace__r.Property__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Reconfiguration - Split</fullName>
                </value>
                <value>
                    <fullName>Reconfiguration - Merge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Space Group</label>
    <nameField>
        <label>Space Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Space Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SpaceProduct__c.object
<CustomObject>
    <description>&lt;SPP&gt; - Represents a products delated to the Space where Space product values is different to property. This caters for space level outgoings eg. Council rates, Air Con</description>
    <fields>
        <fullName>Active__c</fullName>
        <description>Confirms that the Space Product can currently be used. This field is driven by the effective dates defined for this space product.</description>
        <formula>IF(ISBLANK(EffectiveToDate__c), 
IF(EffectiveFromDate__c &lt;= TODAY(),TRUE,FALSE), 
(AND(EffectiveFromDate__c &lt;= TODAY(), 
TODAY() &lt;= EffectiveToDate__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Confirms that the Space Product can currently be used. This field is driven by the effective dates defined for this space product.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CalculationMethod__c</fullName>
        <description>Drives the price calculation.</description>
        <label>Calculation Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>Percentage</fullName>
                </value>
                <value>
                    <fullName>PSM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EffectiveFromDate__c</fullName>
        <description>The Date from which this Product becomes or became available for use for any Opportunity related to the Space.</description>
        <label>Effective From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <description>The Property to which this Space Product applies. This field is defaulted based on the selected Space.</description>
        <formula>Space__r.Property__r.Name</formula>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <description>The Space to which the Space Product applies.</description>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipLabel>Space Products</relationshipLabel>
        <relationshipName>SpaceProducts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Space Product</label>
    <nameField>
        <displayFormat>SPP - {0000}</displayFormat>
        <label>Space Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Space Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Floor.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>0001</fullName>
    </customValue>
    <customValue>
        <fullName>0002</fullName>
    </customValue>
    <customValue>
        <fullName>0003</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <customValue>
        <fullName>13</fullName>
    </customValue>
    <customValue>
        <fullName>14</fullName>
    </customValue>
    <customValue>
        <fullName>15</fullName>
    </customValue>
    <customValue>
        <fullName>16</fullName>
    </customValue>
    <customValue>
        <fullName>160</fullName>
    </customValue>
    <customValue>
        <fullName>17</fullName>
    </customValue>
    <customValue>
        <fullName>18</fullName>
    </customValue>
    <customValue>
        <fullName>19</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>22</fullName>
    </customValue>
    <customValue>
        <fullName>23</fullName>
    </customValue>
    <customValue>
        <fullName>24</fullName>
    </customValue>
    <customValue>
        <fullName>25</fullName>
    </customValue>
    <customValue>
        <fullName>26</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>50</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>6&amp;7</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <masterLabel>Floor</masterLabel>
</GlobalValueSet>

globalValueSets/Relationship.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Parent</fullName>
    </customValue>
    <customValue>
        <fullName>Child</fullName>
    </customValue>
    <customValue>
        <fullName>-None-</fullName>
        <default>true</default>
        <label>-None-</label>
    </customValue>
    <masterLabel>Relationship</masterLabel>
</GlobalValueSet>

globalValueSets/SpaceBillingCategory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>NR</fullName>
        <label>Non Retail</label>
    </customValue>
    <customValue>
        <fullName>PE</fullName>
        <label>External Precinct</label>
    </customValue>
    <customValue>
        <fullName>ATM</fullName>
    </customValue>
    <customValue>
        <fullName>EX</fullName>
        <label>Car Park - External</label>
    </customValue>
    <customValue>
        <fullName>PM</fullName>
        <label>Car Park - Permanent</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Car Park - Internal</label>
    </customValue>
    <customValue>
        <fullName>VL</fullName>
        <label>Car Park - Valet</label>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
        <default>true</default>
        <label>Not Applicable</label>
    </customValue>
    <description>Space Billing Category</description>
    <masterLabel>Space Billing Category</masterLabel>
</GlobalValueSet>

globalValueSets/SpaceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Shop</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Kiosk</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Office Suite</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Store Room</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Seating</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sundry Property</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Garage / Parking</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sundry</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Space Bank</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Common Mall</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>Re-design</label>
    </customValue>
    <customValue>
        <fullName>Seating License</fullName>
        <isActive>false</isActive>
        <label>Seating License</label>
    </customValue>
    <customValue>
        <fullName>Sundry Site</fullName>
        <isActive>false</isActive>
        <label>Sundry Site</label>
    </customValue>
    <masterLabel>Space Type</masterLabel>
</GlobalValueSet>

classes/SpaceManagementBatchHelperTest.cls
@isTest
public without sharing class SpaceManagementBatchHelperTest {
    @TestSetup private static void testSetup(){
        Map<String, Schema.RecordTypeInfo> spaceRecordTypeMap = RecordTypeUtil.getAllRecordTypesByName(Constants.SPACE);
        List<Pricebook2> priceBookList = new List<Pricebook2>();
		
        //Create Price Book
        priceBookList = TestDataFactory.createPricebook(1);
        database.insert(priceBookList);
        
        Property__c property = TestDataFactory.createProperty(1, priceBookList[0])[0];
        Database.insert(property);

        List<Space__c> spaceList = TestDataFactory.createSpace(5, property);
        Map<Id, Space__c> spaceMap = new Map<Id, Space__c>();
        for(Space__c space : spaceList){
            space.RentableArea__c = 40;
            space.DevelopmentType__c = null;
            space.ReconfiguredCurrentRent__c = 100000;
            space.ReconfiguredCurrentRentSemiGross__c = 50000;
            space.RecordTypeId = spaceRecordTypeMap.get(Constants.PROSPECTIVE_SPACE).getRecordTypeId();
            space.CurrencyIsoCode = 'AUD';
        }
        spaceList[4].billingCategory__c = Constants.SPACEBILLINGCATEGORY_NON_RETAIL; // --- additional code coverage; else statement is unreachable due to validation rule
        Database.insert(spaceList);

        spaceMap.putAll(spaceList);

        SpaceBudgetAndForecast__c spaceBudgetTemp;
        List<SpaceBudgetAndForecast__c> spaceBudgetList = new List<SpaceBudgetAndForecast__c>();

        Set<String> modelTypeSet = new Set<String>{
            Constants.BUDGET,
            Constants.JV_BUDGET,
            Constants.FORECAST
        };

        for(Space__c space : spaceList){
            for(String modelType : modelTypeSet){
                spaceBudgetTemp = TestDataFactory.createSpaceBudget(1, space)[0];
                spaceBudgetTemp.ModelType__c = modelType;
                spaceBudgetTemp.AnnualisedRentDecSemiGross__c = 250000;
                spaceBudgetTemp.AnnualisedRentDecNet__c = 250000;
                spaceBudgetTemp.AnnualisedRentJanSemiGross__c = 350000;
                spaceBudgetTemp.AnnualisedRentJanNet__c = 350000;
                spaceBudgetTemp.AnnualisedPVRentSemiGross__c = 150000;
                spaceBudgetTemp.AnnualisedPVRentNet__c = 150000;
                spaceBudgetTemp.AnnualisedPVRentGross__c = 150000;
                spaceBudgetTemp.PromotionalAllowance__c = 250000;
                spaceBudgetTemp.CapitalSiteEstablishment__c = 250000;

                spaceBudgetList.add(spaceBudgetTemp);
            }
        }

        Database.insert(spaceBudgetList);

        Space__c spaceTemp;
        for(SpaceBudgetAndForecast__c sBudget : spaceBudgetList){
            if(spaceMap.containsKey(sBudget.Space__c)){
                spaceTemp = spaceMap.get(sBudget.Space__c);
                if(Constants.BUDGET.equalsIgnoreCase(sBudget.ModelType__c)){
                    spaceTemp.LatestBudget__c = sBudget.Id;
                } else if(Constants.JV_BUDGET.equalsIgnoreCase(sBudget.ModelType__c)){
                    spaceTemp.LatestJVBudget__c = sBudget.Id;
                } else if(Constants.FORECAST.equalsIgnoreCase(sBudget.ModelType__c)){
                    spaceTemp.LatestForecast__c = sBudget.Id;
                }
            }
        }
		Billcode__c abc = new Billcode__c();
        abc.Active__c = true;
        abc.BillCode__c = 'ABC';
        abc.BillCodeDescription__c = 'abc';
        Database.insert(abc);
        Database.update(spaceMap.values());
        Product2 prodRec = new Product2();
        prodRec = TestDataFactory.createProduct('Test Name', 'Fam');
        prodRec.Family = 'Recoveries';
        prodRec.Billcode__c = abc.Id;
        prodRec.OutgoingsCategory__c = 'Land Tax';			// --- code coverage: 'Cleaning' is not included in Label.SpaceReconfig_OutgoingCategory
        prodRec.EffectiveFromDate__c = Date.today();
        database.insert(prodRec);
        
        List<SpaceProduct__c> spaceProdList = new List<SpaceProduct__c>();
        spaceProdList = TestDataFactory.createSpaceProduct(1, spaceTemp, '', prodRec);
        spaceProdList[0].CalculationMethod__c = 'Fixed';
        spaceProdList[0].CurrencyIsoCode = 'AUD';
        database.insert(spaceProdList);
    }

    @isTest
    public static void runBatch(){
        Space__c space = new Space__c();
        List<Space__c> newSpaceList = new List<Space__c>();
		space = [SELECT Id, Property__c FROM Space__c WHERE LatestBudget__c != null LIMIT 1];
        Id propertyId = space.Property__c;
        space.Type__c = '2';
        space.Name = 'SP0001';
        space.RentableArea__c = 100;
        space.UsableArea__c = 100;
        space.Relationship__c = 'Parent';
        space.MainFloor__c = '0';
        newSpaceList.add(space);

        space = new Space__c();
        space.Type__c = '2';
        space.Name = 'SP0002';
        space.RentableArea__c = 40;
        space.UsableArea__c = 40;
        space.Relationship__c = 'Child';
        space.Property__c = propertyId;
        space.MainFloor__c = '0';
        newSpaceList.add(space);

        space = new Space__c();
        space.Type__c = '20';
        space.Name = 'SP0003';
        space.RentableArea__c = 60;
        space.UsableArea__c = 60;
        space.Relationship__c = 'Child';
        space.Property__c = propertyId;
        space.MainFloor__c = '0';
        space.ReasonForChange__c = 'Lost Space';
        newSpaceList.add(space);
		
        upsert newSpaceList;
        
        List<SpaceGroup__c> spaceGroups = new List<SpaceGroup__c>();
        SpaceGroup__c spaceGroup = new SpaceGroup__c();
        spaceGroup.Active__c = true;
        spaceGroup.ChildSpace__c = newSpaceList[1].Id;
        spaceGroup.ParentSpace__c = newSpaceList[0].Id;
        spaceGroups.add(spaceGroup);
        
        spaceGroup = new SpaceGroup__c();
        spaceGroup.Active__c = true;
        spaceGroup.ChildSpace__c = newSpaceList[2].Id;
        spaceGroup.ParentSpace__c = newSpaceList[0].Id;
        spaceGroups.add(spaceGroup);
        
        insert spaceGroups;
        
        Test.startTest();
        
        SpaceManagementBatchHelper.runSpaceManagementBatch();
        Test.stopTest();
    }
}