objects/CaseEvent__e.object
<CustomObject>
    <fields>
        <fullName>CasePayload__c</fullName>
        <label>Case Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Case Event</label>
    <pluralLabel>Case Events</pluralLabel>
</CustomObject>

objects/CaseEventTrigger__mdt.object
<CustomObject>
    <fields>
        <fullName>CaseStatus__c</fullName>
        <label>Case Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                    <default>true</default>
                    <label>Approved</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CaseType__c</fullName>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CAS_InspectionReport</fullName>
                </value>
                <value>
                    <fullName>CAS_LVIIssueCreditNote</fullName>
                </value>
                <value>
                    <fullName>CAS_LVIRequestForRefund</fullName>
                </value>
                <value>
                    <fullName>CAS_LVIVariancetoRentCommencementDate</fullName>
                </value>
                <value>
                    <fullName>CAS_LVIVoluntaryWorkApproval</fullName>
                </value>
                <value>
                    <fullName>CAS_LVIAssignmentofaLease</fullName>
                </value>
                <value>
                    <fullName>CAS_LVIConductMarketReview</fullName>
                </value>
                <value>
                    <fullName>CAS_LVILeaseAreaVariation</fullName>
                </value>
                <value>
                    <fullName>CAS_LVIManageBankGuarantee</fullName>
                </value>
                <value>
                    <fullName>CAS_LVIMerchantOrPromotionalAllowance</fullName>
                </value>
                <value>
                    <fullName>CAS_LVIRetailAdminLeaseVariations</fullName>
                </value>
                <value>
                    <fullName>CAS_LVISurrenderaLease</fullName>
                </value>
                <value>
                    <fullName>CAS_LVITerminateaLease</fullName>
                </value>
                <value>
                    <fullName>CAS_LVITradingNameChange</fullName>
                </value>
                <value>
                    <fullName>CAS_LVIVariationofSpecialty_Leases</fullName>
                </value>
                <value>
                    <fullName>CAS_RetailDesignBilling</fullName>
                </value>
                <value>
                    <fullName>CAS_RetailDesignInstruction</fullName>
                </value>
                <value>
                    <fullName>CAS_StatementofCompletion</fullName>
                </value>
                <value>
                    <fullName>CAS_LVICentreTeam</fullName>
                </value>
                <value>
                    <fullName>CAS_LVIMiscellaneous</fullName>
                </value>
                <value>
                    <fullName>CAS_LVILeasingFinance</fullName>
                </value>
                <value>
                    <fullName>CAS_AncillaryTaxInvoiceRequest</fullName>
                </value>
                <value>
                    <fullName>Inspection Report</fullName>
                    <isActive>false</isActive>
                    <label>Inspection Report</label>
                </value>
                <value>
                    <fullName>LVI - Assignment of a Lease</fullName>
                    <isActive>false</isActive>
                    <label>LVI - Assignment of a Lease</label>
                </value>
                <value>
                    <fullName>LVI - Conduct Market Review</fullName>
                    <isActive>false</isActive>
                    <label>LVI - Conduct Market Review</label>
                </value>
                <value>
                    <fullName>LVI - Issue Credit Note</fullName>
                    <isActive>false</isActive>
                    <label>LVI - Issue Credit Note</label>
                </value>
                <value>
                    <fullName>LVI - Lease Area Variation</fullName>
                    <isActive>false</isActive>
                    <label>LVI - Lease Area Variation</label>
                </value>
                <value>
                    <fullName>LVI - Manage Bank Guarantee</fullName>
                    <isActive>false</isActive>
                    <label>LVI - Manage Bank Guarantee</label>
                </value>
                <value>
                    <fullName>LVI - Merchant Or Promotional Allowance</fullName>
                    <isActive>false</isActive>
                    <label>LVI - Merchant Or Promotional Allowance</label>
                </value>
                <value>
                    <fullName>LVI - Request For Refund</fullName>
                    <isActive>false</isActive>
                    <label>LVI - Request For Refund</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Event Trigger</label>
    <pluralLabel>Case Event Trigger</pluralLabel>
</CustomObject>

objects/Contract__c.object
<CustomObject>
    <description>&lt;CON&gt; - Represents a contract signed with a retailer. Either lease, Commercial lease, license agreement</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts (Account)</relationshipLabel>
        <relationshipName>Contracts1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LeaseEndDate__c</fullName>
        <label>Lease End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipName>Leases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lease</fullName>
                </value>
                <value>
                    <fullName>License Agreement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PropertyTeam__c.object
<CustomObject>
    <description>&lt;PRT&gt; - Represents a internal team working for the property eg. Centre Manager, Facility Manager, RDM, Leasing Executive, Development Leasing Executive</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You should only select Third party type accounts.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ACCThirdParty</value>
            </filterItems>
            <infoMessage>You can only select Third party type accounts.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Property Team (Account)</relationshipLabel>
        <relationshipName>Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <formula>IF(AND(!TeamMember__r.IsActive, RecordType.DeveloperName=&apos;PRT_InternalTeamMember&apos;),false,IF(ISBLANK(EndDate__c),
IF(StartDate__c &lt;= TODAY(),TRUE,FALSE),
(AND(StartDate__c &lt;= TODAY(),
TODAY() &lt;= EndDate__c))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Property Team</relationshipLabel>
        <relationshipName>Property_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RoleType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TeamMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Property_Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property Team</label>
    <nameField>
        <displayFormat>PRT-{0000}</displayFormat>
        <label>Property Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CurrentLease__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Lease</label>
        <referenceTo>Contract__c</referenceTo>
        <relationshipLabel>Spaces (Current Lease)</relationshipLabel>
        <relationshipName>CurrentLease</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>At Risk</fullName>
                </value>
                <value>
                    <fullName>Held</fullName>
                </value>
                <value>
                    <fullName>Trading</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SpaceType</valueSetName>
        </valueSet>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/RoleType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accounts Receivable Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Administration Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Architectural Technician</fullName>
    </customValue>
    <customValue>
        <fullName>Asset General Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Centre Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Chief Operating Officer</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Leasing Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Leasing General Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Leasing Regional Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Property Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Retail Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate Legal</fullName>
    </customValue>
    <customValue>
        <fullName>D&amp;C Special Project Coordinator</fullName>
    </customValue>
    <customValue>
        <fullName>Development Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Development Finance Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Director LARS &amp; NZ Development</fullName>
    </customValue>
    <customValue>
        <fullName>Facilities Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Filing Clerk</fullName>
    </customValue>
    <customValue>
        <fullName>Fitout Contributions Admin</fullName>
    </customValue>
    <customValue>
        <fullName>General Manager Leasing</fullName>
    </customValue>
    <customValue>
        <fullName>General Manager Retail Design</fullName>
    </customValue>
    <customValue>
        <fullName>GM of Corporate Accounting</fullName>
    </customValue>
    <customValue>
        <fullName>GM Retail Admin &amp; Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Group General Manager - LARS</fullName>
    </customValue>
    <customValue>
        <fullName>Group Renewal Admin Team</fullName>
        <label>Group Renewal Team</label>
    </customValue>
    <customValue>
        <fullName>Leasing Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Leasing Finance Analyst</fullName>
    </customValue>
    <customValue>
        <fullName>Project Regional Manager - LARS</fullName>
    </customValue>
    <customValue>
        <fullName>Project Retail Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>Project Retail Design Manager</fullName>
    </customValue>
    <masterLabel>Role Type</masterLabel>
</GlobalValueSet>

globalValueSets/SpaceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Shop</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Kiosk</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Office Suite</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Store Room</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Seating</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sundry Property</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Garage / Parking</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sundry</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Space Bank</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Common Mall</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>Re-design</label>
    </customValue>
    <customValue>
        <fullName>Seating License</fullName>
        <isActive>false</isActive>
        <label>Seating License</label>
    </customValue>
    <customValue>
        <fullName>Sundry Site</fullName>
        <isActive>false</isActive>
        <label>Sundry Site</label>
    </customValue>
    <masterLabel>Space Type</masterLabel>
</GlobalValueSet>

classes/CaseBL.cls
public class CaseBL {
    private static Map<String, Schema.RecordTypeInfo> casetRecordTypeMapByName  = RecordTypeUtil.getAllRecordTypesByName(Constants.OBJECT_CASE);
    
    //RPP-11090
    public static set<Id> parentCovidCaseIds = new set<Id>();
    
    public class caseApproversWrapper{
        public Id userId {get;set;}
        public String Role {get;set;}
        public Id Id {get;set;}
        public Id PropId {get;set;}
    }
    //MDC  6.11.18
    //To get the property team members user ID to Case fields for reference.
    public static List<caseApproversWrapper> getApprovers(Set<Id> propertyIDs) {
        List<caseApproversWrapper> caseApproverWrapperLst = new List<caseApproversWrapper>();
        Set<String> rolesSet = new Set<String>{constants.TEAM_ROLE_FINANCE,constants.TEAM_ROLE_ACCREVPAYABLES,constants.TEAM_ROLE_GMLEASING,constants.TEAM_ROLE_REGMGR,
            constants.TEAM_ROLE_TENCOORD,constants.TEAM_ROLE_DIROFLEASE,constants.TEAM_ROLE_COMMRETMGR,constants.TEAM_ROLE_COMMPRPMGR,constants.TEAM_ROLE_REGLEAMGR,
            constants.TEAM_ROLE_REGMGRRETADM, Constants.TEAM_ROLE_REVASSU_ADMIN, Constants.TEAM_ROLE_LEAS_EXEC, Constants.TEAM_ROLE_CXMNG};
                
                for(PropertyTeam__c propTeam : [Select TeamMember__c,property__c,id,role__c from PropertyTeam__c where property__c in :propertyIDs AND TeamMember__c != null AND Active__c=true AND TeamMember__r.IsActive=true]){  
                    //if(rolesSet.contains(propTeam.role__c)){
                    caseApproversWrapper caseApprover = new caseApproversWrapper();
                    caseApprover.Role = propTeam.role__c;
                    caseApprover.userId = propTeam.TeamMember__c;
                    caseApprover.Id = propTeam.id;
                    caseApprover.PropId = propTeam.property__c;
                    caseApproverWrapperLst.add(caseApprover);
                    //}
                }
        return caseApproverWrapperLst;
    }           
    //MDC  6.11.18
    //To get the property team members user ID to Case fields for reference.
    public static String getRoleId(List<Id> contractIDLst,String roleName) {
        List<String> returnedStr = new List<String>();
        String approverId = '';
        Map<Id,String> propertyIdSpaceTypeMap = new Map<Id,String>();
        for(Contract__c contractRec : [Select Id, Space__c, Space__r.Type__c, Space__r.Property__c from contract__c where id in : contractIDLst]){
            
            if(contractRec.Space__c != null && contractRec.Space__r.Type__c != null && contractRec.Space__r.Property__c != null){
                propertyIdSpaceTypeMap.put(contractRec.Space__r.Property__c,contractRec.Space__r.Type__c);
            }
        }
        if(propertyIdSpaceTypeMap.keySet().size()>0){
            for (caseApproversWrapper caseApproversWrapp : getApprovers(propertyIdSpaceTypeMap.keySet())){
                System.debug(' **ROLE** '+caseApproversWrapp.Role);
                if(caseApproversWrapp.Role == roleName){
                    approverId = ''+caseApproversWrapp.userId;
                    break;
                }
            }
        }
        System.debug(' **FINAL ROLE ID** '+approverId);
        return approverId;
    }   
    public static List<Case> CreateInspectionforContract(List<Contract__c> contractList){
        List<Case> caseListtoCreate=new List<Case>();
        if(contractList.size()>0&&!contractList.isEmpty()){
            Set<Id> propertyIdsSet=new Set<Id>();
            Set<Id> accountIdsSet=new Set<Id>();
            for(Contract__c contractRecord: contractList){
                propertyIdsSet.add(contractRecord.Property__c);
                accountIdsSet.add(contractRecord.Account__c);
                accountIdsSet.add(contractRecord.Account__r.ParentId);
            }
            Map<String,AccountTeamMember> accountteamMap=new Map<String,AccountTeamMember>();
            Map<String,PropertyTeam__c> rolepropertyTeamMap=new Map<String,PropertyTeam__c>();
            for(AccountTeamMember memberRecod: [Select id,TeamMemberRole,UserId from AccountTeamMember where AccountId IN :accountIdsSet and TeamMemberRole=:Constants.TEAM_ROLE_RDAM AND Account.RecordType.Name=:Constants.GROUP_LEVEL]){
                accountteamMap.put(memberRecod.TeamMemberRole,memberRecod);
            }
            for(PropertyTeam__c propertyteam: [Select id,Role__c,TeamMember__c from PropertyTeam__c where Property__c IN: propertyIdsSet AND TeamMember__r.IsActive=true AND Active__c=true AND Role__c=:Constants.TEAM_ROLE_RDM]){
                rolepropertyTeamMap.put(propertyteam.Role__c,propertyteam);
            }
            for(Contract__c contractRecord: contractList){
                Case newCaseRecord=new Case();
                newCaseRecord.DueDate__c=System.Today().addDays(14);
                newCaseRecord.RecordTypeId=casetRecordTypeMapByName.get(Constants.INSPECTION_REPORT).getRecordTypeId();
                newCaseRecord.AccountId=contractRecord.Account__c;
                newCaseRecord.Space__c=contractRecord.Space__c;
                
                //RPP-10995 - Change the Subject Naming Convention
                if(contractRecord.Space__r.CurrentLease__c!=null){
                    newCaseRecord.Subject = contractRecord.Property__r.Name + ' - ' + contractRecord.Space__r.Name + ' - ' + Constants.INSPECTION_REPORT;
                }else{
                    newCaseRecord.Subject = contractRecord.Property__r.Name + ' - ' + contractRecord.Name + ' - '+ Constants.INSPECTION_REPORT; 
                }
                
                newCaseRecord.Status=Constants.CASE_STATUS_SCHEDULED;
                newCaseRecord.Contract__c=contractRecord.Id;
                newCaseRecord.Opportunity__c=contractRecord.Opportunity__c;
                //newCaseRecord.OtherInspectionComments__c=System.Label.OtherInspectionComments;
                Id ownerid=userinfo.getUserId();
                if(accountteamMap.containskey(Constants.TEAM_ROLE_RDAM)){
                    ownerid=accountteamMap.get(Constants.TEAM_ROLE_RDAM).UserId;
                }else if(rolepropertyTeamMap.containskey(Constants.TEAM_ROLE_RDM)){
                    ownerid=rolepropertyTeamMap.get(Constants.TEAM_ROLE_RDM).TeamMember__c;
                }
                newCaseRecord.OwnerId=ownerid;
                
                if(contractRecord.LeaseEndDate__c>System.Today().addMonths(9)){
                    newCaseRecord.Priority=Constants.CASE_PRIORITY_LOW;
                }else if(contractRecord.LeaseEndDate__c>=System.Today().addMonths(6)&&contractRecord.LeaseEndDate__c<=System.Today().addMonths(9)){
                    newCaseRecord.Priority=Constants.CASE_PRIORITY_LOW;
                }else if(contractRecord.LeaseEndDate__c>=System.Today().addMonths(3)&&contractRecord.LeaseEndDate__c<=System.Today().addMonths(6)){
                    newCaseRecord.Priority=Constants.CASE_PRIORITY_MEDIUM;
                }else if(contractRecord.LeaseEndDate__c<=System.Today().addMonths(3)){
                    newCaseRecord.Priority=Constants.CASE_PRIORITY_HIGH;
                }
                caseListtoCreate.add(newCaseRecord);
            }
        }
        return caseListtoCreate;
    }
    
    /**
* @Author : Chen chen
* @Parameter : list of cases need to be checked
* @Description : based on the custom meta data case event trigger to determine whether to send event or not
*/
    public static List<Case> caseEventCriteriaCheck(List<Case> cases) {
        String caseStatus = Label.CaseStatus;
        List<Case> validCases = new List<Case>();
        List<RecordType> recordTypeCases = [Select Id, Name, DeveloperName From RecordType where sobjecttype =: Constants.OBJECT_CASE];
        Map<Id, String> recordIdToName = new Map<Id, String>();
        for (RecordType recordType : recordTypeCases) {
            recordIdToName.put(recordType.Id, recordType.DeveloperName);
        }
        List<CaseEventTrigger__mdt> criteriaSelections = [SELECT CaseStatus__c, CaseType__c FROM CaseEventTrigger__mdt LIMIT 10000];
        for (Case caseRecord : cases) {
            for (CaseEventTrigger__mdt caseEventTrigger : criteriaSelections) {
                if (caseRecord.recordTypeId != null && caseRecord.JDESentStatus__c != null && recordIdToName.get(caseRecord.recordTypeId) != null) {
                    if (recordIdToName.get(caseRecord.recordTypeId) == caseEventTrigger.CaseType__c && caseRecord.JDESentStatus__c == caseEventTrigger.CaseStatus__c && caseRecord.Status != null && !caseStatus.contains(caseRecord.Status)) {
                        validCases.add(caseRecord);
                        break;
                    }
                }
            }
        }
        return validCases;
    }
    
    /**
* @Author: Chen Chen
* @Parameter: successfullpublish successfull publish case event
* @Description: according to the successful publish event, update the case dispatch verison and timestamp
*/
    public static void updateCaseWhenCaseEventSentSuccess(List<CaseEvent__e> successfullpublish) {
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(SecurityController.class.getName());
        List<Case> caseToUpdateDispatchDetailsList=new List<Case>(); 
        if(!successfullpublish.isEmpty() && successfullpublish.size()>0){
            for(CaseEvent__e publishedEvent: successfullpublish){
                // get values from pubished event payload to update parent records
                Map<String, Object> publishedCaseEvents;
                try {
                    publishedCaseEvents = (Map<String, Object>)JSON.deserializeUntyped(publishedEvent.CasePayload__c);
                } catch (Exception e) {
                    publishedCaseEvents = NULL;
                }
                
                if (publishedCaseEvents != NULL && !publishedCaseEvents.isEmpty()) {
                    Case caseToUpdateDispatchDetails = new Case();
                    caseToUpdateDispatchDetails.id=(id)publishedCaseEvents.get(Constants.DML_ID.toUpperCase());
                    String dispatchtimestampstr=(String)publishedCaseEvents.get(Constants.TECH_DISPATCHTIMESTAMP.toUpperCase());
                    caseToUpdateDispatchDetails.TechDispatchedTimeStamp__c =DateTime.valueOf(dispatchtimestampstr);
                    String dispatchversionstr=(String)publishedCaseEvents.get(Constants.TECH_DISPATCHVERSION.toUpperCase());
                    caseToUpdateDispatchDetails.TechDispatchedVersion__c=Decimal.valueOf(dispatchversionstr);
                    caseToUpdateDispatchDetailsList.add(caseToUpdateDispatchDetails);
                }
            }
        }
        if(!caseToUpdateDispatchDetailsList.isEmpty() && caseToUpdateDispatchDetailsList.size()>0){
            try {
                Database.update(caseToUpdateDispatchDetailsList, false);
            } catch (Exception e) {
                errorHandler.createError(e);
            }
            errorHandler.save();
        }
    }
    
    /**
* @Author: Chen Chen
* @Parameter: payloads List of case payloads
* @Description: according to the successful publish event, update the case dispatch verison and timestamp
*/
    public static List<CaseEvent__e> generateCaseEvents(List<String> payloads) {
        //Get all record type name, take in a map
        List<CaseEvent__e> caseEvents = new List<CaseEvent__e>();
        if (payloads.size() > 0) {
            for (String payload : payloads) {
                CaseEvent__e caesE = new CaseEvent__e();
                caesE.CasePayload__c = payload;
                caseEvents.add(caesE);
            }
        }
        return caseEvents;
    }
    
    /**
* @Author: Chen Chen
* @Parameter: payloads map of case payloads
* @Description: according to the successful publish event, update the case dispatch verison and timestamp
*/
    public static List<CaseEvent__e> generateCaseEventsByMap(Map<Id, String> payloads, Map<Id, Id> recordIdToRecordTypeId) {
        //Get all record type name, take in a map
        List<RecordType> caseRTs = [select id, name, SobjectType from RecordType where SobjectType =: Constants.OBJECT_CASE];
        Map<Id, String> recordTypeIdToName = new Map<Id, String>();
        for (RecordType caseRT : caseRTs) {
            recordTypeIdToName.put(caseRT.Id, caseRT.Name);
        }
        List<CaseEvent__e> caseEvents = new List<CaseEvent__e>();
        if (payloads.size() > 0) {
            for (Id payload : payloads.keyset()) {
                CaseEvent__e caesE = new CaseEvent__e();
                caesE.CasePayload__c = payloads.get(payload);
                if (recordIdToRecordTypeId.get(payload) != null){
                    caesE.RecordTypeName__c = recordTypeIdToName.get(recordIdToRecordTypeId.get(payload));   
                }
                caseEvents.add(caesE);
            }
        }
        return caseEvents;
    }
    
    /**
* @Author: Chen Chen
* @Parameter: trigger new map
* @Description: when case is fulfilled the critera from custom meta data type case event trigger, put it into map
*/
    public static Map<Id, Case> caseEventTriggerCriteriaCheckMap(Map<Id, Sobject> caseNewMap) {
        Map<Id, Case> dbCaseDataMapToPublish = new Map<Id, Case>();
        List<Case> dbCasedataMap = caseNewMap.values();
        List<Case> validCases = caseEventCriteriaCheck(dbCasedataMap);
        if (validCases.size() > 0) {
            for (Case caseRecord : validCases) {
                dbCaseDataMapToPublish.put(caseRecord.Id, (Case)caseNewMap.get(caseRecord.Id));
            }   
        }
        return dbCaseDataMapToPublish;
    }
    
    /**
* @Author: Chen Chen
* @Parameter: List of case Ids
* @Description: called in the process builder to create nso billing case 
*/
    @InvocableMethod 
    public static void retailDesignBillingCase(List<Id> ids) {
        List<Case> newCases = new List<Case>();
        List<Case> sNewCases = new List<Case>();
        List<Case> originCases = [Select Id, RecordTypeId, Space__c, TechBillingTriggered__c, Contract__c From Case Where Id in: ids];
        List<RecordType> recordTypeCases = [Select Id, Name From RecordType where sobjecttype =: Constants.OBJECT_CASE];
        Map<Id, String> recordIdToName = new Map<Id, String>();
        String retailDesignBillingId = '';
        for (RecordType recordType : recordTypeCases) {
            recordIdToName.put(recordType.Id, recordType.Name);
            if (recordType.Name == Constants.RETAIL_DESIGN_BILLING) {
                retailDesignBillingId = recordType.Id;
            }
        }
        if (originCases.size() > 0) {
            for (Case originCase : originCases) {
                Case retailDesingBillingCase = new Case();
                retailDesingBillingCase.Space__c = originCase.Space__c;
                retailDesingBillingCase.RecordTypeId = retailDesignBillingId;
                retailDesingBillingCase.Status = Constants.COMPLETED;
                if (originCase.Contract__c != null) {
                    retailDesingBillingCase.Contract__c = originCase.Contract__c;
                }
                retailDesingBillingCase.ParentId = originCase.Id;
                if (originCase.RecordTypeId != null && recordIdToName.get(originCase.RecordTypeId) != null) {
                    String recordTypeName = recordIdToName.get(originCase.RecordTypeId);
                    if (Constants.INSPECTION_REPORT == recordTypeName) {
                        retailDesingBillingCase.InspectionType__c = Constants.DSIR;
                    } else if (Constants.RETAIL_DESIGN_BILLING == recordTypeName) {
                        retailDesingBillingCase.InspectionType__c = Constants.DSMT;
                    } else if (Constants.STATEMENT_OF_COMPLETION == recordTypeName) {
                        retailDesingBillingCase.InspectionType__c = Constants.DSSO;
                    }
                }
                System.debug(retailDesingBillingCase.Status);
                newCases.add(retailDesingBillingCase);
            }
        }
        insert newCases;
        for (Case uCase : newCases) {
            uCase.Status = Constants.COMPLETED;
            sNewCases.add(uCase);
        }
        for (Case urCase : originCases) {
            urCase.TechBillingTriggered__c = true;
            sNewCases.add(urCase);
        }
        update sNewCases;
    }
    
    public static Map<Id, AccountTeamMember> caseOwnerAccountTeamMap = new Map<Id, AccountTeamMember>();
    public static Map<Id, PropertyTeam__c> caseOwnerPropertyTeamMap = new Map<Id, PropertyTeam__c>();
    
    /**
    * @Author: pkumarlg
    * @Parameter: set
    * @Description: called in the process builder to create nso billing case 
    */
    public static void getRelevantCaseOwners(Set<Id> accountIdSet, Set<Id> propertIdset){
        /*if(caseOwnerAccountTeamMap != null && accountIdSet != null && accountIdSet.size() > 0){
            try{
                for(AccountTeamMember memberRecord : DatabaseSOQLBank.getRetaiDesignAccountTeamPerAccount(accountIdSet)){
                    caseOwnerAccountTeamMap.put(memberRecord.AccountId, memberRecord);
                }
            } catch(Exception e){
                caseOwnerAccountTeamMap = null;
            }
        }
        
        if(caseOwnerPropertyTeamMap != null && propertIdset != null && propertIdset.size() > 0){
            try{
                for(PropertyTeam__c propertyTeam : DatabaseSOQLBank.getRetaiDesignPropertyTeamPerProperty(propertIdset)){
                    caseOwnerPropertyTeamMap.put(propertyteam.Property__c, propertyTeam);
                }
            } catch(Exception e){
                caseOwnerPropertyTeamMap = null;
            }
        }*/
    }
    
    public static Case updateCaseOwner(Case currentCase, Space__c space, String recordTypeName, Account account, Map<Id, Map<String, AccountTeamMember>> accountTeamRoleMap, Map<String, PropertyTeam__c> rolePropertyTeamMap){
        Boolean isAssigned = false;
        
        if(Label.CaseRecordTypeForOwnerUpdate.contains(recordTypeName)){
            if(account != null && account.ParentId != null 
                && accountTeamRoleMap.containsKey(account.ParentId) 
                && !Constants.STATEMENT_OF_COMPLETION.equalsIgnoreCase(recordTypeName)){
                if(accountTeamRoleMap.get(account.ParentId).containsKey(Constants.TEAM_ROLE_RDAM)){
                    currentCase.OwnerId = accountTeamRoleMap.get(account.ParentId).get(Constants.TEAM_ROLE_RDAM).UserId;
                    isAssigned = true;
                } 
            } 
            
            if(!isAssigned && account != null && account.Parent.ParentId != null 
                && accountTeamRoleMap.containsKey(account.Parent.ParentId) 
                && !Constants.STATEMENT_OF_COMPLETION.equalsIgnoreCase(recordTypeName)){
                
                if(accountTeamRoleMap.get(account.Parent.ParentId).containsKey(Constants.TEAM_ROLE_RDAM)){
                    currentCase.OwnerId = accountTeamRoleMap.get(account.Parent.ParentId).get(Constants.TEAM_ROLE_RDAM).UserId;
                    isAssigned = true;
                }
            }
            
            if(!isAssigned && rolePropertyTeamMap != null){
                if((Constants.INSPECTION_REPORT.equalsIgnoreCase(recordTypeName) 
                    || Constants.RETAIL_DESIGN_INSTRUCTION.equalsIgnoreCase(recordTypeName))
                    && rolePropertyTeamMap.containsKey(Constants.TEAM_ROLE_PRDM)
                    && Constants.SPACE_STATUS_PROJECT.equalsIgnoreCase(space.Status__c)){
                    currentCase.OwnerId = rolePropertyTeamMap.get(Constants.TEAM_ROLE_PRDM).TeamMember__c;
                    isAssigned = true;
                } 
                
                if (!isAssigned && rolePropertyTeamMap.containsKey(Constants.TEAM_ROLE_RDM)){
                    currentCase.OwnerId = rolePropertyTeamMap.get(Constants.TEAM_ROLE_RDM).TeamMember__c;
                    isAssigned = true;
                }
            }
        }
        
        return currentCase;
    }
    
    public static Case updateCaseApprovers(Case currentCase, Map<String, String> matrixRoleFieldMap,  Map<String, PropertyTeam__c> rolePropertyTeamMap, Space__c caseSpace, String caseRecordTypeName){
		String roleName;
		String fieldName;
        if(matrixRoleFieldMap != null && rolePropertyTeamMap != null){
            for(String matrixRole : matrixRoleFieldMap.keySet()){
				fieldName = matrixRoleFieldMap.get(matrixRole);
				roleName = matrixRole;
				
				if(caseRecordTypeName == 'Leasing Checksheet' && fieldName == 'TechRetailAdmin__c'){
					if(caseSpace.Status__c == 'Project'){
						roleName = 'Project Retail Administrator';
					}
				}
				
                if(rolePropertyTeamMap.containsKey(roleName)){
                    currentCase.put(matrixRoleFieldMap.get(matrixRole), rolePropertyTeamMap.get(roleName).TeamMember__c);
                }
            }
        }
        
        return currentCase;
    }
    
    /**
     * @author:         Kyle Tan
     * @desc:           populates contract field of case from the related opportunity
     **/
    public static Id getContractfromOpportunity(Map<Id, Opportunity> opportunityMap, Id opportunityId) {
        Id contractId = null;
        Set<String> validContractStatusSet = new Set<String>();
        List<String> tempContractStatusList = new List<String>();
        try{
            tempContractStatusList = Label.ContractStatus.split(';');
        } catch(Exception e) {
            tempContractStatusList = null;
        }
        if(tempContractStatusList != null) {
            validContractStatusSet.addAll(tempContractStatusList);
        }
        for(Contract__c contractRecord :opportunityMap.get(opportunityId).Contracts__r) {
            if(contractRecord.LeaseStatus__c != null && validContractStatusSet.contains(contractRecord.LeaseStatus__c)) {
                contractId = contractRecord.LeaseStatus__c;
            }
        }        
        return contractId;
    }
    
    /**
    * @author:         Janus Gargoles
    * @parameter:	   List of Opportunities, Map<Id: Space Id,Date: Terminate Lease Date>
    * @desc:           Populates the Forecasted Rent Termination Date of the Opportunities based on 
    * 				   Case LV05 Terminate Lease Date, and also updates the Latest Achieved Opportunity
    * 				   of the Space related to the opportunities - RPP - 4286
    **/
    public static List<Opportunity> updateFRTerminationDate(List<Opportunity> oppList, Map<Id,Date> spaceIdDateMap){
        List<Opportunity> oppListUpdated = new List<Opportunity>();
        Set<Id> latestAchievedOpportunitySet = new Set<Id>();
        Set<Id> oppUpdateIdSet = new Set<Id>();
        Opportunity latestAchievedOpp;
        if(oppList.size() != 0 && !oppList.isEmpty()){
            for(Opportunity oppty : oppList){
                if(spaceIdDateMap.containsKey(oppty.Space__c)){
                    oppty.ForecastedRentTerminationDate__c = spaceIdDateMap.get(oppty.Space__c);
                }
                if(oppty.Space__r.LatestAchievedOpportunity__c != null){
                    latestAchievedOpportunitySet.add(oppty.Space__r.LatestAchievedOpportunity__c);
                }
                oppListUpdated.add(oppty);
                oppUpdateIdSet.add(oppty.Id);
            }
        }
        if(latestAchievedOpportunitySet.size() != 0){
            latestAchievedOpp = DatabaseSOQLBank.getLatestAchievedOpportunity(latestAchievedOpportunitySet);
            if(!oppUpdateIdSet.contains(latestAchievedOpp.Id)){
                if(spaceIdDateMap.containsKey(latestAchievedOpp.Space__c)){
                    latestAchievedOpp.ForecastedRentTerminationDate__c = spaceIdDateMap.get(latestAchievedOpp.Space__c);
                }
                oppListUpdated.add(latestAchievedOpp);
            }
        }
        system.debug('oppListUpdated size - ' + oppListUpdated.size());
        return oppListUpdated;
    }
    
    /**
    * @author:         Janus Gargoles
    * @parameter:	   List of Space, Map<Id :Space Id, Id :Space Contract__c>
    * @desc:           Populates the Space status to Closed if the Case Contract is equal to 
    * 				   the Space Current Lease and if Space Status is At Risk or Trading - RPP - 4286
    **/
    public static List<Space__c> updateSpaceStatus(List<Space__c> spaceList, Map<Id,Id> spaceIdCurrentLeaseMap){
        List<Space__c> spaceListUpdated = new List<Space__c>();
        if(spaceList.size() != 0 && !spaceList.isEmpty()){
            for(Space__c space : spaceList){
                if(spaceIdCurrentLeaseMap.containsKey(space.Id)){
                    if(spaceIdCurrentLeaseMap.get(space.Id).equals(space.CurrentLease__c)){
                        if(space.Status__c == Constants.SPACE_STATUS_TRADING || space.Status__c == Constants.SPACE_STATUS_ATRISK){
                            space.Status__c = Constants.SPACE_STATUS_CLOSED;
                        }
                    }
                }
                spaceListUpdated.add(space);
            }
        }
        return spaceListUpdated;
    }
    
    public static List<CaseTeamMember> populateCaseTeamMembers(List<Case> newList){
        
        List<Case> casesToOperateOn = new List<Case>();
        List<CaseTeamMember> caseTeamsToCreate = new List<CaseTeamMember>();
        
        for(Case cs : newList){
            
            if(cs.SubType__c != Constants.CASE_SUBTYPE_COVID_RENT_REQUEST && !cs.TECH_Is_National_Account__c)
                continue;
            
            casesToOperateOn.add(cs);
        }
        
        if(casesToOperateOn.size() == 0)
            return caseTeamsToCreate;
        
        Set<String> userNames = new Set<String>(); 
        for(CovidCaseAccessibleUsers__mdt customMetadata : [SELECT MasterLabel, DeveloperName FROM CovidCaseAccessibleUsers__mdt]){
        	userNames.add(customMetadata.MasterLabel);
        }
        
        List<User> usersToAddinCaseTeams = [SELECT Id FROM User WHERE Name IN :userNames];
       	List<CaseTeamRole> caseTeamRole = [SELECT Id FROM CaseTeamRole WHERE Name = 'National Request' LIMIT 1];
		
        //List<CaseTeamMember> caseTeamsToCreate = new List<CaseTeamMember>();
        
        for(Case cs : casesToOperateOn){
            for(User u : usersToAddinCaseTeams){
                CaseTeamMember csTm = new CaseTeamMember();
                csTm.ParentId = cs.Id;
                csTm.MemberId = u.Id;
                csTm.TeamRoleId = caseTeamRole[0].Id;
                caseTeamsToCreate.add(csTm);
            }
        }
        
        return caseTeamsToCreate;
    }
    
    //RPP-11090 START
    public static Set<Id> getCovidParentCaseSet(List<Case> parentCases){
        System.debug('parentCases === '+parentCases);
        Set<Id> covidParentCases = new Set<Id>();
        for(Case parentCase : parentCases){
            system.debug('parentCase.SubType__c === '+parentCase.SubType__c);
            System.debug('Constants.CASE_SUBTYPE_COVID_RENT_REQUEST === '+Constants.CASE_SUBTYPE_COVID_RENT_REQUEST);
            System.debug('parentCase.ParentId === '+parentCase.ParentId);
            if(parentCase.SubType__c == Constants.CASE_SUBTYPE_COVID_RENT_REQUEST && parentCase.ParentId == null){
                covidParentCases.add(parentCase.Id);
            }
        }
        
        return covidParentCases;
    }
    
    public static List<Case> updateChildCases(Case parentCase, Case oldParentCase, List<Case> childCases, List<Copy_Covid_Case_Details__mdt> fieldsToCheckMetadata){
        List<Case> childCasesToUpdate = new List<Case>();
        Boolean isFieldUpdate = FALSE;
            
        for(Case childCase : childCases){
            Case cs = childCase;
            isFieldUpdate = FALSE;
            
            if(cs.ParentId != parentCase.Id)
                continue;
            
            for(Copy_Covid_Case_Details__mdt metadata : fieldsToCheckMetadata){
                String fieldApiName = metadata.Field_API_Name__c;
                
                if(oldParentCase.get(fieldApiName) == parentCase.get(fieldApiName))
                    continue;
                
                if(metadata.Copy_Every_Time__c){
                	cs.put(fieldApiName, parentCase.get(fieldApiName));
                    isFieldUpdate = TRUE;
                }else if(metadata.Copy_Only_Once__c){
                    System.debug(fieldApiName + ' === ' + cs.get(fieldApiName));
                    if(cs.get(fieldApiName) == '' || cs.get(fieldApiName) == NULL){
                        cs.put(fieldApiName, parentCase.get(fieldApiName));
                        isFieldUpdate = TRUE;
                    }else{
                        parentCovidCaseIds.add(parentCase.Id);
                        System.debug('parentCovidCaseIds === '+parentCovidCaseIds);
                    }
                }
            }
            if(isFieldUpdate)
            	childCasesToUpdate.add(cs);
            	System.debug('cs === '+ cs.Id);
        }
        System.debug('childCasesToUpdate size === ' + childCasesToUpdate.size());
        return childCasesToUpdate;
    }
    //RPP-11090 - END
}