objects/ClauseLibrary__c.object
<CustomObject>
    <description>&lt;CLA&gt; - Represents a list of clauses for scentre group eg. Standard Clauses, Non-Standard Clauses</description>
    <fields>
        <fullName>ApplicableState__c</fullName>
        <label>Applicable State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DocumentLocation__c</fullName>
        <label>Document Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Upfront Price Components</fullName>
                    <default>true</default>
                    <label>Upfront Price Components</label>
                </value>
                <value>
                    <fullName>LESSOR’S DISCLOSURE STATEMENT</fullName>
                </value>
                <value>
                    <fullName>KEY DISCLOSURE ITEMS</fullName>
                </value>
                <value>
                    <fullName>PART 1. PREMISES</fullName>
                </value>
                <value>
                    <fullName>PART 2. TERM OF LEASE AND OPTION/S TO RENEW LEASE</fullName>
                </value>
                <value>
                    <fullName>PART 3. WORKS FIT OUT AND REFURBISHMENT</fullName>
                </value>
                <value>
                    <fullName>PART 4. RENT</fullName>
                </value>
                <value>
                    <fullName>PART 5. OUTGOINGS</fullName>
                </value>
                <value>
                    <fullName>PART 6. OTHER COSTS</fullName>
                </value>
                <value>
                    <fullName>PART 7. ALTERATION WORKS (INCLUDING RENOVATIONS, EXTENSIONS, REDEVELOPMENT, DEMOLITION)</fullName>
                </value>
                <value>
                    <fullName>PART 8. TRADING HOURS</fullName>
                </value>
                <value>
                    <fullName>PART 9. RETAIL SHOPPING CENTRE DETAILS</fullName>
                </value>
                <value>
                    <fullName>PART 10. OTHER DISCLOSURES</fullName>
                </value>
                <value>
                    <fullName>ADDITIONAL RESPONSES FOR RECURRING LESSEE COMMENTS</fullName>
                </value>
                <value>
                    <fullName>PART 11. LANDLORD ACKNOWLEDGEMENT AND SIGNING</fullName>
                </value>
                <value>
                    <fullName>ADVICE TO LESSOR</fullName>
                </value>
                <value>
                    <fullName>PART 4.  RENT</fullName>
                    <isActive>false</isActive>
                    <label>PART 4.  RENT</label>
                </value>
                <value>
                    <fullName>Permitted Use</fullName>
                    <isActive>false</isActive>
                    <label>Permitted Use</label>
                </value>
                <value>
                    <fullName>Premises details</fullName>
                    <isActive>false</isActive>
                    <label>Premises details</label>
                </value>
                <value>
                    <fullName>Term of Lease</fullName>
                    <isActive>false</isActive>
                    <label>Term of Lease</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ClauseType</valueSetName>
        </valueSet>
    </fields>
    <label>Clause Library</label>
    <nameField>
        <label>Clause Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clause Libraries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityClause__c.object
<CustomObject>
    <description>&lt;OPC&gt; - Represents a clause applied to a deal.</description>
    <fields>
        <fullName>ReferencedClause__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referenced Clause</label>
        <referenceTo>ClauseLibrary__c</referenceTo>
        <relationshipLabel>Opportunity Clause</relationshipLabel>
        <relationshipName>Opportunity_Clauses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ClauseType</valueSetName>
        </valueSet>
    </fields>
    <label>Opportunity Clause</label>
    <nameField>
        <label>Opportunity Clauses Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Clauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/States.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ACT</fullName>
    </customValue>
    <customValue>
        <fullName>NSW</fullName>
    </customValue>
    <customValue>
        <fullName>NT</fullName>
    </customValue>
    <customValue>
        <fullName>QLD</fullName>
    </customValue>
    <customValue>
        <fullName>SA</fullName>
    </customValue>
    <customValue>
        <fullName>TAS</fullName>
    </customValue>
    <customValue>
        <fullName>VIC</fullName>
    </customValue>
    <customValue>
        <fullName>WA</fullName>
    </customValue>
    <customValue>
        <fullName>National</fullName>
        <default>true</default>
        <label>National</label>
    </customValue>
    <customValue>
        <fullName>NZ</fullName>
    </customValue>
    <description>Australian States</description>
    <masterLabel>States</masterLabel>
</GlobalValueSet>

classes/ManageAcceptanceController.cls
/**
 * @author:			Kyle Tan
 * @desc:			APEX Controller for the Manage Acceptance Lightning Component
 **/
public with sharing class ManageAcceptanceController {
    
    public class OpportunityClauseWrapper{
        @AuraEnabled public List<ClauseLibrary__c> availableClauseList = new List<ClauseLibrary__c>();
        @AuraEnabled public List<OpportunityClause__c> opportunityClauseList = new List<OpportunityClause__c>();
    }

    /**
     * @author:			Kyle Tan
     * @desc:			retrieves the list of available clauses from the ClauseLibrary__c and the Opportunity Clauses
     * 					of the opportunity
     **/
    @AuraEnabled
    public static LightningResponse buildOpportunityClauseWrapper(Id opportunityId) {
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(ManageAcceptanceController.class.getName());
        LightningResponse responseObject = new LightningResponse();
        OpportunityClauseWrapper wrapperObject = new OpportunityClauseWrapper();
        List<OpportunityClause__c> selectedOppClauseList = new List<OpportunityClause__c>();
        List<ClauseLibrary__c> clauseLibraryList = new List<ClauseLibrary__c>();
        List<ClauseLibrary__c> filteredClauseLibraryList = new List<ClauseLibrary__c>();
        Set<Id> opportunityIdSet = new Set<Id>();
        Set<Id> selectedClauseIdSet = new Set<Id>();
        Set<String> picklistValues = new Set<String>();
        
        picklistValues.add(Constants.CLAUSE_TYPE_ACCEPTANCE);
        picklistValues.add(Constants.CLAUSE_TYPE_COUNTER_OFFER);
        
        opportunityIdSet.add(opportunityId);
        try{
            selectedOppClauseList = DatabaseSOQLBank.getOpportunityClauseListForStandardResponse(opportunityIdSet);
        } catch(Exception e) {
            selectedOppClauseList = null;
        }
        if(selectedOppClauseList != null && selectedOppClauseList.size() > 0) {
            for(OpportunityClause__c tempOppClauseRec :selectedOppClauseList) {
                if(tempOppClauseRec.ReferencedClause__c != null ) {
                    selectedClauseIdSet.add(tempOppClauseRec.ReferencedClause__c);
                }
            }
        }
        try{
            filteredClauseLibraryList = DatabaseSOQLBank.getFilteredClauseLibraryList(selectedClauseIdSet);
        } catch(Exception e) {
            filteredClauseLibraryList = null;
        }
        if(filteredClauseLibraryList != null && filteredClauseLibraryList.size() > 0) {
            for(ClauseLibrary__c clauseLibraryRec : filteredClauseLibraryList) {
                if(picklistValues.contains(clauseLibraryRec.Type__c) && Constants.CL_STANDARD_RESPONSES.equalsIgnoreCase(clauseLibraryRec.RecordType.DeveloperName)) {
                    clauseLibraryList.add(clauseLibraryRec);
                }
            }
        }
        if(clauseLibraryList != null && clauseLibraryList.size() > 0) {
            wrapperObject.availableClauseList = clauseLibraryList;
        }
        if(selectedOppClauseList != null && selectedOppClauseList.size() > 0) {
            wrapperObject.opportunityClauseList = selectedOppClauseList;
        }
        if(wrapperObject != null) {
            responseObject.returnValue = JSON.serialize(wrapperObject);
        }
        errorHandler.save();
        return responseObject;
    }
    
    /**
     * @author:			Kyle Tan
     * @desc:			method verifies if the user is able to edit the opportunity
     **/
    @AuraEnabled
    public static Boolean verifyOpportunity(Id opportunityId) {
        return ClauseSelectionController.enableClauseEditUpdate(opportunityId);
    }
    
    /**
     * @author:			Kyle Tan
     * @desc:			retrieves the picklist values for the Clause Type picklist in the lightning component
     **/
    @AuraEnabled
    public static LightningResponse getClauseTypePicklistValues() {
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(ManageAcceptanceController.class.getName());
        LightningResponse responseObject = new LightningResponse();
        Set<String> picklistValues = new Set<String>();
        Schema.DescribeFieldResult fieldResult = ClauseLibrary__c.Type__c.getDescribe();
        List<Schema.PicklistEntry> fieldVal = new List<Schema.PicklistEntry>();
        List<String> typeOptions = new List<String>();
        
        picklistValues.add(Constants.CLAUSE_TYPE_ACCEPTANCE);
        picklistValues.add(Constants.CLAUSE_TYPE_COUNTER_OFFER);
        
        try{
            fieldVal = fieldResult.getPicklistValues();
        } catch(Exception e) {
            fieldVal = null;
        }
        
        if(fieldVal != null && fieldVal.size() > 0) {
            for(Schema.PicklistEntry field: fieldVal) {
                if(picklistValues.contains(field.getLabel())) {
                    typeOptions.add(field.getLabel());
                }
            }
            responseObject.returnValue = JSON.serialize(typeOptions);
        }
        return responseObject;
    }
    
    /**
     * @author:			Kyle Tan
     * @desc:			retrieves the picklist values for the Document Location picklist in the lightning component
     **/
    @AuraEnabled
    public static LightningResponse getDocLocPicklistValues() {
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(ManageAcceptanceController.class.getName());
        LightningResponse responseObject = new LightningResponse();
        Schema.DescribeFieldResult fieldResult = ClauseLibrary__c.DocumentLocation__c.getDescribe();
        List<Schema.PicklistEntry> fieldVal = new List<Schema.PicklistEntry>();
        List<String> typeOptions = new List<String>();
        
        try{
            fieldVal = fieldResult.getPicklistValues();
        } catch(Exception e) {
            fieldVal = null;
        }
        if(fieldVal != null && fieldVal.size() > 0) {
            for (Schema.PicklistEntry field: fieldVal) {
                typeOptions.add(field.getLabel());
            }
            responseObject.returnValue = JSON.serialize(typeOptions);
        }
        return responseObject;
    }
    
    /**
     * @author:			Kyle Tan
     * @desc:			retrieves the picklist values for the Applicable State picklist in the lightning component
     **/
    @AuraEnabled
    public static LightningResponse getApplicationStatePicklistValues() {
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(ManageAcceptanceController.class.getName());
        LightningResponse responseObject = new LightningResponse();
        Schema.DescribeFieldResult fieldResult = ClauseLibrary__c.ApplicableState__c.getDescribe();
        List<Schema.PicklistEntry> fieldVal = new List<Schema.PicklistEntry>();
        List<String> typeOptions = new List<String>();
        
        try{
            fieldVal = fieldResult.getPicklistValues();
        } catch(Exception e) {
            fieldVal = null;
        }
        if(fieldVal != null && fieldVal.size() > 0) {
            for (Schema.PicklistEntry field: fieldVal) {
                typeOptions.add(field.getLabel());
            }
            responseObject.returnValue = JSON.serialize(typeOptions);
        }
        return responseObject;
    }
    
    /**
     * @author:			Kyle Tan
     * @desc:			method used to create the selected clauses into opportunity clauses
     **/
    @AuraEnabled
    public static LightningResponse createOpportunityClause(String clauseLibraryStringList, Id opportunityId) {
        return ClauseSelectionController.saveClause(clauseLibraryStringList, opportunityId);
    }
    
    /**
     * @author:			Kyle Tan
     * @desc:			deletes the selected opportunity clause
     **/
    @AuraEnabled
    public static LightningResponse deleteOpportunityClause(Id opportunityClauseId) {
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(ManageAcceptanceController.class.getName());
        LightningResponse responseObject = new LightningResponse();
        try{
            database.delete(opportunityClauseId);
        } catch(Exception e) {
            responseObject.status = Constants.FAILED;
            responseObject.message = e.getMessage();
            errorHandler.createError(e);
        }
        errorHandler.save();
        return responseObject;
    }
}