objects/ClauseLibrary__c.object
<CustomObject>
    <description>&lt;CLA&gt; - Represents a list of clauses for scentre group eg. Standard Clauses, Non-Standard Clauses</description>
    <fields>
        <fullName>RiskApplies__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Risk Applies?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <description>This is sub type if clauses. It&apos;s dependent on the type of the clause</description>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ClauseSubType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ClauseType</valueSetName>
        </valueSet>
    </fields>
    <label>Clause Library</label>
    <nameField>
        <label>Clause Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clause Libraries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityClause__c.object
<CustomObject>
    <description>&lt;OPC&gt; - Represents a clause applied to a deal.</description>
    <fields>
        <fullName>RiskApplies__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This flag is ticked if there is a risk applied Clause associated with this space. Please contact Retail Admin for any questions.</inlineHelpText>
        <label>Risk Applies?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <description>This is the sub type of the clause. It&apos;s dependent on type of clause</description>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ClauseSubType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ClauseType</valueSetName>
        </valueSet>
    </fields>
    <label>Opportunity Clause</label>
    <nameField>
        <label>Opportunity Clauses Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Clauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PrecedentClause__c.object
<CustomObject>
    <description>&lt;PRC&gt; - Represents the link between clauses and agreed clauses for an account at National level.</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ClauseType</valueSetName>
        </valueSet>
    </fields>
    <label>Precedent Clause</label>
    <nameField>
        <label>Clause Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Precedent Clauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>PriceBook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Properties (PriceBook)</relationshipLabel>
        <relationshipName>PropertiesPriceBook</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SpaceType</valueSetName>
        </valueSet>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/ClauseSubType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Aggregate Rent &gt;$7.5M</fullName>
    </customValue>
    <customValue>
        <fullName>Amendment to Repayment of Fitout Contribution</fullName>
    </customValue>
    <customValue>
        <fullName>Area &gt; 2500sqm</fullName>
    </customValue>
    <customValue>
        <fullName>Capital &gt; $5M</fullName>
    </customValue>
    <customValue>
        <fullName>Capped Occ Costs</fullName>
    </customValue>
    <customValue>
        <fullName>Capped Outgoings, statutory charges</fullName>
    </customValue>
    <customValue>
        <fullName>Change in Usage</fullName>
    </customValue>
    <customValue>
        <fullName>Compensation Clause</fullName>
    </customValue>
    <customValue>
        <fullName>Co-Tenancy Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>Delete or Amend Demolition Clause ability to invoke demo cl.</fullName>
    </customValue>
    <customValue>
        <fullName>Delete or Amend Demolition Clause ability to invoke relocation cl.</fullName>
    </customValue>
    <customValue>
        <fullName>Early termination rights</fullName>
    </customValue>
    <customValue>
        <fullName>Exclusion Zone</fullName>
    </customValue>
    <customValue>
        <fullName>Exclusivity</fullName>
    </customValue>
    <customValue>
        <fullName>Fitout Period</fullName>
    </customValue>
    <customValue>
        <fullName>Guarantee</fullName>
    </customValue>
    <customValue>
        <fullName>Lessee Owns Fitout paid for by fitout contrib.</fullName>
    </customValue>
    <customValue>
        <fullName>Amendment to Lessor indemnities and warranties</fullName>
    </customValue>
    <customValue>
        <fullName>National Change in Security Position</fullName>
    </customValue>
    <customValue>
        <fullName>National Change in Usage</fullName>
    </customValue>
    <customValue>
        <fullName>Deviation from Security Policy</fullName>
    </customValue>
    <customValue>
        <fullName>Non-standard fitout period</fullName>
    </customValue>
    <customValue>
        <fullName>Option Lease</fullName>
    </customValue>
    <customValue>
        <fullName>Percentage Rent</fullName>
    </customValue>
    <customValue>
        <fullName>Radius Clause</fullName>
    </customValue>
    <customValue>
        <fullName>Reduced Outgoings</fullName>
    </customValue>
    <customValue>
        <fullName>Rent Free Period</fullName>
    </customValue>
    <customValue>
        <fullName>Rent Review</fullName>
    </customValue>
    <customValue>
        <fullName>Rent Review which contravenes Act</fullName>
    </customValue>
    <customValue>
        <fullName>Right of Refusal</fullName>
    </customValue>
    <description>This is dependent picklist of clause Type</description>
    <masterLabel>Clause Sub Type</masterLabel>
</GlobalValueSet>

globalValueSets/SpaceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Shop</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Kiosk</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Office Suite</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Store Room</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Seating</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sundry Property</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Garage / Parking</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sundry</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Space Bank</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Common Mall</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>Re-design</label>
    </customValue>
    <customValue>
        <fullName>Seating License</fullName>
        <isActive>false</isActive>
        <label>Seating License</label>
    </customValue>
    <customValue>
        <fullName>Sundry Site</fullName>
        <isActive>false</isActive>
        <label>Sundry Site</label>
    </customValue>
    <masterLabel>Space Type</masterLabel>
</GlobalValueSet>

classes/OpportunityLineItemTriggerHandlerTest.cls
/**
 * @author:        Kyle Tan
 * @desc:        Test Class for OpportunityLineItemTriggerHandler
 **/
@isTest
private class OpportunityLineItemTriggerHandlerTest {
    
    @testSetup 
    private static void testSetup() {
        Map<String, Schema.RecordTypeInfo> accountRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(Constants.ACCOUNT);
        Map<String, Schema.RecordTypeInfo> clauseLibTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(Constants.CLAUSE_LIBRARY_API);
        Map<String, Schema.RecordTypeInfo> oppClauseTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(Constants.OPPORTUNITY_CLAUSE_API);
       
        //Create Price Book
        List<Pricebook2> priceBookList = new List<Pricebook2>();
        priceBookList = TestDataFactory.createPricebook(1);
        database.insert(priceBookList);
        
        //Create Property
        List<Property__c> propertyList = new List<Property__c>();
        propertyList = TestDataFactory.createProperty(1, priceBookList[0]);
        propertyList[0].Pricebook__c = Test.getStandardPricebookId();
        database.insert(propertyList);
        
        //Create Account
        List<Account> accountList = new List<Account>();
        accountList = TestDataFactory.createAccountBulk(5, propertyList[0].Id, accountRecordTypeMapByName.get(Constants.PROPERTY_BASED).getRecordTypeId());
        accountList[0].PartnershipSegmentation__c = Constants.GROWTH_PARTNER;
        database.insert(accountList);
        
        //Create Contact
        List<Contact> contactList = new List<Contact>();
        contactList.add(TestDataFactory.createContact('Test Name', accountList[0]));
        database.insert(contactList);
        
        //Create Space
        List<Space__c> spaceList = new List<Space__c>();
        spaceList = TestDataFactory.createSpace(1, propertyList[0]);
        database.insert(spaceList);

        //Create Opportunity
        List<Opportunity> oppList = new List<Opportunity>();
        oppList = TestDataFactory.createOpportunity(3, accountList[0], propertyList[0], spaceList[0]);
        oppList[0].TechByPassOnClone__c = true;
        database.insert(oppList);
        
        //Create Product
        List<Product2> productList = new List<Product2>();
        productList.add(TestDataFactory.createProduct(Constants.PRODUCT_RENT_REVIEW, Constants.PRODUCT_RENT_REVIEW));
        productList.add(TestDataFactory.createProduct(Constants.PRODUCT_PROMO_REVIEW, Constants.PRODUCT_PROMO_REVIEW));
        productList.add(TestDataFactory.createProduct(Constants.FEES_CHARGES, Constants.FEES_CHARGES));
        productList.add(TestDataFactory.createProduct(Constants.RECOVERIES, Constants.RECOVERIES));
        productList[3].OutgoingsCategory__c=Constants.PRODUCT_AIR_CON;
        productList.add(TestDataFactory.createProduct(Constants.CAPITAL, Constants.CAPITAL));
        productList[4].CapitalCategory__c='Contribution';
        database.insert(productList);
        
        //Create Pricebook Entry
        List<PricebookEntry> pbEntryList = new List<PricebookEntry>();
        
        /*for (Integer counter=0; counter<5; counter++) {
            pbEntryList.addAll(TestDataFactory.createStandardPriceBookEntry(1, productList[counter]));
        }*/
		pbEntryList.addAll(TestDataFactory.createStandardPriceBookEntry(1, productList[0]));        
        pbEntryList.addAll(TestDataFactory.createStandardPriceBookEntry(1, productList[1]));        
        pbEntryList.addAll(TestDataFactory.createStandardPriceBookEntry(1, productList[2]));        
        pbEntryList.addAll(TestDataFactory.createStandardPriceBookEntry(1, productList[3]));        
        pbEntryList.addAll(TestDataFactory.createStandardPriceBookEntry(1, productList[4]));        
        database.insert(pbEntryList);
        
        //Create Opportunity Line Items
        List<OpportunityLineItem> oppLineItemList = new List<OpportunityLineItem>();
        for (Integer pbEntryListCounter=0; pbEntryListCounter<5; pbEntryListCounter++) {
            for (Integer productListCounter=0; productListCounter<5; productListCounter++) {
                for (Integer oppListCounter=0; oppListCounter<3; oppListCounter++) {
                oppLineItemList.add(TestDataFactory.createOpportunityLineItem(0, oppList[oppListCounter], productList[productListCounter], pbEntryList[pbEntryListCounter]));                   
                }
            }   
        }
        
        OpportunityLineItem opportunityLineItemClone = TestDataFactory.createOpportunityLineItem(1, oppList[2], productList[2], pbEntryList[2]);
        opportunityLineItemClone.TechIsClone__c	=false;
        oppLineItemList.add(opportunityLineItemClone);
        
        database.insert(oppLineItemList);
        
        //Create Clause Library
        List<ClauseLibrary__c> clauseLibList = new List<ClauseLibrary__c>();
        clauseLibList = TestDataFactory.createClauseLibrary(2);
        clauseLibList[1].Type__c = 'RCA';
        clauseLibList[1].SubType__c = 'Rent Review';
        clauseLibList[1].RiskApplies__c = true;
        database.insert(clauseLibList);
        
        //Create Opportunity Clause
        List<OpportunityClause__c> oppClauseList = new List<OpportunityClause__c>();
        oppClauseList = TestDataFactory.createOpportunityClause(2, oppList[0], clauseLibList[0]);
        oppClauseList[0].Type__c = 'RCA';
        oppClauseList[0].SubType__c = 'Rent Review';
        database.insert(oppClauseList);
    }
    
    
    

    public static testMethod void testNationalAgreement() {
        //CREATE PRECEDENT CLAUSE
        Map<String, Schema.RecordTypeInfo> precclasueRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(CONSTANTS.PRECEDENT_CLAUSE_API); 
        Account acc = [Select id from Account limit 1];
        PrecedentClause__c precRecord = TestDataFactory.createPrecedentClause(1, acc.Id, precclasueRecordTypeMapByName.get(CONSTANTS.NATIONAL_AGREEMENTS).getRecordTypeId());
        database.insert(precRecord);
        
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SYSTEM_ADMINISTRATOR LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser(CONSTANTS.TEST_FNAME, CONSTANTS.TEST_LNAME, profileRec.Id);
         List<OpportunityLineItem> opportunityLineItemList = new List<OpportunityLineItem>();
        opportunityLineItemList = [SELECT Id, StandardReviewType__c,Opportunityid FROM OpportunityLineItem LIMIT 1];
        
        
        Opportunity opportunityRecord = [select id,NationalAgreement__c from Opportunity where id =: opportunityLineItemList[0].Opportunityid limit 1];
        opportunityRecord.NationalAgreement__c = precRecord.Id;
        database.update(opportunityRecord);
        
        System.runAs(testUser) {
            
            Test.startTest();
            for(OpportunityLineItem oppLineItem : opportunityLineItemList){
                oppLineItem.StandardReviewType__c = 'CPI';
            }
            update opportunityLineItemList;
            
            Test.stopTest();
        }
        
        
        
    }       
    public static testMethod void testUpdateSecurityDeposit() {
       
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SYSTEM_ADMINISTRATOR LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser(CONSTANTS.TEST_FNAME, CONSTANTS.TEST_LNAME, profileRec.Id);
        
        List<OpportunityLineItem> opportunityLineItemList = new List<OpportunityLineItem>();
        opportunityLineItemList = [SELECT Id, UnitPrice FROM OpportunityLineItem LIMIT 1];
        //RUN TEST
        System.runAs(testUser) {
            
            Test.startTest();
            for(OpportunityLineItem oppLineItem : opportunityLineItemList){
                oppLineItem.UnitPrice = 1000;
            }
            update opportunityLineItemList;
            
            Test.stopTest();
        }
        
        
        
        List<Opportunity> assertOpportunityList = new List<Opportunity>([SELECT Id, SecurityDeposit__c FROM Opportunity]);
        
        //ASSERTION
        for(Opportunity opp : assertOpportunityList) {
            System.assertNotEquals(0, opp.SecurityDeposit__c);
        }
    }
    public static testMethod void testUpdateOpportunityLineRecover() {
       
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SYSTEM_ADMINISTRATOR LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser(CONSTANTS.TEST_FNAME, CONSTANTS.TEST_LNAME, profileRec.Id);
        
        List<OpportunityLineItem> opportunityLineItemList = new List<OpportunityLineItem>();
        opportunityLineItemList = [SELECT isActive__c,Id,Description FROM OpportunityLineItem LIMIT 1];
        List<product2> prod2list = [select id,Family from Product2 limit 1];
        prod2list[0].Family = Constants.RECOVERIES;
        prod2list[0].OutgoingsCategory__c = 'Air Con';
        database.update(prod2list);
        //RUN TEST
        System.runAs(testUser) {
         
            Test.startTest();
            opportunityLineItemList[0].Description = 'test desc12';
            opportunityLineItemList[0].isActive__c = false;
            opportunityLineItemList[0].unitprice = 122;
            database.update(opportunityLineItemList);
            opportunityLineItemList[0].isActive__c = true;
            database.update(opportunityLineItemList);
            Test.stopTest();
        }
    }  
    public static testMethod void testUpdateOpportunityLineFees() {
       
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SYSTEM_ADMINISTRATOR LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser(CONSTANTS.TEST_FNAME, CONSTANTS.TEST_LNAME, profileRec.Id);
        
        List<OpportunityLineItem> opportunityLineItemList = new List<OpportunityLineItem>();
        opportunityLineItemList = [SELECT isActive__c,Id,Description FROM OpportunityLineItem LIMIT 1];
        List<product2> prod2list = [select id,Family from Product2 limit 1];
        //RUN TEST
        System.runAs(testUser) {
         Test.startTest();
            prod2list[0].Family = Constants.FEES_CHARGES;
            prod2list[0].OutgoingsCategory__c = 'Air Con';
            database.update(prod2list);
            
            opportunityLineItemList[0].Description = 'test desc13';
            opportunityLineItemList[0].isActive__c = false;
            opportunityLineItemList[0].unitprice = 123;
            database.update(opportunityLineItemList);
            opportunityLineItemList[0].isActive__c = true;
            database.update(opportunityLineItemList);

        Test.stopTest();
        }
    }
    public static testMethod void testUpdateOpportunityLineCapital() {
       
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SYSTEM_ADMINISTRATOR LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser(CONSTANTS.TEST_FNAME, CONSTANTS.TEST_LNAME, profileRec.Id);
        
        List<OpportunityLineItem> opportunityLineItemList = new List<OpportunityLineItem>();
        opportunityLineItemList = [SELECT isActive__c,Id,Description FROM OpportunityLineItem LIMIT 1];
        List<product2> prod2list = [select id,Family from Product2 limit 1];
        //RUN TEST
        System.runAs(testUser) {
         Test.startTest();

            prod2list[0].Family = Constants.CAPITAL;
            prod2list[0].capitalcategory__c = 'Lessor Works';
            database.update(prod2list);
            
            opportunityLineItemList[0].Description = 'test desc14';
            opportunityLineItemList[0].isActive__c = false;
            opportunityLineItemList[0].totalprice = 124;
            database.update(opportunityLineItemList);
            opportunityLineItemList[0].isActive__c = true;
            database.update(opportunityLineItemList);
            
        Test.stopTest();
        }
    }           
    public static testMethod void testDeleteOpportunityLine() {
       
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SYSTEM_ADMINISTRATOR LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser(CONSTANTS.TEST_FNAME, CONSTANTS.TEST_LNAME, profileRec.Id);
        
        List<OpportunityLineItem> opportunityLineItemList = new List<OpportunityLineItem>();
        opportunityLineItemList = [SELECT Id FROM OpportunityLineItem LIMIT 1];
        
        //RUN TEST
        System.runAs(testUser) {
            
            Test.startTest();
            
            delete opportunityLineItemList;
            
            Test.stopTest();
        }
        
        
        
        List<Opportunity> assertOpportunityList = new List<Opportunity>([SELECT Id, SecurityDeposit__c FROM Opportunity]);
        //ASSERTION
        for(Opportunity opp : assertOpportunityList) {
            System.assertNotEquals(0, opp.SecurityDeposit__c);
        }
    }
    
    /**
     * @author:        Kyle Tan
     **/
    @isTest
    private static void highRiskClauseTest() {
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SCG_SYS_ADM LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        List<OpportunityLineItem> oppLineItemList = new List<OpportunityLineItem>([SELECT Id, StandardReviewType__c FROM OpportunityLineItem]);
        for(OpportunityLineItem oppLineItemRec :oppLineItemList) {
            oppLineItemRec.StandardReviewType__c = 'NZ CPI+2.0';
        }
        system.runAs(testUser) {
            test.startTest();
            database.update(oppLineItemList[1]);
            test.stopTest();
        }
    }
}