objects/ClauseLibrary__c.object
<CustomObject>
    <description>&lt;CLA&gt; - Represents a list of clauses for scentre group eg. Standard Clauses, Non-Standard Clauses</description>
    <label>Clause Library</label>
    <nameField>
        <label>Clause Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clause Libraries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract__c.object
<CustomObject>
    <description>&lt;CON&gt; - Represents a contract signed with a retailer. Either lease, Commercial lease, license agreement</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts (Account)</relationshipLabel>
        <relationshipName>Contracts1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipName>Leases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OpportunityClause__c.object
<CustomObject>
    <description>&lt;OPC&gt; - Represents a clause applied to a deal.</description>
    <fields>
        <fullName>ReferencedClause__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referenced Clause</label>
        <referenceTo>ClauseLibrary__c</referenceTo>
        <relationshipLabel>Opportunity Clause</relationshipLabel>
        <relationshipName>Opportunity_Clauses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Clause</label>
    <nameField>
        <label>Opportunity Clauses Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Clauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>BackupRetailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Back up Retailer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Spaces (Back up Retailer)</relationshipLabel>
        <relationshipName>Spaces1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DisplayRiskClauseControllerTest.cls
/*
*       author: Clark Marie Garde
*       created date: June 28, 2018
*       description: Test class for DisplayRiskClauseController
* 
*/

@isTest
public class DisplayRiskClauseControllerTest {
    @TestSetup private static void testSetup() {
        Map<String, Schema.RecordTypeInfo> accountRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(CONSTANTS.ACCOUNT);
        Account account = new Account();
        List<Property__c> propertyList = new List<Property__c>();
        List<Space__c> spaceList= new List<Space__c>();
        List<Contract__c> contrList= new List<Contract__c>();
        List<Opportunity> oppList = new List<Opportunity>();
        List<OpportunityClause__c> oppClauseList = new List<OpportunityClause__c>();
        List<Account> parentAccList = new List<Account>();
        Property__c propertyRecord = new Property__c();
        Account accountRecord = new Account();
        Contract__c contrRecord = new Contract__c();
        Space__c spaceRecord = new Space__c();
        Opportunity oppRecord = new Opportunity();
        OpportunityClause__c oppClauseRecord = new OpportunityClause__c();
        List<Pricebook2> pricebookList = new List<Pricebook2>();
        
        //CREATE PRICEBOOK
        pricebookList = TestDataFactory.createPricebook(10);
        database.insert(pricebookList);
        pricebookList = [SELECT Id, CurrencyIsoCode FROM Pricebook2];
        
        //CREATE PROPERTY
        propertyList = TestDataFactory.createProperty(10, pricebookList[0]);
        database.insert(propertyList);
        propertyRecord = [SELECT Id FROM Property__c LIMIT 1];
        
        //CREATE PARENT ACCOUNT
        parentAccList.addAll(TestDataFactory.createAccountBulk(1, propertyList.get(0).Id, accountRecordTypeMapByName.get(CONSTANTS.PROPERTY_BASED).getRecordTypeId()));
        database.insert(parentAccList);
        parentAccList = [SELECT Id, Property__c FROM Account LIMIT 1];
        
        //CREATE ACCOUNT
        account = TestDataFactory.createAccountwithParent(1, propertyList.get(0).Id, accountRecordTypeMapByName.get(CONSTANTS.PROPERTY_BASED).getRecordTypeId(), parentAccList.get(0).Id);
        database.insert(account);
        
        //CREATE Space
        spaceList = TestDataFactory.createSpace(10, account, propertyList[0]);
        Database.insert(spaceList);
        spaceRecord = [SELECT Id, BackupRetailer__c, Property__c FROM Space__c limit 1];
        
        //CREATE OPPORTUNITY
        oppList = TestDataFactory.createOpportunity(10, account, propertyList[0], spaceList[0]);
        Database.insert(oppList);
        oppRecord = [SELECT Id, AccountId, Property__c, Space__c FROM Opportunity limit 1];
        
        //CREATE Contract
        contrList = TestDataFactory.createContract(10, account, propertyList[0], oppList[0]);
        database.insert(contrList);
        system.debug('contracttt' + contrList);
        contrRecord = [SELECT Id, Name, Account__c FROM Contract__c limit 1]; 
        
        //CREATE CLAUSE LIBRARY
        List<ClauseLibrary__c> clauseLibraryList = TestDataFactory.createClauseLibrary(10);
        Database.insert(clauseLibraryList);
        
        //CREATE OPPORTUNITY CLAUSE
        Integer counter = 0;
        for(Opportunity opp : oppList){
            counter = 0;
            for(OpportunityClause__c oppClause : TestDataFactory.createOpportunityClause(10, opp)){
                oppClause.ReferencedClause__c = clauseLibraryList[counter].Id;
                counter++;
                
                oppClauseList.add(oppClause);
            }
        }
        
        Database.insert(oppClauseList);
    }
    
    @isTest
    private static void testGetPropertyRecord() {
        Property__c prop = [SELECT ID FROM Property__c LIMIT 1];
        DisplayRiskClauseController.Response response = new DisplayRiskClauseController.Response();
        
        Test.startTest();
            response = DisplayRiskClauseController.getDetails(prop.ID, 'Risktab');
        Test.stopTest();
        
        System.assertEquals('Success', response.status);
        
    }
    
    @isTest
    private static void testGetOpportunityRecord() {
        Opportunity opp = [SELECT ID FROM Opportunity LIMIT 1];
        DisplayRiskClauseController.Response response = new DisplayRiskClauseController.Response();
        
        Test.startTest();
            response = DisplayRiskClauseController.getDetails(opp.ID, '');
        Test.stopTest();
        
        System.assertEquals('Success', response.status);
        
    }
    
    @isTest
    private static void testGetOpportunityRecordRiskTab() {
        Opportunity opp = [SELECT ID FROM Opportunity LIMIT 1];
        DisplayRiskClauseController.Response response = new DisplayRiskClauseController.Response();
        
        Test.startTest();
            response = DisplayRiskClauseController.getDetails(opp.ID, 'Risktab');
        Test.stopTest();
        
        System.assertEquals('Success', response.status);
        
    }
    
    @isTest
    private static void testGetSpaceRecord() {
        Space__c spac = [SELECT ID FROM Space__c LIMIT 1];
        DisplayRiskClauseController.Response response = new DisplayRiskClauseController.Response();
        
        Test.startTest();
            response = DisplayRiskClauseController.getDetails(spac.ID, '');
        Test.stopTest();
        
        system.assertEquals('Success', response.status);
        
    }
    
    @isTest
    private static void testIsColumnEditable() {
        Opportunity opp = [SELECT Id, Stagename, OwnerId from Opportunity limit 1];
        Boolean canUpdate;
        
        Test.startTest();
            canUpdate = DisplayRiskClauseController.isColumnEditable(opp);
        Test.stopTest();
        
        System.assertEquals(true, canUpdate);
        
    }
    
    @isTest
    private static void testUserHasEditAccess() {
        Opportunity opp = [SELECT id, DealAchieved__c FROM Opportunity limit 1];
        Boolean userAccess;
        
        Test.startTest();
            userAccess = DisplayRiskClauseController.userHasEditAccess(opp.Id);
        Test.stopTest();
        
        System.assertEquals(true, userAccess);
        
    }
    
    @isTest
    private static void testUpdateOpportunityClause() {
        Opportunity opp = [SELECT ID FROM Opportunity LIMIT 1];
        DisplayRiskClauseController.Response response = new DisplayRiskClauseController.Response();
        
        response = DisplayRiskClauseController.getDetails(opp.ID, 'Risktab');
        
        Test.startTest();
            response = DisplayRiskClauseController.updateOpportunityClause(response.returnValue);
        Test.stopTest();
    }
    
}