objects/ClauseLibrary__c.object
<CustomObject>
    <description>&lt;CLA&gt; - Represents a list of clauses for scentre group eg. Standard Clauses, Non-Standard Clauses</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ClauseStatuses</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ClauseType</valueSetName>
        </valueSet>
    </fields>
    <label>Clause Library</label>
    <nameField>
        <label>Clause Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clause Libraries</pluralLabel>
    <recordTypes>
        <fullName>CLA_RetailClauses</fullName>
        <active>true</active>
        <description>All retail related clauses</description>
        <label>CLA - Retail Clauses</label>
    </recordTypes>
    <recordTypes>
        <fullName>CLA_StandardResponses</fullName>
        <active>true</active>
        <description>All clauses for acceptance and counter offer letter</description>
        <label>CLA - Standard Responses</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract__c.object
<CustomObject>
    <description>&lt;CON&gt; - Represents a contract signed with a retailer. Either lease, Commercial lease, license agreement</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipName>Leases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lease</fullName>
                </value>
                <value>
                    <fullName>License Agreement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OpportunityAuditHistory__c.object
<CustomObject>
    <description>&lt;OAH&gt; Represents data changes for audit purposes ie. Capture changes to stage for an opportunity</description>
    <fields>
        <fullName>ChangedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Changed By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunity_Audit_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DateEffective__c</fullName>
        <label>Date Effective</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ModifiedFieldLabel__c</fullName>
        <label>Modified Field Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ModifiedFieldName__c</fullName>
        <label>Modified Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewValue__c</fullName>
        <label>New Value</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Audit Histories</relationshipLabel>
        <relationshipName>OpportunityAuditHistories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PreviousValue__c</fullName>
        <label>Previous Value</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Opportunity Audit History</label>
    <nameField>
        <displayFormat>OAH-{00000000}</displayFormat>
        <label>Opportunity Audit History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Audit Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OpportunityClause__c.object
<CustomObject>
    <description>&lt;OPC&gt; - Represents a clause applied to a deal.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Clauses</relationshipLabel>
        <relationshipName>Opportunity_Clauses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ClauseType</valueSetName>
        </valueSet>
    </fields>
    <label>Opportunity Clause</label>
    <nameField>
        <label>Opportunity Clauses Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Clauses</pluralLabel>
    <recordTypes>
        <fullName>OPC_LeasingClause</fullName>
        <active>true</active>
        <description>Deal specific clauses</description>
        <label>Leasing Clause</label>
    </recordTypes>
    <recordTypes>
        <fullName>OPC_PrecedentClause</fullName>
        <active>true</active>
        <description>Account specific clauses</description>
        <label>Precedent Clause</label>
    </recordTypes>
    <recordTypes>
        <fullName>OPC_StandardResponseClause</fullName>
        <active>true</active>
        <description>Record type to list all clauses for Acceptance and Counter offer letter</description>
        <label>Standard Response Clause</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PrecedentClause__c.object
<CustomObject>
    <description>&lt;PRC&gt; - Represents the link between clauses and agreed clauses for an account at National level.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ClauseType</valueSetName>
        </valueSet>
    </fields>
    <label>Precedent Clause</label>
    <nameField>
        <label>Clause Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Precedent Clauses</pluralLabel>
    <recordTypes>
        <fullName>PRC_NationalAgreements</fullName>
        <active>true</active>
        <description>This to capture Rent review, percentage rent, security position and fitout period</description>
        <label>National Agreements</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PropertyTeam__c.object
<CustomObject>
    <description>&lt;PRT&gt; - Represents a internal team working for the property eg. Centre Manager, Facility Manager, RDM, Leasing Executive, Development Leasing Executive</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Property Team</relationshipLabel>
        <relationshipName>Property_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Property Team</label>
    <nameField>
        <displayFormat>PRT-{0000}</displayFormat>
        <label>Property Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Team</pluralLabel>
    <recordTypes>
        <fullName>PRT_ExternalTeamMember</fullName>
        <active>true</active>
        <description>Used to assign a Solicitor Firm to the Property Team.</description>
        <label>PRT - External Team Member</label>
    </recordTypes>
    <recordTypes>
        <fullName>PRT_InternalTeamMember</fullName>
        <active>true</active>
        <description>Used to assign an individual (Scentre Group employee or external Solicitor User) to the Property Team.</description>
        <label>PRT - Internal Team Member</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>LatestBudget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Latest Budget</label>
        <referenceTo>SpaceBudgetAndForecast__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Spaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LatestForecast__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Latest Forecast</label>
        <referenceTo>SpaceBudgetAndForecast__c</referenceTo>
        <relationshipLabel>Spaces (Latest Forecast)</relationshipLabel>
        <relationshipName>Spaces2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LatestJVBudget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Latest JV Budget</label>
        <referenceTo>SpaceBudgetAndForecast__c</referenceTo>
        <relationshipLabel>Spaces (Latest JV Budget)</relationshipLabel>
        <relationshipName>Spaces1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RentableArea__c</fullName>
        <label>Rentable Area</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>At Risk</fullName>
                </value>
                <value>
                    <fullName>Held</fullName>
                </value>
                <value>
                    <fullName>Trading</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TechDispatchedTimeStamp__c</fullName>
        <label>Tech_DispatchedTimeStamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TechDispatchedVersion__c</fullName>
        <label>Tech_DispatchedVersion</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SpaceType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>UsableArea__c</fullName>
        <inlineHelpText>Equals the rentable area.</inlineHelpText>
        <label>Usable Area</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SpaceAuditHistory__c.object
<CustomObject>
    <description>&lt;SPH&gt; -  Represents data changes for audit purposes ie. Capture changes to area for a space</description>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ChangedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Changed By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Space_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DateEffective__c</fullName>
        <label>Date Effective</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NewArea__c</fullName>
        <label>New Area</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipLabel>Space Audit Histories</relationshipLabel>
        <relationshipName>SpaceAuditHistories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Space Audit History</label>
    <nameField>
        <displayFormat>SPH - {0000}</displayFormat>
        <label>Space History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Space Audit Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/ClauseStatuses.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Pending Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Rejects</fullName>
    </customValue>
    <customValue>
        <fullName>Archived</fullName>
    </customValue>
    <customValue>
        <fullName>Superseded</fullName>
    </customValue>
    <masterLabel>Clause Statuses</masterLabel>
</GlobalValueSet>

globalValueSets/SpaceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Shop</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Kiosk</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Office Suite</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Store Room</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Seating</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sundry Property</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Garage / Parking</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sundry</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Space Bank</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Common Mall</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>Re-design</label>
    </customValue>
    <customValue>
        <fullName>Seating License</fullName>
        <isActive>false</isActive>
        <label>Seating License</label>
    </customValue>
    <customValue>
        <fullName>Sundry Site</fullName>
        <isActive>false</isActive>
        <label>Sundry Site</label>
    </customValue>
    <masterLabel>Space Type</masterLabel>
</GlobalValueSet>

classes/Constants.cls
public class Constants {
    public static final String INITIAL_APPROVAL = 'Initial Approval';
    public static final String RETAIL_FINANCE = 'SCG-Retail Finance';
    public static final String RETAIL_LEASING = 'SCG-Retail Lease';
    public static final String DEAL_ACHIEVED = 'Deal Achieve';
    public static final String Opp_ACCEPT_DISCLOSURE_STATEMENT = 'Accept Disclosure Statement';
    public static final String Opp_UPDATE_COST_ESTIMATE = 'Update Cost Estimate';
    public static final String Opp_Send_DISCLOSURE_STATEMENT = 'Send Disclosure Statement';
    public static final String Opp_RECEIVE_DISCLOSURE_STATEMENT = 'Receive Disclosure Statement';
    public static final String MANAGED = 'Managed';
    public static final String ACCOUNT = 'Account';
    public static final String CONTACT = 'CONTACT';
    public static final String PROPERTY = 'Property__c';
    public static final String PROPERTYTEAM = 'PropertyTeam__c';
    public static final String OPPORTUNITY_CONTACT_ROLE = 'OpportunityContactRole';
    public static final String OPPORTUNITY_LINE_ITEM = 'OpportunityLineItem';
    public static final String TASK = 'Task';
    public static final String OBJECT_CASE = 'Case';
    public static final String ACCOUNT_CONTACT_RELATION = 'AccountContactRelation';
    public static final String GROUP_LEVEL = 'ACC - Group Level';
    public static final String GROUP_LEVEL_APINAME = 'ACCGroupLevel';
    public static final String PROPERTY_BASED = 'ACC - Property Based';
    public static final String PROPERTY_BASED_APINAME = 'ACCPropertyBased';
    public static final String THIRD_PARTY = 'ACC - Third Party';
    public static final String THIRD_PARTY_APINAME = 'ACCThirdParty';
    public static final String DASH = ' - ';
    public static final String COMMA = ', ';
    public static final String SEMICOLON = ';';
    public static final String TEST = 'Test';
    public static final String SCG_RETAIL_ADMIN = 'SCG-Retail Admin';
    public static final String SCG_BUSINESS_SUPPORT = 'SCG-Sys BusinessSupport';
    public static final String SCG_DATA_MIGRATION = 'SCG-Sys DataMigration';
    public static final String SCG_INTEGRATION = 'SCG-Sys Integration'; 
    public static final String SYSTEM_ADMINISTRATOR = 'System Administrator';
    public static final String SCG_SYS_ADM = 'SCG-SysAdm';
    public static final String UNDERSTAND_NEGOTIATE = 'Understand & Negotiate';
    public static final String APPROVE = 'Approve';
    public static final String PROPOSE_ACCEPT = 'Propose & Accept';
    public static final String ACTIVE = 'Active';
    public static final String SPACE = 'Space__c';
    public static final String SPACE_AREA = 'RentableArea__c';
    public static final String SPACE_USABLE_AREA = 'usablearea__c';
    public static final String PROSPECTIVE_SPACE = 'Prospective Space';
    public static final String PRECEDENT_CLAUSE_API = 'PrecedentClause__c';
    public static final String PRECEDENT_CLAUSE = 'Precedent Clause';
    public static final String LEASING_CLAUSE = 'Leasing Clause';
    public static final String OPPORTUNITY = 'Opportunity';
    public static final String OPPORTUNITYWITHC = 'Opportunity__c';
    public static final String OPPORTUNITY_CLAUSE_API = 'OpportunityClause__c';
    public static final String OPPORTUNITY_CLAUSE = 'Opportunity Clause';  
    public static final String FIELD_SET_API_NAME = 'HistoryTracking';
    public static final String FIELD_SET_API_NAME_CLONE = 'CloneExcludedField';
    public static final String HISTORY_TRACKING_SPACE = 'SpaceAuditHistory__c';
    public static final String HISTORY_TRACKING_OPPO = 'OpportunityAuditHistory__c';
    public static final String OPPORTUNITYSTAGE_ISSUE_LEASE = 'Issue Lease';
    public static final String SPACE_INTEGRATION_FIELDSET = 'IsChangedFieldsforIntegration';
    public static final String ACCOUNT_INTEGRATION_FIELDSET = 'AccountIsChangedFieldsforIntegration';
    public static final String CONTACT_INTEGRATION_FIELDSET = 'ContactIsChangedFieldsforIntegration';
    public static final String OPPORTUNITY_INTEGRATION_FIELDSET = 'OpportunityIsChangedFieldsforIntegration';
    public static final String TASK_INTEGRATION_FIELDSET = 'TaskIsChangedFieldsforIntegration';
    public static final String CASE_INTEGRATION_FIELDSET = 'CaseIsChangedFieldsforIntegration';
    public static final String CASE_BILLING_NOTREQ_FIELDSET = 'BillingNotRequiredEditable';  //10532
    public static final String OPP_FIELDS_ALLOWED_FOR_EDITS = 'Opp_Fields_Allowed_For_Edits';  //10677
    public static final string TECH_DISPATCHVERSION='TechDispatchedVersion__c';
    public static final string TECH_DISPATCHTIMESTAMP='TechDispatchedTimeStamp__c';
    public static final String BANK_GUARANTEE_ENTITY = 'Bank Guarantee Entity';
    public static final String NUMBER_ONE = '1';
    public static final String NUMBER_TWO = '2';
    public static final String NUMBER_FIVE = '5';
    public static final String PERCENT = '%';
    public static final String SLASH = '/';
    public static final String ENDLINE = '\n';
    public static final String OPPORTUNITYID = 'OpportunityId';
    public static final String TOTALPRICE= 'TotalPrice';
    public static final String OTG = 'OTG';
    public static final String RENT = 'Rent';
    public static final String RECOVERIES = 'Recoveries';
    public static final String RECOVERIES_GROSS = 'Recoveries - Gross';
    public static final String RECOVERIES_NET = 'Recoveries - Net';
    public static final String RECOVERIES_SEMI_GROSS = 'Recoveries - Semi-Gross';
    public static final String PROMO_MARKETING = 'Promo & Marketing';
    public static final String DML_ID = 'Id';
    public static final String DML_NAME = 'Name';
    public static final String DML_SELECT = 'SELECT ';
    public static final String DML_FROM = ' FROM ';
    public static final String DML_WHERE = ' WHERE ';
    public static final String ID_IN_RECORDS = 'Id in:RecordIds';
    public static final String FINAL_HISTORY_RECODS_TO_INSET = 'FINAL HISTORY RECODS TO INSET';
    public static final String CONCATENATE_AND = 'and ';
    public static final String BLANK_SPACE = ' ';
    public static final String COMPLETED = 'Completed';
    public static final String TEST_FNAME = 'John';
    public static final String TEST_LNAME = 'Doe';
    public static final String OPEN = 'Open';
    public static final String YOU = 'You';
    public static final String FINALE = 'Final';
    public static final String RISK = 'Risk';
    public static final String CURRENT = 'Current';
    public static final String TEST_EMAIL = 'test@test.test';
    public static final String DUMMY_USER = 'Dummy User';
    public static final String SPA_SHOP = 'Office Suite';
    public static final String NON_RETAIL = 'Non Retail';
    public static final String CLAUSE_LIBRARY_API = 'ClauseLibrary__c';
    
    public static final String PROMOTION_LEVY_CLAUSE_LIBRARY = 'Promotion Levy Clause Library';
    public static final String CLAUSE_RECORD_TYPE_RETAIL_CLAUSE = 'CLA_RetailClauses';
    public static final String OPPORTUNITY_CLAUSE_NO_PROMOTION_FUND_APPLICABLE = 'Promotion fund Applicable : Set to No';
    public static final String OPPORTUNITY_CLAUSE_CHANGE_IN_PROMOTION_LEVY = 'Change In Total Promotion Levy';
    
    // Opportunity Stage Name constants
    public static final string OPPTY_STAGENAME_NEWRETAILER ='New Retailer';
    public static final string OPPTY_STAGENAME_NEWLEASE='New Lease';
    public static final string OPPTY_STAGENAME_ISSUE_LEASE = 'Issue Lease';
    public static final string OPPTY_STAGENAME_REGISTER_LEASE = 'Register Lease';
    public static final string OPPTY_STAGENAME_EXECUTE_LEASE = 'Execute Lease';
    public static final string OPPTY_STAGENAME_CLOSED = 'Closed - Cancelled';
    public static final String OPPTY_UNDERSTAND_NEGOTIATE = 'Understand & Negotiate';
    
    //Contract Lease Status picklist values
    public static final string CONTRACT_STATUS_FUTURE_DnC='Future - D&C';
    public static final string CONTRACT_FUTURE_LEASE='Future Lease';
    public static final string CONTRACT_HOLDOVER='Holdover';
    public static final string CONTRACT_EXTENSION_OF_LEASE_TERM='Extension of lease term';
    public static final string CONTRACT_LOCKOUT='Lockout';
    public static final string CONTRACT_NEW_MERCHANT_CURRENT='New Merchant(Current)';
    public static final string CONTRACT_NEW_MERCHANT_HOLDOVER='New Merchant (Cur) - Holdover';
    public static final string CONTRACT_NEW_LEASE_RENEWAL='New Lease (Renewal)';
    public static final string CONTRACT_NEW_LEASE_HOLDOVER='New Lease (Renewal) - Holdover';
    
    // Space__r.status__c API Name constants
    public static final string SPACE_STATUS_NEW='New';
    public static final string SPACE_STATUS_ATRISK='At Risk';
    public static final string SPACE_STATUS_HELD='Held';
    public static final string SPACE_STATUS_TRADING='Trading';
    public static final string SPACE_STATUS_PROJECT='Project';
    public static final string SPACE_STATUS_CLOSED='Closed';
    public static final string SPACE_STATUS_INACTIVE='Inactive';
    
    // Space__r.OccupancyStau__c api Names
    public static final string SPACE_OCCUPANCYSTATUS_VACANCY='1 - Vacancy';
    public static final string SPACE_OCCUPANCYSTATUS_LEASINGISSUES='2 - Leasing Issues';
    public static final string SPACE_OCCUPANCYSTATUS_LBNT='3 - LBNT (Leased but not trading)';
    public static final string SPACE_OCCUPANCYSTATUS_HELDVACANCIES='4 - Held Vacancies';
    public static final string SPACE_OCCUPANCYSTATUS_TRADINGNEWRETAILERS='5 - Trading New Retailers';
    public static final string SPACE_OCCUPANCYSTATUS_EXPAIRINGLEASES='6 - Expiring Leases';
    public static final string SPACE_OCCUPANCYSTATUS_HOLDOVERS='7 - Holdovers';
    public static final string SPACE_OCCUPANCYSTATUS_PROJECTSHOPS='8 - Project Shops';
    public static final string SPACE_OCCUPANCYSTATUS_TRADING='9 - Trading';
    
    // Space RelationShip
    public static final String SPACE_REL_PARENT = 'Parent'; //RPP-10807
    public static final String SPACE_REL_CHILD = 'Child'; //RPP-10807

    // Boolean string 
    public static final string BOOLEAN_FALSE='false';
    public static final string BOOLEAN_TRUE='true';
    public static final String SUCCESS = 'SUCCESS';
    public static final String FAILED = 'FAILED';
    public static final String API_TYPE = 'Type__c';
    public static final String SPACE_SPLIT = 'split';
    public static final String SPACE_MERGE = 'merge';
    public static final String RECONFIGURATION_SPLIT = 'Reconfiguration - Split';
    public static final String RECONFIGURATION_MERGE = 'Reconfiguration - Merge';
    public static final String DASH_NO_SPACE = '-';
    public static final String UNDERSCORE_NO_SPACE = '_';
    public static final String BUDGET = 'Budget';
    public static final String JV_BUDGET = 'JV Budget';
    public static final String FORECAST = 'Forecast';
    public static final String API_LATEST_BUDGET = 'LatestBudget__c';
    public static final String API_LATEST_JV_BUDGET = 'LatestJVBudget__c';
    public static final String API_LATEST_FORECAST = 'LatestForecast__c';
    public static final String API_ANNUAL_RENT_DEC_SG = 'AnnualisedRentDecSemiGross__c';
    public static final String API_ANNUAL_RENT_DEC_NET = 'AnnualisedRentDecNet__c';
    public static final String API_ANNUAL_RENT_JAN_SG = 'AnnualisedRentJanSemiGross__c';
    public static final String API_ANNUAL_RENT_JAN_NET = 'AnnualisedRentJanNet__c';
    public static final String API_ANNUAL_PV_RENT_SG = 'AnnualisedPVRentSemiGross__c';
    public static final String API_ANNUAL_PV_RENT_NET = 'AnnualisedPVRentNet__c';
    public static final String API_ANNUAL_PV_RENT_GROSS = 'AnnualisedPVRentGross__c';
    public static final String API_PROMOTIONAL_ALLOWANCE = 'PromotionalAllowance__c';
    public static final String API_CAPITAL_SITE_ESTABLISHMENT = 'CapitalSiteEstablishment__c';
    public static final String API_DATE_EFFECTIVE = 'DateEffective__c';
    public static final String API_NEW_AREA = 'NewArea__c';
    public static final String API_RETMGR = 'RetailManager__c';
    public static final String API_CENTREMGR = 'CentreManager__c';
    public static final String API_AREA = 'Area__c';
    public static final String API_CHANGE_BY = 'ChangedBy__c';
    public static final String API_MODIFIED_BY = 'ModifiedBy__c';
    public static final String API_MODIFIED_DATETIME = 'ModifiedDatetime__c';
    public static final String API_MODIFIED_FIELD_LABEL = 'ModifiedFieldLabel__c';
    public static final String API_MODIFIED_FIELD_NAME = 'ModifiedFieldName__c';
    public static final String API_NEW_VALUE = 'NewValue__c';
    public static final String API_PREVIOUS_VALUE = 'PreviousValue__c';
    public static final String ALIAS_TYPELABEL = 'TypeLabel';
    public static final String ALIAS_MAXSPACEGROUPNUMBER = 'MaxSpaceGroupNumber';
    public static final String EMPTY = '';
    public static final String SPACE_BANK = 'Space Bank';
    public static final String COMMON_MALL = 'Common Mall';
    public static final String RE_DESIGN = 'Re-design';
    public static final String GROSS = 'Gross';
    
    //Account Contact Relation Role
    public static final String ACC_CON_RELATION_BILLING = 'Billing Contact';
    public static final String ACC_CON_RELATION_SALES = 'Sales Turnover Contact';
    public static final String OBJECT_CONTACT = 'Contact';
    public static final String OBJECT_ACR = 'AccountContactRelation';
    
    //Product Names
    public static final String PRODUCT_OUTGOINGS = 'Outgoings';
    public static final String PRODUCT_AIR_CON = 'Air Con';
    public static final String PRODUCT_SUNDAY_TRADE = 'Sunday Trade';
    public static final String PRODUCT_SUNDAY_TRADE_AIRCON = 'Sunday Trade - Air Con';
    public static final String PRODUCT_SUNDAY_TRADE_SEMIGROSS = 'Sunday Trade - Semi Gross';
    public static final String PRODUCT_EXTENDED_TRADE = 'Extended Trade';
    public static final String PRODUCT_COUNCIL_RATES = 'Council Rates';
    public static final String PRODUCT_COUNCIL_RATES_NET = 'Council Rates - Net';
    public static final String PRODUCT_WATER_RATES = 'Water Rates';
    public static final String PRODUCT_LAND_TAX = 'Land Tax';
    public static final String PRODUCT_RENT_REVIEW = 'Rent Review';
    public static final String PRODUCT_BASE_RENT_GROSS = 'Base Rent - Gross';
    public static final String PRODUCT_FITOUT_CONTRIBUTION = 'Fitout Contribution';
    public static final String PRODUCT_PROMOTIONAL_LEVY = 'Promotional Levy';
    public static final String PRODUCT_PROMO_REVIEW = 'Promo Review';
    
    //Product Names
    public static final String PRODUCT_CONTINGENCY = 'Contingency';
    public static final String PRODUCT_DCCOSTS = 'D&C Costs (TW)';
    public static final String PRODUCT_DA_BA_CDC = 'DA/BA/CDC fees';
    public static final String PRODUCT_DEFIT_MAKEGOOD = 'Defit/Makegood';
    public static final String PRODUCT_ENGG_FEES = 'Engineering fees';
    public static final String PRODUCT_STRUCTURAL_FIRE_OTHER = 'Structural/Fire/Other';
    public static final String PRODUCT_EXTRAOVERCAPPED = 'Extra Over Capped ROLO Costs';
    public static final String PRODUCT_HOARDINGCOSTS = 'Hoarding costs';
    public static final String PRODUCT_OTHERLESSORWORKS = 'Other Lessor Works';
    
    //Product Family
    public static final String PRODUCT_FAMILY_RENT = 'Rent';
    public static final String PRODUCT_FAMILY_RECOVERIES_GROSS = 'Recoveries - Gross';
    public static final String PRODUCT_FAMILY_RECOVERIES_SEMIGROSS = 'Recoveries - Semi Gross';
    public static final String PRODUCT_FAMILY_RECOVERIES_NET = 'Recoveries - Net';
    public static final String PRODUCT_FAMILY_PROMO_MARKETING = 'Promo and Marketing';
    
    
    
    //OpportunityLineItem
    public static final String OPP_LINEITEM_RES_MESSAGE = 'Cant Find Opportunity';
    public static final String OPP_LINEITEM_BASERENT = 'Base Rent';
    public static final String OPP_LINEITEM_BASERENT_NET = 'Base Rent - Net';
    public static final String OPP_LINEITEM_BASERENT_SEMIGROSS = 'Base Rent - Semi Gross';
    public static final String OPP_LINEITEM_BASERENT_GROSS = 'Base Rent - Gross';
    public static final String OPP_LINEITEM_NET = 'Net';
    public static final String OPP_LINEITEM_SEMI_GROSS = 'Semi Gross';
    public static final String OPP_LINEITEM_PROMOTION_FUND = 'Promotional Fund';
    
    //Pricebook Entry Name
    public static final String PRICEBOOK_ENTRY_NAME_BASERENT_GROSS = 'Base Rent - Gross';
    public static final String PRICEBOOK_ENTRY_NAME_SUNDAY_TRADE_SG = 'Sunday Trade - Semi Gross';
    public static final String PRICEBOOK_ENTRY_NAME_FITOUT_CONTRIBUTION = 'Fitout Contribution';
    public static final String PRICEBOOK_ENTRY_NAME_PROMOTIONAL_LEVY = 'Promotional Levy';
    public static final String PRICEBOOK_ENTRY_NAME_COUNCIL_RATES_NET = 'Council Rates - Net';
    
   
        
    //Precedent Clause Record Types
    public static final String NATIONAL_AGREEMENTS = 'National Agreements';
    public static final String NATIONAL_PRECEDENT_CLAUSES = 'National Precedent Clauses';
    public static final String NATIONAL_AGREEMENTS_API = 'PRC_NationalAgreements';
    
    //ACR API Fields
    public static final String ACR_ROLES = 'Roles';
    public static final String ACR_ISACTIVE = 'IsActive';
    //CPI Types
    public static final String NATIONAL = 'National';
    public static final String STATE = 'State';
    
    // Case priority values 
    public static final string CASE_PRIORITY_HIGH='High';
    public static final string CASE_PRIORITY_MEDIUM='Medium';
    public static final string CASE_PRIORITY_LOW='Low';
    
    // Case status values 
    public static final string CASE_STATUS_NEW='New';
    public static final string CASE_STATUS_SCHEDULED='Scheduled';
    public static final string CASE_STATUS_APPROVED='Approved';
    public static final string CASE_STATUS_NO_WORKS_REQUIRED='No Works Required';
    public static final string CASE_STATUS_COMPLETED='Completed';
    public static final string CASE_STATUS_PENDING_APPROVAL = 'Pending Approval';
    
    
    //Case Type Values
    public static final string CASE_TYPE_LV04BANK_GUARANTEE = 'LV04 - Bank Guarantee or Security Deposit Management';
    public static final string CASE_TYPE_LV18MISCELLANEOUS = 'LV18 - Miscellaneous';
    public static final string CASE_TYPE_LV10CENTRE = 'LV10 - Centre / RAS Team Lease Variations';
    public static final string CASE_TYPE_LV11LEASING_FINANCE = 'LV11 - Leasing Finance Lease Variations';
    public static final string CASE_TYPE_LV05TERMINATION = 'LV05 - Termination';
    
    
    // Case Subtype values values 
    public static final string CASE_SUBTYPE_RETURN='Return';
    public static final string CASE_SUBTYPE_LEGALLOCKOUT = 'Legal/Lockout';
    public static final string CASE_SUBTYPE_LEASE_EXPIRED = 'Lease Expired';
    public static final string CASE_SUBTYPE_PRE_EXPIRY_OF_LEASE = 'Pre-Expiry of Lease';
    public static final string CASE_SUBTYPE_MAILBOX_CHARGES = 'Mailbox Charges';
    public static final string CASE_SUBTYPE_HOARDING = 'Hoarding';
    public static final string CASE_SUBTYPE_BAD_DEBIT_WRITE_OFF = 'Bad Debt Write Off (BDWO)';
    public static final string CASE_SUBTYPE_BILLING_OF_PERCENT_RENT = 'Billing of % Rent';
    public static final string CASE_SUBTYPE_CAPPED_OCCUPANCY_COST = 'Capped Occupancy Cost';
    public static final string CASE_SUBTYPE_CENTRE = 'Centre';
    public static final string CASE_SUBTYPE_LEASING_FINANCE = 'Leasing Finance';
    // START RPP-10481 LF
    public static final string CASE_SUBTYPE_LEASE_CHECKSHEET = 'Lease Checksheet';
    public static final string CASE_SUBTYPE_SURRENDER_CHECKSHEET = 'Surrender Checksheet';
    public static final string CASE_SUBTYPE_VARIATION_CHECKSHEET = 'Variation Checksheet';
    public static final string CASE_SUBTYPE_ASSIGNMENT_CHECKSHEET = 'Assignment Checksheet';
    // END RPP-10481 LF
    // START RPP-11056 LF
    public static final string CASE_SUBTYPE_COVID_RENT_REQUEST = 'COVID-19 Rent Request';
    //END RPP-11056 LF
    
    // Case Record Types
    public static final string CASE_RECORDTYPE_INSPECTIONREPORT='Inspection Report';
    public static final string CASE_RECORDTYPE_LICENCEAGREEMENTVARIATION = 'LVI - Licence Agreement Variations';
    
    
    // Case Subject for Retail Design Billing
    public static final string CASE_SUBJECT_RDB_IR='Retail Design Billing - IR';
    public static final string CASE_SUBJECT_RDB_RDI='Retail Design Billing - RDI';
    public static final string CASE_SUBJECT_RDB_SOC='Retail Design Billing - SOC';
    
    // Property Team Roles
    public static final string TEAM_ROLE_RDM='Retail Design Manager';
    public static final string TEAM_ROLE_RDAM='Retail Design Account Manager';
    public static final string TEAM_ROLE_FINANCE='Leasing Finance Manager';
    public static final string TEAM_ROLE_ACCREVPAYABLES='Account Receivable Manager';//12.06.2018 Neel added for LVI - Request for Refund
    public static final string TEAM_ROLE_GMLEASING='General Manager Leasing';
    public static final string TEAM_ROLE_REGMGR='Regional Manager - LARS';
    public static final string TEAM_ROLE_DIROFLEASE='Director LARS & NZ Development';
    public static final string TEAM_ROLE_COMMRETMGR='Commercial Retail Manager';
    public static final string TEAM_ROLE_TENCOORD='Tenancy Coordinator'; 
    public static final string TEAM_ROLE_COMMPRPMGR='Commercial Property Manager';
    public static final string TEAM_ROLE_REGLEAMGR='Regional Manager - LARS';
    public static final string TEAM_ROLE_REGLEAMGR_LARS='Regional Manager - LARS';
    public static final string TEAM_ROLE_REGMGRRETADM='Regional Mgr Retail Admin';  //= 'Regional Manager of Retail Admin'; 
    public static final string TEAM_ROLE_NSO_TEAM_COORDINATOR = 'NSO Team Coordinator';
    public static final string TEAM_ROLE_REVASSU_ADMIN = 'Revenue Assurance Manager';
    public static final string TEAM_ROLE_REV_ADMIN = 'Revenue Administrator';
    public static final string TEAM_ROLE_LEAS_EXEC = 'Leasing Executive';
    public static final string TEAM_ROLE_CXMNG = 'Centre Manager';
    public static final string TEAM_ROLE_RMRA = 'Regional Mgr Retail Admin'; //= 'Regional Manager of Retail Admin'; 
    public static final string TEAM_ROLE_RML = 'Regional Manager - LARS';
    public static final string TEAM_ROLE_GMRA = 'GM Retail Admin & Delivery';
    public static final string TEAM_ROLE_COO = 'Chief Operating Officer';
    public static final string TEAM_ROLE_CL = 'Corporate Legal';
    public static final string TEAM_ROLE_RETAILMANAGER = 'Retail Manager';
    public static final string TEAM_ROLE_CENTREMANAGER = 'Centre Manager';
    public static final string TEAM_ROLE_GRPGENERALMGRLARS = 'Group General Manager - LARS';
    public static final string TEAM_ROLE_LEASMGR = 'Leasing Admin';
    public static final string TEAM_ROLE_COMMERCIAL_PROPERTY_MGR = 'Commercial Property Manager';
    public static final string TEAM_ROLE_LFA = 'Leasing Finance Analyst';
    public static final String TEAM_ROLE_PRDM = 'Project Retail Design Manager';
    // START RPP-10481 LF
    public static final String TEAM_ROLE_PRA = 'Project Retail Administrator'; 
    public static final String TEAM_ROLE_RA = 'Retail Administrator'; 
    // END RPP-10481 LF
    // START RPP-9340 LF
    public static final String TEAM_ROLE_RDC = 'Retail Delivery Coordinator';
    public static final String TEAM_ROLE_AT = 'Architectural Technician';
    public static final String TEAM_ROLE_RMR_DESIGN = 'Regional Manager Retail Design';
    public static final String TEAM_ROLE_RMR_DELIVERY = 'Regional Mgr Retail Delivery';
    // END RPP-9340 LF
    
    // Opportunity Record Type
    public static final String OPP_RETAIL_LEASING = 'Retail Leasing';
    public static final String OPP_RETAIL_LEASING_API_NAME = 'OPP_RetailLeasing';
    public static final String OPP_COMMERCIAL_LEASING = 'Commercial Leasing';
    public static final String OPP_COMMERCIAL_LEASING_API_NAME = 'OPP_CommercialLeasing';
    public static final String OPP_STORE_ROOM_LEASING = 'Storeroom Leasing';
    public static final String OPP_STORE_ROOM_LEASING_API_NAME = 'OPP_StoreRoomLeasing';
    
    // Space Product Calculation Method
    public static final String SP_PSM = 'PSM';
    public static final String SP_PERCENTAGE = 'Percentage';
    public static final String SP_FIXED = 'Fixed';
    public static final String LAT_BUDGRENT = 'Budgeted';
    public static final String LAT_JVBUDRENT = 'JV Budgeted';
    public static final String LAT_LFORCRENT = 'Forecasted';
    public static final String LAT_STRERENT = 'Stretched';
    
    public static final String LAT_BUDGSGRENT = 'Budgeted';
    public static final String LAT_JVBUDSGRENT = 'JV Budgeted';
    public static final String LAT_LFORCSGRENT = 'Forecasted';
    public static final String LAT_STRECRENT = 'Stretched';
    
    public static final String LAT_BUDSGRENT = 'Budgeted';
    public static final String LAT_JVBUDGRENT = 'JV Budgeted';
    public static final String LAT_LFORCGRENT = 'Forecasted';
    public static final String LAT_STRETCHRENT = 'Stretched';
    
    
    public static final String PROPERTY_TEAM = 'Property Team';
    public static final String PROPERTY_TEAM_API = 'PropertyTeam__c';
    public static final String OPPORTUNITY_TEAM = 'Opportunity Team';
    public static final String TASK_AUTOMATIC = 'TAS - Automatic';
    public static final String FEES_CHARGES = 'Fees & Charges';
    public static final String OPPORTUNITYLINEITEM = 'OpportunityLineItem';
    public static final String PRICEBOOKENTRY = 'PriceBookEntry';
    public static final String NO_PRODUCTS_AVAILABLE = 'No Products available.';
    public static final String RETAIL = 'Retail';
    public static final String COMMERCIAL = 'Commercial';
    public static final string LEASE_PLAN='Lease Plan';
    public static final string CONTENTLINK_VISIBILITY_INTERNALUSERS='InternalUsers';
    public static final string CONTENTLINK_SHARETYPE='I'; //Inferred permission
    
    //Standard Review Types
    public static final String NON_STANDARD = 'Non-standard';
    
    //Review Types
    public static final String FIXED_PERCENT = 'Fixed %';
    public static final String FIXED_FIVE_PERCENT = 'Fixed 5.0%';
     
    //Case Record Types Name
    public static final String REQUEST_FOR_REFUND = 'LVI - Request For Refund';
    public static final String MISCELLANEOUS_SERVICE = 'LVI - Retail Admin Lease Variations';
    public static final String VARIANCE_TO_RENT_COMMENCEMENT = 'LVI - Variance to Rent Commencement Date';
    public static final String VOLUNTARY_WORKS = 'LVI - Voluntary Work Approval';
    public static final String UPDATE_PROMOTIONAL_ALLOWANCE = 'LVI - Merchant Or Promotional Allowance';
    public static final String CONDUCT_MARKET_REVIEW = 'LVI - Conduct Market Review';
    public static final String CREDIT_NOTE = 'LVI - Issue Credit Note';
    public static final String LEASE_AREA_VARIATION = 'LVI - Lease Area Variation';
    public static final String RETAIL_DESIGN_BILLING = 'Retail Design Billing';
    public static final String STATEMENT_OF_COMPLETION = 'Statement of Completion';
    public static final String RETAIL_DESIGN_INSTRUCTION = 'Retail Design Instruction';
    public static final String INSPECTION_REPORT = 'Inspection Report';
    public static final String MANAGE_BANK_GUARANTEE= 'LVI - Manage Bank Guarantee';
    public static final String SURRENDER_A_LEASE= 'LVI - Surrender a Lease';
    public static final String TERMINATE_A_LEASE= 'LVI - Terminate a Lease';
    public static final String ASSIGN_OF_A_LEASE= 'LVI - Assignment of a Lease';
    public static final String TRADING_NAME_CHANGE = 'LVI - Trading Name Change';
    public static final String CENTRE_TEAM = 'LVI - Centre Team';
    public static final String LEASING_FINANCE = 'LVI - Leasing Finance';
    public static final String MISCELLANEOUS_LEASE = 'LVI - Miscellaneous';
    public static final String ANCILLARY_TAX_INVOICE = 'Ancillary Tax Invoice Request';
    public static final string LEASING_CHECKSHEET = 'Leasing Checksheet';
    public static final String LV19_LICENSE_AGREEMENT_VARIATION = 'LV19_Licence_Agreement_Variations'; 
    // START RPP-11056 LF
    public static final String LVI_COVID19 = 'LVI - COVID19';
    // END RPP-11056 LF
    
    //Case RecordType Developer Name
    public static final String LV18_MISCELLANEOUS = 'CAS_LVIMiscellaneous';
    public static final String LV02_SPECIALTY_VARIATION = 'CAS_LVIVariationofSpecialty_Leases';
    
    //Case Origin
    public static final String CASE_ORIGIN_DEVELOPMENT = 'Development';
    
    //Case Status
    public static final String CASE_STATUS_INVALID = 'Invalid Request';
    public static final String CASE_STATUS_MANUAL = 'Manual';
    public static final String CASE_STATUS_COMPLETED_BATCH_PROCESSING = 'Completed - Batch Processing';
    public static final String CASE_STATUS_COMPLETED_CANCELLED = 'Cancelled';
    public static final String CASE_STATUS_COMPLETED_REJECTED = 'Rejected';
    public static final String CASE_STATUS_RESEND = 'RESEND';
    
    //Case Inspection Type
    public static final String DSIR = 'DSIR';
    public static final String DSMT = 'DSMT';
    public static final String DSSO = 'DSSO';
    public static final String CASE_SUBTYPE_CLAIM_ADMINISTRATION= 'Claim-Administration';
    public static final String CASE_SUBTYPE_CLAIM= 'Claim';
    public static final String CASE_SUBTYPE_TRANSFER='Transfer';
    public static final String CAPITAL = 'Capital';

    //Opportunity Approval Status
    public static final String RMRISK_APPRGRANTED = 'RM & Risk Approval Granted';
    public static final String RSKAPPR_GRANTED = 'Risk Approval Granted';
    public static final String RM_APPV_REJ = 'RM Approval Rejected';
    public static final String INI_APPV_REJ = 'Initial Approval Rejected';
    public static final String PEND_FINALAPPROV = 'Pending Final Approval';
    public static final String FINALAPPR_REJ = 'Final Approval Rejected';
    public static final String INIAPPR_GRANTED = 'Initial Approval Granted';
    public static final String FINALAPPR_GRANT = 'Final Approval Granted';
    public static final String RMAPPR_GRANTED = 'RM Approval Granted';
    public static final String SRMLCNSAPPROV = 'Store Room License Approval';
    public static final String STRAPPOVALGRANTED = 'Licence Approval Granted';
    public static final String STRAPPOVALREJ = 'Licence Approval Rejected';
    public static final String STRPENDING_LICENCE_APPROVAL = 'Pending Licence Approval';
    public static final String RISK_APPRV_REJ = 'Risk Approval Rejected';
    public static final String PENDING_RISK_APRV = 'Pending Risk Approval';
    public static final String PENDING_INI_APRV = 'Pending Initial Approval';

    // RPP - 5521 - BudgetFields locking applicable approval values
    public static final Set<String> BUDGET_LOCK_APPROVAL_STATUS = new Set<String>{Constants.PEND_FINALAPPROV,
                                                                                    Constants.FINALAPPR_GRANT,
                                                                                    Constants.STRPENDING_LICENCE_APPROVAL,
                                                                                    Constants.STRAPPOVALGRANTED
    };
        
    //Opportunity Approval Metadata Types
    public static final String RET_FINALAPPROVAL = 'Retail Final Approval';
    public static final String STOREROOM = 'Store Room';
    public static final String STOREROOMTYPE = 'Storeroom';
    public static final String RETAILRISKAPPROVAL = 'Retail Risk Approval';
    public static final String COMMRISKAPPROVAL = 'Commercial Risk Approval';
    public static final String COMMFINALAPPROVAL = 'Commercial Final Approval';
    public static final String RETAILRMAPPROVAL = 'Retail RM Approval';
    public static final String COMMRMAPPROVAL = 'Commercial RM Approval';
    public static final String SCGRETCENTREMGT = 'SCG-Retail CentreMgt';
    public static final String DATE_FORMAT_DDMMYYYY = 'ddMMyyyy';
    public static final String RETAILINITAPPROVAL = 'Retail Initial Approval';
    public static final String COMMINITAPPROVAL = 'Commercial Initial Approval';
    
    //Affiliation types
    public static final String COMP_PERSONAL_GUARANTEES = 'Company with Personal Guarantees';
    public static final String COMP_PARENT_GUARANTEES = 'Company with Parent Guarantees';
    public static final String PERSONAL_GUARANTEES_FRANCHISEE = 'Personal Guarantees by Franchisee';
    public static final String REQUIRED = 'Required';
    public static final String NOT_REQUIRED = 'Not Required';
    public static final String INDEPENDENT = 'Independent';
    public static final String PROVIDE_LEASE_PLAN_TASK_API = '14 - Provide Lease Plan';
    public static final String OPPORTUNITY_OWNER = 'Opportunity Owner';
    public static final String CASE_OWNER = 'Case Owner';
    public static final String JV = 'JV';
    public static final String OBLIGATIONS_RECEIVED_TASK_API = '16 - Obligations Received';
    public static final String UPDATE_COSE_ESTIMATE = '38 - Update Cost Estimate';
    
    //Property Team Record Type
    public static final String PRT_INTERNAL_TEAM_MEMBER = 'PRT - Internal Team Member';
    public static final String PRT_EXTERNAL_TEAM_MEMBER = 'PRT - External Team Member';
    
    //Property Team Record Type API
    public static final String PRT_INTERNAL_TEAM_MEMBER_API = 'PRT_InternalTeamMember';
    public static final String PRT_EXTERNAL_TEAM_MEMBER_API = 'PRT_ExternalTeamMember';
    
    //Accounts Shipping States
    public static final String ACT = 'ACT';
    
    //Security Deposit picklist values
    public static final String YES = 'Yes';
    public static final String NO = 'No';
    
    //Product Multiselect Values
    public static final String SPACEBILLINGCATEGORY_NON_RETAIL = 'NR';
    public static final String DEALTYPE_SEMI_GROSS = 'Semi Gross';
    public static final String SPACETYPE_SHOP = '1';
    public static final String COMMA_NO_SPACE = ',';
    public static final String OWNER_ID = 'OwnerId';
    public static final String CANCELLED = 'Cancelled';
    public static final String STR_DEFAULT = 'Default';
    public static final String TECH_PROPERTY_ID = 'TechPropertyId__c';
    public static final String PREPARE_COUNTER_OFFER_API = '37 - Prepare Counter Offer';
    public static final String ACCEPT_DISCLOSURE_STATEMENT_API = '01 - Accept Disclosure Statement';
    public static final String GENERATE_OWNER_PACK_SUBMIT_JV_APPROVAL = '09 - Generate Owner’s Pack and Submit for JV Approval';
    public static final String SEND_DOC_FOR_EXECUTION_API = '23 - Send Documents for Execution';
    public static final String SEND_DISCLOSURE_STATEMENT = '22 - Send Disclosure Statement';
    public static final String RECEIVE_DISCLOSURE_STATEMENT = '35 - Receive Disclosure Statement';
    public static final String PRE_DS_REAA_APPROVAL = '59 - Pre-DS REAA Approval';
    public static final String UPDATE_DEAL_TERMS = '36 - Update Deal Terms';
    public static final String GENERATE_ACCEPTANCE = '07 - Generate Acceptance (w/ Modifications)';
    public static final String SEND_ACCEPTANCE = '40 - Send Acceptance (w/ Modifications)';
    public static final String INSTRUCT_SOLICITOR = '39 - Instruct Solicitor';
    public static final String GENERATE_SUBMIT_JV_APPROVAL = '09 - Generate Owner’s Pack and Submit for JV Approval';
    public static final String JV_APPROVAL = '41 - JV Approval';
        
    //Opportunity JDE Status
    public static final String OPPO_JDE_STATUS_READY = 'Ready';
    public static final String OPPO_JDE_STATUS_COMPLETED = 'Completed';
    
    //Picture file formats
    public static final String SVG = '.svg';
    public static final String PNG = '.png';
    public static final String FINAL_APPROVAL_GRANTED = 'Final Approval Granted';
    
    // Space Type constants
    public static final String SPACETYPEKIOSK='Kiosk';
    
    // Org Currenct code
    public static final String CURRENCYCODEAUD='AUD';
    public static final String CURRENCYCODENZD='NZD';
    
    public static final String JV_APPROVAL_API = '41 - JV Approval';
    
    //Clause Type Picklist Values
    public static final String CLAUSE_TYPE_ACCEPTANCE = 'Acceptance';
    public static final String CLAUSE_TYPE_COUNTER_OFFER = 'Counter Offer';
    
    //Clause Library Record Type Developer Name
    public static final String CL_RETAIL_CLAUSES = 'CLA_RetailClauses';
    public static final String CL_STANDARD_RESPONSES = 'CLA_StandardResponses';
    
    //Clause Library Record Type Name
    public static final String CL_STANDARD_RESPONSES_NAME = 'CLA - Standard Responses';
    
    //Opportunity Clause Record Type Developer Name
    public static final String OC_LEASING_CLAUSE = 'OPC_LeasingClause';
    public static final String OC_PRECEDENT_CLAUSE = 'OPC_PrecedentClause';
    public static final String OC_STANDARD_RESPONSE_CLAUSE = 'OPC_StandardResponseClause';
    
    //Opportunity Clause Record Type Name
    public static final String OC_STANDARD_RESPONSE_CLAUSE_NAME = 'Standard Response Clause';
    public static final String NA = 'NA';
    
    //Property Countries
    public static final String AUSTRALIA = 'Australia';
    public static final String NEW_ZEALAND= 'New Zealand';
    
    //GST Custom Meta Data Labels
    public static final String GST = 'GST';
    public static final String GST_NEW_ZEALAND= 'GSTNewZealand';
    public static final String CREATE = 'CREATE';
    public static final String REMOVE = 'REMOVE';
    public static final String ANNUAL_RENT_75M = 'Annual Rent > $7.5M';
    public static final String ATLEAST_ONE_NUM_OF_OPTIONS = 'Atleast 1 number of options';
    public static final String RECOVERABLE_AREA_2500SQM = 'Recoverable Area > 2500 SQM';
    public static final String CAPITAL_5M = 'Capital > $5M';
    public static final String RECOVERABLE_AREA_NOT_EQUAL_RENTABLE_AREA = 'Recoverable area is not same as Rentable area';
    public static final String CHANGE_IN_FITOUT_DAYS = 'Change in the Fitout days';
    public static final String SECURITY_POSITION_COUNT_4 = 'Security position count < 4';
    public static final String OPTION_LEASE = 'Option Lease';
    public static final String FITOUT_CONTRIBUTION_LESS_THAN_A_YEAR = 'Fitout contribution for term less than a year';
    public static final String TERM_MORE_THAN_10_YEARS = 'Term is more than 10 years';
    public static final String MANUAL = 'Manual';
    public static final String REV_ASSURANCE_MANUAL_PROCESSING = '65 - Revenue Assurance Manual Processing';
    
    //Chatter Approval Status Messages
    public static final String RM_RISK_APRV_REQ = 'RM and Risk Approval request';
    public static final String FINAL_APRV_REQ = 'Final Approval request';
    public static final String RM_APRV_REQ = 'RM Approval request';
    public static final String IN_APPR_REQ = 'Initial Approval request';
    public static final String LIC_APRV_REQ = 'Licence Approval request';
    public static final String RISK_APPRV_REQ= 'Risk Approval request';
    public static final String RM_RISK_APPRV_REQ= 'RM and Risk Approval request';
    
    //ABN Validation
    public static final String LINK_ABR_BUSINESS = 'https://abr.business.gov.au/abrxmlsearch/ABRXMLSearch.asmx/';
    public static final String LINK_CONT_ABR_BUSINESS = '?authenticationGuid=ed19f77e-8587-4292-a9cf-4c00ad377150';
    public static final String POST = 'POST';
    public static final String GET = 'GET';
    public static final String OPEN_BRACKET = '{';
    public static final String CLOSE_BRACKET = '}';
    public static final String ABN_SEARCH_METHOD = 'SearchByABNv201408';
    public static final String ACN_SEARCH_METHOD = 'SearchByASICv201408';
    public static final String HIST_DET_URL_STRING = '&includeHistoricalDetails=';
    public static final String SEARCH_STR_URL_STRING = '&searchString=';
    public static final String Y = 'Y';
    public static final String N = 'N';
    public static final String AMP = '&';
    public static final String URL_ABN = 'abn=';
    public static final String URL_ACN = 'acn=';
    public static final String URL_NAME = 'name=';
    public static final String ABN_MATCH_NAME_URL = 'https://abr.business.gov.au/json/MatchingNames.aspx?';
    public static final String NZBN_HEADER_ACCEPT = 'Accept';
    public static final String NZBN_HEADER_APP_JSON = 'application/json';
    public static final String NZBN_HEADER_AUTH = 'Authorization';
    public static final String NZBN_HEADER_BEARER = 'Bearer ';
    public static final String MAX_RESULTS = 'maxResults=20';
    
    //Precedent Usage Clause
    public static final String PERMITTED_USE = 'Permitted Use';
    public static final String USAGE = 'Usage';
    
    public static final String ABN = 'ABN';
    public static final String ACN = 'ACN';
    public static final String NZBN = 'NZBN';
    public static final String VALID = 'Valid';
    public static final String INVALID = 'Invalid';
    
    //Task Types API Name
    public static final String TASK_TYPE_APPROVAL_REJECTED='67 - Update the Opportunity and Resubmit for Approval';
    public static final String TASK_SUBJECT='Update the Opportunity and Resubmit for Approval';
    public static final String TASK_TYPE_CONFIRM_JV_APPROVAL = '66 - Confirm JV Approval not required';
    public static final String TASK_TYPE_INSTRUCT_SOLICITOR = '39 - Instruct Solicitor';
    // START RPP-10481 LF
    public static final String TASK_TYPE_SEND_DOCS_FOR_EXECUTION = '23 - Send Documents for Execution';
    public static final String TASK_UPDATE_CHILD_CASES = 'Update Child Cases';
    
    // Task Priority Values
    public static final String TASK_PRIORITY_NORMAL = 'Normal';
    public static final String TASK_PRIORITY_HIGH = 'High';
    // END RPP-10481 LF
    
    //Task Record Types
    public static final String TAS_AUTOMATIC_DEV_NAME = 'TASAutomatic';
    public static final String TAS_ADHOC_DEV_NAME = 'TASAdhoc';
    
    //Tier Picklist Values
    public static final String TIER_ALL = 'All';
    
    //
    public static final String TRADING_NAME = 'Trading Name';
    public static final String BUSINESS_NAME = 'Business Name';
    public static final String ENTITY_NAME = 'Entity Name';
    
    public static final String GROWTH_PARTNER = 'Growth Partner';
    public static final String STRATEGIC_PARTNER = 'Strategic Partner';
    public static final String NATIONAL_CHANGE_IN_SECURITY = 'National Change in Security Position';
    
    public static final String ANNUAL_MINIMUM_RENT_API = 'AnnualMinimumRent__c';

    
    //mock json return for ABN/NZBN Test class
    public static final String MOCK_HTTP_RESPONSE_BODY_NZBN = '{"pageSize":10,"page":0,"totalItems":1,"sortBy":null,"sortOrder":null,"items":[{"nzbn":"1231231231231","entityName":"test","entityType":{"id":"LTD","name":"test"},"sourceRegisterUniqueId":"0000000","tradingNames":[],"previousEntityNames":[],"previousTradingNames":[],"industryClassification":[{"uniqueIdentifier":null,"classificationCode":"C000000","classificationDescription":"test"}],"entityStatus":{"id":50,"name":"Registered"},"changeEvent":[],"registrationDate":"2018-01-01T13:57:36.000+1200","entity":{"rel":"self","href":"../1231231231231"}}],"links":[]}';
    public static final String MOCK_HTTP_RESPONSE_BODY_ABN = '{"Message":"","Names":[{"Abn":"12312312312","AbnStatus":"9876543211","IsCurrent":true,"Name":"Test","NameType":"Trading Name","Postcode":"4321","Score":100,"State":"QLD"},{"Abn":"1234567890","AbnStatus":"9876543212","IsCurrent":true,"Name":"Test Name","NameType":"Entity Name","Postcode":"1234","Score":84,"State":"SA"}]}';
    
    public static final String SHOP = 'Shop';
    
    public static final String CONTRACTID = 'ContractId';
    public static final String EFFECTIVE_DATE = 'EffectiveDate';
    public static final String COLON = ':';
    public static final String JDE_LEASE = 'JDE Lease';
    public static final String LV02_QUERY_SELECT = 'SELECT Id, Name, ';
    public static final String LV02_QUERY_WHERE = ' WHERE Id = ';
    public static final String CONTRACT_API = 'Contract__c';
    public static final String APOSTROPHE = '\'';
    
    public static final String OPPSTAGE_CLOSE_COMPLETED = 'Closed - Completed';
    public static final String VARIATION_TO_LEASE = 'Variation to Lease';
    public static final String VARIATION_OF_LEASE = 'Variation of Lease';
    
    // ContactVersion.DocumentType__c
    public static final String SKETCH_PLAN_DOC = 'Sketch Plan';
    public static final String LEASE_PLAN_DOC = 'Lease Plan';
    
    // Profile
    public static final String SCGRETAILCENTREMGT = 'SCG-Retail CentreMgt';
    
    // Contract Record Type
    public static final String CON_COMMERCIAL_CONTRACT = 'CON - Commercial Contract';
    public static final String CON_RETAIL_CONTRACT = 'CON - Retail Contract';
    
    // Contract Lease Status
    public static final String CON_EXPIRED_STATUS = 'Expired';
    
    //Contract Lease Types
    public static final String CON_LEASE_TYPE_MAJOR = 'MJ';
    
    //Opportunity Type Picklist Values
    public static final String OPP_TYPE_NEW_LEASE = 'New Lease';
    
    //Case Teams
    public static final String NATIONAL_REQUEST_CASE_TEAM = 'National Request';
    public static final String PROPERTY_REQUEST_CASE_TEAM = 'Property Request';
    
    //Task Template And Condition - TaskType
    public static FINAL String TASKTEMPLATE_GENERATE_OFFER_LETTER = 'Generate Offer Letter';
    public static FINAL String TASKTEMPLATE_ISSUE_OFFER_LETTER = 'Issue Offer Letter';
    public static FINAL String TASKTEMPLATE_RECEIVE_SIGNED_OFFER_LETTER = 'Receive Signed Offer Letter';
    public static FINAL String TASKTEMPLATE_RETAIL_ADMINISTRATOR_REVIEW = 'Retail Administrator Review';
    public static FINAL String TASKTEMPLATE_ACCEPT_OFFER_LETTER = 'Accept Offer Letter';
    public static FINAL String TASKTEMPLATE_SUBMIT_FOR_APPROVAL = 'Submit for Approval';
    public static FINAL String TASKTEMPLATE_UPDATE_CASE_TERMS = 'Update Case Terms & Resubmit for Approval';
    
    public static FINAL String CASE_MILESTONE_OFFER_LETTER_GENERATED = 'Offer Letter Generated';
    public static FINAL String CASE_MILESTONE_OFFER_LETTER_ISSUED = 'Offer Letter Issued';
    public static FINAL String CASE_MILESTONE_OFFER_LETTER_RECEVIED = 'Offer Letter Received';
    public static FINAL String CASE_MILESTONE_PENDING_RETAIL_ADMIN_REVIEW = 'Pending Retail Admin Review';
    public static FINAL String CASE_MILESTONE_RETAIL_ADMIN_REVIEW_COMPLETED = 'Retail Admin Review Complete';
    public static FINAL String CASE_MILESTONE_OFFER_LETTER_ACCEPTED = 'Offer Letter Accepted';
}