objects/ClauseLibrary__c.object
<CustomObject>
    <description>&lt;CLA&gt; - Represents a list of clauses for scentre group eg. Standard Clauses, Non-Standard Clauses</description>
    <fields>
        <fullName>HighRiskClause__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag drives reporting on Opportunity</description>
        <inlineHelpText>This is applicable for Exclusions, Exclusivity and First Right of Refusal only.</inlineHelpText>
        <label>High Risk Clause</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RiskApplies__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Risk Applies?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <description>This is sub type if clauses. It&apos;s dependent on the type of the clause</description>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ClauseSubType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ClauseType</valueSetName>
        </valueSet>
    </fields>
    <label>Clause Library</label>
    <nameField>
        <label>Clause Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clause Libraries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityClause__c.object
<CustomObject>
    <description>&lt;OPC&gt; - Represents a clause applied to a deal.</description>
    <fields>
        <fullName>RiskApplies__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This flag is ticked if there is a risk applied Clause associated with this space. Please contact Retail Admin for any questions.</inlineHelpText>
        <label>Risk Applies?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <description>This is the sub type of the clause. It&apos;s dependent on type of clause</description>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ClauseSubType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ClauseType</valueSetName>
        </valueSet>
    </fields>
    <label>Opportunity Clause</label>
    <nameField>
        <label>Opportunity Clauses Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Clauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/ClauseSubType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Aggregate Rent &gt;$7.5M</fullName>
    </customValue>
    <customValue>
        <fullName>Amendment to Repayment of Fitout Contribution</fullName>
    </customValue>
    <customValue>
        <fullName>Area &gt; 2500sqm</fullName>
    </customValue>
    <customValue>
        <fullName>Capital &gt; $5M</fullName>
    </customValue>
    <customValue>
        <fullName>Capped Occ Costs</fullName>
    </customValue>
    <customValue>
        <fullName>Capped Outgoings, statutory charges</fullName>
    </customValue>
    <customValue>
        <fullName>Change in Usage</fullName>
    </customValue>
    <customValue>
        <fullName>Compensation Clause</fullName>
    </customValue>
    <customValue>
        <fullName>Co-Tenancy Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>Delete or Amend Demolition Clause ability to invoke demo cl.</fullName>
    </customValue>
    <customValue>
        <fullName>Delete or Amend Demolition Clause ability to invoke relocation cl.</fullName>
    </customValue>
    <customValue>
        <fullName>Early termination rights</fullName>
    </customValue>
    <customValue>
        <fullName>Exclusion Zone</fullName>
    </customValue>
    <customValue>
        <fullName>Exclusivity</fullName>
    </customValue>
    <customValue>
        <fullName>Fitout Period</fullName>
    </customValue>
    <customValue>
        <fullName>Guarantee</fullName>
    </customValue>
    <customValue>
        <fullName>Lessee Owns Fitout paid for by fitout contrib.</fullName>
    </customValue>
    <customValue>
        <fullName>Amendment to Lessor indemnities and warranties</fullName>
    </customValue>
    <customValue>
        <fullName>National Change in Security Position</fullName>
    </customValue>
    <customValue>
        <fullName>National Change in Usage</fullName>
    </customValue>
    <customValue>
        <fullName>Deviation from Security Policy</fullName>
    </customValue>
    <customValue>
        <fullName>Non-standard fitout period</fullName>
    </customValue>
    <customValue>
        <fullName>Option Lease</fullName>
    </customValue>
    <customValue>
        <fullName>Percentage Rent</fullName>
    </customValue>
    <customValue>
        <fullName>Radius Clause</fullName>
    </customValue>
    <customValue>
        <fullName>Reduced Outgoings</fullName>
    </customValue>
    <customValue>
        <fullName>Rent Free Period</fullName>
    </customValue>
    <customValue>
        <fullName>Rent Review</fullName>
    </customValue>
    <customValue>
        <fullName>Rent Review which contravenes Act</fullName>
    </customValue>
    <customValue>
        <fullName>Right of Refusal</fullName>
    </customValue>
    <description>This is dependent picklist of clause Type</description>
    <masterLabel>Clause Sub Type</masterLabel>
</GlobalValueSet>

classes/RiskOpportunityClauseControllerTest.cls
/**
 * @author:			Kyle Tan
 * @desc:			test class for RiskOpportunityClauseController
 **/
@isTest
private class RiskOpportunityClauseControllerTest {
    
	@testSetup
    private static void testSetup() {
        Map<String, Schema.RecordTypeInfo> accountRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(CONSTANTS.ACCOUNT);
        Map<String, Schema.RecordTypeInfo> oppClauseTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(Constants.OPPORTUNITY_CLAUSE_API);
        Map<String, Schema.RecordTypeInfo> clauseLibTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(Constants.CLAUSE_LIBRARY_API);
        List<Pricebook2> priceBookList = new List<Pricebook2>();
        List<Property__c> propertyList = new List<Property__c>();
        List<ClauseLibrary__c> clauseLibList = new List<ClauseLibrary__c>();
        List<OpportunityClause__c> oppClauseList = new List<OpportunityClause__c>();
        List<Opportunity> oppList = new List<Opportunity>();
        List<Account> accList = new List<Account>();
        
        //Create Price Book
        priceBookList = TestDataFactory.createPricebook(1);
        database.insert(priceBookList);
        
        //Create Property
        propertyList = TestDataFactory.createProperty(1, priceBookList[0]);
        database.insert(propertyList);
        
        //Create Account
        accList = TestDataFactory.createAccountBulk(1, propertyList[0].Id, accountRecordTypeMapByName.get(Constants.PROPERTY_BASED).getRecordTypeId());
        database.insert(accList);
        
        //Create Clause Library
        clauseLibList = TestDataFactory.createClauseLibrary(2);
        clauseLibList[1].Type__c = Constants.CLAUSE_TYPE_ACCEPTANCE;
        clauseLibList[1].SubType__c = null;
        clauseLibList[1].RiskApplies__c = false;
        clauseLibList[1].HighRiskClause__c = false;
        clauseLibList[1].RecordTypeId = clauseLibTypeMapByName.get(Constants.CL_STANDARD_RESPONSES_NAME).getRecordTypeId();
        database.insert(clauseLibList);
        
        //Create Opportunity
        oppList = TestDataFactory.createOpportunity(1, accList[0]);
        database.insert(oppList);
        
        //Create Opportunity Clause
        oppClauseList = TestDataFactory.createOpportunityClause(1, oppList[0], clauseLibList[0]);
        oppClauseList[0].RecordTypeId = oppClauseTypeMapByName.get(Constants.OC_STANDARD_RESPONSE_CLAUSE_NAME).getRecordTypeId();
        oppClauseList[0].Type__c = 'Counter Offer';
        database.insert(oppClauseList);
    }
    
    /**
     * @author:			Kyle Tan
     **/
    @isTest
    private static void getOpportunityClauseTest() {
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SCG_SYS_ADM LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        LightningResponse response = new LightningResponse();
        List<Opportunity> oppList = new List<Opportunity>([SELECT Id FROM Opportunity]);
        system.runAs(testUser) {
            test.startTest();
            response = RiskOpportunityClauseController.getOpportunityClause(oppList[0].Id);
            test.stopTest();
        }
        system.assertEquals('SUCCESS', response.status);
    }
    
    /**
     * @author:			Kyle Tan
     **/
    @isTest
    private static void canUpdateTest() {
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SCG_SYS_ADM LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        List<Opportunity> oppList = new List<Opportunity>([SELECT Id, OwnerId FROM Opportunity]);
        Boolean canUpdate = false;
        system.runAs(testUser) {
            test.startTest();
            canUpdate = RiskOpportunityClauseController.canUpdate(oppList[0]);
            test.stopTest();
        }
        system.assertEquals(false, canUpdate);
    }
    
    /**
     * @author:			Kyle Tan
     **/
    @isTest
    private static void updateOpportunityClauseTest() {
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SCG_SYS_ADM LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        LightningResponse response = new LightningResponse();
        List<OpportunityClause__c> oppClauseList = new List<OpportunityClause__c>([SELECT Id FROM OpportunityClause__c]);
        system.runAs(testUser) {
            test.startTest();
            response = RiskOpportunityClauseController.updateOpportunityClause(JSON.serialize(oppClauseList));
            test.stopTest();
        }
        system.assertEquals('SUCCESS', response.status);
    }
}