objects/ClauseLibrary__c.object
<CustomObject>
    <description>&lt;CLA&gt; - Represents a list of clauses for scentre group eg. Standard Clauses, Non-Standard Clauses</description>
    <fields>
        <fullName>HighRiskClause__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag drives reporting on Opportunity</description>
        <inlineHelpText>This is applicable for Exclusions, Exclusivity and First Right of Refusal only.</inlineHelpText>
        <label>High Risk Clause</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ReasonRecommendation__c</fullName>
        <label>Reason Recommendation</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RiskApplies__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Risk Applies?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <description>This is sub type if clauses. It&apos;s dependent on the type of the clause</description>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ClauseSubType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ClauseType</valueSetName>
        </valueSet>
    </fields>
    <label>Clause Library</label>
    <nameField>
        <label>Clause Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clause Libraries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract__c.object
<CustomObject>
    <description>&lt;CON&gt; - Represents a contract signed with a retailer. Either lease, Commercial lease, license agreement</description>
    <fields>
        <fullName>Category__c</fullName>
        <formula>TEXT(Account__r.Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Retailer grouping based on usage and product/service offering.</inlineHelpText>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeaseStatus__c</fullName>
        <label>Lease Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                    <label>Assigned</label>
                </value>
                <value>
                    <fullName>B</fullName>
                    <label>Assigned - Holdover</label>
                </value>
                <value>
                    <fullName>C</fullName>
                    <label>Assigned - after Renewal</label>
                </value>
                <value>
                    <fullName>D</fullName>
                    <label>Future - D&amp;C</label>
                </value>
                <value>
                    <fullName>E</fullName>
                    <label>Expired</label>
                </value>
                <value>
                    <fullName>F</fullName>
                    <label>Future Lease</label>
                </value>
                <value>
                    <fullName>H</fullName>
                    <label>Holdover</label>
                </value>
                <value>
                    <fullName>I</fullName>
                    <label>Extension of lease term</label>
                </value>
                <value>
                    <fullName>K</fullName>
                    <label>Lockout</label>
                </value>
                <value>
                    <fullName>M</fullName>
                    <label>Marketing Fund</label>
                </value>
                <value>
                    <fullName>N</fullName>
                    <label>New Merchant (Current)</label>
                </value>
                <value>
                    <fullName>O</fullName>
                    <label>New Merchant (Cur) - Holdover</label>
                </value>
                <value>
                    <fullName>R</fullName>
                    <label>New Lease (Renewal)</label>
                </value>
                <value>
                    <fullName>U</fullName>
                    <label>New Lease (Renewal) - Holdover</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipName>Leases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Reduced ROLO</fullName>
                </value>
                <value>
                    <fullName>No ROLO</fullName>
                </value>
                <value>
                    <fullName>Over payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lease</fullName>
                </value>
                <value>
                    <fullName>License Agreement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OpportunityClause__c.object
<CustomObject>
    <description>&lt;OPC&gt; - Represents a clause applied to a deal.</description>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Clauses</relationshipLabel>
        <relationshipName>Opportunity_Clauses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ReasonRecommendation__c</fullName>
        <inlineHelpText>Retail Admin Use Only.</inlineHelpText>
        <label>Reason Recommendation</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ReferencedClause__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referenced Clause</label>
        <referenceTo>ClauseLibrary__c</referenceTo>
        <relationshipLabel>Opportunity Clause</relationshipLabel>
        <relationshipName>Opportunity_Clauses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RiskApplies__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This flag is ticked if there is a risk applied Clause associated with this space. Please contact Retail Admin for any questions.</inlineHelpText>
        <label>Risk Applies?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <description>This is the sub type of the clause. It&apos;s dependent on type of clause</description>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ClauseSubType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ClauseType</valueSetName>
        </valueSet>
    </fields>
    <label>Opportunity Clause</label>
    <nameField>
        <label>Opportunity Clauses Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Clauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SpaceType</valueSetName>
        </valueSet>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/ClauseSubType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Aggregate Rent &gt;$7.5M</fullName>
    </customValue>
    <customValue>
        <fullName>Amendment to Repayment of Fitout Contribution</fullName>
    </customValue>
    <customValue>
        <fullName>Area &gt; 2500sqm</fullName>
    </customValue>
    <customValue>
        <fullName>Capital &gt; $5M</fullName>
    </customValue>
    <customValue>
        <fullName>Capped Occ Costs</fullName>
    </customValue>
    <customValue>
        <fullName>Capped Outgoings, statutory charges</fullName>
    </customValue>
    <customValue>
        <fullName>Change in Usage</fullName>
    </customValue>
    <customValue>
        <fullName>Compensation Clause</fullName>
    </customValue>
    <customValue>
        <fullName>Co-Tenancy Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>Delete or Amend Demolition Clause ability to invoke demo cl.</fullName>
    </customValue>
    <customValue>
        <fullName>Delete or Amend Demolition Clause ability to invoke relocation cl.</fullName>
    </customValue>
    <customValue>
        <fullName>Early termination rights</fullName>
    </customValue>
    <customValue>
        <fullName>Exclusion Zone</fullName>
    </customValue>
    <customValue>
        <fullName>Exclusivity</fullName>
    </customValue>
    <customValue>
        <fullName>Fitout Period</fullName>
    </customValue>
    <customValue>
        <fullName>Guarantee</fullName>
    </customValue>
    <customValue>
        <fullName>Lessee Owns Fitout paid for by fitout contrib.</fullName>
    </customValue>
    <customValue>
        <fullName>Amendment to Lessor indemnities and warranties</fullName>
    </customValue>
    <customValue>
        <fullName>National Change in Security Position</fullName>
    </customValue>
    <customValue>
        <fullName>National Change in Usage</fullName>
    </customValue>
    <customValue>
        <fullName>Deviation from Security Policy</fullName>
    </customValue>
    <customValue>
        <fullName>Non-standard fitout period</fullName>
    </customValue>
    <customValue>
        <fullName>Option Lease</fullName>
    </customValue>
    <customValue>
        <fullName>Percentage Rent</fullName>
    </customValue>
    <customValue>
        <fullName>Radius Clause</fullName>
    </customValue>
    <customValue>
        <fullName>Reduced Outgoings</fullName>
    </customValue>
    <customValue>
        <fullName>Rent Free Period</fullName>
    </customValue>
    <customValue>
        <fullName>Rent Review</fullName>
    </customValue>
    <customValue>
        <fullName>Rent Review which contravenes Act</fullName>
    </customValue>
    <customValue>
        <fullName>Right of Refusal</fullName>
    </customValue>
    <description>This is dependent picklist of clause Type</description>
    <masterLabel>Clause Sub Type</masterLabel>
</GlobalValueSet>

globalValueSets/SpaceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Shop</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Kiosk</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Office Suite</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Store Room</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Seating</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sundry Property</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Garage / Parking</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sundry</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Space Bank</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Common Mall</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>Re-design</label>
    </customValue>
    <customValue>
        <fullName>Seating License</fullName>
        <isActive>false</isActive>
        <label>Seating License</label>
    </customValue>
    <customValue>
        <fullName>Sundry Site</fullName>
        <isActive>false</isActive>
        <label>Sundry Site</label>
    </customValue>
    <masterLabel>Space Type</masterLabel>
</GlobalValueSet>

classes/DisplayRiskClauseController.cls
public class DisplayRiskClauseController {
    public class Response{
        @AuraEnabled
        public String status; 
        @AuraEnabled
        public String message;
        @AuraEnabled
        public String returnValue;
        
        public Response(){
            this.status ='Success';
            this.message = '';
            this.returnValue = '';
        }
    }
    
    public class displayClauseWrapper{        
        public String accountName;
        public String accountId;
        public String clauseName;
        public String clauseId;
        public String clauseType;
        public String spaceName;
        public Id spaceId;
        public String propertyName;
        public String accountCategory;
        public Boolean highRiskClause;
        public Boolean riskApplies;
        public Boolean approved;
        public String reasonRecommendation;
    }
    
    @AuraEnabled
    public static Response getDetails(Id recordID, String sourceName){
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(DisplayRiskClauseController.class.getName());
        Response responsedetails=new Response();   
        List<OpportunityClause__c> oppClauseRecordList=new List<OpportunityClause__c>();
        Id opportunityRecordId;
        Schema.SObjectType sobjectype=recordID.getsobjecttype();
        String accountCategory=null;
        if(String.isNotBlank(recordID)){
            List<displayClauseWrapper> displayWrapperList = new List<displayClauseWrapper>();
            if(String.isBlank(sourceName)){            
                
                Set<String> contarctStatusSet=new Set<String>();
                List<String> validcontarctStatus=Label.ContractStausforRisk.split(';');
                contarctStatusSet.addAll(validcontarctStatus);
                Opportunity opportunityRecord;
                List<Contract__c> contractRecordList =new List<Contract__c>();
                Space__c spaceRecord;
                if(sobjectype+'' == Constants.OPPORTUNITY){
                    opportunityRecordId=recordID;
                    try {
                        opportunityRecord =[Select id,Property__c,Space__c,Account.Category__c from Opportunity where Id=:recordID]; 
                    } catch (Exception e) {
                        opportunityRecord = NULL;
                    }
                    
                    accountCategory=OpportunityRecord.Account.Category__c;
                    recordID=OpportunityRecord.Property__c;
                    
                }            
                if(sobjectype+'' == Constants.SPACE){
                    try {
                        spaceRecord=[Select id,Property__c from Space__c where Id =: recordID];
                    } catch (Exception e) {
                        spaceRecord = NULL;
                    }
                    recordID=spaceRecord.Property__c;
                }
                contractRecordList = [SELECT Id,Name,Property__c,Opportunity__c,LeaseStatus__c from Contract__c 
                                      WHERE Property__c =: recordID
                                      AND (LeaseStatus__c IN : contarctStatusSet)];
                
                Set<Id> opportunityIdSet = new Set<Id>();
                for(Contract__c contr: contractRecordList){
                    if(contr.Opportunity__c!=opportunityRecordId||String.isBlank(opportunityRecordId)){
                        opportunityIdSet.add(contr.Opportunity__c);
                    }
                }
                Set<String> impactedRCASet=new Set<String>();
                impactedRCASet.add('Exclusivity');
                impactedRCASet.add('Exclusion Zone');
                impactedRCASet.add('Right of Refusal');
                
                try{
                    if(sobjectype+'' == Constants.OPPORTUNITY){
                        oppClauseRecordList = [SELECT Id, Name,Type__c,Opportunity__r.Space__c,Opportunity__r.Space__r.Name,
                                               Opportunity__r.Account.Id,Opportunity__r.Account.Name,Opportunity__r.Property__r.Name,
                                               toLabel(Opportunity__r.Account.Category__c),ReferencedClause__r.HighRiskClause__c,
                                               ReferencedClause__r.RiskApplies__c,ReasonRecommendation__c,Approved__c
                                               FROM OpportunityClause__c WHERE Opportunity__c IN: opportunityIdSet 
                                               //AND (ReferencedClause__r.HighRiskClause__c=true)
                                               AND ReferencedClause__r.SubType__c IN: impactedRCASet 
                                               ORDER BY ReferencedClause__r.HighRiskClause__c,Opportunity__r.Space__r.Name,Opportunity__r.Account.Category__c];
                    }else{
                        oppClauseRecordList = [SELECT Id, Name,Type__c,Opportunity__r.Space__c,Opportunity__r.Space__r.Name,
                                               Opportunity__r.Account.Id,Opportunity__r.Account.Name,Opportunity__r.Property__r.Name,
                                               toLabel(Opportunity__r.Account.Category__c),ReferencedClause__r.HighRiskClause__c,
                                               ReferencedClause__r.RiskApplies__c,ReasonRecommendation__c,Approved__c
                                               FROM OpportunityClause__c WHERE Opportunity__c IN: opportunityIdSet 
                                               AND (ReferencedClause__r.HighRiskClause__c=true OR ReferencedClause__r.RiskApplies__c = true) 
                                               ORDER BY ReferencedClause__r.HighRiskClause__c DESC,Opportunity__r.Space__r.Name,Opportunity__r.Account.Category__c];
                    }                    
                } catch(Exception e) {
                    responsedetails.status = Constants.FAILED;
                    responsedetails.message = e.getMessage();
                    errorHandler.createError(e);
                } 
            }
            else if(sourceName=='Risktab'){
                oppClauseRecordList = [SELECT Id, Name,Type__c,Opportunity__r.Space__c,Opportunity__r.Space__r.Name,
                                       Opportunity__r.Account.Id,Opportunity__r.Account.Name,Opportunity__r.Property__r.Name,
                                       toLabel(Opportunity__r.Account.Category__c),ReferencedClause__r.HighRiskClause__c,
                                       ReferencedClause__r.RiskApplies__c, ReasonRecommendation__c,Approved__c
                                       FROM OpportunityClause__c WHERE Opportunity__c =: recordID
                                       AND (ReferencedClause__r.RiskApplies__c = true OR ReferencedClause__r.HighRiskClause__c=true) 
                                       ORDER BY ReferencedClause__r.HighRiskClause__c,Opportunity__r.Space__r.Name];
            }
            for(OpportunityClause__c opptyClauseRecord: oppClauseRecordList){
                displayClauseWrapper displayWrapper = new displayClauseWrapper();
                displayWrapper.accountName=opptyClauseRecord.Opportunity__r.Account.Name;
                displayWrapper.accountId=opptyClauseRecord.Opportunity__r.Account.Id;
                displayWrapper.clauseName=opptyClauseRecord.Name;
                displayWrapper.clauseId=opptyClauseRecord.Id;
                displayWrapper.clauseType=opptyClauseRecord.Type__c;
                displayWrapper.spaceName=opptyClauseRecord.Opportunity__r.Space__r.Name;
                displayWrapper.spaceId=opptyClauseRecord.Opportunity__r.Space__c;
                displayWrapper.propertyName=opptyClauseRecord.Opportunity__r.Property__r.Name;
                displayWrapper.accountCategory=opptyClauseRecord.Opportunity__r.Account.Category__c;
                displayWrapper.highRiskClause=opptyClauseRecord.ReferencedClause__r.HighRiskClause__c;
                displayWrapper.riskApplies=opptyClauseRecord.ReferencedClause__r.RiskApplies__c;
                displayWrapper.reasonRecommendation = opptyClauseRecord.ReasonRecommendation__c;
                displayWrapper.approved =opptyClauseRecord.Approved__c;
                displayWrapperList.add(displayWrapper);
            }
            
            try {
                responsedetails.returnValue = JSON.serialize(displayWrapperList);
            } catch (Exception e) {
                responsedetails.returnValue = NULL;
            }
        }
        return responsedetails;
    }
    
    @AuraEnabled
    public static Response updateOpportunityClause(String clauseWrapperJSON){
        OpportunityClause__c oppClauseTemp;
        Response res = new Response();
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(DisplayRiskClauseController.class.getName());
        List<DisplayClauseWrapper> clauseWrapperList;
        List<OpportunityClause__c> opportunityClauseList = new List<OpportunityClause__c>();
        if(clauseWrapperJSON != '' && clauseWrapperJSON != null){
            try {
                clauseWrapperList = (List<DisplayClauseWrapper>) JSON.deserialize(clauseWrapperJSON, List<DisplayClauseWrapper>.class);
            } catch (Exception e) {
                clauseWrapperList = NULL;
            }
            
        }
        for(DisplayClauseWrapper cWrapper :clauseWrapperList){
            oppClauseTemp = new OpportunityClause__c();   
            oppClauseTemp.Id = cWrapper.clauseId;
            oppClauseTemp.ReasonRecommendation__c = cWrapper.reasonRecommendation;
            opportunityClauseList.add(oppClauseTemp);
        }
        if(opportunityClauseList != null && opportunityClauseList.size() > 0){
            try{
                Database.update(opportunityClauseList);
            } catch(Exception e){
                res.status = Constants.FAILED;
                res.message = e.getMessage();
                errorHandler.createError(e);
            }
        }       
        errorHandler.save();
        return res;
    }
    
    @AuraEnabled
    public static Boolean isColumnEditable(Opportunity opportunity){
        Boolean canUpdate = false;        
        Profile prof = DatabaseSOQLBank.getProfile(UserInfo.getProfileId());        
        if(!Constants.OPPTY_STAGENAME_ISSUE_LEASE.equalsIgnoreCase(opportunity.StageName) 
           && (opportunity.OwnerId == UserInfo.getUserId() || Constants.SYSTEM_ADMINISTRATOR.equalsIgnoreCase(prof.Name))){
               canUpdate = true;
           }        
        return canUpdate;
    }
    
    @AuraEnabled
    public static Boolean userHasEditAccess(Id opportunityId) {
        Boolean hasEditAccess = false;
        Boolean isOppLocked = false;
        Boolean isDealAchieved = false;
        Boolean userAccess = false;
        opportunity oppRecord = new Opportunity();
        if(opportunityId != null) {
            try {
                oppRecord = [SELECT id, DealAchieved__c FROM Opportunity WHERE id =: opportunityId];
            } catch(Exception e) {
                oppRecord = null;
            }
            if(Approval.isLocked(opportunityId)) {
                isOppLocked = true;
            }
        }
        if(oppRecord != null) {
            isDealAchieved = oppRecord.DealAchieved__c;
        }
        for(UserRecordAccess usrRecAcc : [SELECT RecordId, HasEditAccess FROM UserRecordAccess WHERE UserId =: userInfo.getUserId() AND RecordId =:opportunityId]){
            hasEditAccess = usrRecAcc.HasEditAccess;
        }      
        if(!isOppLocked && !isDealAchieved && hasEditAccess) {
            userAccess = true;
        }
        return userAccess;
    }
}