objects/ClauseLibrary__c.object
<CustomObject>
    <description>&lt;CLA&gt; - Represents a list of clauses for scentre group eg. Standard Clauses, Non-Standard Clauses</description>
    <fields>
        <fullName>ClauseDetails__c</fullName>
        <label>Clause Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RiskApplies__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Risk Applies?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RiskClauseNotifyUsers__c</fullName>
        <label>Risk Clause Notify Users</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RoleType</valueSetName>
        </valueSet>
    </fields>
    <label>Clause Library</label>
    <nameField>
        <label>Clause Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clause Libraries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityClause__c.object
<CustomObject>
    <description>&lt;OPC&gt; - Represents a clause applied to a deal.</description>
    <fields>
        <fullName>ClauseDetails__c</fullName>
        <inlineHelpText>Please enter the information required.</inlineHelpText>
        <label>Clause Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ReferencedClause__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referenced Clause</label>
        <referenceTo>ClauseLibrary__c</referenceTo>
        <relationshipLabel>Opportunity Clause</relationshipLabel>
        <relationshipName>Opportunity_Clauses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RiskApplies__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This flag is ticked if there is a risk applied Clause associated with this space. Please contact Retail Admin for any questions.</inlineHelpText>
        <label>Risk Applies?</label>
        <type>Checkbox</type>
    </fields>
    <label>Opportunity Clause</label>
    <nameField>
        <label>Opportunity Clauses Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Clauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PropertyTeam__c.object
<CustomObject>
    <description>&lt;PRT&gt; - Represents a internal team working for the property eg. Centre Manager, Facility Manager, RDM, Leasing Executive, Development Leasing Executive</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Property Team</relationshipLabel>
        <relationshipName>Property_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Property Team</label>
    <nameField>
        <displayFormat>PRT-{0000}</displayFormat>
        <label>Property Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/RoleType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accounts Receivable Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Administration Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Architectural Technician</fullName>
    </customValue>
    <customValue>
        <fullName>Asset General Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Centre Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Chief Operating Officer</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Leasing Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Leasing General Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Leasing Regional Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Property Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Retail Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate Legal</fullName>
    </customValue>
    <customValue>
        <fullName>D&amp;C Special Project Coordinator</fullName>
    </customValue>
    <customValue>
        <fullName>Development Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Development Finance Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Director LARS &amp; NZ Development</fullName>
    </customValue>
    <customValue>
        <fullName>Facilities Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Filing Clerk</fullName>
    </customValue>
    <customValue>
        <fullName>Fitout Contributions Admin</fullName>
    </customValue>
    <customValue>
        <fullName>General Manager Leasing</fullName>
    </customValue>
    <customValue>
        <fullName>General Manager Retail Design</fullName>
    </customValue>
    <customValue>
        <fullName>GM of Corporate Accounting</fullName>
    </customValue>
    <customValue>
        <fullName>GM Retail Admin &amp; Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Group General Manager - LARS</fullName>
    </customValue>
    <customValue>
        <fullName>Group Renewal Admin Team</fullName>
        <label>Group Renewal Team</label>
    </customValue>
    <customValue>
        <fullName>Leasing Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Leasing Finance Analyst</fullName>
    </customValue>
    <customValue>
        <fullName>Project Regional Manager - LARS</fullName>
    </customValue>
    <customValue>
        <fullName>Project Retail Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>Project Retail Design Manager</fullName>
    </customValue>
    <masterLabel>Role Type</masterLabel>
</GlobalValueSet>

classes/PostChatterToOppRiskInvocTest.cls
/**
* @author:          Sidney Garcia
* @description:     Test class for PostChatterToOppRiskInvoc
**/
@isTest
public class PostChatterToOppRiskInvocTest {
    @TestSetup private static void testSetup() {
        Map<String, Schema.RecordTypeInfo> accountRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(Constants.ACCOUNT);
        Product2 productRecord;
        List<Property__c> propertyList = new List<Property__c>();
        Account account = new Account();
        List<Account> parentAccList = new List<Account>();
        List<Opportunity> opportunityList = new List<Opportunity>();
        List<Pricebook2> pricebookList = new List<Pricebook2>();
        List<OpportunityClause__c> oppClauseList = new List<OpportunityClause__c>();
        List<ClauseLibrary__c> clauseLibList = new List<ClauseLibrary__c>();
        ClauseLibrary__c clauseLibRecord = new ClauseLibrary__c();
        
        //CREATE TEST USERS
        List<User> testUserList = new List<User>();
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :Constants.SYSTEM_ADMINISTRATOR LIMIT 1];
        
        testUserList.add(TestDataFactory.createUniqueTestUser('Test', 'User 1', profileRec.Id));
        testUserList.add(TestDataFactory.createUniqueTestUser('Test', 'User 2', profileRec.Id));
        
        Database.insert(testUserList); 
        
        //CREATE PRODUCT
        productRecord = TestDataFactory.createProduct(Constants.PRODUCT_RENT_REVIEW, Constants.RENT);
        database.insert(productRecord);
        
        //CREATE PRICEBOOK
        pricebookList = TestDataFactory.createPricebook(10);
        database.insert(pricebookList);
        pricebookList = [SELECT Id, CurrencyIsoCode FROM Pricebook2];
        
        //CREATE PROPERTY
        propertyList = TestDataFactory.createProperty(10, pricebookList[0]);
        database.insert(propertyList);
        Property__c propRec = [SELECT Id FROM Property__c LIMIT 1];
        
       //CREATE PARENT ACCOUNT
        parentAccList.addAll(TestDataFactory.createAccountBulk(1, propertyList.get(0).Id, accountRecordTypeMapByName.get(Constants.PROPERTY_BASED).getRecordTypeId()));
        database.insert(parentAccList);
        parentAccList = [SELECT Id, Property__c FROM Account LIMIT 1];
        
        //CREATE ACCOUNT
        account = TestDataFactory.createAccountwithParent(1, propertyList.get(0).Id, accountRecordTypeMapByName.get(Constants.PROPERTY_BASED).getRecordTypeId(), parentAccList.get(0).Id);
        database.insert(account);
        account = [SELECT Id, Property__c from Account LIMIT 1];
        
        //CREATE OPPORTUNITY
        opportunityList = TestDataFactory.createOpportunity(10, account);
        database.insert(opportunityList);
        
        //CREATE CLAUSE LIBRARY
        clauseLibList = TestDataFactory.createClauseLibrary(1);
        clauseLibList[0].RiskClauseNotifyUsers__c = 'Accounts Receivable Admin';
        Database.insert(clauseLibList);
        
        //CREATE OPPORTUNITY CLAUSE
        for(Opportunity opp : opportunityList){
            oppClauseList.add(
                TestDataFactory.createOpportunityClause(1, opp, clauseLibList[0])[0]
            );
        }
        Database.insert(oppClauseList);      
        
        //oppClauseList = [SELECT Id,Name, ClauseDetails__c, ReferencedClause__c,RecordType.Name,RiskApplies__c FROM OpportunityClause__c];
        //System.debug('Opp Clause List' + oppClauseList);
        
        //CREATE PROPERTY TEAM
        Id internalTeamRecTypeId;
        Map<String,Schema.RecordTypeInfo> propertyTeamRecordTypeMap = RecordTypeUtil.getAllRecordTypesByName('PropertyTeam__c');
        
        internalTeamRecTypeId = propertyTeamRecordTypeMap.get('PRT - Internal Team Member').getRecordTypeId();
        PropertyTeam__c propteam = TestDataFactory.createPropertyTeam(propertyList[0].id, 'Accounts Receivable Admin',  testUserList[0].Id, internalTeamRecTypeId);
        database.insert(propteam);
    }
    
    public static testMethod void postChatterToOppRiskTest(){
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :Constants.SYSTEM_ADMINISTRATOR LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        List<Opportunity> oppList = [SELECT Id FROM Opportunity];
        ChatterPostUtil.chatterNotificationWrapper chatterItem = new ChatterPostUtil.chatterNotificationWrapper();
        List<Id> oppIDLst = new List<Id>();
        
        for(Opportunity opp : oppList){
            oppIDLst.add(opp.Id);
        }
        
        System.runAs(testUser) {
            
            Test.startTest();
            
            PostChatterToOppRiskInvoc.postChatterToOppRisk(oppIDLst);
            Test.stopTest();
        }
        List<OpportunityFeed> oppFeed = [SELECT ID, ParentId, Body from OpportunityFeed where Id in :oppIDlst];
        System.assertEquals(true, oppFeed <> null);
        
    }
}