objects/ClauseLibrary__c.object
<CustomObject>
    <description>&lt;CLA&gt; - Represents a list of clauses for scentre group eg. Standard Clauses, Non-Standard Clauses</description>
    <fields>
        <fullName>ActivatedDate__c</fullName>
        <label>Activated Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ClauseDetails__c</fullName>
        <label>Clause Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HighRiskClause__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag drives reporting on Opportunity</description>
        <inlineHelpText>This is applicable for Exclusions, Exclusivity and First Right of Refusal only.</inlineHelpText>
        <label>High Risk Clause</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ReasonRecommendation__c</fullName>
        <label>Reason Recommendation</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RiskApplies__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Risk Applies?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ClauseStatuses</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <description>This is sub type if clauses. It&apos;s dependent on the type of the clause</description>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ClauseSubType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ClauseType</valueSetName>
        </valueSet>
    </fields>
    <label>Clause Library</label>
    <nameField>
        <label>Clause Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clause Libraries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityClause__c.object
<CustomObject>
    <description>&lt;OPC&gt; - Represents a clause applied to a deal.</description>
    <fields>
        <fullName>ClauseDetails__c</fullName>
        <inlineHelpText>Please enter the information required.</inlineHelpText>
        <label>Clause Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EffectiveFromDate__c</fullName>
        <label>Effective From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Clauses</relationshipLabel>
        <relationshipName>Opportunity_Clauses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ReasonRecommendation__c</fullName>
        <inlineHelpText>Retail Admin Use Only.</inlineHelpText>
        <label>Reason Recommendation</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ReferencedClause__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referenced Clause</label>
        <referenceTo>ClauseLibrary__c</referenceTo>
        <relationshipLabel>Opportunity Clause</relationshipLabel>
        <relationshipName>Opportunity_Clauses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RiskApplies__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This flag is ticked if there is a risk applied Clause associated with this space. Please contact Retail Admin for any questions.</inlineHelpText>
        <label>Risk Applies?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <description>This is the sub type of the clause. It&apos;s dependent on type of clause</description>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ClauseSubType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ClauseType</valueSetName>
        </valueSet>
    </fields>
    <label>Opportunity Clause</label>
    <nameField>
        <label>Opportunity Clauses Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Clauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/ClauseStatuses.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Pending Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Rejects</fullName>
    </customValue>
    <customValue>
        <fullName>Archived</fullName>
    </customValue>
    <customValue>
        <fullName>Superseded</fullName>
    </customValue>
    <masterLabel>Clause Statuses</masterLabel>
</GlobalValueSet>

globalValueSets/ClauseSubType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Aggregate Rent &gt;$7.5M</fullName>
    </customValue>
    <customValue>
        <fullName>Amendment to Repayment of Fitout Contribution</fullName>
    </customValue>
    <customValue>
        <fullName>Area &gt; 2500sqm</fullName>
    </customValue>
    <customValue>
        <fullName>Capital &gt; $5M</fullName>
    </customValue>
    <customValue>
        <fullName>Capped Occ Costs</fullName>
    </customValue>
    <customValue>
        <fullName>Capped Outgoings, statutory charges</fullName>
    </customValue>
    <customValue>
        <fullName>Change in Usage</fullName>
    </customValue>
    <customValue>
        <fullName>Compensation Clause</fullName>
    </customValue>
    <customValue>
        <fullName>Co-Tenancy Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>Delete or Amend Demolition Clause ability to invoke demo cl.</fullName>
    </customValue>
    <customValue>
        <fullName>Delete or Amend Demolition Clause ability to invoke relocation cl.</fullName>
    </customValue>
    <customValue>
        <fullName>Early termination rights</fullName>
    </customValue>
    <customValue>
        <fullName>Exclusion Zone</fullName>
    </customValue>
    <customValue>
        <fullName>Exclusivity</fullName>
    </customValue>
    <customValue>
        <fullName>Fitout Period</fullName>
    </customValue>
    <customValue>
        <fullName>Guarantee</fullName>
    </customValue>
    <customValue>
        <fullName>Lessee Owns Fitout paid for by fitout contrib.</fullName>
    </customValue>
    <customValue>
        <fullName>Amendment to Lessor indemnities and warranties</fullName>
    </customValue>
    <customValue>
        <fullName>National Change in Security Position</fullName>
    </customValue>
    <customValue>
        <fullName>National Change in Usage</fullName>
    </customValue>
    <customValue>
        <fullName>Deviation from Security Policy</fullName>
    </customValue>
    <customValue>
        <fullName>Non-standard fitout period</fullName>
    </customValue>
    <customValue>
        <fullName>Option Lease</fullName>
    </customValue>
    <customValue>
        <fullName>Percentage Rent</fullName>
    </customValue>
    <customValue>
        <fullName>Radius Clause</fullName>
    </customValue>
    <customValue>
        <fullName>Reduced Outgoings</fullName>
    </customValue>
    <customValue>
        <fullName>Rent Free Period</fullName>
    </customValue>
    <customValue>
        <fullName>Rent Review</fullName>
    </customValue>
    <customValue>
        <fullName>Rent Review which contravenes Act</fullName>
    </customValue>
    <customValue>
        <fullName>Right of Refusal</fullName>
    </customValue>
    <description>This is dependent picklist of clause Type</description>
    <masterLabel>Clause Sub Type</masterLabel>
</GlobalValueSet>

classes/ClauseSelectionController.cls
public with sharing class ClauseSelectionController {
    @AuraEnabled
    public static clauseAndOptionWrapper getClauses(id oppId) {
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(ClauseSelectionController.class.getName());
        List<OpportunityClause__c> selectedClauses;
        try{
            selectedClauses  = [SELECT Id,Name, ClauseDetails__c, ReferencedClause__c, ReferencedClause__r.HighRiskClause__c, RecordType.Name, RiskApplies__c, ReasonRecommendation__c FROM OpportunityClause__c WHERE Opportunity__c =: oppId AND RecordType.DeveloperName = :Constants.OC_LEASING_CLAUSE ORDER BY ReferencedClause__r.Name];
        } catch(Exception e) {
            errorHandler.createError(e);
        }
        
        List<OpportunityClause__c> precedentSelectedClauses;
        try{
            precedentSelectedClauses = [SELECT Id,Name, ClauseDetails__c, ReferencedClause__c, ReferencedClause__r.HighRiskClause__c, RecordType.Name, RiskApplies__c, ReasonRecommendation__c FROM OpportunityClause__c WHERE Opportunity__c =: oppId AND RecordType.DeveloperName = :Constants.OC_PRECEDENT_CLAUSE ORDER BY ReferencedClause__r.Name];
        } catch(Exception e) {
            errorHandler.createError(e);
        }
        
        Set<Id> clauseIds = new Set<Id>();
        for(OpportunityClause__c oppClauseVar : selectedClauses) {
            clauseIds.add(oppClauseVar.ReferencedClause__c);
        }
        for(OpportunityClause__c oppClauseVar : precedentSelectedClauses) {
            clauseIds.add(oppClauseVar.ReferencedClause__c);
        }
        List<ClauseLibrary__c> availableOppClause;
        try{
            availableOppClause = [SELECT Id, Name, Type__c, ActivatedDate__c, ClauseDetails__c, RiskApplies__c, ReasonRecommendation__c, HighRiskClause__c, SubType__c FROM ClauseLibrary__c WHERE Id not in: clauseIds AND Status__c = :Constants.ACTIVE AND RecordType.DeveloperName = :Constants.CL_RETAIL_CLAUSES ORDER BY Name];
        } catch(Exception e) {
            errorHandler.createError(e);
        }
        
        List<clauseWrapper> clauseWrap = new List<clauseWrapper>();
        For (ClauseLibrary__c clauseVar : availableOppClause){
            clauseWrap.add( new clauseWrapper(clauseVar, false));
        }
        
        List<String> typeOptions = new List<String>();
        
        Schema.DescribeFieldResult fieldResult = ClauseLibrary__c.Type__c.getDescribe();
        List<Schema.PicklistEntry> fieldVal = fieldResult.getPicklistValues();
        Set<String> picklistValues = new Set<String>();
        
        picklistValues.add(Constants.CLAUSE_TYPE_ACCEPTANCE);
        picklistValues.add(Constants.CLAUSE_TYPE_COUNTER_OFFER);
        
        for (Schema.PicklistEntry field: fieldVal) {
            if(!picklistValues.contains(field.getLabel())) {
                typeOptions.add(field.getLabel());
            }
        }
        
        return (new clauseAndOptionWrapper(clauseWrap, typeOptions, selectedClauses, precedentSelectedClauses));
    }
    
    @AuraEnabled
    //public static list<OpportunityClause__c> saveClause(String oppClauseSOQL, Id oppId) {
    public static LightningResponse saveClause(String oppClauseJSON, Id oppId){
        Map<String, Schema.RecordTypeInfo> oppClauseRecordTypeMapByName  = RecordTypeUtil.getAllRecordTypesByName(Constants.OPPORTUNITY_CLAUSE_API);
        LightningResponse res = new LightningResponse();
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(ClauseSelectionController.class.getName());
        List<ClauseLibrary__c> selectedClauseList = new List<ClauseLibrary__c>();
        List<OpportunityClause__c> oppClauseList = new List<OpportunityClause__c>();
        
        try{
            //selectedClause = database.query(oppClauseSOQL);
            selectedClauseList = (List<ClauseLibrary__c>) JSON.deserialize(oppClauseJSON, List<ClauseLibrary__c>.class);
        } catch (Exception e) {
            selectedClauseList = null;
            res.status = Constants.FAILED;
            res.message = e.getMessage();    
            errorHandler.createError(e);
        } 
        
        if(selectedClauseList!=null && !selectedClauseList.isEmpty()){
            for(ClauseLibrary__c clauseVar : selectedClauseList){
                OpportunityClause__c oppVar = new OpportunityClause__c();
                oppVar.Name = clauseVar.Name;
                oppVar.ClauseDetails__c = clauseVar.ClauseDetails__c;
                oppVar.EffectiveFromDate__c = clauseVar.ActivatedDate__c;
                oppVar.Opportunity__c = oppId;
                oppVar.Type__c = clauseVar.Type__c;
                oppVar.ReferencedClause__c = clauseVar.Id;
                oppVar.RiskApplies__c = clauseVar.RiskApplies__c;
                oppVar.ReasonRecommendation__c = clauseVar.ReasonRecommendation__c;
                oppVar.SubType__c = clauseVar.SubType__c;
                if(Constants.CL_STANDARD_RESPONSES.equalsIgnoreCase(clauseVar.RecordType.DeveloperName)) {
                    oppVar.RecordTypeId = oppClauseRecordTypeMapByName.get(Constants.OC_STANDARD_RESPONSE_CLAUSE_NAME).getRecordTypeId();
                } else if(Constants.CL_RETAIL_CLAUSES.equalsIgnoreCase(clauseVar.RecordType.DeveloperName)) {
                    oppVar.RecordTypeId = oppClauseRecordTypeMapByName.get(Constants.LEASING_CLAUSE).getRecordTypeId();
                }
                oppClauseList.add(oppVar);
            }
            
            try{
                Database.insert(oppClauseList);
                
                oppClauseList = [SELECT Id, Name, ClauseDetails__c, ReferencedClause__c, ReferencedClause__r.HighRiskClause__c, RecordType.Name, RiskApplies__c, ReasonRecommendation__c, SubType__c 
                                 FROM OpportunityClause__c
                                 WHERE Id IN: oppClauseList];
                
                res.returnValue = JSON.serialize(oppClauseList);
            } catch(Exception e){
                res.status = Constants.FAILED;
            	res.message = e.getMessage();
             	errorHandler.createError(e);
            }
        }
        
        errorHandler.save();
        return res;
    }
    
    @AuraEnabled
    public static OpportunityClause__c getUpdatedClause(Id oppClause) {
        return [SELECT Id,Name, ClauseDetails__c, ReferencedClause__c,RecordType.Name,RiskApplies__c, SubType__c FROM OpportunityClause__c WHERE Id =: oppClause Limit 1];
    }
    @AuraEnabled
    public static clauseAndOptionWrapper deleteClause(id oppClause,Id clauseIds) {
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(ClauseSelectionController.class.getName());
        OpportunityClause__c selectedClauses;
        try{
            selectedClauses = [SELECT Id,Opportunity__c FROM OpportunityClause__c WHERE Id =: oppClause Limit 1];
        } catch(Exception e) {
            errorHandler.createError(e);
        }
        
        Id opptyID=selectedClauses.Opportunity__c;
        delete selectedClauses;
        return getClauses(opptyID);
    }
    
    public class clauseWrapper {
        @AuraEnabled public ClauseLibrary__c clauseAvailable = new ClauseLibrary__c();
        @AuraEnabled public Boolean isSelected;
        public clauseWrapper (ClauseLibrary__c clauseAvailable, Boolean isSelected) {
            this.clauseAvailable = clauseAvailable;
            this.isSelected = isSelected;
        }
    }
    
    public class clauseAndOptionWrapper {
        @AuraEnabled public List<clauseWrapper> clauseWrap = new List<clauseWrapper>();        
        @AuraEnabled public List<String> clauseType = new List<String>();
        @AuraEnabled public List<OpportunityClause__c> clauseSelected = new List<OpportunityClause__c>();
        @AuraEnabled public List<OpportunityClause__c> precedentClauseSelected = new List<OpportunityClause__c>();
        
        public clauseAndOptionWrapper (List<clauseWrapper> clauseWrap, List<String> clauseType, List<OpportunityClause__c> clauseSelected, List<OpportunityClause__c> precedentClauseSelected){
            this.clauseWrap = clauseWrap;
            this.clauseType = clauseType;
            this.clauseSelected = clauseSelected;
            this.precedentClauseSelected = precedentClauseSelected;
            
        }
    }
    @AuraEnabled
    public static Boolean enableClauseEditUpdate(Id oppId){
        Boolean isLocked = false;
        Set<String> profilenameSet = new Set<String>();
        List<Profile> userProfile = [SELECT Id, Name FROM Profile WHERE Id=:userinfo.getProfileId()];
        String name = userProfile[0].Name;
        
        profilenameSet.add(CONSTANTS.SYSTEM_ADMINISTRATOR);
        profilenameSet.add(CONSTANTS.SCG_SYS_ADM);
        profilenameSet.add(CONSTANTS.SCG_BUSINESS_SUPPORT);
        profilenameSet.add(CONSTANTS.SCG_DATA_MIGRATION);
        profilenameSet.add(CONSTANTS.SCG_INTEGRATION);
        
        if(Approval.isLocked(oppId) && !profilenameSet.Contains(name)){
            isLocked = true;
        }
        return isLocked;
    }
    
}