objects/ClauseLibrary__c.object
<CustomObject>
    <description>&lt;CLA&gt; - Represents a list of clauses for scentre group eg. Standard Clauses, Non-Standard Clauses</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RiskClauseNotifyUsers__c</fullName>
        <label>Risk Clause Notify Users</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RoleType</valueSetName>
        </valueSet>
    </fields>
    <label>Clause Library</label>
    <nameField>
        <label>Clause Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clause Libraries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityClause__c.object
<CustomObject>
    <description>&lt;OPC&gt; - Represents a clause applied to a deal.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Clauses</relationshipLabel>
        <relationshipName>Opportunity_Clauses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ReferencedClause__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referenced Clause</label>
        <referenceTo>ClauseLibrary__c</referenceTo>
        <relationshipLabel>Opportunity Clause</relationshipLabel>
        <relationshipName>Opportunity_Clauses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Clause</label>
    <nameField>
        <label>Opportunity Clauses Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Clauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PropertyTeam__c.object
<CustomObject>
    <description>&lt;PRT&gt; - Represents a internal team working for the property eg. Centre Manager, Facility Manager, RDM, Leasing Executive, Development Leasing Executive</description>
    <fields>
        <fullName>Active__c</fullName>
        <formula>IF(AND(!TeamMember__r.IsActive, RecordType.DeveloperName=&apos;PRT_InternalTeamMember&apos;),false,IF(ISBLANK(EndDate__c),
IF(StartDate__c &lt;= TODAY(),TRUE,FALSE),
(AND(StartDate__c &lt;= TODAY(),
TODAY() &lt;= EndDate__c))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Property Team</relationshipLabel>
        <relationshipName>Property_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RoleType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TeamMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Property_Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property Team</label>
    <nameField>
        <displayFormat>PRT-{0000}</displayFormat>
        <label>Property Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/RoleType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accounts Receivable Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Administration Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Architectural Technician</fullName>
    </customValue>
    <customValue>
        <fullName>Asset General Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Centre Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Chief Operating Officer</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Leasing Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Leasing General Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Leasing Regional Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Property Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Retail Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate Legal</fullName>
    </customValue>
    <customValue>
        <fullName>D&amp;C Special Project Coordinator</fullName>
    </customValue>
    <customValue>
        <fullName>Development Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Development Finance Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Director LARS &amp; NZ Development</fullName>
    </customValue>
    <customValue>
        <fullName>Facilities Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Filing Clerk</fullName>
    </customValue>
    <customValue>
        <fullName>Fitout Contributions Admin</fullName>
    </customValue>
    <customValue>
        <fullName>General Manager Leasing</fullName>
    </customValue>
    <customValue>
        <fullName>General Manager Retail Design</fullName>
    </customValue>
    <customValue>
        <fullName>GM of Corporate Accounting</fullName>
    </customValue>
    <customValue>
        <fullName>GM Retail Admin &amp; Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Group General Manager - LARS</fullName>
    </customValue>
    <customValue>
        <fullName>Group Renewal Admin Team</fullName>
        <label>Group Renewal Team</label>
    </customValue>
    <customValue>
        <fullName>Leasing Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Leasing Finance Analyst</fullName>
    </customValue>
    <customValue>
        <fullName>Project Regional Manager - LARS</fullName>
    </customValue>
    <customValue>
        <fullName>Project Retail Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>Project Retail Design Manager</fullName>
    </customValue>
    <masterLabel>Role Type</masterLabel>
</GlobalValueSet>

classes/OpportunityChatterNotificationHelper.cls
/**
* Description: Utility class for Opportunity chatter post notification.
*/
public class OpportunityChatterNotificationHelper {
    
    public static List<ChatterPostUtil.ChatterNotificationWrapper> preparedatafornotification(List<Opportunity> OpportunityList) {
        Set<Id> propertyidSet=new Set<Id>();
        Set<Id> opportunityidSet=new Set<Id>();
        Set<String> propertyroleSet = new Set<String>();
        Map<Id,Set<String>> opportunityIdpropertyroleSet = new Map<Id,Set<String>>();
        Map<Id, Map<String,Set<Id>>> propertyIdroleandteamMap = new Map<Id, Map<String,Set<Id>>>();
        
        List<ChatterPostUtil.ChatterNotificationWrapper> chatterwrapperItemList = new List<ChatterPostUtil.ChatterNotificationWrapper>();
        
        
        if(!OpportunityList.isEmpty()&OpportunityList.size()>0){
            for(Opportunity opportunityRecord: OpportunityList){
                opportunityidSet.add(opportunityRecord.Id);
                if(String.IsNotBlank(opportunityRecord.property__c)){
                    propertyidSet.add(opportunityRecord.property__c);
                }
            }
            
            for(OpportunityClause__c oppclause: [select id,opportunity__c,ReferencedClause__c,ReferencedClause__r.RiskClauseNotifyUsers__c
                                                 from OpportunityClause__c where opportunity__c in : opportunityidSet and ReferencedClause__r.RiskClauseNotifyUsers__c != null]){
                                                     if(String.isNotBlank(oppclause.ReferencedClause__r.RiskClauseNotifyUsers__c)){
                                                         propertyroleSet.addall((oppclause.ReferencedClause__r.RiskClauseNotifyUsers__c).split(';')); 
                                                         if(opportunityIdpropertyroleSet.containskey(oppclause.opportunity__c)){
                                                             opportunityIdpropertyroleSet.get(oppclause.opportunity__c).addall((oppclause.ReferencedClause__r.RiskClauseNotifyUsers__c).split(';'));
                                                         }else{
                                                             opportunityIdpropertyroleSet.put(oppclause.opportunity__c,propertyroleSet);
                                                         }
                                                     }
                                                 }
            
            // get all active property team records.
            for(propertyteam__c propertyTeam: [select property__c,id,teammember__c,role__c from propertyteam__c where property__c in: propertyidSet and teammember__c != null AND teammember__r.IsActive=true AND Active__c=true]){
                if(propertyIdroleandteamMap.containskey(propertyTeam.property__c)){
                    if(propertyIdroleandteamMap.get(propertyTeam.property__c).containsKey(propertyTeam.role__c)){
                        propertyIdroleandteamMap.get(propertyTeam.property__c).get(propertyTeam.role__c).add(propertyTeam.teammember__c);
                    }else{
                        propertyIdroleandteamMap.get(propertyTeam.property__c).put(propertyTeam.role__c,new Set<Id>{propertyTeam.teammember__c});
                    }
                }else{
                    propertyIdroleandteamMap.put(propertyTeam.property__c,new Map<String,Set<Id>>());
                    propertyIdroleandteamMap.get(propertyTeam.property__c).put(propertyTeam.role__c,new Set<Id>{propertyTeam.teammember__c});
                }
            }
            
            for(Opportunity opportunityRecord: OpportunityList){
                
                Set<Id> mentionUsers = new Set<Id>();
                mentionUsers.add(opportunityRecord.OwnerId);
                system.debug('OWNERID: '+opportunityRecord.OwnerId);
                List<String> parameters = new List<String>();
                parameters.add(opportunityRecord.Name);
                // prepare data to post message
                ChatterPostUtil.ChatterNotificationWrapper chatterwrapperItem = new ChatterPostUtil.ChatterNotificationWrapper();
                chatterwrapperItem.subjectId = opportunityRecord.id;
                
               // if(opportunityRecord.ApprovalStatus__c==Constants.PENDING_RISK_APRV &&String.IsNotBlank(opportunityRecord.Property__c)){
                if((opportunityRecord.ApprovalStatus__c==Constants.RSKAPPR_GRANTED || opportunityRecord.ApprovalStatus__c==Constants.RISK_APPRV_REJ) &&
                   String.IsNotBlank(opportunityRecord.Property__c)){
                       
                       if(opportunityIdpropertyroleSet.containsKey(opportunityRecord.Id)){
                           Set<String> applicableroleSet=opportunityIdpropertyroleSet.get(opportunityRecord.Id);
                           if(propertyIdroleandteamMap.containsKey(opportunityRecord.Property__c)){
                               for(String applicablerole : propertyIdroleandteamMap.get(opportunityRecord.Property__c).keySet()){
                                   if(applicableroleSet.contains(applicablerole)){
                                       mentionUsers.addAll(propertyIdroleandteamMap.get(opportunityRecord.Property__c).get(applicablerole));
                                   }
                               }
                           }
                       }
                       
                       parameters.add(opportunityRecord.ApprovalStatus__c==Constants.RSKAPPR_GRANTED ? 'approved' : 'rejected');
                       
                       chatterwrapperItem.body=String.format(Label.RiskApprovalChatterMsg, parameters);
                }
                
                // logic to get message after opportunity is approved.
                // if(opportunityRecord.ApprovalStatus__c==Constants.RSKAPPR_GRANTED ||
                if(opportunityRecord.ApprovalStatus__c==Constants.FINALAPPR_GRANT||
                   opportunityRecord.ApprovalStatus__c==Constants.INIAPPR_GRANTED ||
                   opportunityRecord.ApprovalStatus__c==Constants.STRAPPOVALGRANTED){
                       
                       //if(opportunityRecord.ApprovalStatus__c==Constants.INIAPPR_GRANTED  || opportunityRecord.ApprovalStatus__c==Constants.RSKAPPR_GRANTED  || opportunityRecord.ApprovalStatus__c==Constants.FINALAPPR_GRANT){
                       if(opportunityRecord.ApprovalStatus__c==Constants.INIAPPR_GRANTED  || opportunityRecord.ApprovalStatus__c==Constants.FINALAPPR_GRANT){
                           if(opportunityRecord.GMLARS__c != null){
                               mentionUsers.add(opportunityRecord.GMLARS__c);
                           }
                           if(opportunityRecord.RMLARS__c != null){
                               mentionUsers.add(opportunityRecord.RMLARS__c);
                           }
                           if(opportunityRecord.GMRetailAdmin__c != null){
                               mentionUsers.add(opportunityRecord.GMRetailAdmin__c);
                           }
                           if(opportunityRecord.DirectorLARSNZDevelopment__c != null){
                               mentionUsers.add(opportunityRecord.DirectorLARSNZDevelopment__c);
                           }
                           if(opportunityRecord.CorporateLegal__c != null){
                               mentionUsers.add(opportunityRecord.CorporateLegal__c);
                           }
                           if(opportunityRecord.COO__c != null){
                               mentionUsers.add(opportunityRecord.COO__c);
                           }
                       }
                       if(opportunityRecord.ApprovalStatus__c==Constants.FINALAPPR_GRANT){
                           parameters.add(Constants.FINAL_APRV_REQ);
                       }else if(opportunityRecord.ApprovalStatus__c==Constants.STRAPPOVALGRANTED){
                           // this is for storeroom opportunity 
                           parameters.add(Constants.LIC_APRV_REQ);
                       }else if(opportunityRecord.ApprovalStatus__c==Constants.INIAPPR_GRANTED){
                           parameters.add(Constants.IN_APPR_REQ);
                       }
                       //else if(opportunityRecord.ApprovalStatus__c==Constants.RSKAPPR_GRANTED){
                       //    parameters.add(Constants.RISK_APPRV_REQ);
                       //}
                       chatterwrapperItem.body = String.format(Label.OpportunityApprovedChatterMessage, parameters);
                   }
                
                // logic to get message after Initial approval is rejected.
                if(opportunityRecord.ApprovalStatus__c==Constants.INI_APPV_REJ){
                    parameters.add(Constants.IN_APPR_REQ);
                    chatterwrapperItem.body = String.format(Label.OpportunityRejectedChatterMessage, parameters);
                }
                // logic to get message after Risk approval is rejected.
                //else if(opportunityRecord.ApprovalStatus__c==Constants.RISK_APPRV_REJ){
                //    parameters.add(Constants.RISK_APPRV_REQ);
                 //   chatterwrapperItem.body = String.format(Label.OpportunityRejectedChatterMessage, parameters);
                //}
                // logic to get message after final approval is rejected.
                else if(opportunityRecord.ApprovalStatus__c==Constants.FINALAPPR_REJ){
                    parameters.add(Constants.FINAL_APRV_REQ);
                    chatterwrapperItem.body = String.format(Label.OpportunityRejectedChatterMessage, parameters);
                }
                // logic to get message after license approval is rejected.
                else if(opportunityRecord.ApprovalStatus__c==Constants.STRAPPOVALREJ){
                    parameters.add(Constants.STRAPPOVALREJ);
                    chatterwrapperItem.body = String.format(Label.OpportunityRejectedChatterMessage, parameters);
                }
                chatterwrapperItem.mentionedUsers=mentionUsers;
                chatterwrapperItemList.add(chatterwrapperItem);
            }
        }
        return chatterwrapperItemList;
    }
}