objects/ClauseLibrary__c.object
<CustomObject>
    <description>&lt;CLA&gt; - Represents a list of clauses for scentre group eg. Standard Clauses, Non-Standard Clauses</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RiskClauseNotifyUsers__c</fullName>
        <label>Risk Clause Notify Users</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RoleType</valueSetName>
        </valueSet>
    </fields>
    <label>Clause Library</label>
    <nameField>
        <label>Clause Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clause Libraries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityClause__c.object
<CustomObject>
    <description>&lt;OPC&gt; - Represents a clause applied to a deal.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Clauses</relationshipLabel>
        <relationshipName>Opportunity_Clauses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ReferencedClause__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referenced Clause</label>
        <referenceTo>ClauseLibrary__c</referenceTo>
        <relationshipLabel>Opportunity Clause</relationshipLabel>
        <relationshipName>Opportunity_Clauses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Clause</label>
    <nameField>
        <label>Opportunity Clauses Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Clauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PropertyTeam__c.object
<CustomObject>
    <description>&lt;PRT&gt; - Represents a internal team working for the property eg. Centre Manager, Facility Manager, RDM, Leasing Executive, Development Leasing Executive</description>
    <fields>
        <fullName>Active__c</fullName>
        <formula>IF(AND(!TeamMember__r.IsActive, RecordType.DeveloperName=&apos;PRT_InternalTeamMember&apos;),false,IF(ISBLANK(EndDate__c),
IF(StartDate__c &lt;= TODAY(),TRUE,FALSE),
(AND(StartDate__c &lt;= TODAY(),
TODAY() &lt;= EndDate__c))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Property Team</relationshipLabel>
        <relationshipName>Property_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RoleType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TeamMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Property_Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property Team</label>
    <nameField>
        <displayFormat>PRT-{0000}</displayFormat>
        <label>Property Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/RoleType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accounts Receivable Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Administration Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Architectural Technician</fullName>
    </customValue>
    <customValue>
        <fullName>Asset General Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Centre Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Chief Operating Officer</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Leasing Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Leasing General Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Leasing Regional Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Property Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Retail Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate Legal</fullName>
    </customValue>
    <customValue>
        <fullName>D&amp;C Special Project Coordinator</fullName>
    </customValue>
    <customValue>
        <fullName>Development Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Development Finance Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Director LARS &amp; NZ Development</fullName>
    </customValue>
    <customValue>
        <fullName>Facilities Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Filing Clerk</fullName>
    </customValue>
    <customValue>
        <fullName>Fitout Contributions Admin</fullName>
    </customValue>
    <customValue>
        <fullName>General Manager Leasing</fullName>
    </customValue>
    <customValue>
        <fullName>General Manager Retail Design</fullName>
    </customValue>
    <customValue>
        <fullName>GM of Corporate Accounting</fullName>
    </customValue>
    <customValue>
        <fullName>GM Retail Admin &amp; Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Group General Manager - LARS</fullName>
    </customValue>
    <customValue>
        <fullName>Group Renewal Admin Team</fullName>
        <label>Group Renewal Team</label>
    </customValue>
    <customValue>
        <fullName>Leasing Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Leasing Finance Analyst</fullName>
    </customValue>
    <customValue>
        <fullName>Project Regional Manager - LARS</fullName>
    </customValue>
    <customValue>
        <fullName>Project Retail Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>Project Retail Design Manager</fullName>
    </customValue>
    <masterLabel>Role Type</masterLabel>
</GlobalValueSet>

classes/PostChatterToOppRiskInvoc.cls
/**
 * Save
 **/

global class PostChatterToOppRiskInvoc{
    @InvocableMethod
    public static void postChatterToOppRisk(List<Id> OpportunityLst) {
        Set<String> roleSet = new Set<String>();
        List<Id> userLstToChatter = new List<Id>();     
        List<Id> propIdLst = new List<Id>();
        List<Opportunity> oppLst = new List<Opportunity>();
        List<ChatterPostUtil.chatterNotificationWrapper> chatterLst = new List<ChatterPostUtil.chatterNotificationWrapper>();
        for(Opportunity opp : [select name,id,property__c from Opportunity where id in: OpportunityLst]){
            if(opp.property__c!=null){
                propIdLst.add(opp.property__c);
                oppLst.add(opp);
            }
        }

        for(OpportunityClause__c oppclause: [select id,ReferencedClause__c,ReferencedClause__r.RiskClauseNotifyUsers__c
        from OpportunityClause__c where opportunity__c in : OpportunityLst and 
        ReferencedClause__r.RiskClauseNotifyUsers__c != null]){
            roleSet.addall((oppclause.ReferencedClause__r.RiskClauseNotifyUsers__c).split(';'));  
        }
        
        for(propertyteam__c prop: [select id,teammember__c,role__c from propertyteam__c where property__c in: propIdLst and role__c in : roleSet and teammember__c != null AND Active__c=true AND TeamMember__r.IsActive=true]){
            userLstToChatter.add(prop.teammember__c);
            
        }
        //system.assertnotequals(userLstToChatter,userLstToChatter);
        chatterpostutil.chatterNotificationWrapper cp = chatterpostutil.ChatterPostToOppRisk(userLstToChatter,oppLst[0]);

        chatterLst.add(cp);
        if(chatterLst.size() > 0){
            ChatterPostUtil.chatterpostBulk(chatterLst);
        }       
    }
}