objects/ClauseLibrary__c.object
<CustomObject>
    <description>&lt;CLA&gt; - Represents a list of clauses for scentre group eg. Standard Clauses, Non-Standard Clauses</description>
    <fields>
        <fullName>ActivatedDate__c</fullName>
        <label>Activated Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ClauseDetails__c</fullName>
        <label>Clause Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ReasonRecommendation__c</fullName>
        <label>Reason Recommendation</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RiskApplies__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Risk Applies?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ClauseType</valueSetName>
        </valueSet>
    </fields>
    <label>Clause Library</label>
    <nameField>
        <label>Clause Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clause Libraries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityClause__c.object
<CustomObject>
    <description>&lt;OPC&gt; - Represents a clause applied to a deal.</description>
    <fields>
        <fullName>ClauseDetails__c</fullName>
        <inlineHelpText>Please enter the information required.</inlineHelpText>
        <label>Clause Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EffectiveFromDate__c</fullName>
        <label>Effective From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Clauses</relationshipLabel>
        <relationshipName>Opportunity_Clauses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ReasonRecommendation__c</fullName>
        <inlineHelpText>Retail Admin Use Only.</inlineHelpText>
        <label>Reason Recommendation</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ReferencedClause__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referenced Clause</label>
        <referenceTo>ClauseLibrary__c</referenceTo>
        <relationshipLabel>Opportunity Clause</relationshipLabel>
        <relationshipName>Opportunity_Clauses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RiskApplies__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This flag is ticked if there is a risk applied Clause associated with this space. Please contact Retail Admin for any questions.</inlineHelpText>
        <label>Risk Applies?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ClauseType</valueSetName>
        </valueSet>
    </fields>
    <label>Opportunity Clause</label>
    <nameField>
        <label>Opportunity Clauses Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Clauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SpaceType</valueSetName>
        </valueSet>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/SpaceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Shop</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Kiosk</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Office Suite</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Store Room</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Seating</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sundry Property</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Garage / Parking</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sundry</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Space Bank</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Common Mall</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>Re-design</label>
    </customValue>
    <customValue>
        <fullName>Seating License</fullName>
        <isActive>false</isActive>
        <label>Seating License</label>
    </customValue>
    <customValue>
        <fullName>Sundry Site</fullName>
        <isActive>false</isActive>
        <label>Sundry Site</label>
    </customValue>
    <masterLabel>Space Type</masterLabel>
</GlobalValueSet>

classes/ClauseSelectionControllerTest.cls
/*
*       author: Clark Marie Garde
*       created date: June 12, 2018
*       description: Test class for ClauseSelectionController
*
*/
@isTest
public class ClauseSelectionControllerTest {
    
    @TestSetup private static void testSetup() {
        
        List<OpportunityClause__c> oppClauseList = new List<OpportunityClause__c>();
        List<ClauseLibrary__c> clauseLibList = new List<ClauseLibrary__c>();
        ClauseLibrary__c clauseLibRecord = new ClauseLibrary__c();
        Map<String, Schema.RecordTypeInfo> accountRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(CONSTANTS.ACCOUNT);
        List<Property__c> propertyList = new List<Property__c>();
        Account account = new Account();
        List<Account> parentAccList = new List<Account>();
        List<Opportunity> opportunityList = new List<Opportunity>();
        List<Space__c> spaceList= new List<Space__c>();
        List<Pricebook2> pricebookList = new List<Pricebook2>();
        Space__c spaceRec = new Space__c();
        
        //CREATE PRICEBOOK
        pricebookList = TestDataFactory.createPricebook(10);
        database.insert(pricebookList);
        pricebookList = [SELECT Id, CurrencyIsoCode FROM Pricebook2];
        
        //CREATE PROPERTY
        propertyList = TestDataFactory.createProperty(10, pricebookList[0]);
        database.insert(propertyList);
        
        //CREATE PARENT ACCOUNT
        parentAccList.addAll(TestDataFactory.createAccountBulk(1, propertyList.get(0).Id, accountRecordTypeMapByName.get(CONSTANTS.PROPERTY_BASED).getRecordTypeId()));
        database.insert(parentAccList);
        parentAccList = [SELECT Id, Property__c FROM Account LIMIT 1];
        
        //CREATE ACCOUNT
        account = TestDataFactory.createAccountwithParent(1, propertyList.get(0).Id, accountRecordTypeMapByName.get(CONSTANTS.PROPERTY_BASED).getRecordTypeId(), parentAccList.get(0).Id);
        database.insert(account);
        account = [SELECT Id, Property__c from Account LIMIT 1];

        //CREATE SPACE
		spaceList = TestDataFactory.createSpace(10, propertyList[0]);
        database.insert(spaceList);
        spaceRec = [SELECT Id FROM Space__c LIMIT 1];
        
        //CREATE OPPORTUNITY
        opportunityList = TestDataFactory.createOpportunity(10, account, propertyList[0], spaceRec);
        database.insert(opportunityList);
        
        //CREATE CLAUSE LIBRARY
        clauseLibList = TestDataFactory.createClauseLibrary(10);
        Database.insert(clauseLibList);
        
        //CREATE OPPORTUNITY CLAUSE
        oppClauseList = TestDataFactory.createOpportunityClause(10,  opportunityList[0], clauseLibList[0]);
        Database.insert(oppClauseList);      
        oppClauseList = [SELECT Id,Name, ClauseDetails__c, ReferencedClause__c,RecordType.Name,RiskApplies__c FROM OpportunityClause__c];
        
    }
    
    public static testMethod void getOppClause() {
        ClauseSelectionController.clauseAndOptionWrapper response = new ClauseSelectionController.clauseAndOptionWrapper(null, null,null,null);
        
        Test.startTest();
       		response = ClauseSelectionController.getClauses([select id from opportunity Limit 1].Id);
       	Test.stopTest();
        
        System.assertEquals(true, response <> null);
        
    }
    
    public static testMethod void createOppClause() {
        ClauseLibrary__c clauseLib = [SELECT Id, Name, ClauseDetails__c,ActivatedDate__c,Type__c,RiskApplies__c, ReasonRecommendation__c from ClauseLibrary__c LIMIT 1];
        String oppClause = 'SELECT Id, Name, ClauseDetails__c, EffectiveFromDate__c, Opportunity__c, Type__c,ReferencedClause__c, RiskApplies__c, ReasonRecommendation__c FROM OpportunityClause__c';
        List<OpportunityClause__c> oppClauseList = new List<OpportunityClause__c>();
       // List<OpportunityClause__c> oppClauseToCreate = new List<OpportunityClause__c>();
        LightningResponse response = new LightningResponse();
        
        Test.startTest();
       		response = ClauseSelectionController.saveClause(oppClause, [select id from opportunity Limit 1].Id);
       	Test.stopTest();
        
        System.assertEquals(true, String.isEmpty(response.returnValue));
        
    }
    
    public static testMethod void getUpdatedClause() {
        OpportunityClause__c oppClasue = [SELECT Id,Name, ClauseDetails__c, ReferencedClause__c,RecordType.Name,RiskApplies__c FROM OpportunityClause__c LIMIT 1];
        OpportunityClause__c updatedOppClasue = new OpportunityClause__c();
        
        Test.startTest();
       		updatedOppClasue = ClauseSelectionController.getUpdatedClause(oppClasue.Id);
       	Test.stopTest();
        
        System.assertEquals(true, updatedOppClasue <> null);
        
    }
    
    public static testMethod void getDeletedClause() {
        List<OpportunityClause__c> oppClasue = [SELECT Id,Opportunity__c FROM OpportunityClause__c LIMIT 1];
        ClauseSelectionController.clauseAndOptionWrapper deleteOppClasue = new ClauseSelectionController.clauseAndOptionWrapper(null, null,null,null);
        List<OpportunityClause__c> selectedClauses = [SELECT Id,Name, ClauseDetails__c, ReferencedClause__c,RecordType.Name,RiskApplies__c FROM OpportunityClause__c];

        Test.startTest();
       		deleteOppClasue = ClauseSelectionController.deleteClause(oppClasue[0].Id, selectedClauses[0].Id);
       	Test.stopTest();
        
        System.assertEquals(true, deleteOppClasue <> null);
        
    }
    
     public static testMethod void getEnableEditStatus() {
        List<Opportunity> oppList = [SELECT Id FROM Opportunity LIMIT 1];
        Boolean editStatus;

        Test.startTest();
       		editStatus = ClauseSelectionController.enableClauseEditUpdate(oppList[0].Id);
       	Test.stopTest();
        
        System.assertEquals(true, editStatus = true);
    }
}