objects/Contract__c.object
<CustomObject>
    <description>&lt;CON&gt; - Represents a contract signed with a retailer. Either lease, Commercial lease, license agreement</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts (Account)</relationshipLabel>
        <relationshipName>Contracts1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LeaseEndDate__c</fullName>
        <label>Lease End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LeaseStatus__c</fullName>
        <label>Lease Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                    <label>Assigned</label>
                </value>
                <value>
                    <fullName>B</fullName>
                    <label>Assigned - Holdover</label>
                </value>
                <value>
                    <fullName>C</fullName>
                    <label>Assigned - after Renewal</label>
                </value>
                <value>
                    <fullName>D</fullName>
                    <label>Future - D&amp;C</label>
                </value>
                <value>
                    <fullName>E</fullName>
                    <label>Expired</label>
                </value>
                <value>
                    <fullName>F</fullName>
                    <label>Future Lease</label>
                </value>
                <value>
                    <fullName>H</fullName>
                    <label>Holdover</label>
                </value>
                <value>
                    <fullName>I</fullName>
                    <label>Extension of lease term</label>
                </value>
                <value>
                    <fullName>K</fullName>
                    <label>Lockout</label>
                </value>
                <value>
                    <fullName>M</fullName>
                    <label>Marketing Fund</label>
                </value>
                <value>
                    <fullName>N</fullName>
                    <label>New Merchant (Current)</label>
                </value>
                <value>
                    <fullName>O</fullName>
                    <label>New Merchant (Cur) - Holdover</label>
                </value>
                <value>
                    <fullName>R</fullName>
                    <label>New Lease (Renewal)</label>
                </value>
                <value>
                    <fullName>U</fullName>
                    <label>New Lease (Renewal) - Holdover</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipName>Leases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TECH_OpportunityRecordTypeId__c</fullName>
        <formula>Opportunity__r.RecordTypeId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TECH_OpportunityRecordTypeId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lease</fullName>
                </value>
                <value>
                    <fullName>License Agreement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UsageClauseDetails__c</fullName>
        <label>Usage Clause Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>UsageClauseName__c</fullName>
        <label>Usage Clause Name</label>
        <type>TextArea</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <recordTypes>
        <fullName>CON_StoreroomContract</fullName>
        <active>true</active>
        <description>Storeroom Leases.</description>
        <label>CON - Storeroom Contract</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OpportunityClause__c.object
<CustomObject>
    <description>&lt;OPC&gt; - Represents a clause applied to a deal.</description>
    <fields>
        <fullName>ClauseDetails__c</fullName>
        <inlineHelpText>Please enter the information required.</inlineHelpText>
        <label>Clause Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Clauses</relationshipLabel>
        <relationshipName>Opportunity_Clauses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ReferencedClause__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referenced Clause</label>
        <referenceTo>ClauseLibrary__c</referenceTo>
        <relationshipLabel>Opportunity Clause</relationshipLabel>
        <relationshipName>Opportunity_Clauses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ClauseType</valueSetName>
        </valueSet>
    </fields>
    <label>Opportunity Clause</label>
    <nameField>
        <label>Opportunity Clauses Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Clauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PromotionFund__mdt.object
<CustomObject>
    <fields>
        <fullName>CategoryAmount__c</fullName>
        <label>Category Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CategoryPecentage__c</fullName>
        <label>Category Pecentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MaxPromotionFund__c</fullName>
        <label>Max Promotion Fund</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MaxRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Max Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MinRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Min Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MinimumPromotionFund__c</fullName>
        <label>Minimum Promotion Fund</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RentCategory__c</fullName>
        <label>Rent Category</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RentRangeMax__c</fullName>
        <label>Rent Range Max</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RentRangeMin__c</fullName>
        <label>Rent Range Min</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Gross</fullName>
                    <default>true</default>
                    <label>Gross</label>
                </value>
                <value>
                    <fullName>Semi Gross</fullName>
                </value>
                <value>
                    <fullName>Net</fullName>
                </value>
                <value>
                    <fullName>Albany</fullName>
                </value>
                <value>
                    <fullName>Manukau</fullName>
                </value>
                <value>
                    <fullName>St. Lukes</fullName>
                </value>
                <value>
                    <fullName>Riccarton</fullName>
                </value>
                <value>
                    <fullName>Newmarket</fullName>
                </value>
                <value>
                    <fullName>St Lukes</fullName>
                </value>
                <value>
                    <fullName>New market</fullName>
                    <isActive>false</isActive>
                    <label>New market</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Promotion Fund</label>
    <pluralLabel>Promotion Funds</pluralLabel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>PriceBook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Properties (PriceBook)</relationshipLabel>
        <relationshipName>PropertiesPriceBook</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>BillingCategory__c</fullName>
        <description>Billing category to identify the bill code.</description>
        <inlineHelpText>For Finance Use Only.</inlineHelpText>
        <label>Billing Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SpaceBillingCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>At Risk</fullName>
                </value>
                <value>
                    <fullName>Held</fullName>
                </value>
                <value>
                    <fullName>Trading</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SpaceType</valueSetName>
        </valueSet>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/SpaceBillingCategory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>NR</fullName>
        <label>Non Retail</label>
    </customValue>
    <customValue>
        <fullName>PE</fullName>
        <label>External Precinct</label>
    </customValue>
    <customValue>
        <fullName>ATM</fullName>
    </customValue>
    <customValue>
        <fullName>EX</fullName>
        <label>Car Park - External</label>
    </customValue>
    <customValue>
        <fullName>PM</fullName>
        <label>Car Park - Permanent</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Car Park - Internal</label>
    </customValue>
    <customValue>
        <fullName>VL</fullName>
        <label>Car Park - Valet</label>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
        <default>true</default>
        <label>Not Applicable</label>
    </customValue>
    <description>Space Billing Category</description>
    <masterLabel>Space Billing Category</masterLabel>
</GlobalValueSet>

globalValueSets/SpaceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Shop</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Kiosk</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Office Suite</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Store Room</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Seating</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sundry Property</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Garage / Parking</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sundry</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Space Bank</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Common Mall</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>Re-design</label>
    </customValue>
    <customValue>
        <fullName>Seating License</fullName>
        <isActive>false</isActive>
        <label>Seating License</label>
    </customValue>
    <customValue>
        <fullName>Sundry Site</fullName>
        <isActive>false</isActive>
        <label>Sundry Site</label>
    </customValue>
    <masterLabel>Space Type</masterLabel>
</GlobalValueSet>

classes/GroupRenewalController.cls
/*
* @author:              Lean Flores
* @description:         Apex Controller for GroupRenewal.cmp
*/

public class GroupRenewalController {
    
    private static Map<String, Schema.RecordTypeInfo> opcRecordTypeMapByName  = RecordTypeUtil.getAllRecordTypesByDeveloperName(Constants.OPPORTUNITY_CLAUSE_API);
    
    public class initializationDataWrapper {
        @AuraEnabled public List<Contract__c> contracts;
        @AuraEnabled public List<String> dealTypeValues;
        @AuraEnabled public Id oppOwnerId;
    }
    
    public class SavedOppsWrapper {
        @AuraEnabled public List<Opportunity> savedOpps;
    }
    

    
	@AuraEnabled
    public static LightningResponse getData(Id accId) {
        LightningResponse response = new LightningResponse(); 
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(GroupRenewalController.class.getName());
        initializationDataWrapper wrapper = new initializationDataWrapper();
        List<Account> childAccounts = new List<Account>();
        wrapper.dealTypeValues = new List<String>{''};
        
        for(Schema.PicklistEntry ple : Opportunity.DealType__c.getDescribe().getPicklistValues()) {
            wrapper.dealTypeValues.add(ple.getValue());
        }
        
        try {
            
            childAccounts = [SELECT Id FROM Account WHERE ParentId=:accId AND RecordType.DeveloperName=:Constants.PROPERTY_BASED_APINAME];
            
            if (childAccounts.size() > 0) {
                wrapper.contracts = [SELECT Id, Opportunity__c, Account__r.Name, Space__r.Name, Property__r.Name, TECH_OpportunityRecordTypeId__c, LeaseEndDate__c 
                                     FROM Contract__c 
                                     WHERE Account__c IN:childAccounts AND LeaseStatus__c!='E' AND RecordType.DeveloperName !='CON_StoreroomContract' ORDER BY Property__r.Name ASC];
            }           
            
            
            List<AccountTeamMember> leasingLead = [SELECT UserId FROM AccountTeamMember WHERE AccountId=:accId AND TeamMemberRole='Leasing Lead' LIMIT 1];
            
            
            wrapper.oppOwnerId = leasingLead != null && leasingLead.size() > 0 ? leasingLead[0].UserId : UserInfo.getUserId();      
            
            
        } catch(Exception e){
            response.status = Constants.FAILED;
            response.message = e.getMessage();
            errorHandler.createError(e);
        }
        

        
        response.returnValue = JSON.serialize(wrapper);
        errorHandler.save();
        return response;
        
    }
    
    @AuraEnabled
    public static LightningResponse saveOpportunities(List<Opportunity> oppList) {
        
        LightningResponse response = new LightningResponse(); 
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(GroupRenewalController.class.getName());
        SavedOppsWrapper wrapper = new SavedOppsWrapper();
           
        List<Opportunity> oppsWithoutClause = new List<Opportunity>();
        List<OpportunityClause__c> newUsageClauses = new List<OpportunityClause__c>(); 
        List<OpportunityClause__c> usageClausesToDelete = new List<OpportunityClause__c>(); 
        Set<Id> parentOppIdSet = new Set<Id>();
        
        
        Map<Id, List<Opportunity>> woClauseOppMapByParentId = new Map<Id, List<Opportunity>>();
        
        
        Savepoint sp = Database.setSavepoint();
        
        try {
            Database.insert(oppList);
            wrapper.savedOpps = [SELECT Name, Account.Name, AccountId, Space__r.Name, Space__c, Property__c,
                                 Property__r.Name, StageName, Type, DealType__c, ParentOpportunity__c, RecordURL__c, RecordType.DeveloperName,
                                 ExistingContract__r.UsageClauseDetails__c, ExistingContract__r.UsageClauseName__c,
                                 (SELECT Id FROM Opportunity_Clauses__r WHERE Type__c=:Constants.USAGE)
                                 FROM Opportunity WHERE Id IN:oppList];
            
            createOppLineItems((new Map<Id, Opportunity>(wrapper.savedOpps)).keySet());            
            
              
            
            for (Opportunity opp : wrapper.savedOpps) {
                // RPP-10601 START LF
                // Create Usage Clause from Existing Contract
                if (!String.isBlank(opp.ExistingContract__r.UsageClauseDetails__c) && !String.isBlank(opp.ExistingContract__r.UsageClauseName__c)) {
                    OpportunityClause__c newOppClause = new OpportunityClause__c(
                        ClauseDetails__c = opp.ExistingContract__r.UsageClauseDetails__c,
                        Name = opp.ExistingContract__r.UsageClauseName__c,
                        Opportunity__c = opp.Id,
                        RecordTypeId = opcRecordTypeMapByName.get(Constants.OC_LEASING_CLAUSE).getRecordTypeId(),
                        Type__c = Constants.USAGE
                    );
                    newUsageClauses.add(newOppClause);
                    if (opp.Opportunity_Clauses__r != null && opp.Opportunity_Clauses__r.size() > 0) {
                        usageClausesToDelete.addAll(opp.Opportunity_Clauses__r);
                    }
                } 
                // Get new Opportunities without Opp Clauses
                else if ((opp.Opportunity_Clauses__r == null || opp.Opportunity_Clauses__r.size() <= 0) &&
                         !String.isBlank(opp.ParentOpportunity__c) &&
                         (opp.RecordType.DeveloperName == Constants.OPP_COMMERCIAL_LEASING_API_NAME || opp.RecordType.DeveloperName == Constants.OPP_RETAIL_LEASING_API_NAME)){
                             oppsWithoutClause.add(opp);
                             parentOppIdSet.add(opp.ParentOpportunity__c);
                         }
                // RPP-10601 END LF
            }
            
            // Create Opp Clause based on Parents Opp Clause
            if (oppsWithoutClause.size() > 0) {  
                List<OpportunityClause__c> parentOpcList = [SELECT ClauseDetails__c, Name, ReferencedClause__c, Opportunity__c
                                                            FROM OpportunityClause__c
                                                            WHERE Opportunity__c IN:parentOppIdSet];
                
                Map<Id, OpportunityClause__c> OpcByParentIdMap = new Map<Id, OpportunityClause__c>();
                
                // Only get 1 Usage Clause as with FLOW:'Renew Contract'
                if (parentOpcList.size() > 0) {
                    for (OpportunityClause__c oppClause : parentOpcList) {
                        if (!OpcByParentIdMap.containsKey(oppClause.Opportunity__c)) {
                            OpcByParentIdMap.put(oppClause.Opportunity__c, oppClause);
                        }
                    }
                }
                // loop on new Opps without clause
                for (Opportunity opp : oppsWithoutClause) {
                    
                    if (OpcByParentIdMap.containsKey(opp.ParentOpportunity__c)) {
                        OpportunityClause__c parentOppClause = OpcByParentIdMap.get(opp.ParentOpportunity__c);
                        OpportunityClause__c newOppClause = new OpportunityClause__c(
                            ClauseDetails__c = parentOppClause.ClauseDetails__c,
                            Name = parentOppClause.Name,
                            Opportunity__c = opp.Id,
                            RecordTypeId = opcRecordTypeMapByName.get(Constants.OC_LEASING_CLAUSE).getRecordTypeId(),
                            Type__c = Constants.USAGE
                        );
                        newUsageClauses.add(newOppClause);
                    }
                }
            }
            // RPP-10601 START LF
            if (usageClausesToDelete.size() > 0) {
                Database.delete(usageClausesToDelete);
                system.debug('Usage Clauses to delete ------ ' + usageClausesToDelete);
            }
            // RPP-10601 END LF
            if (newUsageClauses.size() > 0) {
                Database.insert(newUsageClauses);
                system.debug('New Clauses ------ ' + newUsageClauses);
            }
            

        } catch (Exception e) {
            Database.rollback(sp);
            response.status = Constants.FAILED;
            response.message = e.getMessage();
            errorHandler.createError(e);
        }
        
        response.returnValue = JSON.serialize(wrapper);
        errorHandler.save();
        return response;
    }
    
    
    public static void createOppLineItems(Set<Id> oppsIdSet) {
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(GroupRenewalController.class.getName());
        Map<Id, Opportunity> oppsMap = new Map<Id, Opportunity>([SELECT id, TotalPromotionLevy__c, TechByPassOnClone__c, RecordTypeId,Property__c, AccountId,AnnualMinimumRent__c,
                                                                 ProposedStartDate__c, TermYr__c, SecurityDeposit__c, PromoLevyIncluded__c, pricebook2Id, Property__r.PriceBook__c,
                                                                 Space__c, Space__r.BillingCategory__c, Space__r.Type__c, DealType__c, CurrencyIsoCode, NZProperty__c, NationalAgreement__r.Status__c,
                                                                 NationalAgreement__r.PromoPercentage__c, NationalAgreement__r.CurrentMinimumThreshold__c, NationalAgreement__r.CurrentMaximumThreshold__c
                                                                 from opportunity 
                                                                 where id IN:oppsIdSet]);
        
        Map<Id, List<PriceBookEntry>> promoPbeByPbMap = new Map<Id, List<PriceBookEntry>>();
        Map<Id, List<PriceBookEntry>> rentPbeByPbMap = new Map<Id, List<PriceBookEntry>>();
        Set<Id> priceBookIdSet = new Set<Id>();
        
        Decimal lowestAnnualMinimumRent = null;
        Decimal highestAnnualMinimumRent = null;
        
        // Data preparation
        for (Opportunity opp : oppsMap.values()) {
            priceBookIdSet.add(opp.Property__r.PriceBook__c);
            if (opp.AnnualMinimumRent__c != null) {
                lowestAnnualMinimumRent = lowestAnnualMinimumRent == null || lowestAnnualMinimumRent > opp.AnnualMinimumRent__c ? opp.AnnualMinimumRent__c : lowestAnnualMinimumRent;
                highestAnnualMinimumRent = highestAnnualMinimumRent == null || highestAnnualMinimumRent < opp.AnnualMinimumRent__c ? opp.AnnualMinimumRent__c : highestAnnualMinimumRent;
            }
        }
        
        Map<String, List<PromotionFund__mdt>> promoFundsByTypeMap = new Map<String, List<PromotionFund__mdt>>();
        
        // Disjunction Queries are not supported for MDT 
        List<PromotionFund__mdt> minMatchingPromos = [SELECT Id, CategoryAmount__c, CategoryPecentage__c, MaxPromotionFund__c,
                                                      MaxRequired__c, MinimumPromotionFund__c, MinRequired__c, RentCategory__c,
                                                      RentRangeMax__c, RentRangeMin__c, Type__c
                                                      FROM PromotionFund__mdt 
                                                      WHERE RentRangeMin__c <= :lowestAnnualMinimumRent];
        
        List<PromotionFund__mdt> maxMatchingPromos = [SELECT Id, CategoryAmount__c, CategoryPecentage__c, MaxPromotionFund__c,
                                                      MaxRequired__c, MinimumPromotionFund__c, MinRequired__c, RentCategory__c,
                                                      RentRangeMax__c, RentRangeMin__c, Type__c
                                                      FROM PromotionFund__mdt 
                                                      WHERE RentRangeMax__c >= :highestAnnualMinimumRent];
        
        Set<PromotionFund__mdt> matchingPromos = new Set<PromotionFund__mdt>();
        matchingPromos.addAll(minMatchingPromos);
        matchingPromos.addAll(maxMatchingPromos);
        
        for (PromotionFund__mdt promoFundMdt : matchingPromos) {
                                                    
            if (promoFundsByTypeMap.containsKey(promoFundMdt.Type__c)) {
                promoFundsByTypeMap.get(promoFundMdt.Type__c).add(promoFundMdt);
            } else {
                promoFundsByTypeMap.put(promoFundMdt.Type__c, new List<PromotionFund__mdt>{promoFundMdt});
            }
            
        }
        
        // PriceBookEntries by PriceBook, although used list for map values, it is very rare to have more than 1 PROMO_MARKETING PriceBookEntries per PriceBook 
        for (PriceBookEntry pbe : [SELECT Id, Pricebook2Id, Product2Id, Product2.Family,
                                   Product2.SpaceBillingCategory__c, Product2.DealType__c,
                                   CurrencyIsoCode, Product2.SpaceType__c
                                   FROM PriceBookEntry
                                   WHERE Pricebook2Id IN:priceBookIdSet
                                   AND (Product2.Family =:Constants.PROMO_MARKETING OR Product2.Family =:Constants.RENT) AND isActive = true]) {
                                       
                                       if (Constants.PROMO_MARKETING.equalsIgnoreCase(pbe.Product2.Family)) {
                                           if (promoPbeByPbMap.containsKey(pbe.Pricebook2Id)) {
                                               promoPbeByPbMap.get(pbe.Pricebook2Id).add(pbe);
                                           } else {
                                               promoPbeByPbMap.put(pbe.Pricebook2Id, new List<PriceBookEntry>{pbe});
                                           }
                                       } else if (Constants.RENT.equalsIgnoreCase(pbe.Product2.Family)) {
                                           if (rentPbeByPbMap.containsKey(pbe.Pricebook2Id)) {
                                               rentPbeByPbMap.get(pbe.Pricebook2Id).add(pbe);
                                           } else {
                                               rentPbeByPbMap.put(pbe.Pricebook2Id, new List<PriceBookEntry>{pbe});
                                           }                                           
                                       }
                                   }
        
        
        List<OpportunityLineItem> opportunityProductsList = new List<OpportunityLineItem>();
        
        
        // OpportunityLineItem Creation
        for (Id oppId : oppsIdSet) {
            Opportunity opp = oppsMap.get(oppId);
            String oppSpaceBillingCategory = opp.Space__r.BillingCategory__c != null ? opp.Space__r.BillingCategory__c : 'NA';
            
            
            // Base Rent
            if (opp.Property__r.PriceBook__c != null && rentPbeByPbMap.containsKey(opp.Property__r.PriceBook__c)) {
                for(PriceBookEntry rentPbe : rentPbeByPbMap.get(opp.Property__r.PriceBook__c)) {
                    
                    String rentPbeSpaceBillingCategory = rentPbe.Product2.SpaceBillingCategory__c != null ? rentPbe.Product2.SpaceBillingCategory__c : '';
                    String rentPbeProduct2DealType = rentPbe.Product2.DealType__c != null ? rentPbe.Product2.DealType__c : '';
                    String rentPbeProduct2SpaceType = rentPbe.Product2.SpaceType__c != null ? rentPbe.Product2.SpaceType__c : '';                    
                    
                    if (rentPbeSpaceBillingCategory.contains(oppSpaceBillingCategory)
                        && rentPbe.CurrencyIsoCode == opp.CurrencyIsoCode
                        && (opp.DealType__c != null && rentPbeProduct2DealType.contains(opp.DealType__c))
                        && (opp.Space__r.Type__c != null && rentPbeProduct2SpaceType.contains(opp.Space__r.Type__c))) {
                            
                            OpportunityLineItem rentLineItem = new OpportunityLineItem();
                            rentLineItem.Product2Id = rentPbe.Product2Id;             
                            rentLineItem.UnitPrice = opp.AnnualMinimumRent__c;
                            rentLineItem.Quantity = 1;
                            rentLineItem.OpportunityId = oppId;
                            rentLineItem.PricebookEntryId = rentPbe.Id;
                            opportunityProductsList.add(rentLineItem);
                            
                            break; // Only need one matching Pbe
                        }
                }
            }
            
            
            // Promotion Fund
            if (opp.Property__r.PriceBook__c != null && promoPbeByPbMap.containsKey(opp.Property__r.PriceBook__c)) {
                
                Double rent = getRentInfo(opp, promoFundsByTypeMap);
                    
                for(PriceBookEntry promoPbe : promoPbeByPbMap.get(opp.Property__r.PriceBook__c)) {
                    
                    String promoPbeSpaceBillingCategory = promoPbe.Product2.SpaceBillingCategory__c != null ? promoPbe.Product2.SpaceBillingCategory__c : '';
                    String promoPbeProduct2DealType = promoPbe.Product2.DealType__c != null ? promoPbe.Product2.DealType__c : '';
                    String promoPbeProduct2SpaceType = promoPbe.Product2.SpaceType__c != null ? promoPbe.Product2.SpaceType__c : '';
                    
                    if (rent != null && promoPbeSpaceBillingCategory.contains(oppSpaceBillingCategory)
                        && promoPbe.CurrencyIsoCode == opp.CurrencyIsoCode
                        && (opp.DealType__c != null && promoPbeProduct2DealType.contains(opp.DealType__c))
                        && (opp.Space__r.Type__c != null && promoPbeProduct2SpaceType.contains(opp.Space__r.Type__c))) {
                        	
                            OpportunityLineItem promoLineItem = new OpportunityLineItem();
                            promoLineItem.Product2Id = promoPbe.Product2Id;
                            promoLineItem.UnitPrice = rent;
                            promoLineItem.Quantity = 1;
                            promoLineItem.OpportunityId = oppId;
                            promoLineItem.PricebookEntryId = promoPbe.Id;
                            opportunityProductsList.add(promoLineItem);
                            
                            break; // Only need one matching Pbe
                    }
                }
            }
        }
        
        try{
            Database.insert(opportunityProductsList);
        } catch(Exception e){
            errorHandler.createError(e);
        }        
        
        errorHandler.save();
    }
    
    /*
    * @Author: Lean Flores
    * @Parameter: 
    * @Description: This is a bulkified version of OpportunityLineItemController.getRentInfo
    */    
    private static Double getRentInfo(Opportunity opp, Map<String, List<PromotionFund__mdt>> promoFundsMap) {
        Double promoFund = null;
        Decimal currentRent = opp.AnnualMinimumRent__c != null ? opp.AnnualMinimumRent__c : 0;
        
        
        if (opp.NationalAgreement__c != null && opp.NationalAgreement__r.PromoPercentage__c != null && 'Active'.equalsIgnoreCase(opp.NationalAgreement__r.Status__c)) {
            Decimal min = opp.NationalAgreement__r.CurrentMinimumThreshold__c != null ? opp.NationalAgreement__r.CurrentMinimumThreshold__c : 0;
            Decimal max = opp.NationalAgreement__r.CurrentMaximumThreshold__c != null ? opp.NationalAgreement__r.CurrentMaximumThreshold__c : 999999999999.99;
            
            promoFund = currentRent * opp.NationalAgreement__r.PromoPercentage__c / 100 >= min ? currentRent * opp.NationalAgreement__r.PromoPercentage__c / 100 : min;
            promoFund = promoFund <= max ? promoFund : max;
            
        } 
        else if (opp.NZProperty__c == null && currentRent > 0 && opp.DealType__c != null) {
            
            List<PromotionFund__mdt> promoFundMdtList = promoFundsMap.containsKey(opp.DealType__c) ? promoFundsMap.get(opp.DealType__c) : new List<PromotionFund__mdt>();
            PromotionFund__mdt matchedPromoFundMdt = null;
            
            for (PromotionFund__mdt promoFundMdt : promoFundMdtList) {
                
                if (promoFundMdt.Type__c == opp.DealType__c && promoFundMdt.RentRangeMax__c >= currentRent && promoFundMdt.RentRangeMin__c <= currentRent) {
                    matchedPromoFundMdt = promoFundMdt;
                    break; // Should only match one 
                }
            }
            
            if (matchedPromoFundMdt != null) {
                promoFund = calculatePromotionFundBasedOnFund(currentRent, matchedPromoFundMdt);
            }
            
            
        } 
        else if (opp.NZProperty__c != null && currentRent > 0) {
            List<PromotionFund__mdt> promoFundMdtList = new List<PromotionFund__mdt>();
            
            for (List<PromotionFund__mdt> mdtList : promoFundsMap.values()) {
                promoFundMdtList.addAll(mdtList);
            }
            
            PromotionFund__mdt matchedPromoFundMdt = null;
            
            for (PromotionFund__mdt promoFundMdt : promoFundMdtList) {
                if (opp.NZProperty__c != null && opp.NZProperty__c.contains(promoFundMdt.Type__c) &&
                   promoFundMdt.RentRangeMax__c >= currentRent && promoFundMdt.RentRangeMin__c <= currentRent) {
                    
                       matchedPromoFundMdt = promoFundMdt;
                       break;
                       
                }
            }
            
            if (matchedPromoFundMdt != null) {
                promoFund = calculatePromotionFundBasedOnFundNZ(currentRent, true, matchedPromoFundMdt); // promoThresholdApplies checkbox in RentCalculator.cmp default value is true
            }            
            
            
        }
        
        return promoFund;
    }
    
    private static Double calculatePromotionFundBasedOnFund(Decimal currentRent, PromotionFund__mdt promotionFund) {
        Decimal promotion= 0;
        if (promotionFund.MinRequired__c != null && promotionFund.MinRequired__c) {
            promotion = currentRent * promotionFund.CategoryPecentage__c / 100 >= promotionFund.MinimumPromotionFund__c ? currentRent * promotionFund.CategoryPecentage__c / 100 : promotionFund.MinimumPromotionFund__c;
        } else if (promotionFund.MaxRequired__c!= null && promotionFund.MaxRequired__c) {
            //promotion =  promotionFund.CategoryAmount__c + (currentRent - promotionFund.RentRangeMin__c + 1) * promotionFund.CategoryPecentage__c / 100 > promotionFund.MaxPromotionFund__c ? promotionFund.MaxPromotionFund__c : promotionFund.CategoryAmount__c + (currentRent - promotionFund.RentRangeMin__c + 1) * promotionFund.CategoryPecentage__c / 100;
            promotion = currentRent * promotionFund.CategoryPecentage__c / 100;
            if (promotion < promotionFund.MinimumPromotionFund__c) {
                promotion = promotionFund.MinimumPromotionFund__c;
            } else if (promotion > promotionFund.MaxPromotionFund__c) {
                promotion = promotionFund.MaxPromotionFund__c;
            }              
        } else {
            //promotion = promotionFund.CategoryAmount__c + (currentRent - promotionFund.RentRangeMin__c + 1) * promotionFund.CategoryPecentage__c / 100;
            //promotion = currentRent * promotionFund.CategoryPecentage__c / 100;
            // minmus should be always checked
            promotion = currentRent * promotionFund.CategoryPecentage__c / 100 >= promotionFund.MinimumPromotionFund__c ? currentRent * promotionFund.CategoryPecentage__c / 100 : promotionFund.MinimumPromotionFund__c;
        }
        return promotion;
    }
    
    private static Double calculatePromotionFundBasedOnFundNZ(Decimal currentRent, Boolean isThresholdApplicable, PromotionFund__mdt promotionFund) {
        Decimal promotion= 0;
        if(isThresholdApplicable){
            promotion = currentRent * promotionFund.CategoryPecentage__c / 100 >= promotionFund.MinimumPromotionFund__c ? currentRent * promotionFund.CategoryPecentage__c / 100 : promotionFund.MinimumPromotionFund__c;
            promotion = promotion <= promotionFund.MaxPromotionFund__c ? promotion : promotionFund.MaxPromotionFund__c;
        }else{
            promotion = currentRent * promotionFund.CategoryPecentage__c / 100;
        }   
        return promotion;
    }
    
}