objects/Contract__c.object
<CustomObject>
    <description>&lt;CON&gt; - Represents a contract signed with a retailer. Either lease, Commercial lease, license agreement</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipName>Leases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Reduced ROLO</fullName>
                </value>
                <value>
                    <fullName>No ROLO</fullName>
                </value>
                <value>
                    <fullName>Over payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lease</fullName>
                </value>
                <value>
                    <fullName>License Agreement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Covid_Case_Rental_Assistan__mdt.object
<CustomObject>
    <fields>
        <fullName>Batch_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Batch Update?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Covid Case Rental Assistance Period</label>
    <pluralLabel>Covid Case Rental Assistance Period</pluralLabel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SpaceType</valueSetName>
        </valueSet>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/SpaceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Shop</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Kiosk</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Office Suite</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Store Room</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Seating</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sundry Property</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Garage / Parking</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sundry</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Space Bank</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Common Mall</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>Re-design</label>
    </customValue>
    <customValue>
        <fullName>Seating License</fullName>
        <isActive>false</isActive>
        <label>Seating License</label>
    </customValue>
    <customValue>
        <fullName>Sundry Site</fullName>
        <isActive>false</isActive>
        <label>Sundry Site</label>
    </customValue>
    <masterLabel>Space Type</masterLabel>
</GlobalValueSet>

classes/RentalAsstDateManagementBatchTest.cls
/*
* @author:              Ashwini Makhija
* @description:         Test class for RentalAsstDateManagementBatch
*/
@isTest
public class RentalAsstDateManagementBatchTest {

    @TestSetup 
    private static void testSetup(){
        String periodVal;
        List<String> RentalAsstPeriodValuesList= new List<String>();
        Schema.DescribeFieldResult fieldResult = case.Rental_Assistance_Period__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            RentalAsstPeriodValuesList.add(pickListVal.getLabel());
        } 
        
        List<Covid_Case_Rental_Assistan__mdt> covidRentalAsstMetadataList = [SELECT MasterLabel, Start_Date__c, End_Date__c, Batch_Update__c 
                                                                             FROM Covid_Case_Rental_Assistan__mdt
                                                                             WHERE Batch_Update__c = TRUE LIMIT 1];
        
        for(String str : RentalAsstPeriodValuesList){
            if(str == covidRentalAsstMetadataList[0].MasterLabel){
                periodVal = covidRentalAsstMetadataList[0].MasterLabel;
            }
        }
        
        Map<String, Schema.RecordTypeInfo> accountRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(CONSTANTS.ACCOUNT);
        Map<String, Schema.RecordTypeInfo> caseRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(CONSTANTS.OBJECT_CASE);
        Account testAccount = New Account();
        Property__c testProperty = New Property__c();
        List<Space__c> testSpace = New List<Space__c>();
        List<Contract__c> contrList = new List<Contract__c>();
        List<Opportunity> opportunityList = new List<Opportunity>();
        List<Case> caseList = new List<Case>();
        
        //CREATE PROPERTY
        testProperty = TestDataFactory.createPropertyRecord();
        database.insert(testProperty);
        
        //CREATE ACCOUNT
        testAccount = TestDataFactory.createAccount(1, testProperty.Id, accountRecordTypeMapByName.get(CONSTANTS.PROPERTY_BASED).getRecordTypeId());
        database.insert(testAccount);
        
        //CREATE SPACE
        testSpace = TestDataFactory.createSpace(1, testProperty);
        testSpace[0].type__c = '1';
        database.insert(testSpace);
        
        //CREATE CONTRACT
        contrList = TestDataFactory.createContract(1, testAccount);
        contrList[0].space__c = testSpace[0].id;
        database.insert(contrList);
        
        //CREATE OPPORTUNITY
        opportunityList = TestDataFactory.createOpportunity(1, testAccount, testProperty, testSpace[0]);
        database.insert(opportunityList);
        
        //CREATE CASES FOR BATCH TESTING
        for(Integer i = 0; i < 50; i++){
            Case newCase = TestDataFactory.CreateCase(testAccount, caseRecordTypeMapByName.get(Constants.LVI_COVID19).getRecordTypeId(), contrList[0].Id);
            newCase.Status = Constants.CASE_STATUS_PENDING_APPROVAL;
            newCase.Space__c = testSpace[0].Id;
            newCase.Contract__c = contrList[0].Id;
            newCase.Opportunity__c = opportunityList[0].Id;
            newCase.AccountId = testAccount.Id;
            newCase.JDESentStatus__c = Constants.OPPO_JDE_STATUS_READY;
            newCase.TechHasChildCase__c = true;
            newCase.SubType__c = Constants.CASE_SUBTYPE_COVID_RENT_REQUEST;
            newCase.Type = 'LV18 - Miscellaneous';
            newCase.Rental_Assistance_Period__c = periodVal;
            newCase.Rental_Assistance_Start_Date__c = system.today();
            newCase.Rental_Assistance_End_Date__c = system.today() + 20;
            caseList.add(newCase);
        }
        database.insert(caseList);
    }
    
    @isTest
    public static void RentalDatesBatchUpdateTest(){
        
        Test.startTest();
            RentalAsstDateManagementBatch testBatch = New RentalAsstDateManagementBatch();
            database.executeBatch(testBatch, 100);
        Test.stopTest();
    }
    
}