objects/Contract__c.object
<CustomObject>
    <description>&lt;CON&gt; - Represents a contract signed with a retailer. Either lease, Commercial lease, license agreement</description>
    <fields>
        <fullName>LeaseEndDate__c</fullName>
        <label>Lease End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LeaseStatus__c</fullName>
        <label>Lease Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                    <label>Assigned</label>
                </value>
                <value>
                    <fullName>B</fullName>
                    <label>Assigned - Holdover</label>
                </value>
                <value>
                    <fullName>C</fullName>
                    <label>Assigned - after Renewal</label>
                </value>
                <value>
                    <fullName>D</fullName>
                    <label>Future - D&amp;C</label>
                </value>
                <value>
                    <fullName>E</fullName>
                    <label>Expired</label>
                </value>
                <value>
                    <fullName>F</fullName>
                    <label>Future Lease</label>
                </value>
                <value>
                    <fullName>H</fullName>
                    <label>Holdover</label>
                </value>
                <value>
                    <fullName>I</fullName>
                    <label>Extension of lease term</label>
                </value>
                <value>
                    <fullName>K</fullName>
                    <label>Lockout</label>
                </value>
                <value>
                    <fullName>M</fullName>
                    <label>Marketing Fund</label>
                </value>
                <value>
                    <fullName>N</fullName>
                    <label>New Merchant (Current)</label>
                </value>
                <value>
                    <fullName>O</fullName>
                    <label>New Merchant (Cur) - Holdover</label>
                </value>
                <value>
                    <fullName>R</fullName>
                    <label>New Lease (Renewal)</label>
                </value>
                <value>
                    <fullName>U</fullName>
                    <label>New Lease (Renewal) - Holdover</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipName>Leases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>CurrentForecastedOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Forecasted Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Opportunity Space don&apos;t match with Selected space Record.</errorMessage>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>Opportunity.Space__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Spaces (Current Forecasted Opportunity)</relationshipLabel>
        <relationshipName>CurrentForecastedOpportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CurrentLeaseExpiryDate__c</fullName>
        <formula>CurrentLease__r.LeaseEndDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Lease Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CurrentLease__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Lease</label>
        <referenceTo>Contract__c</referenceTo>
        <relationshipLabel>Spaces (Current Lease)</relationshipLabel>
        <relationshipName>CurrentLease</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HeldVacantSpace__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>For Finance Use Only.</inlineHelpText>
        <label>Held Vacant Space</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LatestAchievedOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Latest Achieved Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Opportunity Space don&apos;t match with Selected space Record.</errorMessage>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>Opportunity.Space__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Spaces (Latest Achieved Opportunity)</relationshipLabel>
        <relationshipName>LatestAchievedOpportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LatestBudget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Latest Budget</label>
        <referenceTo>SpaceBudgetAndForecast__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Spaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LatestForecast__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Latest Forecast</label>
        <referenceTo>SpaceBudgetAndForecast__c</referenceTo>
        <relationshipLabel>Spaces (Latest Forecast)</relationshipLabel>
        <relationshipName>Spaces2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OccupancyStatus__c</fullName>
        <description>This lists the status of the property being leased.</description>
        <label>Occupancy Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 - Vacancy</fullName>
                </value>
                <value>
                    <fullName>2 - Leasing Issues</fullName>
                </value>
                <value>
                    <fullName>3 - LBNT (Leased but not trading)</fullName>
                </value>
                <value>
                    <fullName>4 - Held Vacancies</fullName>
                </value>
                <value>
                    <fullName>5 - Trading New Retailers</fullName>
                </value>
                <value>
                    <fullName>6 - Expiring Leases</fullName>
                </value>
                <value>
                    <fullName>7 - Holdovers</fullName>
                </value>
                <value>
                    <fullName>8 - Project Shops</fullName>
                </value>
                <value>
                    <fullName>9 - Trading</fullName>
                </value>
                <value>
                    <fullName>10 - Inactive</fullName>
                </value>
                <value>
                    <fullName>1- Vacancy</fullName>
                    <isActive>false</isActive>
                    <label>1- Vacancy</label>
                </value>
                <value>
                    <fullName>9 - Closed Shops</fullName>
                    <isActive>false</isActive>
                    <label>9 - Closed Shops</label>
                </value>
                <value>
                    <fullName>Achieved</fullName>
                    <isActive>false</isActive>
                    <label>Achieved</label>
                </value>
                <value>
                    <fullName>Closed Shops</fullName>
                    <isActive>false</isActive>
                    <label>Closed Shops</label>
                </value>
                <value>
                    <fullName>Expiring Leases</fullName>
                    <isActive>false</isActive>
                    <label>Expiring Leases</label>
                </value>
                <value>
                    <fullName>Held Vacancies</fullName>
                    <isActive>false</isActive>
                    <label>Held Vacancies</label>
                </value>
                <value>
                    <fullName>Holdovers</fullName>
                    <isActive>false</isActive>
                    <label>Holdovers</label>
                </value>
                <value>
                    <fullName>LBNT (Leased but not trading)</fullName>
                    <isActive>false</isActive>
                    <label>LBNT (Leased but not trading)</label>
                </value>
                <value>
                    <fullName>Leasing Issues</fullName>
                    <isActive>false</isActive>
                    <label>Leasing Issues</label>
                </value>
                <value>
                    <fullName>Project Shops</fullName>
                    <isActive>false</isActive>
                    <label>Project Shops</label>
                </value>
                <value>
                    <fullName>Trading New Retailers</fullName>
                    <isActive>false</isActive>
                    <label>Trading New Retailers</label>
                </value>
                <value>
                    <fullName>Vacancy</fullName>
                    <isActive>false</isActive>
                    <label>Vacancy</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>At Risk</fullName>
                </value>
                <value>
                    <fullName>Held</fullName>
                </value>
                <value>
                    <fullName>Trading</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SpaceBudgetAndForecast__c.object
<CustomObject>
    <description>&lt;SBF&gt; - Represents approved annualised amount for budget for CY and JV FY and forecast periods</description>
    <fields>
        <fullName>CapitalSiteEstablishment__c</fullName>
        <label>Capital (Site Establishment)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PromotionalAllowance__c</fullName>
        <label>Promotional Allowance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <formula>Space__r.Property__r.Name</formula>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipLabel>Space Budget and Forecast</relationshipLabel>
        <relationshipName>Space_Budget_and_Forecast</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Space Budget and Forecast</label>
    <nameField>
        <label>Space Budget and Forecast Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Space Budget and Forecast</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SpaceOccupancyUpdateHelperTest.cls
/*
*       author: Miguel Paguio
*       created date: May 9, 2018
*       description: Test class for SpaceOccupancyUpdateHelper
*       history: May 9, 2018 Miguel Paguio- Created
*
*/

@isTest
public class SpaceOccupancyUpdateHelperTest {
    
    @TestSetup 
    private static void testSetup() {
        List<Space__c> spaceList= new List<Space__c>();
        List<Account> accountList = new List<Account>();
        List<Pricebook2> pricebookList = new List<Pricebook2>();
        List<Contract__c> contractList = new List<Contract__c>();
        List<Property__c> propertyList = new List<Property__c>();
        List<Opportunity> opportunityList = new List<Opportunity>();
        List<SpaceBudgetAndForecast__c> spaceBudgetCreateRec = new List<SpaceBudgetAndForecast__c>();
        Map<String, Schema.RecordTypeInfo> contractRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName('Contract__c');
        Map<String, Schema.RecordTypeInfo> accountRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(Constants.ACCOUNT);
        
        //CREATE PRICEBOOK
        pricebookList = TestDataFactory.createPricebook(10);
        database.insert(pricebookList);
        pricebookList = [SELECT Id, CurrencyIsoCode FROM Pricebook2];
        
        //CREATE PROPERTY
        propertyList = TestDataFactory.createProperty(10, pricebookList[0]);
        database.insert(propertyList);
        
        //CREATE ACCOUNT
        accountList.addAll(TestDataFactory.createAccountBulk(1, propertyList.get(0).Id, accountRecordTypeMapByName.get(CONSTANTS.PROPERTY_BASED).getRecordTypeId()));
        database.insert(accountList);
        
        //CREATE SPACE
        spaceList = TestDataFactory.createSpace(15, propertyList[0]);
        // VACANCY
        spaceList[0].Status__c = Constants.SPACE_STATUS_CLOSED;
        
        //LBNT
        spaceList[1].Status__c = Constants.SPACE_STATUS_NEW;
        
        //LBNT
        spaceList[2].Status__c = Constants.SPACE_STATUS_ATRISK;
        
        //HELD VACANCIES
        spaceList[3].Status__c = Constants.SPACE_STATUS_HELD;
        spaceList[3].HeldVacantSpace__c = true;
        
        //PROJECT SHOPS
        spaceList[4].Status__c = Constants.SPACE_STATUS_PROJECT;
        
        //EXPIRING LEASES
        spaceList[5].Status__c = Constants.SPACE_STATUS_TRADING;
        //spaceList[5].CurrentLeaseExpiryDate__c = Date.today();
        
        //HOLDOVERS
        spaceList[6].Status__c = Constants.SPACE_STATUS_TRADING;
        //spaceList[6].CurrentLeaseExpiryDate__c = Date.today().addDays(-1);
        
        // TRADING NEW RETAILERS
        spaceList[7].Status__c = Constants.SPACE_STATUS_TRADING;
        //spaceList[7].CurrentLeaseExpiryDate__c = Date.today().addYears(1);
        //spaceList[7].LatestAchievedOpportunity__c = true;
        
        // TRADING NEW RETAILERS
        spaceList[8].Status__c = Constants.SPACE_STATUS_TRADING;
        
        database.insert(spaceList);
        
        //CREATE OPPORTUNITY
        accountList = [SELECT Id, Property__c FROM Account LIMIT 1];
        opportunityList = TestDataFactory.createOpportunity(15, accountList[0], propertyList[0]);
        
        for(Integer counter = 0; counter < opportunityList.size(); counter++){
            opportunityList[counter].Space__c = spaceList[counter].Id;
            opportunityList[counter].CurrentLeaseVirtualVacancy__c = 'No';
        }
        
        opportunityList[0].Type = Constants.OPPTY_STAGENAME_NEWRETAILER;
        opportunityList[2].CurrentLeaseVirtualVacancy__c = null;
        opportunityList[7].Type = Constants.OPPTY_STAGENAME_NEWRETAILER;
        opportunityList[8].Type = Constants.OPPTY_STAGENAME_NEWRETAILER;
        
        database.insert(opportunityList);
        
        //CREATE CONTRACT
        contractList = TestDataFactory.createContract(15, accountList[0], propertyList[0]);
        contractList[0].Opportunity__c = opportunityList[0].Id;
        contractList[1].Opportunity__c = opportunityList[9].Id;
        contractList[2].Opportunity__c = opportunityList[2].Id;
        contractList[3].Opportunity__c = opportunityList[3].Id;
        contractList[4].Opportunity__c = opportunityList[4].Id;
        contractList[5].Opportunity__c = opportunityList[5].Id;
        contractList[6].Opportunity__c = opportunityList[6].Id;
        contractList[7].Opportunity__c = opportunityList[7].Id;
        contractList[8].Opportunity__c = opportunityList[8].Id;
        contractList[9].Opportunity__c = opportunityList[1].Id;
        contractList[10].Opportunity__c = opportunityList[10].Id;
        contractList[11].Opportunity__c = opportunityList[11].Id;
        contractList[12].Opportunity__c = opportunityList[12].Id;
        
        for(Contract__c con : contractList){
            con.RecordTypeId = contractRecordTypeMapByName.get('CON - Retail Contract').getRecordTypeId();
            con.LeaseStatus__c = 'A';
        }
        
        contractList[5].LeaseEndDate__c = Date.today();
        contractList[6].LeaseEndDate__c = Date.today().addDays(-1);
        contractList[7].LeaseEndDate__c = Date.today().addYears(1);
        contractList[8].LeaseEndDate__c = Date.today().addYears(1);
        
        Database.insert(contractList);
        
        //UPDATE SPACE
        for(Integer counter = 0; counter < opportunityList.size(); counter++){
            spaceList[counter].CurrentLease__c = contractList[counter].Id;
            spaceList[counter].LatestAchievedOpportunity__c = opportunityList[counter].Id;
            spaceList[counter].CurrentForecastedOpportunity__c = opportunityList[counter].Id;
        }
        
        database.update(spaceList);
        
        //CREATE SPACE BUDGET AND FORECAST RECORD
        spaceBudgetCreateRec = TestDataFactory.createSpaceBudget(15, spaceList[0]);
        Database.insert(spaceBudgetCreateRec);      
    }
    
    @isTest
    private static void checkStatus() {
        Space__c spaceTemp;
        Set<Id> spaceIdSet = new Set<Id>();
        List<Space__c> spaceList = new List<Space__c>();
        Map<Id, Space__c> oldSpaceMap;
        Map<Id, Space__c> spaceMap = new Map<Id, Space__c>();
        
        oldSpaceMap = new Map<Id, Space__c>([SELECT Id, CurrentLease__c, HeldVacantSpace__c, Status__c, OccupancyStatus__c, 
                                                LatestAchievedOpportunity__c, CurrentLeaseExpiryDate__c,
                                                CurrentForecastedOpportunity__r.CurrentLeaseVirtualVacancy__c, 
                                                LatestBudget__r.PromotionalAllowance__c, CurrentForecastedOpportunity__c,
                                                LatestForecast__r.CapitalSiteEstablishment__c
                                             FROM Space__c]);
                                             
        spaceList = oldSpaceMap.values();
                     
        for(Space__c spa : oldSpaceMap.values()){
            spaceIdSet.add(spa.Id);
        }
                     
        Test.startTest();
            spaceMap = SpaceOccupancyUpdateHelper.updateOccupancyStatus(spaceIdSet, oldSpaceMap.values(), oldSpaceMap);
        Test.stopTest();
        
        for(Integer counter = 0; counter < spaceList.size(); counter++){
            spaceTemp = spaceList[counter];
            
            if(spaceMap.containsKey(spaceTemp.Id)){
                spaceTemp = spaceMap.get(spaceTemp.Id);
                
                if(counter == 0){
                    system.assertEquals(Constants.SPACE_OCCUPANCYSTATUS_VACANCY, spaceTemp.OccupancyStatus__c);
                } else if(counter == 1){
                    system.assertEquals(Constants.SPACE_OCCUPANCYSTATUS_LBNT, spaceTemp.OccupancyStatus__c);
                }  else if(counter == 2){
                    system.assertEquals(Constants.SPACE_OCCUPANCYSTATUS_LEASINGISSUES, spaceTemp.OccupancyStatus__c);
                } else if(counter == 3){
                    system.assertEquals(Constants.SPACE_OCCUPANCYSTATUS_HELDVACANCIES, spaceTemp.OccupancyStatus__c);
                } else if(counter == 4){
                    system.assertEquals(Constants.SPACE_OCCUPANCYSTATUS_PROJECTSHOPS, spaceTemp.OccupancyStatus__c);
                } else if(counter == 5){
                    system.assertEquals(Constants.SPACE_OCCUPANCYSTATUS_EXPAIRINGLEASES, spaceTemp.OccupancyStatus__c);
                } else if(counter == 6){
                    system.assertEquals(Constants.SPACE_OCCUPANCYSTATUS_HOLDOVERS, spaceTemp.OccupancyStatus__c);
                }/* else if(counter == 7){
                    system.assertEquals(Constants.SPACE_OCCUPANCYSTATUS_LEASINGISSUES, spaceTemp.OccupancyStatus__c);
                }*/
            }
        }
    }
}