objects/Contract__c.object
<CustomObject>
    <description>&lt;CON&gt; - Represents a contract signed with a retailer. Either lease, Commercial lease, license agreement</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipName>Leases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>CurrentForecastedOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Forecasted Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Opportunity Space don&apos;t match with Selected space Record.</errorMessage>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>Opportunity.Space__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Spaces (Current Forecasted Opportunity)</relationshipLabel>
        <relationshipName>CurrentForecastedOpportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CurrentLeaseExpiryDate__c</fullName>
        <formula>CurrentLease__r.LeaseEndDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Lease Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CurrentLease__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Lease</label>
        <referenceTo>Contract__c</referenceTo>
        <relationshipLabel>Spaces (Current Lease)</relationshipLabel>
        <relationshipName>CurrentLease</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HeldVacantSpace__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>For Finance Use Only.</inlineHelpText>
        <label>Held Vacant Space</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LatestAchievedOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Latest Achieved Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Opportunity Space don&apos;t match with Selected space Record.</errorMessage>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>Opportunity.Space__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Spaces (Latest Achieved Opportunity)</relationshipLabel>
        <relationshipName>LatestAchievedOpportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LatestBudget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Latest Budget</label>
        <referenceTo>SpaceBudgetAndForecast__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Spaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LatestForecast__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Latest Forecast</label>
        <referenceTo>SpaceBudgetAndForecast__c</referenceTo>
        <relationshipLabel>Spaces (Latest Forecast)</relationshipLabel>
        <relationshipName>Spaces2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OccupancyStatus__c</fullName>
        <description>This lists the status of the property being leased.</description>
        <label>Occupancy Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 - Vacancy</fullName>
                </value>
                <value>
                    <fullName>2 - Leasing Issues</fullName>
                </value>
                <value>
                    <fullName>3 - LBNT (Leased but not trading)</fullName>
                </value>
                <value>
                    <fullName>4 - Held Vacancies</fullName>
                </value>
                <value>
                    <fullName>5 - Trading New Retailers</fullName>
                </value>
                <value>
                    <fullName>6 - Expiring Leases</fullName>
                </value>
                <value>
                    <fullName>7 - Holdovers</fullName>
                </value>
                <value>
                    <fullName>8 - Project Shops</fullName>
                </value>
                <value>
                    <fullName>9 - Trading</fullName>
                </value>
                <value>
                    <fullName>10 - Inactive</fullName>
                </value>
                <value>
                    <fullName>1- Vacancy</fullName>
                    <isActive>false</isActive>
                    <label>1- Vacancy</label>
                </value>
                <value>
                    <fullName>9 - Closed Shops</fullName>
                    <isActive>false</isActive>
                    <label>9 - Closed Shops</label>
                </value>
                <value>
                    <fullName>Achieved</fullName>
                    <isActive>false</isActive>
                    <label>Achieved</label>
                </value>
                <value>
                    <fullName>Closed Shops</fullName>
                    <isActive>false</isActive>
                    <label>Closed Shops</label>
                </value>
                <value>
                    <fullName>Expiring Leases</fullName>
                    <isActive>false</isActive>
                    <label>Expiring Leases</label>
                </value>
                <value>
                    <fullName>Held Vacancies</fullName>
                    <isActive>false</isActive>
                    <label>Held Vacancies</label>
                </value>
                <value>
                    <fullName>Holdovers</fullName>
                    <isActive>false</isActive>
                    <label>Holdovers</label>
                </value>
                <value>
                    <fullName>LBNT (Leased but not trading)</fullName>
                    <isActive>false</isActive>
                    <label>LBNT (Leased but not trading)</label>
                </value>
                <value>
                    <fullName>Leasing Issues</fullName>
                    <isActive>false</isActive>
                    <label>Leasing Issues</label>
                </value>
                <value>
                    <fullName>Project Shops</fullName>
                    <isActive>false</isActive>
                    <label>Project Shops</label>
                </value>
                <value>
                    <fullName>Trading New Retailers</fullName>
                    <isActive>false</isActive>
                    <label>Trading New Retailers</label>
                </value>
                <value>
                    <fullName>Vacancy</fullName>
                    <isActive>false</isActive>
                    <label>Vacancy</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>At Risk</fullName>
                </value>
                <value>
                    <fullName>Held</fullName>
                </value>
                <value>
                    <fullName>Trading</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SpaceBudgetAndForecast__c.object
<CustomObject>
    <description>&lt;SBF&gt; - Represents approved annualised amount for budget for CY and JV FY and forecast periods</description>
    <fields>
        <fullName>CapitalSiteEstablishment__c</fullName>
        <label>Capital (Site Establishment)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PromotionalAllowance__c</fullName>
        <label>Promotional Allowance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <formula>Space__r.Property__r.Name</formula>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipLabel>Space Budget and Forecast</relationshipLabel>
        <relationshipName>Space_Budget_and_Forecast</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Space Budget and Forecast</label>
    <nameField>
        <label>Space Budget and Forecast Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Space Budget and Forecast</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SpaceOccupancyUpdateBatch.cls
/*
*       author: Miguel Paguio
*       created date: May 9, 2018
*       description: Batch class for SpaceOccupancyUpdateHelper
*       history: May 9, 2018 Miguel Paguio- Created
*
*/

global class SpaceOccupancyUpdateBatch implements Database.Batchable<sObject>, Database.Stateful, Schedulable{
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([SELECT Id, CurrentLease__c,HeldVacantSpace__c, CurrentLeaseExpiryDate__c,  Status__c, OccupancyStatus__c, 
                                         LatestAchievedOpportunity__c, LatestAchievedOpportunity__r.Type, LatestForecast__c,
                                         CurrentForecastedOpportunity__r.CurrentLeaseVirtualVacancy__c,
                                         LatestBudget__r.PromotionalAllowance__c,
                                         LatestForecast__r.CapitalSiteEstablishment__c,
                                         CurrentLease__r.Opportunity__c
                                         FROM Space__c order by Property__c]);
    }
    
    global void execute(SchedulableContext sc){
        SpaceOccupancyUpdateBatch schedulableBatch = new SpaceOccupancyUpdateBatch();
        Database.executeBatch(schedulableBatch);
    }

    global void execute(Database.BatchableContext BC, List<Space__c> spaceList){
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(SpaceOccupancyUpdateBatch.class.getName());
        Set<Id> spaceidsSet = (new Map<Id,Space__c>(spaceList)).keySet();
        Map<Id,Space__c> spacemap= SpaceOccupancyUpdateHelper.updateOccupancyStatus(spaceidsSet ,spaceList,null);
        spaceList.clear();
        spaceList.addAll(spacemap.values());
        // bypass space trigger for batch run
        TriggerHandler.bypass('SpaceTriggerHandler');
        if(!spaceList.IsEmpty()){
            Integer counter = 0;
            List<Database.SaveResult> saveResultList = Database.update(spaceList, false);      
            for(Database.SaveResult saveResult : saveResultList){
                for(Database.Error err : saveResult.getErrors()) {
                    errorHandler.createError(err, spaceList[counter++].Id);
                }
            }
            errorHandler.save();
            system.debug('spaceList' + spaceList);
        }   
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
}