objects/Contract__c.object
<CustomObject>
    <description>&lt;CON&gt; - Represents a contract signed with a retailer. Either lease, Commercial lease, license agreement</description>
    <fields>
        <fullName>LeaseStartDate__c</fullName>
        <label>Lease Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipName>Leases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>CurrentForecastedOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Forecasted Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Opportunity Space don&apos;t match with Selected space Record.</errorMessage>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>Opportunity.Space__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Spaces (Current Forecasted Opportunity)</relationshipLabel>
        <relationshipName>CurrentForecastedOpportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CurrentLeaseExpiryDate__c</fullName>
        <formula>CurrentLease__r.LeaseEndDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Lease Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CurrentLease__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Lease</label>
        <referenceTo>Contract__c</referenceTo>
        <relationshipLabel>Spaces (Current Lease)</relationshipLabel>
        <relationshipName>CurrentLease</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HeldVacantSpace__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>For Finance Use Only.</inlineHelpText>
        <label>Held Vacant Space</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LatestAchievedOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Latest Achieved Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Opportunity Space don&apos;t match with Selected space Record.</errorMessage>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>Opportunity.Space__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Spaces (Latest Achieved Opportunity)</relationshipLabel>
        <relationshipName>LatestAchievedOpportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LatestBudget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Latest Budget</label>
        <referenceTo>SpaceBudgetAndForecast__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Spaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LatestForecast__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Latest Forecast</label>
        <referenceTo>SpaceBudgetAndForecast__c</referenceTo>
        <relationshipLabel>Spaces (Latest Forecast)</relationshipLabel>
        <relationshipName>Spaces2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OccupancyStatus__c</fullName>
        <description>This lists the status of the property being leased.</description>
        <label>Occupancy Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 - Vacancy</fullName>
                </value>
                <value>
                    <fullName>2 - Leasing Issues</fullName>
                </value>
                <value>
                    <fullName>3 - LBNT (Leased but not trading)</fullName>
                </value>
                <value>
                    <fullName>4 - Held Vacancies</fullName>
                </value>
                <value>
                    <fullName>5 - Trading New Retailers</fullName>
                </value>
                <value>
                    <fullName>6 - Expiring Leases</fullName>
                </value>
                <value>
                    <fullName>7 - Holdovers</fullName>
                </value>
                <value>
                    <fullName>8 - Project Shops</fullName>
                </value>
                <value>
                    <fullName>9 - Trading</fullName>
                </value>
                <value>
                    <fullName>10 - Inactive</fullName>
                </value>
                <value>
                    <fullName>1- Vacancy</fullName>
                    <isActive>false</isActive>
                    <label>1- Vacancy</label>
                </value>
                <value>
                    <fullName>9 - Closed Shops</fullName>
                    <isActive>false</isActive>
                    <label>9 - Closed Shops</label>
                </value>
                <value>
                    <fullName>Achieved</fullName>
                    <isActive>false</isActive>
                    <label>Achieved</label>
                </value>
                <value>
                    <fullName>Closed Shops</fullName>
                    <isActive>false</isActive>
                    <label>Closed Shops</label>
                </value>
                <value>
                    <fullName>Expiring Leases</fullName>
                    <isActive>false</isActive>
                    <label>Expiring Leases</label>
                </value>
                <value>
                    <fullName>Held Vacancies</fullName>
                    <isActive>false</isActive>
                    <label>Held Vacancies</label>
                </value>
                <value>
                    <fullName>Holdovers</fullName>
                    <isActive>false</isActive>
                    <label>Holdovers</label>
                </value>
                <value>
                    <fullName>LBNT (Leased but not trading)</fullName>
                    <isActive>false</isActive>
                    <label>LBNT (Leased but not trading)</label>
                </value>
                <value>
                    <fullName>Leasing Issues</fullName>
                    <isActive>false</isActive>
                    <label>Leasing Issues</label>
                </value>
                <value>
                    <fullName>Project Shops</fullName>
                    <isActive>false</isActive>
                    <label>Project Shops</label>
                </value>
                <value>
                    <fullName>Trading New Retailers</fullName>
                    <isActive>false</isActive>
                    <label>Trading New Retailers</label>
                </value>
                <value>
                    <fullName>Vacancy</fullName>
                    <isActive>false</isActive>
                    <label>Vacancy</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>At Risk</fullName>
                </value>
                <value>
                    <fullName>Held</fullName>
                </value>
                <value>
                    <fullName>Trading</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SpaceBudgetAndForecast__c.object
<CustomObject>
    <description>&lt;SBF&gt; - Represents approved annualised amount for budget for CY and JV FY and forecast periods</description>
    <fields>
        <fullName>CapitalSiteEstablishment__c</fullName>
        <label>Capital (Site Establishment)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PromotionalAllowance__c</fullName>
        <label>Promotional Allowance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipLabel>Space Budget and Forecast</relationshipLabel>
        <relationshipName>Space_Budget_and_Forecast</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Space Budget and Forecast</label>
    <nameField>
        <label>Space Budget and Forecast Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Space Budget and Forecast</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SpaceOccupancyUpdateHelper.cls
public class SpaceOccupancyUpdateHelper{
    
    
    public static Map<Id,Space__c> updateOccupancyStatus(Set<Id> spaceidsSet,List<Space__c> spaceList,Map<Id,Space__c> dbspaceRecordsMap) {
        Map<id,Space__c> spacemap=new Map<Id,Space__c>();
        
        Set<String> opptytypeforvacancy=new Set<String>();
        opptytypeforvacancy.add(Constants.OPPTY_STAGENAME_NEWRETAILER);
        opptytypeforvacancy.add(Constants.OPPTY_STAGENAME_NEWLEASE);
        
        Set<String> spacesstatuslistone=new Set<String>();
        spacesstatuslistone.add(Constants.SPACE_STATUS_ATRISK);
        spacesstatuslistone.add(Constants.SPACE_STATUS_CLOSED);
        spacesstatuslistone.add(Constants.SPACE_STATUS_NEW);
        
        Set<String> spacesstatuslisttwo=new Set<String>();
        spacesstatuslisttwo.add(Constants.SPACE_STATUS_HELD);
        spacesstatuslisttwo.add(Constants.SPACE_STATUS_PROJECT);
        Map<Id,Opportunity> opportunityMap=new Map<Id,opportunity>([Select Id,Type,ProposedStartDate__c,ProposedEndDate__c from opportunity where Space__c IN : spaceidsSet]);
        Set<Id> spacecurrentleaseId=new Set<Id>();
        for (Space__c spaceRecord : spaceList){
            if(spaceRecord.CurrentLease__c!=null){
                spacecurrentleaseId.add(spaceRecord.CurrentLease__c);
            }
        }
        Map<Id,Contract__c> currentleaseMap=new Map<Id,Contract__c>();
        if(spacecurrentleaseId!=null&&spacecurrentleaseId.size()>0){
            currentleaseMap=new Map<Id,Contract__c>([select id,Opportunity__c ,LeaseStartDate__c from Contract__c where Id IN: spacecurrentleaseId]);
        }
        for (Space__c spaceRec : spaceList){
            Space__c oldRecord=new Space__c();
            if(dbspaceRecordsMap!=null && dbspaceRecordsMap.containskey(spaceRec.id)){
                oldRecord=dbspaceRecordsMap.get(spaceRec.id);
            }else{
                oldRecord=spaceRec;
            }
            
            if (spacesstatuslistone.contains(SpaceRec.Status__c)){ 
                if(spaceRec.Status__c == Constants.SPACE_STATUS_CLOSED){
                    if(spaceRec.LatestAchievedOpportunity__c==null){
                        spaceRec.OccupancyStatus__c = Constants.SPACE_OCCUPANCYSTATUS_VACANCY;
                    }
                    if(currentleaseMap.containsKey(spaceRec.CurrentLease__c)){
                        If(currentleaseMap.get(spaceRec.CurrentLease__c).Opportunity__c==spaceRec.LatestAchievedOpportunity__c){
                            spaceRec.OccupancyStatus__c = Constants.SPACE_OCCUPANCYSTATUS_VACANCY;
                        }
                    }
                }
                
                if((spaceRec.LatestAchievedOpportunity__c!=null &&
                    currentleaseMap.containsKey(spaceRec.CurrentLease__c) &&
                    opportunityMap.get(spaceRec.LatestAchievedOpportunity__c).Type==Constants.OPPTY_STAGENAME_NEWRETAILER &&
                    currentleaseMap.get(spaceRec.CurrentLease__c).Opportunity__c!=spaceRec.LatestAchievedOpportunity__c) ||
                   (spaceRec.LatestAchievedOpportunity__c!=null && spaceRec.CurrentLease__c ==null)) {  
                       spaceRec.OccupancyStatus__c = Constants.SPACE_OCCUPANCYSTATUS_LBNT;
                   } 
                else if(spaceRec.Status__c == Constants.SPACE_STATUS_ATRISK || spaceRec.Status__c == Constants.SPACE_STATUS_NEW) {
                        /*&&((oldRecord.CurrentForecastedOpportunity__r.CurrentLeaseVirtualVacancy__c!='No') 
                           || (oldRecord.LatestBudget__r.PromotionalAllowance__c !=null)
                           || (oldRecord.LatestForecast__r.CapitalSiteEstablishment__c != null)
                          )){
                              
                              spaceRec.OccupancyStatus__c = Constants.SPACE_OCCUPANCYSTATUS_LEASINGISSUES;
                          } else if(spaceRec.Status__c == Constants.SPACE_STATUS_NEW){*/
                              spaceRec.OccupancyStatus__c = Constants.SPACE_OCCUPANCYSTATUS_LEASINGISSUES;
                          }
           
            } else if (spacesstatuslisttwo.contains(SpaceRec.Status__c)){
                
                if(spaceRec.Status__c == Constants.SPACE_STATUS_HELD && spaceRec.HeldVacantSpace__c){
                    spaceRec.OccupancyStatus__c = Constants.SPACE_OCCUPANCYSTATUS_HELDVACANCIES;
                }else if(spaceRec.Status__c == Constants.SPACE_STATUS_PROJECT){
                    spaceRec.OccupancyStatus__c = Constants.SPACE_OCCUPANCYSTATUS_PROJECTSHOPS;
                }
            } else if(spaceRec.Status__c == Constants.SPACE_STATUS_TRADING){
                //START END: NEEL 19072018 RPP-3449
                if(spaceRec.CurrentLeaseExpiryDate__c>=System.Today() && spaceRec.CurrentLeaseExpiryDate__c <= date.newinstance(System.Today().Year()+1, 12, 31)) {
                    
                    spaceRec.OccupancyStatus__c = Constants.SPACE_OCCUPANCYSTATUS_EXPAIRINGLEASES;
                } else if(spaceRec.CurrentLeaseExpiryDate__c < System.Today()){
                    
                    spaceRec.OccupancyStatus__c = Constants.SPACE_OCCUPANCYSTATUS_HOLDOVERS;
                }
                else if( spaceRec.LatestAchievedOpportunity__c!=null&&opportunityMap.containsKey(spaceRec.LatestAchievedOpportunity__c)){
                    
                    if(opportunityMap.get(spaceRec.LatestAchievedOpportunity__c).Type==Constants.OPPTY_STAGENAME_NEWRETAILER){
                        spaceRec.OccupancyStatus__c = Constants.SPACE_OCCUPANCYSTATUS_TRADINGNEWRETAILERS;
                        if(spaceRec.CurrentLease__c!=null&&currentleaseMap.containskey(spaceRec.CurrentLease__c)){
                            if(currentleaseMap.get(spaceRec.CurrentLease__c).Opportunity__c== spaceRec.LatestAchievedOpportunity__c&&currentleaseMap.get(spaceRec.CurrentLease__c).LeaseStartDate__c!=null){
                                if(currentleaseMap.get(spaceRec.CurrentLease__c).LeaseStartDate__c.Year()!=System.Today().Year()){
                                    spaceRec.OccupancyStatus__c = Constants.SPACE_OCCUPANCYSTATUS_TRADING;
                                }
                            }
                        }
                    } else {
                    	spaceRec.OccupancyStatus__c = Constants.SPACE_OCCUPANCYSTATUS_TRADING;
                	} 
                }     
                if(spaceRec.OccupancyStatus__c == Constants.SPACE_OCCUPANCYSTATUS_HOLDOVERS||spaceRec.OccupancyStatus__c == Constants.SPACE_OCCUPANCYSTATUS_EXPAIRINGLEASES){
                    
                    if(spaceRec.LatestAchievedOpportunity__c!=null&&opportunityMap.containsKey(spaceRec.LatestAchievedOpportunity__c)&&opportunityMap.get(spaceRec.LatestAchievedOpportunity__c).ProposedEndDate__c > date.newinstance(System.Today().Year()+1, 12, 31)){
                        
                        if(opportunityMap.get(spaceRec.LatestAchievedOpportunity__c).Type==Constants.OPPTY_STAGENAME_NEWRETAILER){
                            spaceRec.OccupancyStatus__c = Constants.SPACE_OCCUPANCYSTATUS_TRADINGNEWRETAILERS;
                        }else if(currentleaseMap.containskey(spaceRec.CurrentLease__c) && currentleaseMap.get(spaceRec.CurrentLease__c).Opportunity__c== spaceRec.LatestAchievedOpportunity__c){
                            spaceRec.OccupancyStatus__c = Constants.SPACE_OCCUPANCYSTATUS_TRADING;
                        }
                    }
                }
            }else if(spaceRec.Status__c == 'Inactive'){
                spaceRec.OccupancyStatus__c = '10 - Inactive';
            } 
            spacemap.put(spaceRec.id,spaceRec);
        }
        return spacemap;
    }
}