objects/Contract__c.object
<CustomObject>
    <description>&lt;CON&gt; - Represents a contract signed with a retailer. Either lease, Commercial lease, license agreement</description>
    <fields>
        <fullName>Category__c</fullName>
        <formula>TEXT(Account__r.Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Retailer grouping based on usage and product/service offering.</inlineHelpText>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CurrentRent__c</fullName>
        <label>Current Rent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LeaseEndDate__c</fullName>
        <label>Lease End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LeaseStartDate__c</fullName>
        <label>Lease Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipName>Leases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>CurrentRent__c</fullName>
        <formula>CurrentLease__r.CurrentRent__c</formula>
        <label>Current Rent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/GetSimilarAccountController.cls
public class GetSimilarAccountController {

   /*@AuraEnabled
    public static list<Contract__c> getSimilarAccountsByCluster(Id recordId){
        List<Account> currentAccount=[Select ID,Name,Cluster__c from Account where Id=:recordId];
        List<Contract__c> contracts=getContractsByAccountCluster(recordId,currentAccount[0].Cluster__c);
        return contracts;
    }
   
    private static List<Contract__c> getContractsByAccountCluster (Id AccountID, string currentAccountCluster) {
        List<Contract__c> leases = [
            Select ID,Name,CurrentRent__c,Property__r.Name,CurrentRetailerTradingName__r.Name,Space__r.Name,LeaseEndDate__c,LeaseStartDate__c
            from Contract__c where CurrentRetailerTradingName__r.Cluster__c=:currentAccountCluster
            Order by CreatedDate Desc Limit 10
        ];
        system.debug('===leases');
        system.debug(leases);
        return leases;
    }
     @AuraEnabled
    public static list<Contract__c> getSimilarAccountsByCategory(Id recordId){
        List<Account> currentAccount=[Select ID,Name,Cluster__c,Category__c from Account where Id=:recordId];
        List<Contract__c> contractsCategory=getContractsByAccountCategory(recordId,currentAccount[0].Category__c);
        return contractsCategory;
    }
   
    private static List<Contract__c> getContractsByAccountCategory (Id AccountID, string currentAccountCategory) {
        List<Contract__c> leasesCategory = [
            Select ID,Name,CurrentRent__c,Property__r.Name,CurrentRetailerTradingName__r.Name,Space__r.Name,LeaseEndDate__c,LeaseStartDate__c,CurrentRetailerTradingName__r.Category__c
            from Contract__c where CurrentRetailerTradingName__r.Category__c=:currentAccountCategory
            Order by CreatedDate Desc Limit 10
        ];
        system.debug('===leases');
        system.debug(leasesCategory);
        return leasesCategory;
    }
     /* @AuraEnabled
    public static Decimal getAvgSQMRentByCluster(Id recordId){
        List<Account> currentAccount=[Select ID,Name,Cluster__c from Account where Id=:recordId];
        Decimal avgContractRent=getAvgSQMRentByAccountCluster(recordId,currentAccount[0].Cluster__c);
        return avgContractRent;
    }*/
        /*private static Decimal getAvgSQMRentByAccountCluster (Id AccountID, string currentAccountCluster) {
        List<AggregateResult> avgRent = [
            Select avg(CurrentRentSQM__c)
            from Contract__c where CurrentRetailerTradingName__r.Cluster__c=:currentAccountCluster
        ];
        return (Decimal)avgRent[0].get('expr0');
    }*/

    /*  @AuraEnabled
    public static Decimal getAvgRentByCluster(Id recordId){
        List<Account> currentAccount=[Select ID,Name,Cluster__c from Account where Id=:recordId];
        Decimal avgContractRent=getAvgRentByAccountCluster(recordId,currentAccount[0].Cluster__c);
        return avgContractRent;
    }   
    private static Decimal getAvgRentByAccountCluster (Id AccountID, string currentAccountCluster) {
        List<AggregateResult> avgRent = [
            Select avg(CurrentRent__c)
            from Contract__c where CurrentRetailerTradingName__r.Cluster__c=:currentAccountCluster
        ];
        return (Decimal)avgRent[0].get('expr0');
    }
      @AuraEnabled
    public static Decimal getAvgRentByCategory(Id recordId){
        List<Account> currentAccount=[Select ID,Name,Cluster__c from Account where Id=:recordId];
        Decimal avgContractRent=getAvgRentByAccountCategory(recordId,currentAccount[0].Category__c);
        return avgContractRent;
    }
   
    private static Decimal getAvgRentByAccountCategory (Id AccountID, string currentAccountCategory) {
        List<AggregateResult> avgRent = [
            Select avg(CurrentRent__c) 
            from Contract__c where CurrentRetailerTradingName__r.Category__c=:currentAccountCategory
        ];
        return (Decimal)avgRent[0].get('expr0');
    }*/
}