objects/Contract__c.object
<CustomObject>
    <description>&lt;CON&gt; - Represents a contract signed with a retailer. Either lease, Commercial lease, license agreement</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts (Account)</relationshipLabel>
        <relationshipName>Contracts1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ActualVacateDate__c</fullName>
        <inlineHelpText>Date when the tenant vacated the shop.</inlineHelpText>
        <label>Actual Vacate Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LeaseStartDate__c</fullName>
        <label>Lease Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LeaseStatus__c</fullName>
        <label>Lease Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                    <label>Assigned</label>
                </value>
                <value>
                    <fullName>B</fullName>
                    <label>Assigned - Holdover</label>
                </value>
                <value>
                    <fullName>C</fullName>
                    <label>Assigned - after Renewal</label>
                </value>
                <value>
                    <fullName>D</fullName>
                    <label>Future - D&amp;C</label>
                </value>
                <value>
                    <fullName>E</fullName>
                    <label>Expired</label>
                </value>
                <value>
                    <fullName>F</fullName>
                    <label>Future Lease</label>
                </value>
                <value>
                    <fullName>H</fullName>
                    <label>Holdover</label>
                </value>
                <value>
                    <fullName>I</fullName>
                    <label>Extension of lease term</label>
                </value>
                <value>
                    <fullName>K</fullName>
                    <label>Lockout</label>
                </value>
                <value>
                    <fullName>M</fullName>
                    <label>Marketing Fund</label>
                </value>
                <value>
                    <fullName>N</fullName>
                    <label>New Merchant (Current)</label>
                </value>
                <value>
                    <fullName>O</fullName>
                    <label>New Merchant (Cur) - Holdover</label>
                </value>
                <value>
                    <fullName>R</fullName>
                    <label>New Lease (Renewal)</label>
                </value>
                <value>
                    <fullName>U</fullName>
                    <label>New Lease (Renewal) - Holdover</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipName>Leases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TechStatusChanged__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tech_StatusChanged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tech_ActualVacateModifiedDate__c</fullName>
        <label>Tech_ActualVacateModifiedDate</label>
        <type>Date</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SpacePreviousAndCurrentUpdateBatch.cls
/**
* @author:     Kyle Tan
* @desc:       batch class that updates the current retailer and previous tenant of the space
**/
global class SpacePreviousAndCurrentUpdateBatch implements Database.Batchable<sObject>, Database.Stateful, Schedulable{
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        //date d = system.today().addDays(1); //added as changes for RPP-10741
        return Database.getQueryLocator([SELECT Id, Account__c, LeaseStatus__c, Opportunity__r.ActualShopOpenedDate__c, 
                                         Account__r.Name, LeaseStartDate__c, Space__c, ActualVacateDate__c, 
                                         Opportunity__r.TradeFlag__c, Opportunity__r.TechTradeFlagChangedDate__c 
                                         FROM Contract__c
                                         WHERE Opportunity__r.TradeFlag__c = true 
                                           AND Opportunity__r.TechTradeFlagChangedDate__c =: date.today()
                                         ]);
        
//This is a backup before implementing RPP-11035 
        /*WHERE (Opportunity__r.TradeFlag__c = true AND Opportunity__r.ActualShopOpenedDate__c <= :d 
AND ((Opportunity__r.TechTradeFlagChangedDate__c = :date.today())
OR Tech_ActualVacateModifiedDate__c = :date.today()
OR CreatedDate =:date.today()
OR TechStatusChanged__c = true))]);*/
    }
    global void execute(SchedulableContext sc){
        SpacePreviousAndCurrentUpdateBatch schedulableBatch = new SpacePreviousAndCurrentUpdateBatch();
        Database.executeBatch(schedulableBatch);
    }
    global void execute(Database.BatchableContext bc, List<Contract__c> contractList){
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(SpacePreviousAndCurrentUpdateBatch.class.getName());
        List<Space__c> spaceToUpdateList = new List<Space__c>();
        TriggerHandler.bypass('SpaceTriggerHandler');
        spaceToUpdateList = SpaceBL.updateCurrentAndPreviousTenant(contractList);
        if(spaceToUpdateList != null && spaceToUpdateList.size() > 0) {
            List<Database.SaveResult> saveResultList = Database.update(spaceToUpdateList, false);
            Integer counter = 0;
            for(Database.SaveResult saveResult : saveResultList){
                counter++;
                if(!saveResult.isSuccess()) {
                    for(Database.Error error : saveResult.getErrors()) {
                        errorHandler.createError(error, spaceToUpdateList[counter].Id);
                    }
                }
            }
        }
        List<Contract__c> untickBox = [Select Id, TechStatusChanged__c From Contract__c Where TechStatusChanged__c = True];
        if (untickBox.size() > 0) {
            for (Contract__c contract : untickBox) {
                contract.TechStatusChanged__c = false;
            }
            try{
                Database.update(untickBox);
            } catch(Exception e) {
                errorHandler.createError(e);
            }
        }
        errorHandler.save();
    }
    global void finish(Database.BatchableContext bc){
    }
}