objects/Contract__c.object
<CustomObject>
    <description>&lt;CON&gt; - Represents a contract signed with a retailer. Either lease, Commercial lease, license agreement</description>
    <fields>
        <fullName>Category__c</fullName>
        <formula>TEXT(Account__r.Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Retailer grouping based on usage and product/service offering.</inlineHelpText>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LesseeName__c</fullName>
        <formula>Account__r.LesseeName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lessee Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipName>Leases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SuperfineCategory__c</fullName>
        <formula>TEXT( Account__r.SuperfineCategory__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Refined Retailer grouping based on usage and product/service offering - maintained by Research &amp; Insights and Business Admin.</inlineHelpText>
        <label>Superfine Category</label>
        <type>Text</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>PropertyStatus__c</fullName>
        <label>Property Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>DevelopmentType__c</fullName>
        <label>Development Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>DevelopmentImpacted__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Operational</fullName>
                    <default>true</default>
                    <label>Operational</label>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Mini Project</fullName>
                </value>
                <value>
                    <fullName>None Project</fullName>
                    <isActive>false</isActive>
                    <label>None Project</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RentableArea__c</fullName>
        <label>Rentable Area</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CreateForecastOpportunityTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class CreateForecastOpportunityTest {

    @isTest
    static void myUnitTest() {
		Map<String, Schema.RecordTypeInfo> accountRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(CONSTANTS.ACCOUNT);
        List<Account> accountList = new List<Account>();
        List<Opportunity> opportunityList = new List<Opportunity>();
        List<Contract__c> contractList = new List<Contract__c>();
        
        List<Pricebook2> priceBookList = TestDataFactory.createPricebook(1);
        Database.insert(priceBookList);
        Pricebook2 priceBookRec = [SELECT Id, CurrencyIsoCode FROM Pricebook2 LIMIT 1];
        
        Property__c property = TestDataFactory.createProperty(1, priceBookRec)[0];
        property.PropertyStatus__c = 'Active';
        Database.insert(property);
        Property__c propRec = [SELECT Id, Name FROM Property__c LIMIT 1];

        //CREATE ACCOUNT
        //accountList.addAll(TestDataFactory.createAccountBulk(10, property.Id, accountRecordTypeMapByName.get(CONSTANTS.PROPERTY_BASED).getRecordTypeId()));
        
        //database.insert(accountList);
        test.startTest();
        Account acc = new Account();
        acc.Name = 'Test Account';
        acc.Type = 'Forecast';
        acc.Property__c = propRec.Id;
        acc.TradingName__c = 'ABCZ';
        acc.RecordTypeId = accountRecordTypeMapByName.get(CONSTANTS.PROPERTY_BASED).getRecordTypeId();
        acc.ShippingCountry = 'Australia';
        acc.ShippingStreet = '1234 Test Street Drive';
        acc.ShippingCity = 'Sydney';
        acc.ShippingState = 'Queensland';
        acc.ShippingPostalCode = '1234';
        acc.BillingCountry = 'Australia';
        acc.BillingStreet = '1234 Test Street Drive';
        acc.BillingCity = 'Sydney';
        acc.BillingState = 'Queensland';
        acc.BillingPostalCode = '1234';
        acc.BillingEmailAddress__c = 'testemail@address.com';
        acc.ACN__c = 'ACN';
        acc.Category__c = 'S420';
        acc.SuperfineCategory__c = 'S421';
        acc.LesseeName__c = 'Test Lessee';
        
        insert acc;
        
        
        List<Space__c> spaceList = TestDataFactory.createSpace(5, propRec);
        Map<String, Schema.RecordTypeInfo> spaceRecordTypeMap = RecordTypeUtil.getAllRecordTypesByName(Constants.SPACE);
        
        for(Space__c space : spaceList){
            space.RentableArea__c = 40;
            space.DevelopmentType__c = null;
            space.RecordTypeId = spaceRecordTypeMap.get(Constants.PROSPECTIVE_SPACE).getRecordTypeId();
        }
            //test.startTest();
                Database.insert(spaceList);
        		CreateForecastOpportunity.checkSpaceCriteria(spaceList);
            test.stopTest();
    }
    
    @isTest
    static void myUnitTest1() {
		Map<String, Schema.RecordTypeInfo> accountRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(CONSTANTS.ACCOUNT);
        List<Account> accountList = new List<Account>();
        List<Opportunity> opportunityList = new List<Opportunity>();
        List<Contract__c> contractList = new List<Contract__c>();
        
        List<Pricebook2> priceBookList = TestDataFactory.createPricebook(1);
        Database.insert(priceBookList);
        Pricebook2 priceBookRec = [SELECT Id, CurrencyIsoCode FROM Pricebook2 LIMIT 1];
        
        Property__c property = TestDataFactory.createProperty(1, priceBookRec)[0];
        property.PropertyStatus__c = 'Active';
        Database.insert(property);
        Property__c propRec = [SELECT Id, Name FROM Property__c LIMIT 1];

        //CREATE ACCOUNT
        //accountList.addAll(TestDataFactory.createAccountBulk(10, property.Id, accountRecordTypeMapByName.get(CONSTANTS.PROPERTY_BASED).getRecordTypeId()));
        
        //database.insert(accountList);
        List<Account> accList = new List<Account>();
        test.startTest();
        Account acc = new Account();
        acc.Name = 'Test Account';
        acc.Type = 'Forecast';
        acc.Property__c = propRec.Id;
        acc.TradingName__c = 'ABCZ';
        acc.RecordTypeId = accountRecordTypeMapByName.get(CONSTANTS.PROPERTY_BASED).getRecordTypeId();
        acc.ShippingCountry = 'Australia';
        acc.ShippingStreet = '1234 Test Street Drive';
        acc.ShippingCity = 'Sydney';
        acc.ShippingState = 'Queensland';
        acc.ShippingPostalCode = '1234';
        acc.BillingCountry = 'Australia';
        acc.BillingStreet = '1234 Test Street Drive';
        acc.BillingCity = 'Sydney';
        acc.BillingState = 'Queensland';
        acc.BillingPostalCode = '1234';
        acc.BillingEmailAddress__c = 'testemail@address.com';
        acc.ACN__c = 'ACN';
        acc.Category__c = 'S420';
        acc.SuperfineCategory__c = 'S421';
        acc.LesseeName__c = 'Test Lessee';
        
        Account acc1 = new Account();
        acc1.Name = 'Account Test';
        acc1.Type = 'Forecast';
        acc1.Property__c = propRec.Id;
        acc1.TradingName__c = 'ABCZ';
        acc1.RecordTypeId = accountRecordTypeMapByName.get(CONSTANTS.PROPERTY_BASED).getRecordTypeId();
        acc1.ShippingCountry = 'Australia';
        acc1.ShippingStreet = '1234 Test Street Drive';
        acc1.ShippingCity = 'Sydney';
        acc1.ShippingState = 'Queensland';
        acc1.ShippingPostalCode = '1234';
        acc1.BillingCountry = 'Australia';
        acc1.BillingStreet = '1234 Test Street Drive';
        acc1.BillingCity = 'Sydney';
        acc1.BillingState = 'Queensland';
        acc1.BillingPostalCode = '1234';
        acc1.BillingEmailAddress__c = 'testemail@address.com';
        acc1.ACN__c = 'ACN1';
        acc1.Category__c = 'S420';
        acc1.SuperfineCategory__c = 'S421';
        acc1.LesseeName__c = 'Test Lessee1';
        
        accList.add(acc);
        accList.add(acc1);
        
        insert accList;
        
        
        List<Space__c> spaceList = TestDataFactory.createSpace(5, propRec);
        Map<String, Schema.RecordTypeInfo> spaceRecordTypeMap = RecordTypeUtil.getAllRecordTypesByName(Constants.SPACE);
        
        for(Space__c space : spaceList){
            space.RentableArea__c = 40;
            space.DevelopmentType__c = null;
            space.RecordTypeId = spaceRecordTypeMap.get(Constants.PROSPECTIVE_SPACE).getRecordTypeId();
        }
            //test.startTest();
                Database.insert(spaceList);
        		CreateForecastOpportunity.checkSpaceCriteria(spaceList);
            test.stopTest();
    }
}