objects/Contract__c.object
<CustomObject>
    <description>&lt;CON&gt; - Represents a contract signed with a retailer. Either lease, Commercial lease, license agreement</description>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipName>Leases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lease</fullName>
                </value>
                <value>
                    <fullName>License Agreement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>PriceBook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Properties (PriceBook)</relationshipLabel>
        <relationshipName>PropertiesPriceBook</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>BillingCategory__c</fullName>
        <description>Billing category to identify the bill code.</description>
        <inlineHelpText>For Finance Use Only.</inlineHelpText>
        <label>Billing Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SpaceBillingCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SpaceType</valueSetName>
        </valueSet>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/SpaceBillingCategory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>NR</fullName>
        <label>Non Retail</label>
    </customValue>
    <customValue>
        <fullName>PE</fullName>
        <label>External Precinct</label>
    </customValue>
    <customValue>
        <fullName>ATM</fullName>
    </customValue>
    <customValue>
        <fullName>EX</fullName>
        <label>Car Park - External</label>
    </customValue>
    <customValue>
        <fullName>PM</fullName>
        <label>Car Park - Permanent</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Car Park - Internal</label>
    </customValue>
    <customValue>
        <fullName>VL</fullName>
        <label>Car Park - Valet</label>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
        <default>true</default>
        <label>Not Applicable</label>
    </customValue>
    <description>Space Billing Category</description>
    <masterLabel>Space Billing Category</masterLabel>
</GlobalValueSet>

globalValueSets/SpaceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Shop</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Kiosk</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Office Suite</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Store Room</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Seating</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sundry Property</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Garage / Parking</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sundry</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Space Bank</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Common Mall</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>Re-design</label>
    </customValue>
    <customValue>
        <fullName>Seating License</fullName>
        <isActive>false</isActive>
        <label>Seating License</label>
    </customValue>
    <customValue>
        <fullName>Sundry Site</fullName>
        <isActive>false</isActive>
        <label>Sundry Site</label>
    </customValue>
    <masterLabel>Space Type</masterLabel>
</GlobalValueSet>

classes/UpdateTaskOwnerControllerTest.cls
/*
*       author: Clark Marie Garde
*       created date: Aug 20, 2018
*       description: Test class for UpdateTaskOwnerController
* 
*/
@isTest
public class UpdateTaskOwnerControllerTest {
    @TestSetup private static void testSetup() {
        Map<String, Schema.RecordTypeInfo> accountRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(CONSTANTS.ACCOUNT);
        User testUser = new User();
        Task task = new Task();
        List<Opportunity> oppList = new List<Opportunity>();
        Contact contact = new Contact();
        Account account = new Account();
        List<Space__c> spaceList = new List<Space__c>();
        List<Property__c> propertyList = new List<Property__c>();
        List<Account> accountList = new List<Account>();
        List<Space__c> spaceLst = new List<Space__c>();
        List<Opportunity> opportunityList = new List<Opportunity>();
        List<Contract__c> contrList = new List<Contract__c>();
        Product2 productRecord;
        
        //CREATE USER
        testUser = TestDataFactory.sysAdministrator();
        database.insert(testUser);
        testUser = [SELECT Id, Profile.Name from User LIMIT 1];
        
        //CREATE PRODUCT
        productRecord = TestDataFactory.createProduct(Constants.PRODUCT_RENT_REVIEW, Constants.RENT);
        insert productRecord;
        
        List<Pricebook2> priceBookList = TestDataFactory.createPricebook(1);
        Database.insert(priceBookList);
        Pricebook2 priceBookRec = [SELECT Id, CurrencyIsoCode FROM Pricebook2 LIMIT 1];
        //System.debug('Pricebook rec ' + priceBookRec);
        
        propertyList = TestDataFactory.createProperty(1);
        for(Property__c property : propertyList){
            property.PriceBook__c = priceBookRec.Id;
        }
        Database.insert(propertyList);
        propertyList = [SELECT Id FROM Property__c LIMIT 5];
        //CREATE ACCOUNT
        accountList.addAll(TestDataFactory.createAccountBulk(1, propertyList[0].Id, accountRecordTypeMapByName.get(CONSTANTS.PROPERTY_BASED).getRecordTypeId()));
        
        database.insert(accountList);
        //System.debug('Account List ' + accountList);
        //CREATE OPPORTUNITY
        accountList = [SELECT Id, Property__c, Name FROM Account LIMIT 1];
        
        //CREATE SPACE
        spaceLst = TestDataFactory.createSpace(1, propertyList[0]);
        spaceLst[0].type__c = '1';
        spaceLst[0].BillingCategory__c = 'NA';
        database.insert(spaceLst);
        
        //CREATE CONTRACT
        spaceLst = [SELECT Id, Type__c FROM Space__c];
        contrList = TestDataFactory.createContract(1, accountList[0]);
        contrList[0].space__c = spaceLst[0].id;
        database.insert(contrList);
        
        opportunityList = TestDataFactory.createOpportunity(1, accountList[0], propertyList, spaceLst);
        //System.debug('Opportunity List' + opportunityList);
        database.insert(opportunityList);
        
        
        //CREATE TASK
        task = TestDataFactory.createTaskRelatedToOpp(opportunityList[0].id, contact);
        database.insert(task);
        task = [SELECT Id,OwnerId from Task];
    }
    
    public static testMethod void testUpdateTaskOwner() {
        User userinfo=[select id,Profile.Name from User LIMIT 1];
        List<Task> taskList = [SELECT Id, OwnerId from Task LIMIT 1];
        String updateTaskOwner;
        
        Test.startTest();
        updateTaskOwner = UpdateTaskOwnerController.UpdateTaskOwner(taskList[0].OwnerId, taskList[0].Id);
        Test.stopTest();
        
    }
    
    public static testMethod void testValidate() {
        User userinfo=[select id,Profile.Name from User LIMIT 1];
        List<Task> taskList = [SELECT Id, OwnerId from Task LIMIT 1];
        String updateTaskOwner;
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :Constants.SCG_SYS_ADM LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        
            Test.startTest();
                UpdateTaskOwnerController temp = new UpdateTaskOwnerController();
                temp.validate();
            Test.stopTest();  
        
    }
    
    public static testMethod void testUpdateTaskOwnerSC() {
        User userinfo=[select id,Profile.Name from User LIMIT 1];
        List<Task> taskList = [SELECT Id, OwnerId from Task LIMIT 1];
        String updateTaskOwner;
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :Constants.SCG_SYS_ADM LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        
            Test.startTest();
        	ApexPages.StandardSetController apSSC = new ApexPages.StandardSetController(taskList);
            UpdateTaskOwnerController ut = new UpdateTaskOwnerController(apSSC);
            Test.stopTest();  
        
    }
    
}