objects/Contract__c.object
<CustomObject>
    <description>&lt;CON&gt; - Represents a contract signed with a retailer. Either lease, Commercial lease, license agreement</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts (Account)</relationshipLabel>
        <relationshipName>Contracts1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ActualVacateDate__c</fullName>
        <inlineHelpText>Date when the tenant vacated the shop.</inlineHelpText>
        <label>Actual Vacate Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LeaseStartDate__c</fullName>
        <label>Lease Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LeaseStatus__c</fullName>
        <label>Lease Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                    <label>Assigned</label>
                </value>
                <value>
                    <fullName>B</fullName>
                    <label>Assigned - Holdover</label>
                </value>
                <value>
                    <fullName>C</fullName>
                    <label>Assigned - after Renewal</label>
                </value>
                <value>
                    <fullName>D</fullName>
                    <label>Future - D&amp;C</label>
                </value>
                <value>
                    <fullName>E</fullName>
                    <label>Expired</label>
                </value>
                <value>
                    <fullName>F</fullName>
                    <label>Future Lease</label>
                </value>
                <value>
                    <fullName>H</fullName>
                    <label>Holdover</label>
                </value>
                <value>
                    <fullName>I</fullName>
                    <label>Extension of lease term</label>
                </value>
                <value>
                    <fullName>K</fullName>
                    <label>Lockout</label>
                </value>
                <value>
                    <fullName>M</fullName>
                    <label>Marketing Fund</label>
                </value>
                <value>
                    <fullName>N</fullName>
                    <label>New Merchant (Current)</label>
                </value>
                <value>
                    <fullName>O</fullName>
                    <label>New Merchant (Cur) - Holdover</label>
                </value>
                <value>
                    <fullName>R</fullName>
                    <label>New Lease (Renewal)</label>
                </value>
                <value>
                    <fullName>U</fullName>
                    <label>New Lease (Renewal) - Holdover</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipName>Leases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TechStatusChanged__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tech_StatusChanged</label>
        <type>Checkbox</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>CurrentLease__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Lease</label>
        <referenceTo>Contract__c</referenceTo>
        <relationshipLabel>Spaces (Current Lease)</relationshipLabel>
        <relationshipName>CurrentLease</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SpacePreviousAndCurrentUpdateBatchTest.cls
@isTest
public class SpacePreviousAndCurrentUpdateBatchTest {
    @TestSetup 
    private static void testSetup() {
        List<Contract__c> contractList = new List<Contract__c>();
        List<Opportunity> oppList = new List<Opportunity>();
        List<Space__c> spaceList= new List<Space__c>();
        List<Property__c> propertyList = new List<Property__c>();
        List<Pricebook2> pricebookList = new List<Pricebook2>();
        
        //CREATE PRICEBOOK
        pricebookList = TestDataFactory.createPricebook(10);
        database.insert(pricebookList);
        pricebookList = [SELECT Id, CurrencyIsoCode FROM Pricebook2];
        
        //CREATE PROPERTY
        propertyList = TestDataFactory.createProperty(10, pricebookList[0]);
        database.insert(propertyList);
        
        //CREATE ACCOUNT
        Account account = new Account();
        account = TestDataFactory.createAccount(10);
        account.Property__c = propertyList[0].Id;
        account.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(Constants.PROPERTY_BASED_APINAME).getRecordTypeId();
        database.insert(account);
        
        //CREATE SPACE
        spaceList = TestDataFactory.createSpace(10, propertyList[0]);
        database.insert(spaceList);
        
        //CREATE OPPORTUNITY
        oppList = TestDataFactory.createOpportunity(1, account.Id);
        oppList[0].Property__c = propertyList[0].Id;
        oppList[0].Space__c = spaceList[0].Id;
        oppList[0].TradeFlag__c = true;
        oppList[0].ActualShopOpenedDate__c = System.today() - 4;
        oppList[0].TechTradeFlagChangedDate__c = System.today();
        insert oppList;
        
        //CREATE OPPORTUNITY
        /*oppList = TestDataFactory.createOpportunity(1, account.Id);
        oppList[0].TradeFlag__c = true;
        oppList[0].TechTradeFlagChangedDate__c = System.today();
        insert oppList;*/
        
        //CREATE CONTRACT
        Integer counter = 0;
        contractList = TestDataFactory.createContract(10, account);
        for(Contract__c con : contractList){
            con.LeaseStartDate__c = Date.today();
            con.Space__c = spaceList[counter++].Id;
            con.TechStatusChanged__c = true;
            con.LeaseStatus__c = 'A';
            con.Opportunity__c =  oppList[0].Id; // ---
        }
        database.insert(contractList);
        
        spaceList[0].CurrentLease__c = contractList[2].Id;
        Database.update(spaceList);
    }
    
    @isTest
    private static void testUpdateSpace() {
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SCG_SYS_ADM LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        List<Space__c> spaceToUpdateList = [SELECT Id from Space__c LIMIT 1];
        List<Contract__c> contractList = [SELECT Id, Account__c, Account__r.Name, Space__c, ActualVacateDate__c FROM Contract__c];
        
        System.runAs(testUser){
            Test.startTest(); 
            //spaceToUpdateList = SpaceBL.updateCurrentAndPreviousTenant(contractList);
            SpacePreviousAndCurrentUpdateBatch spacePrevBatch = new SpacePreviousAndCurrentUpdateBatch(); 
            Id batchId = Database.executeBatch(spacePrevBatch);
            Test.stopTest();
            
            //System.assertEquals(true, spaceToUpdateList <> null);
        }
    }
    
    @isTest
    private static void testSchedulableBatch() {
        Test.StartTest();
        SpacePreviousAndCurrentUpdateBatch sh1 = new SpacePreviousAndCurrentUpdateBatch();
        String sch = '0 0 23 * * ?'; 
        system.schedule('Test SpacePreviousAndCurrentUpdateBatch Schedule', sch, sh1); 
        Test.stopTest(); 
    }
    
}