objects/Contract__c.object
<CustomObject>
    <description>&lt;CON&gt; - Represents a contract signed with a retailer. Either lease, Commercial lease, license agreement</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts (Account)</relationshipLabel>
        <relationshipName>Contracts1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ActualVacateDate__c</fullName>
        <inlineHelpText>Date when the tenant vacated the shop.</inlineHelpText>
        <label>Actual Vacate Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LeaseStartDate__c</fullName>
        <label>Lease Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipName>Leases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CurrentForecastedOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Forecasted Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Opportunity Space don&apos;t match with Selected space Record.</errorMessage>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>Opportunity.Space__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Spaces (Current Forecasted Opportunity)</relationshipLabel>
        <relationshipName>CurrentForecastedOpportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CurrentLease__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Lease</label>
        <referenceTo>Contract__c</referenceTo>
        <relationshipLabel>Spaces (Current Lease)</relationshipLabel>
        <relationshipName>CurrentLease</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CurrentRetailerName__c</fullName>
        <label>Current Retailer Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CurrentRetailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Neel 03042018: Updated FieldLabel and FieldName</description>
        <label>Current Retailer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Spaces (Current Tenant)</relationshipLabel>
        <relationshipName>LeasedSpace</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LatestAchievedOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Latest Achieved Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Opportunity Space don&apos;t match with Selected space Record.</errorMessage>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>Opportunity.Space__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Spaces (Latest Achieved Opportunity)</relationshipLabel>
        <relationshipName>LatestAchievedOpportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OccupancyStatus__c</fullName>
        <description>This lists the status of the property being leased.</description>
        <label>Occupancy Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 - Vacancy</fullName>
                </value>
                <value>
                    <fullName>2 - Leasing Issues</fullName>
                </value>
                <value>
                    <fullName>3 - LBNT (Leased but not trading)</fullName>
                </value>
                <value>
                    <fullName>4 - Held Vacancies</fullName>
                </value>
                <value>
                    <fullName>5 - Trading New Retailers</fullName>
                </value>
                <value>
                    <fullName>6 - Expiring Leases</fullName>
                </value>
                <value>
                    <fullName>7 - Holdovers</fullName>
                </value>
                <value>
                    <fullName>8 - Project Shops</fullName>
                </value>
                <value>
                    <fullName>9 - Trading</fullName>
                </value>
                <value>
                    <fullName>10 - Inactive</fullName>
                </value>
                <value>
                    <fullName>1- Vacancy</fullName>
                    <isActive>false</isActive>
                    <label>1- Vacancy</label>
                </value>
                <value>
                    <fullName>9 - Closed Shops</fullName>
                    <isActive>false</isActive>
                    <label>9 - Closed Shops</label>
                </value>
                <value>
                    <fullName>Achieved</fullName>
                    <isActive>false</isActive>
                    <label>Achieved</label>
                </value>
                <value>
                    <fullName>Closed Shops</fullName>
                    <isActive>false</isActive>
                    <label>Closed Shops</label>
                </value>
                <value>
                    <fullName>Expiring Leases</fullName>
                    <isActive>false</isActive>
                    <label>Expiring Leases</label>
                </value>
                <value>
                    <fullName>Held Vacancies</fullName>
                    <isActive>false</isActive>
                    <label>Held Vacancies</label>
                </value>
                <value>
                    <fullName>Holdovers</fullName>
                    <isActive>false</isActive>
                    <label>Holdovers</label>
                </value>
                <value>
                    <fullName>LBNT (Leased but not trading)</fullName>
                    <isActive>false</isActive>
                    <label>LBNT (Leased but not trading)</label>
                </value>
                <value>
                    <fullName>Leasing Issues</fullName>
                    <isActive>false</isActive>
                    <label>Leasing Issues</label>
                </value>
                <value>
                    <fullName>Project Shops</fullName>
                    <isActive>false</isActive>
                    <label>Project Shops</label>
                </value>
                <value>
                    <fullName>Trading New Retailers</fullName>
                    <isActive>false</isActive>
                    <label>Trading New Retailers</label>
                </value>
                <value>
                    <fullName>Vacancy</fullName>
                    <isActive>false</isActive>
                    <label>Vacancy</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PreviousLease__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Lease</label>
        <referenceTo>Contract__c</referenceTo>
        <relationshipLabel>Spaces (Previous Lease)</relationshipLabel>
        <relationshipName>Spaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreviousTenant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Tenant</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Spaces (Previous Tenant)</relationshipLabel>
        <relationshipName>Spaces2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReadyToForecast__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ready to Forecast</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ReconfiguredCurrentRentSemiGross__c</fullName>
        <label>Reconfigured Current Rent (Semi Gross)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ReconfiguredCurrentRent__c</fullName>
        <description>This field will hold the pro-rata rent based on Space Reconfiguration process</description>
        <label>Reconfigured Current Rent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <description>Parent
Child</description>
        <label>Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Relationship</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>At Risk</fullName>
                </value>
                <value>
                    <fullName>Held</fullName>
                </value>
                <value>
                    <fullName>Trading</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TechDispatchedTimeStamp__c</fullName>
        <label>Tech_DispatchedTimeStamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TechDispatchedVersion__c</fullName>
        <label>Tech_DispatchedVersion</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <recordTypes>
        <fullName>SPA_LeasedSpaces</fullName>
        <active>true</active>
        <description>This captures space that has been leased to the retailer</description>
        <label>Leased Spaces</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SpaceEvent__e.object
<CustomObject>
    <fields>
        <fullName>JSONPayload__c</fullName>
        <label>JSON Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Space Event</label>
    <pluralLabel>Space Events</pluralLabel>
</CustomObject>

objects/SpaceGroup__c.object
<CustomObject>
    <description>&lt;SPG&gt; - Represents a grouping of spaces eg. Sales Precinct, Development Project</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ChildSpace__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Child Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipLabel>Space Groups (Child Space)</relationshipLabel>
        <relationshipName>Space_Groups2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParentSpace__c</fullName>
        <label>Parent Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipLabel>Space Groups (Parent Space)</relationshipLabel>
        <relationshipName>Space_Groups3</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SpaceGroupNumber__c</fullName>
        <description>Same group number for the group saved.</description>
        <inlineHelpText>This is the unique identifier for the reconfiguration group.</inlineHelpText>
        <label>Space Group Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Space Group</label>
    <nameField>
        <label>Space Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Space Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Relationship.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Parent</fullName>
    </customValue>
    <customValue>
        <fullName>Child</fullName>
    </customValue>
    <customValue>
        <fullName>-None-</fullName>
        <default>true</default>
        <label>-None-</label>
    </customValue>
    <masterLabel>Relationship</masterLabel>
</GlobalValueSet>

classes/SpaceBL.cls
public class SpaceBL{
    /**
* @Author: Chen Chen
* @Para: List<String> jsonPayloads, List of json payload that need to send out as space event
* @Desc: This is used for generating space platform events by the providing payloads
*/
    
    public static List<SpaceEvent__e> generateSpaceEvents(List<String> payloads) {
        List<SpaceEvent__e> spaceEvents = new List<SpaceEvent__e>();
        if (payloads.size() > 0) {
            for (String payload : payloads) {
                SpaceEvent__e spaceE = new SpaceEvent__e();
                spaceE.JSONPayload__c = payload;
                spaceEvents.add(spaceE);
            }
        }
        return spaceEvents;
    }
    
    public static List<Space__c> updatedispatchdetailsonSpace(){
        List<Space__c> spacelist=new List<Space__c>();
        
        return spacelist;
    }
    
    public static void updateSpaceWhenSpaceEventSentSuccess(List<SpaceEvent__e> successfullpublish) {
        List<Space__c> spacetoupdatedispatchdetailsList=new List<Space__c>(); 
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(SpaceBL.class.getName());
        if(!successfullpublish.isEmpty()&&successfullpublish.size()>0){
            for(SpaceEvent__e publishedevent: successfullpublish){
                // get values from pubished event payload to update parent records
                Map<String, Object> publishedspaceevents;
                try {
                    publishedspaceevents=(Map<String, Object>)JSON.deserializeUntyped(publishedevent.JSONPayload__c);
                } catch (Exception e) {
                    publishedspaceevents = NULL;
                }
                if(publishedspaceevents != NULL && !publishedspaceevents.isEmpty()) {
                    System.debug('**DISPATCHEEVENT**'+publishedspaceevents);
                    Space__c spacetoupdatedispatchdetails=new Space__c();
                    spacetoupdatedispatchdetails.id=(id)publishedspaceevents.get(Constants.DML_ID.toUpperCase());
                    String dispatchtimestampstr=(String)publishedspaceevents.get(Constants.TECH_DISPATCHTIMESTAMP.toUpperCase());
                    spacetoupdatedispatchdetails.TechDispatchedTimeStamp__c =DateTime.valueOf(dispatchtimestampstr);
                    String dispatchversionstr=(String)publishedspaceevents.get(Constants.TECH_DISPATCHVERSION.toUpperCase());
                    spacetoupdatedispatchdetails.TechDispatchedVersion__c=Decimal.valueOf(dispatchversionstr);
                    spacetoupdatedispatchdetailsList.add(spacetoupdatedispatchdetails);
                }
            }
        }
        System.debug('**FORUPDATE**'+spacetoupdatedispatchdetailsList);
        if(!spacetoupdatedispatchdetailsList.isEmpty()&&spacetoupdatedispatchdetailsList.size()>0){
            try{
                Database.update(spacetoupdatedispatchdetailsList);
            } catch(Exception e) {
                errorHandler.createError(e);
            }
        }
        errorHandler.save();
    }
    
    public static List<SpaceGroup__c> getAllSpaceGroupByGroupNumber(Set<Id> childSpaceIdSet){
        Set<Decimal> spacegroupNumberSet = new Set<Decimal>();
        List<SpaceGroup__c> spaceGroupList = new List<SpaceGroup__c>();
        
        try{
            for(SpaceGroup__c spaceGroup : DatabaseSOQLBank.getSpaceGroupOfChildSpace(childSpaceIdSet)){
                spacegroupNumberSet.add(spaceGroup.SpaceGroupNumber__c);
            }
        } catch(Exception e){
            spacegroupNumberSet = null;
        }
        
        if(spaceGroupNumberSet != null){
            try{
                spaceGroupList = DatabaseSOQLBank.getSpaceGroupBySpaceGroupNumber(spacegroupNumberSet);
            } catch(Exception e){
                spaceGroupList = null;
            }
        }
        
        return spaceGroupList;
    }
    
    //RPP-4311 SG 6.26.18
    
    public static List<Space__c> updateSpaceRecords(Map<Id, Opportunity> opportunityMap, List<SpaceGroup__c> spaceGroupList){
        Space__c spaceTemp;
        Set<Id> spaceIdSet = new Set<Id>();
        Set<Id> childSpaceIdSet = new Set<Id>();
        Set<Decimal> spacegroupNumberSet = new Set<Decimal>();
        List<Space__c> spaceTempList = new List<Space__c>();
        List<Space__c> spaceToUpdateList = new List<Space__c>();
        Map<Id, Space__c> spaceMap = new Map<Id, Space__c>();
        Map<Id, Opportunity> spaceIdOpportunityMap = new Map<Id, Opportunity>();
        //Map<Decimal, Set<Id>> sGroupNumberChildSpaceIdSetMap = new Map<Decimal, Set<Id>>();
        //Map<Decimal, Set<Id>> sGroupNumberParentSpaceIdSetMap = new Map<Decimal, Set<Id>>();
        Map<Decimal, Map<Id, Space__c>> sGroupNumberChildSpaceMap = new Map<Decimal, Map<Id, Space__c>>();
        Map<Decimal, Map<Id, Space__c>> sGroupNumberParentSpaceMap = new Map<Decimal, Map<Id, Space__c>>();
        Map<String, Schema.RecordTypeInfo> spaceRecordTypeByDeveloperName=RecordTypeUtil.getAllRecordTypesByDeveloperName(Constants.SPACE);
        Set<String> openStageSet = new Set<String>{
            Constants.APPROVE,
                Constants.PROPOSE_ACCEPT,
                Constants.UNDERSTAND_NEGOTIATE
                };
                    
                    for(Opportunity opp : opportunityMap.values()){
                        if(opp.Space__c != null){
                            spaceTemp = new Space__c(Id = opp.Space__c);
                            spaceMap.put(spaceTemp.Id, spaceTemp);                            
                            if(opp.DealAchieved__c && !opp.TechByPassOnClone__c){
                                spaceMap.get(opp.Space__c).LatestAchievedOpportunity__c=opp.Id;
                            } else if(openStageSet.contains(opp.StageName) && opp.BestBet__c){
                                spaceMap.get(opp.Space__c).CurrentForecastedOpportunity__c=opp.Id;
                            }
                            // update space record type to SPA_LeasedSpaces
                            if(opp.JDESentStatus__c==Constants.OPPO_JDE_STATUS_READY){
                                spaceMap.get(opp.Space__c).RecordTypeId=spaceRecordTypeByDeveloperName.get('SPA_LeasedSpaces').getRecordTypeId();
                            }
                        }
                    }
        if(spaceGroupList != null && !spaceGroupList.isEmpty()){
            if(spaceGroupList != null && spaceGroupList.size() > 0){
                for(SpaceGroup__c spaceGroupRecord : spaceGroupList){
                    if(spaceMap.containsKey(spaceGroupRecord.ChildSpace__c)){
                        spaceTemp = spaceMap.get(spaceGroupRecord.ChildSpace__c);
                    } else {
                        spaceTemp = new Space__c(Id = spaceGroupRecord.ChildSpace__c);
                    }
                    spaceTemp.ReadyToForecast__c = true;
                    if(sGroupNumberParentSpaceMap.containsKey(spaceGroupRecord.SpaceGroupNumber__c)){
                        if(!sGroupNumberParentSpaceMap.get(spaceGroupRecord.SpaceGroupNumber__c).containsKey(spaceGroupRecord.ParentSpace__c)){
                            sGroupNumberParentSpaceMap
                                .get(spaceGroupRecord.SpaceGroupNumber__c)
                                .put(spaceGroupRecord.ParentSpace__c, spaceGroupRecord.ParentSpace__r);
                        }
                    } else {
                        sGroupNumberParentSpaceMap.put(spaceGroupRecord.SpaceGroupNumber__c,
                                                       new Map<Id, Space__c>{
                                                           spaceGroupRecord.ParentSpace__c => spaceGroupRecord.ParentSpace__r
                                                               }
                                                      );
                    }
                    
                    if(sGroupNumberChildSpaceMap.containsKey(spaceGroupRecord.SpaceGroupNumber__c)){
                        if(!sGroupNumberChildSpaceMap.get(spaceGroupRecord.SpaceGroupNumber__c).containsKey(spaceGroupRecord.ChildSpace__c)){
                            sGroupNumberChildSpaceMap
                                .get(spaceGroupRecord.SpaceGroupNumber__c)
                                .put(spaceGroupRecord.ChildSpace__c, spaceGroupRecord.ChildSpace__r);
                        }
                    } else {
                        sGroupNumberChildSpaceMap.put(spaceGroupRecord.SpaceGroupNumber__c,
                                                      new Map<Id, Space__c>{
                                                          spaceGroupRecord.ChildSpace__c => spaceGroupRecord.ChildSpace__r
                                                              }
                                                     );
                    }
                    
                    spaceMap.put(spaceTemp.Id, spaceTemp);
                }
            }
            
            if(!sGroupNumberParentSpaceMap.isEmpty() && !sGroupNumberChildSpaceMap.isEmpty()){
                for(Decimal groupNumber : sGroupNumberParentSpaceMap.keySet()){
                    if(sGroupNumberChildSpaceMap.containsKey(groupNumber)){
                        spaceTempList = SpaceManagementController.calculateCurrenRent(
                            sGroupNumberParentSpaceMap.get(groupNumber).values(),
                            sGroupNumberChildSpaceMap.get(groupNumber).values()
                        );
                        for(Space__c space : spaceTempList){
                            if(spaceMap.containsKey(space.Id)){
                                spaceTemp = spaceMap.get(space.Id);
                                spaceTemp.ReconfiguredCurrentRent__c = space.ReconfiguredCurrentRent__c;
                                spaceTemp.ReconfiguredCurrentRentSemiGross__c = space.ReconfiguredCurrentRentSemiGross__c;
                            } else {
                                spaceTemp = new Space__c(
                                    Id = space.Id,
                                    ReconfiguredCurrentRent__c = space.ReconfiguredCurrentRent__c,
                                    ReconfiguredCurrentRentSemiGross__c = space.ReconfiguredCurrentRentSemiGross__c
                                );
                            }
                            
                            spaceMap.put(spaceTemp.Id, spaceTemp);
                        }
                    }
                }
            }
        }
        
        return spaceMap.values();
    }
    
    /**
* @author:          Kyle Tan
* @desc:            check any of the space group is reconfigured
**/
    public static Boolean checkActiveConfigurations(List<SpaceGroup__c> spaceGroupList, Id spaceId) {
        Boolean isConfigured = false;
        if(spaceGroupList != null && spaceGroupList.size() > 0) {
            for(SpaceGroup__c spaceGroupRec :spaceGroupList) {
                if(spaceGroupRec.Active__c && spaceGroupRec.ParentSpace__c == spaceId) {
                    isConfigured = true;
                }
            }
        }
        return isConfigured;
    }
    
    /**
* @author:          Kyle Tan
* @desc:            updates spaces by adding in the new tenant
**/
    public static List<Space__c> updateCurrentAndPreviousTenant(List<Contract__c> contractList) {
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(SpaceBL.class.getName());
        List<Space__c> spaceToUpdateList = new List<Space__c>();
        List<Space__c> spaceList = new List<Space__c>();
        Set<Id> spaceIdSet = new Set<Id>();
        Map<Id, Contract__c> spaceIdContractMap = new Map<Id, Contract__c>();
        system.debug('contractList-->' + contractList);
        if(contractList != null && contractList.size() > 0) {
            for(Contract__c contractRecord :contractList) {
                if(contractRecord.Space__c != null) {
                    spaceIdSet.add(contractRecord.Space__c);
                    //if(contractRecord.LeaseStartDate__c == date.today()) {
                    //if(contractRecord.LeaseStartDate__c <= date.today() && contractRecord.ActualVacateDate__c == null) {
                    //if(contractRecord.ActualVacateDate__c == null) {
                    spaceIdContractMap.put(contractRecord.Space__c, contractRecord);
                    //}
                }
            }
            system.debug('spaceIdContractMap-->' + spaceIdContractMap);
            if(spaceIdSet != null && spaceIdSet.size() > 0) {
                try{
                    spaceList = DatabaseSOQLBank.getSpaces(spaceIdSet);
                } catch(Exception e) {
                    spaceList = null;
                    errorHandler.createError(e);
                }
                system.debug('spaceList-->' + spaceList);
                if(spaceList != null && spaceList.size() > 0) {
                    for(Space__c spaceRecord :spaceList) {
                        //if(!(spaceIdContractMap.get(spaceRecord.Id).Account__c == spaceRecord.CurrentRetailer__c)){   //commented out and logic enhanced for RPP-10741
                        if(spaceRecord.CurrentLease__c != spaceIdContractMap.get(spaceRecord.Id).Id){
                            
                            if(spaceRecord.CurrentLease__c == null 
                               && spaceIdContractMap.get(spaceRecord.Id).LeaseStartDate__c <= date.today() 
                               && spaceIdContractMap.get(spaceRecord.Id).ActualVacateDate__c == null){
                                   
                                spaceRecord.CurrentLease__c = spaceIdContractMap.get(spaceRecord.Id).Id;
                                spaceRecord.CurrentRetailer__c = spaceIdContractMap.get(spaceRecord.Id).Account__c;
                                spaceRecord.CurrentRetailerName__c  = spaceIdContractMap.get(spaceRecord.Id).Account__r.Name;
                                spaceToUpdateList.add(spaceRecord);
                            } 
                            else {
                                if(spaceRecord.CurrentLease__c != null &&
                                   spaceRecord.CurrentRetailer__c != null) {
                                       spaceRecord.PreviousLease__c = spaceRecord.CurrentLease__c;
                                       spaceRecord.PreviousTenant__c = spaceRecord.CurrentRetailer__c;
                                   }
                                spaceRecord.CurrentLease__c = spaceIdContractMap.get(spaceRecord.Id).Id;
                                spaceRecord.CurrentRetailer__c = spaceIdContractMap.get(spaceRecord.Id).Account__c;
                                spaceRecord.CurrentRetailerName__c  = spaceIdContractMap.get(spaceRecord.Id).Account__r.Name;
                                spaceToUpdateList.add(spaceRecord);
                            } 
                            
                        }
                        
                        
                        /*if((spaceRecord.CurrentLease__c != null && 
spaceRecord.CurrentLease__r.ActualVacateDate__c != null && 
spaceRecord.CurrentLease__r.ActualVacateDate__c < date.today()) || 
spaceRecord.CurrentLease__c == null) {
if(spaceIdContractMap.containsKey(spaceRecord.Id)) {
if(spaceRecord.CurrentLease__c != null &&
spaceRecord.CurrentRetailer__c != null) {
spaceRecord.PreviousLease__c = spaceRecord.CurrentLease__c;
spaceRecord.PreviousTenant__c = spaceRecord.CurrentRetailer__c;
}
spaceRecord.CurrentLease__c = spaceIdContractMap.get(spaceRecord.Id).Id;
spaceRecord.CurrentRetailer__c = spaceIdContractMap.get(spaceRecord.Id).Account__c;
spaceRecord.CurrentRetailerName__c  = spaceIdContractMap.get(spaceRecord.Id).Account__r.Name;
}
spaceToUpdateList.add(spaceRecord);
}*/
                    }
                }
            }
        }
        errorHandler.save();
        return spaceToUpdateList;
    }
    // RPP-10553 Lean Flores June 19 2019
    public static Space__c updateStatusBasedOnVirtualVacancy(Space__c spc, Opportunity opp) {
        
        if (spc == null) {
            return null;
        }
        
        Boolean virtualVacancy = !Constants.NO.equalsIgnoreCase(opp.CurrentLeaseVirtualVacancy__c) && !String.isBlank(opp.CurrentLeaseVirtualVacancy__c);
        
        if(virtualVacancy && Constants.SPACE_STATUS_TRADING.equalsIgnoreCase(spc.Status__c)) { 
            
            spc.Status__c = Constants.SPACE_STATUS_ATRISK;
            
        } else if (!virtualVacancy && Constants.SPACE_STATUS_ATRISK.equalsIgnoreCase(spc.Status__c) && !Constants.SPACE_OCCUPANCYSTATUS_LBNT.equalsIgnoreCase(spc.OccupancyStatus__c) && String.isBlank(spc.Relationship__c)) {
            
            spc.Status__c = Constants.SPACE_STATUS_TRADING;
        }
        
        return spc;
    }    
}