objects/Contract__c.object
<CustomObject>
    <description>&lt;CON&gt; - Represents a contract signed with a retailer. Either lease, Commercial lease, license agreement</description>
    <fields>
        <fullName>LeaseStatus__c</fullName>
        <label>Lease Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                    <label>Assigned</label>
                </value>
                <value>
                    <fullName>B</fullName>
                    <label>Assigned - Holdover</label>
                </value>
                <value>
                    <fullName>C</fullName>
                    <label>Assigned - after Renewal</label>
                </value>
                <value>
                    <fullName>D</fullName>
                    <label>Future - D&amp;C</label>
                </value>
                <value>
                    <fullName>E</fullName>
                    <label>Expired</label>
                </value>
                <value>
                    <fullName>F</fullName>
                    <label>Future Lease</label>
                </value>
                <value>
                    <fullName>H</fullName>
                    <label>Holdover</label>
                </value>
                <value>
                    <fullName>I</fullName>
                    <label>Extension of lease term</label>
                </value>
                <value>
                    <fullName>K</fullName>
                    <label>Lockout</label>
                </value>
                <value>
                    <fullName>M</fullName>
                    <label>Marketing Fund</label>
                </value>
                <value>
                    <fullName>N</fullName>
                    <label>New Merchant (Current)</label>
                </value>
                <value>
                    <fullName>O</fullName>
                    <label>New Merchant (Cur) - Holdover</label>
                </value>
                <value>
                    <fullName>R</fullName>
                    <label>New Lease (Renewal)</label>
                </value>
                <value>
                    <fullName>U</fullName>
                    <label>New Lease (Renewal) - Holdover</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TechStatusChanged__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tech_StatusChanged</label>
        <type>Checkbox</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ContractTriggerHandlerTest.cls
/**
  *		Test Class for ContractTriggerHandler
  *		Created by Prince; 3/20/2019
  */
@isTest
public class ContractTriggerHandlerTest {
    @testSetup private static void testSetup() {
        // Create Test User
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SYSTEM_ADMINISTRATOR LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('Test', 'User 1', profileRec.Id);
        Database.insert(testUser);
        
        // Create Account
        Account accountRecord = new Account();
        accountRecord = TestDataFactory.createAccount(0);
        Database.insert(accountRecord);
        
        // Create Contract
        List<Contract__c> contractList = new List<Contract__c>();
        // contractList = TestDataFactory.createContract(1, accountRecord, propertyRecord, opportunityList[0]);
        contractList = TestDataFactory.createContract(1, accountRecord);
        contractList[0].LeaseStatus__c = 'F';
        
        Database.insert(contractList);
    }

    /**
	  *		Check 'Before Update' logic
	  */
    @isTest public static void updateTechStatus() {
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SYSTEM_ADMINISTRATOR LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('Test', 'User 2', profileRec.Id);
        
        Contract__c contractRecord = [SELECT Id, LeaseStatus__c, TechStatusChanged__c FROM Contract__c LIMIT 1];
        
        System.runAs(testUser) {
            Test.startTest();
          	
            contractRecord.LeaseStatus__c = 'D';
            database.update(contractRecord);
                
            Test.stopTest();
        }
        
    }
}