objects/Contract__c.object
<CustomObject>
    <description>&lt;CON&gt; - Represents a contract signed with a retailer. Either lease, Commercial lease, license agreement</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipName>Leases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Reduced ROLO</fullName>
                </value>
                <value>
                    <fullName>No ROLO</fullName>
                </value>
                <value>
                    <fullName>Over payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PropertyTeam__c.object
<CustomObject>
    <description>&lt;PRT&gt; - Represents a internal team working for the property eg. Centre Manager, Facility Manager, RDM, Leasing Executive, Development Leasing Executive</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Property Team</relationshipLabel>
        <relationshipName>Property_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TeamMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Property_Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property Team</label>
    <nameField>
        <displayFormat>PRT-{0000}</displayFormat>
        <label>Property Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>At Risk</fullName>
                </value>
                <value>
                    <fullName>Held</fullName>
                </value>
                <value>
                    <fullName>Trading</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TaskTemplateAndCondition__c.object
<CustomObject>
    <description>&lt;TTC&gt; - Used to define which tasks must be created during the Opportunity life cycle, as well the task creation criteria, the assignee and target resolution time frame for each task.</description>
    <fields>
        <fullName>GroupRenewalRole__c</fullName>
        <label>Group Renewal Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Group Renewal Admin Team</fullName>
                    <label>Group Renewal Team</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TaskType__c</fullName>
        <label>Task Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>OpportunityTaskType</valueSetName>
        </valueSet>
    </fields>
    <label>Task Template And Condition</label>
    <nameField>
        <displayFormat>TCN-{0000}</displayFormat>
        <label>Task Template And Condition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Template And Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TaskUtilityInvocableTest.cls
@isTest
public class TaskUtilityInvocableTest {
    
    private static Map<String, Schema.RecordTypeInfo> oppRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(Constants.OPPORTUNITY);
    
	@testSetup
    private static void testSetup() {
        Map<String, Schema.RecordTypeInfo> accountRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(Constants.ACCOUNT);
        Map<String, Schema.RecordTypeInfo> propTeamRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(Constants.PROPERTY_TEAM_API);
        Map<String, Schema.RecordTypeInfo> caseRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(Constants.OBJECT_CASE);
        
        //Create Price Book
        List<Pricebook2> priceBookList = new List<Pricebook2>();
        priceBookList = TestDataFactory.createPricebook(1);
        database.insert(priceBookList);
        
        //Create Property
        List<Property__c> propertyList = new List<Property__c>();
        propertyList = TestDataFactory.createProperty(1, priceBookList[0]);
        database.insert(propertyList);
        
        //Create Account
        List<Account> accountList = new List<Account>();
        accountList = TestDataFactory.createAccountBulk(5, propertyList[0].Id, accountRecordTypeMapByName.get(Constants.PROPERTY_BASED).getRecordTypeId());
        database.insert(accountList);        
        
        //Create Space
        List<Space__c> spaceList = new List<Space__c>();
        spaceList = TestDataFactory.createSpace(1, propertyList[0]);
        database.insert(spaceList);
        
        //Create Opportunity
        List<Opportunity> oppList = new List<Opportunity>();
        oppList = TestDataFactory.createOpportunity(1, accountList[0], propertyList[0], spaceList[0]);
        database.insert(oppList);      
        
        //Create Users
        List<User> testUserList = new List<User>();
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SCG_SYS_ADM LIMIT 1];
        testUserList.add(TestDataFactory.createUniqueTestUser('Test', 'User 1', profileRec.Id));
        testUserList.add(TestDataFactory.createUniqueTestUser('Test', 'User 2', profileRec.Id));
        testUserList.add(TestDataFactory.createUniqueTestUser('Test', 'User 3', profileRec.Id));
        database.insert(testUserList);        
        
        //Create Property Team
        List<PropertyTeam__c> propertyTeamList = new List<PropertyTeam__c>();
        propertyTeamList.add(TestDataFactory.createPropertyTeam(propertyList[0].Id, 
                                                                Constants.TEAM_ROLE_PRA, 
                                                                testUserList[0].Id, 
                                                                propTeamRecordTypeMapByName.get(Constants.PRT_INTERNAL_TEAM_MEMBER).getRecordTypeId()));
        propertyTeamList.add(TestDataFactory.createPropertyTeam(propertyList[0].Id, 
                                                                Constants.TEAM_ROLE_RA, 
                                                                testUserList[1].Id, 
                                                                propTeamRecordTypeMapByName.get(Constants.PRT_INTERNAL_TEAM_MEMBER).getRecordTypeId()));
        propertyTeamList.add(TestDataFactory.createPropertyTeam(propertyList[0].Id, 
                                                                'Group Renewal Admin Team', 
                                                                testUserList[2].Id, 
                                                                propTeamRecordTypeMapByName.get(Constants.PRT_INTERNAL_TEAM_MEMBER).getRecordTypeId()));        
        database.insert(propertyTeamList);       
        
        //Create Task Template
        List<TaskTemplateAndCondition__c> taskTemplateList = new List<TaskTemplateAndCondition__c>();
        TaskTemplateAndCondition__c sendDocsTemplate = TestDataFactory.createTaskTemplate(Constants.TASK, 
                                                                'Retail Administrator', 
                                                                null, 
                                                                'Propose & Accept', 
                                                                'Send Documents for Execution', 
                                                                '23 - Send Documents for Execution', 
                                                                'Property Team', 
                                                                Constants.RETAIL);
        
        sendDocsTemplate.GroupRenewalRole__c = 'Group Renewal Admin Team';
        taskTemplateList.add(sendDocsTemplate);
        database.insert(taskTemplateList);
        
        
        //Create Contract
        List<Contract__c> contractList = new List<Contract__c>();
        contractList.addAll(TestDataFactory.createContract(1, accountList[0]));
        database.insert(contractList);
        
        //Create Case
        List<Case> caseList = new List<Case>();
        Case sampleCase = TestDataFactory.createCase(contractList[0], spaceList[0], caseRecordTypeMapByName.get(Constants.LEASING_CHECKSHEET).getRecordTypeId());
        sampleCase.Opportunity__c = oppList[0].Id;
        sampleCase.Type = 'Checksheet';
        sampleCase.SubType__c = 'Variation Checksheet';
        
        caseList.add(sampleCase);
        database.insert(caseList);
        
    }
    @isTest
    private static void sendDocsPRATest() {
        Case case1 = [SELECT Id, Opportunity__c, Space__c, Space__r.Property__c, OwnerId, Type FROM Case LIMIT 1];
        Opportunity opp =  [SELECT Id, Tech_isCreatedFromGroupRenew__c, RecordType.DeveloperName, SpecialityLeaseType__c, CurrencyIsoCode, Type
                                      FROM Opportunity
                                      WHERE Id=:case1.Opportunity__c];
        
        Map<String, PropertyTeam__c> propTeamMap = DatabaseSOQLBank.getPropertyTeamByProperty(new Set<Id>{case1.Space__r.Property__c}).get(case1.Space__r.Property__c);
        
        
        system.debug('ZZZ Case Type -- ' + case1.Type);
        update case1;

        Test.startTest();        
        system.debug('Record Type -- ' + opp.RecordType.DeveloperName);
        system.debug('Type -- ' + opp.Type);
        system.debug('SpecialityLeaseType -- ' + opp.SpecialityLeaseType__c);
        system.debug('Currency -- ' + opp.CurrencyIsoCode);
        
        TaskUtilityInvocable.createSendDocsFromCase(new List<Id>{case1.Id});
        
        system.debug('PRA -- ' + propTeamMap.get(Constants.TEAM_ROLE_PRA).TeamMember__c);
        system.debug('RA -- ' + propTeamMap.get(Constants.TEAM_ROLE_RA).TeamMember__c);
        system.debug('GRAT -- ' + propTeamMap.get('Group Renewal Admin Team').TeamMember__c);
        system.debug('Case owner -- ' + case1.OwnerId);
        
        
        for (Task createdTask : [SELECT Id, TaskType__c, OwnerId FROM Task WHERE WhatId=:opp.Id AND TaskType__c='23 - Send Documents for Execution']) {
            system.debug('task owner -- ' + createdTask.OwnerId);
            System.assert(createdTask.OwnerId == propTeamMap.get(Constants.TEAM_ROLE_RA).TeamMember__c);
        }
        
        
        Test.stopTest();
    }
    @isTest
    private static void sendDocsRATest(){
        Case case1 = [SELECT Id, Opportunity__c, Space__c, Space__r.Property__c, OwnerId, Type FROM Case LIMIT 1];
        Opportunity opp =  [SELECT Id, Tech_isCreatedFromGroupRenew__c, RecordType.DeveloperName, SpecialityLeaseType__c, CurrencyIsoCode, Type
                            FROM Opportunity
                            WHERE Id=:case1.Opportunity__c];
        
        Map<String, PropertyTeam__c> propTeamMap = DatabaseSOQLBank.getPropertyTeamByProperty(new Set<Id>{case1.Space__r.Property__c}).get(case1.Space__r.Property__c);
        
        
        system.debug('ZZZ Case Type -- ' + case1.Type);
        update case1;
        
        Test.startTest();        
        
        opp.RecordTypeId = oppRecordTypeMapByName.get(Constants.OPP_COMMERCIAL_LEASING).getRecordTypeId();
        update opp;
        
        Space__c space1 = [SELECT Id, Status__c FROM Space__c WHERE Id =:case1.Space__c];
        space1.Status__c = Constants.SPACE_STATUS_PROJECT;
        update space1;
        
        TaskUtilityInvocable.createSendDocsFromCase(new List<Id>{case1.Id});
        
        for (Task createdTask : [SELECT Id, TaskType__c, OwnerId FROM Task WHERE WhatId=:opp.Id AND TaskType__c='23 - Send Documents for Execution']) {
            system.debug('task owner -- ' + createdTask.OwnerId);
            System.assert(createdTask.OwnerId == propTeamMap.get(Constants.TEAM_ROLE_PRA).TeamMember__c);
        }
        
        
        Test.stopTest();
    }
    @isTest
    private static void sendDocsGRATTest(){
        Case case1 = [SELECT Id, Opportunity__c, Space__c, Space__r.Property__c, OwnerId, Type FROM Case LIMIT 1];
        Opportunity opp =  [SELECT Id, Tech_isCreatedFromGroupRenew__c, RecordType.DeveloperName, SpecialityLeaseType__c, CurrencyIsoCode, Type
                            FROM Opportunity
                            WHERE Id=:case1.Opportunity__c];
        
        Map<String, PropertyTeam__c> propTeamMap = DatabaseSOQLBank.getPropertyTeamByProperty(new Set<Id>{case1.Space__r.Property__c}).get(case1.Space__r.Property__c);
        
        
        system.debug('ZZZ Case Type -- ' + case1.Type);
        update case1;
        
        Test.startTest();        

        opp.Tech_IsCreatedFromGroupRenew__c = true;
        update opp;
        TaskUtilityInvocable.createSendDocsFromCase(new List<Id>{case1.Id});
        
        
        for (Task createdTask : [SELECT Id, TaskType__c, OwnerId FROM Task WHERE WhatId=:opp.Id AND TaskType__c='23 - Send Documents for Execution']) {
            system.debug('task owner -- ' + createdTask.OwnerId);
            System.assert(createdTask.OwnerId == propTeamMap.get('Group Renewal Admin Team').TeamMember__c);
        }
        
        
        Test.stopTest();
    }   
}