objects/Contract__c.object
<CustomObject>
    <description>&lt;CON&gt; - Represents a contract signed with a retailer. Either lease, Commercial lease, license agreement</description>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipName>Leases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lease</fullName>
                </value>
                <value>
                    <fullName>License Agreement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>DevelopmentType__c</fullName>
        <label>Development Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>DevelopmentImpacted__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Operational</fullName>
                    <default>true</default>
                    <label>Operational</label>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Mini Project</fullName>
                </value>
                <value>
                    <fullName>None Project</fullName>
                    <isActive>false</isActive>
                    <label>None Project</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LatestAchievedOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Latest Achieved Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Opportunity Space don&apos;t match with Selected space Record.</errorMessage>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>Opportunity.Space__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Spaces (Latest Achieved Opportunity)</relationshipLabel>
        <relationshipName>LatestAchievedOpportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RentableArea__c</fullName>
        <label>Rentable Area</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>At Risk</fullName>
                </value>
                <value>
                    <fullName>Held</fullName>
                </value>
                <value>
                    <fullName>Trading</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SpaceType</valueSetName>
        </valueSet>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/SpaceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Shop</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Kiosk</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Office Suite</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Store Room</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Seating</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sundry Property</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Garage / Parking</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sundry</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Space Bank</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Common Mall</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>Re-design</label>
    </customValue>
    <customValue>
        <fullName>Seating License</fullName>
        <isActive>false</isActive>
        <label>Seating License</label>
    </customValue>
    <customValue>
        <fullName>Sundry Site</fullName>
        <isActive>false</isActive>
        <label>Sundry Site</label>
    </customValue>
    <masterLabel>Space Type</masterLabel>
</GlobalValueSet>

classes/SpaceTriggerHandlerTest.cls
/*
* @author:              Sidney Garcia
* @description:         Test class for SpaceTriggerHandler
*/

@isTest
public class SpaceTriggerHandlerTest {
    @TestSetup private static void testSetup(){
        Map<String, Schema.RecordTypeInfo> accountRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(CONSTANTS.ACCOUNT);
        List<Account> accountList = new List<Account>();
        List<Opportunity> opportunityList = new List<Opportunity>();
        List<Contract__c> contractList = new List<Contract__c>();
        
        List<Pricebook2> priceBookList = TestDataFactory.createPricebook(1);
        Database.insert(priceBookList);
        Pricebook2 priceBookRec = [SELECT Id, CurrencyIsoCode FROM Pricebook2 LIMIT 1];
        
        Property__c property = TestDataFactory.createProperty(1, priceBookRec)[0];
        Database.insert(property);
        Property__c propRec = [SELECT Id, Name FROM Property__c LIMIT 1];
        //CREATE ACCOUNT
        accountList.addAll(TestDataFactory.createAccountBulk(10, property.Id, accountRecordTypeMapByName.get(CONSTANTS.PROPERTY_BASED).getRecordTypeId()));
        database.insert(accountList);
        
        //CREATE OPPORTUNITY
        /*accountList = [SELECT Id, Property__c FROM Account LIMIT 10];
        opportunityList = TestDataFactory.createOpportunity(accountList);
        
        for(Opportunity opp : opportunityList){
            opp.JDESentStatus__c = 'Ready';
        }
        
        database.insert(opportunityList);
        
        Integer counter = 0;
        List<Space__c> spaceList = TestDataFactory.createSpace(200, property);
        for(Space__c space : spaceList){
            space.RentableArea__c = 40;
            space.DevelopmentType__c = null;
            space.RecordTypeId = spaceRecordTypeMap.get(Constants.PROSPECTIVE_SPACE).getRecordTypeId();
            
            if(counter != (opportunityList.size() - 1)){
                space.LatestAchievedOpportunity__c = opportunityList[counter].Id;
                counter++;
            }
        }
        
        Database.insert(spaceList);
        List<Space__c> newSpaceList = [SELECT Id, RentableArea__c, DevelopmentType__c, RecordTypeId, Type__c, Property__c FROM Space__c LIMIT 200];*/
        
        
    }
    
    @isTest
    private static void testSpaceInsert1() {
        List<Property__c> propertyList = [SELECT Id, Name FROM Property__c];
        List<Space__c> spaceList = TestDataFactory.createSpace(200, propertyList[0]);
        Map<String, Schema.RecordTypeInfo> spaceRecordTypeMap = RecordTypeUtil.getAllRecordTypesByName(Constants.SPACE);
        
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SYSTEM_ADMINISTRATOR LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        
        for(Space__c space : spaceList){
            space.RentableArea__c = 40;
            space.DevelopmentType__c = null;
            space.RecordTypeId = spaceRecordTypeMap.get(Constants.PROSPECTIVE_SPACE).getRecordTypeId();
        }
        
        system.runAs(testUser) {
            test.startTest();
                Database.insert(spaceList);
            test.stopTest();
        }
    }
    
    @isTest
    private static void testSpaceUpdate1() {
        test.startTest();
        List<Account> accountList = new List<Account>();
        List<Property__c> propertyList = [SELECT Id, Name FROM Property__c];
        List<Space__c> spaceList = TestDataFactory.createSpace(10, propertyList[0]);
        List<Opportunity> opportunityList = new List<Opportunity>();
        List<Opportunity> opportunityTempList = new List<Opportunity>();
        Map<Id, Opportunity> spaceIdOpportunityMap = new Map<Id, Opportunity>();
        Map<String, Schema.RecordTypeInfo> spaceRecordTypeMap = RecordTypeUtil.getAllRecordTypesByName(Constants.SPACE);
        
        Profile retailFinanceProf = [SELECT Id FROM Profile WHERE Name = 'SCG-Retail Finance' LIMIT 1];
        Profile retailCentreMgtProf = [SELECT Id FROM Profile WHERE Name = 'SCG-Retail CentreMgt' LIMIT 1];
        
        UserRole retailCRMRole = [SELECT Id FROM UserRole WHERE Name='Retail CRM' LIMIT 1];
        User retailFinance = TestDataFactory.createUniqueTestUser('John', 'Doe', retailFinanceProf.Id);
        User retailCentreMgt = TestDataFactory.createUniqueTestUser('John', 'Doe', retailCentreMgtProf.Id);
        retailFinance.UserRoleId = retailCRMRole.Id;
        retailCentreMgt.UserRoleId = retailCRMRole.Id;
            
        system.runAs(retailFinance) {
            for(Space__c space : spaceList){
                space.RentableArea__c = 40;
                space.DevelopmentType__c = null;
                space.RecordTypeId = spaceRecordTypeMap.get(Constants.PROSPECTIVE_SPACE).getRecordTypeId();
            }
            
            Database.insert(spaceList);
            
            //CREATE OPPORTUNITY
            Integer counter = 0;
            accountList = [SELECT Id, Property__c FROM Account LIMIT 10];
            for(Account acc : accountList){
                opportunityTempList = TestDataFactory.createOpportunity(1, acc);
                
                for(Opportunity opp : opportunityTempList){
                    opp.JDESentStatus__c = 'Ready';
                    opp.Space__c = spaceList[counter].Id;
                    counter++;
                }
                
                opportunityList.addAll(opportunityTempList);
            }
            
            database.insert(opportunityList);
            
            for(Opportunity opp : opportunityList){
                spaceIdOpportunityMap.put(opp.Space__c, opp);
            }
            
        
            
            for(Space__c spc : spaceList){
                spc.LatestAchievedOpportunity__c = spaceIdOpportunityMap.get(spc.Id).Id;
                spc.RentableArea__c = 50;
            }
            TriggerHandler.clearBypass('SpaceTriggerHandler');
            spaceList[0].Status__c = 'Project';
            Database.update(spaceList[0]);
            
            
        }
        /*system.runAs(retailCentreMgt) { 
        	spaceList[1].RentableArea__c = 60;
			Database.update(spaceList[1]);       
        }*/
        
        test.stopTest();
    }
    
    
    
    @isTest
    private static void testSpaceUpdate2() {
        test.startTest();
        List<Account> accountList = new List<Account>();
        List<Property__c> propertyList = [SELECT Id, Name FROM Property__c];
        List<Space__c> spaceList = TestDataFactory.createSpace(10, propertyList[0]);
        List<Opportunity> opportunityList = new List<Opportunity>();
        List<Opportunity> opportunityTempList = new List<Opportunity>();
        Map<Id, Opportunity> spaceIdOpportunityMap = new Map<Id, Opportunity>();
        Map<String, Schema.RecordTypeInfo> spaceRecordTypeMap = RecordTypeUtil.getAllRecordTypesByName(Constants.SPACE);
        
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SYSTEM_ADMINISTRATOR LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        
        Profile retailFinanceProf = [SELECT Id FROM Profile WHERE Name = 'SCG-Retail Finance' LIMIT 1];
        Profile retailCentreMgtProf = [SELECT Id FROM Profile WHERE Name = 'SCG-Retail CentreMgt' LIMIT 1];
        
        UserRole retailCRMRole = [SELECT Id FROM UserRole WHERE Name='Retail CRM' LIMIT 1];
        User retailFinance = TestDataFactory.createUniqueTestUser('John', 'Doe', retailFinanceProf.Id);
        User retailCentreMgt = TestDataFactory.createUniqueTestUser('John', 'Doe', retailCentreMgtProf.Id);
        retailFinance.UserRoleId = retailCRMRole.Id;
        retailCentreMgt.UserRoleId = retailCRMRole.Id;        
        system.runAs(retailCentreMgt) {
            for(Space__c space : spaceList){
                space.RentableArea__c = 40;
                space.DevelopmentType__c = null;
                space.RecordTypeId = spaceRecordTypeMap.get(Constants.PROSPECTIVE_SPACE).getRecordTypeId();
            }
            
            Database.insert(spaceList);
            
            
            
            //CREATE OPPORTUNITY
            Integer counter = 0;
            accountList = [SELECT Id, Property__c FROM Account LIMIT 10];
            for(Account acc : accountList){
                opportunityTempList = TestDataFactory.createOpportunity(1, acc);
                
                for(Opportunity opp : opportunityTempList){
                    opp.JDESentStatus__c = 'Ready';
                    opp.Space__c = spaceList[counter].Id;
                    counter++;
                }
                
                opportunityList.addAll(opportunityTempList);
            }
            
            database.insert(opportunityList);
            
            for(Opportunity opp : opportunityList){
                spaceIdOpportunityMap.put(opp.Space__c, opp);
            }
            
            
            
            for(Space__c spc : spaceList){
                spc.LatestAchievedOpportunity__c = spaceIdOpportunityMap.get(spc.Id).Id;
                spc.Status__c = 'Trading';
                spc.RentableArea__c = 50;
            }
            spaceList[0].Status__c = 'Inactive';
            TriggerHandler.clearBypass('SpaceTriggerHandler');
            
            try {
                spaceList[0].Type__c = '4';
            	Database.update(spaceList[0]);    
            } catch (Exception e) {
                system.assert(e != null, 'Error not triggered');
            }
            
            try {
                spaceList[1].Type__c = '4';
                Database.update(spaceList[1]);
                system.assert(spaceList[1].Type__c == '4', 'Update Failed');
            } catch (Exception e) { 
                
            }
            
            
            
            test.stopTest();
        }
    }
}