objects/Contract__c.object
<CustomObject>
    <description>&lt;CON&gt; - Represents a contract signed with a retailer. Either lease, Commercial lease, license agreement</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts (Account)</relationshipLabel>
        <relationshipName>Contracts1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipName>Leases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PropertyTeam__c.object
<CustomObject>
    <description>&lt;PRT&gt; - Represents a internal team working for the property eg. Centre Manager, Facility Manager, RDM, Leasing Executive, Development Leasing Executive</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You should only select Third party type accounts.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ACCThirdParty</value>
            </filterItems>
            <infoMessage>You can only select Third party type accounts.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Property Team (Account)</relationshipLabel>
        <relationshipName>Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Property Team</relationshipLabel>
        <relationshipName>Property_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Property Team</label>
    <nameField>
        <displayFormat>PRT-{0000}</displayFormat>
        <label>Property Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CreateInspectionfromSpaceControllerTest.cls
/*
*       author: Clark Marie Garde
*       created date: June 5, 2018
*       description: Test class for CreateInspectionfromSpaceController
*
*/

@isTest
public class CreateInspectionfromSpaceControllerTest {
    
    @TestSetup private static void testSetup() {
        Map<String, Schema.RecordTypeInfo> accountRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(CONSTANTS.ACCOUNT);
        List<Property__c> propertyList = new List<Property__c>();
        Property__c propertyRecord = new Property__c();
        Account account = new Account();
        List<Space__c> spaceList= new List<Space__c>();
        Account accountRecord = new Account();
        List<Contract__c> contrList= new List<Contract__c>();
        List<Contract__c> contrRecord = new List<Contract__c>();
        List<Pricebook2> pricebookList = new List<Pricebook2>();
        
        //CREATE PRICEBOOK
        pricebookList = TestDataFactory.createPricebook(10);
        database.insert(pricebookList);
        pricebookList = [SELECT Id, CurrencyIsoCode FROM Pricebook2];
        
        //CREATE PROPERTY
        propertyList = TestDataFactory.createProperty(10, pricebookList[0]);
        database.insert(propertyList);
        propertyRecord = [SELECT Id FROM Property__c LIMIT 1];
        
        //CREATE Account
        account = TestDataFactory.createAccount(20, propertyRecord.id, accountRecordTypeMapByName.get(CONSTANTS.GROUP_LEVEL).getRecordTypeId());
        database.insert(account);
        accountRecord = [SELECT Id, Name FROM Account];
        
        //CREATE Contract
        contrList = TestDataFactory.createContract(20, account);
        database.insert(contrList);
        system.debug('contracttt' + contrList);
        contrRecord = [SELECT Id, Name, Account__c FROM Contract__c limit 1];
        
        //CREATE Space
        spaceList = TestDataFactory.createSpace(20, account, propertyList[0], contrRecord[0]);
        Database.insert(spaceList);

    }
    
    public static testMethod void getSpaceDetails() {
        Space__c space = [SELECT ID FROM Space__c LIMIT 1];
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SCG_SYS_ADM LIMIT 1];
        Account account = [SELECT Id FROM Account LIMIT 1];
        //Create Users
        List<User> userList = new List<User>();
        userList.add(TestDataFactory.createUniqueTestUser('Bruce', 'Wayne', profileRec.Id));
        database.insert(userList);
        CreateInspectionfromSpaceController.Response response = new CreateInspectionfromSpaceController.Response();
        //Create Account Team
        List<AccountTeamMember> accountTeamList = new List<AccountTeamMember>();
        accountTeamList.add(TestDataFactory.createAccountTeamMember(account.Id, userList[0].Id));
        database.insert(accountTeamList);
        Test.startTest();
        response = CreateInspectionfromSpaceController.getspacedetails(space.ID);
        Test.stopTest();
        
        System.assertEquals('Success', response.status); 
    }
    
    public static testMethod void getSpaceDetails2() {
        Space__c space = [SELECT ID, Property__c FROM Space__c LIMIT 1];
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SCG_SYS_ADM LIMIT 1];
        //Create Users
        List<User> userList = new List<User>();
        userList.add(TestDataFactory.createUniqueTestUser('Bruce', 'Wayne', profileRec.Id));
        database.insert(userList);
        //Create Property Team
        Map<String, Schema.RecordTypeInfo> propTeamRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(Constants.PROPERTY_TEAM_API);
        List<PropertyTeam__c> propertyTeamList = new List<PropertyTeam__c>();
        propertyTeamList.add(TestDataFactory.createPropertyTeam(space.Property__c, Constants.TEAM_ROLE_RDM, userList[0].Id, propTeamRecordTypeMapByName.get(Constants.PRT_INTERNAL_TEAM_MEMBER).getRecordTypeId()));
        database.insert(propertyTeamList);
        CreateInspectionfromSpaceController.Response response = new CreateInspectionfromSpaceController.Response();
        
        Test.startTest();
        response = CreateInspectionfromSpaceController.getspacedetails(space.ID);
        Test.stopTest();
        
        System.assertEquals('Success', response.status); 
    }
    
    public static testMethod void isIRCaseRaisedEarlierTest(){
        Space__c space = [SELECT ID, Property__c FROM Space__c LIMIT 1];
        
        Test.startTest();
        	Boolean flag = CreateInspectionfromSpaceController.isIRCaseRaisedEarlier(space.Id);
        Test.stopTest();
        
        System.assertEquals(flag, false);
    }
}