objects/Contract__c.object
<CustomObject>
    <description>&lt;CON&gt; - Represents a contract signed with a retailer. Either lease, Commercial lease, license agreement</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts (Account)</relationshipLabel>
        <relationshipName>Contracts1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AutoInspectionReportCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field get updated when 9 month expiry inspection report is created.</description>
        <label>Auto Inspection Report Created ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LeaseEndDate__c</fullName>
        <label>Lease End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LeaseStatus__c</fullName>
        <label>Lease Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                    <label>Assigned</label>
                </value>
                <value>
                    <fullName>B</fullName>
                    <label>Assigned - Holdover</label>
                </value>
                <value>
                    <fullName>C</fullName>
                    <label>Assigned - after Renewal</label>
                </value>
                <value>
                    <fullName>D</fullName>
                    <label>Future - D&amp;C</label>
                </value>
                <value>
                    <fullName>E</fullName>
                    <label>Expired</label>
                </value>
                <value>
                    <fullName>F</fullName>
                    <label>Future Lease</label>
                </value>
                <value>
                    <fullName>H</fullName>
                    <label>Holdover</label>
                </value>
                <value>
                    <fullName>I</fullName>
                    <label>Extension of lease term</label>
                </value>
                <value>
                    <fullName>K</fullName>
                    <label>Lockout</label>
                </value>
                <value>
                    <fullName>M</fullName>
                    <label>Marketing Fund</label>
                </value>
                <value>
                    <fullName>N</fullName>
                    <label>New Merchant (Current)</label>
                </value>
                <value>
                    <fullName>O</fullName>
                    <label>New Merchant (Cur) - Holdover</label>
                </value>
                <value>
                    <fullName>R</fullName>
                    <label>New Lease (Renewal)</label>
                </value>
                <value>
                    <fullName>U</fullName>
                    <label>New Lease (Renewal) - Holdover</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipName>Leases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lease</fullName>
                </value>
                <value>
                    <fullName>License Agreement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>CreateInspectionReport__c</fullName>
        <formula>IF( DAY( TODAY() ) = 31 &amp;&amp; MONTH( TODAY() ) = 10 &amp;&amp;  
    CurrentLeaseExpiryDate__c  &gt; ADDMONTHS( TODAY() ,9) &amp;&amp; CurrentLeaseExpiryDate__c &lt;= ADDMONTHS( TODAY() , 11) &amp;&amp; 
	(ISPICKVAL(Type__c, &apos;1&apos;)||ISPICKVAL(Type__c, &apos;2&apos;)) &amp;&amp; 
	NOT( ISPICKVAL(CurrentLease__r.LeaseStatus__c , &apos;E&apos;) || ISPICKVAL(CurrentLease__r.LeaseStatus__c , &apos;F&apos;) || 
        	ISPICKVAL(CurrentLease__r.LeaseStatus__c , &apos;D&apos;) || ISPICKVAL(CurrentLease__r.LeaseStatus__c , &apos;K&apos;) || ISPICKVAL(CurrentLease__r.LeaseStatus__c , &apos;M&apos;)), 
	true , 
	IF( CurrentLeaseExpiryDate__c = ADDMONTHS( TODAY() ,9) &amp;&amp;
	   (MONTH(CurrentLeaseExpiryDate__c) != 8 &amp;&amp; MONTH(CurrentLeaseExpiryDate__c) != 9) &amp;&amp;
	   (ISPICKVAL(Type__c, &apos;1&apos;)||ISPICKVAL(Type__c, &apos;2&apos;)) &amp;&amp; 
	    NOT(ISPICKVAL(CurrentLease__r.LeaseStatus__c , &apos;E&apos;) || ISPICKVAL(CurrentLease__r.LeaseStatus__c , &apos;F&apos;) || ISPICKVAL(CurrentLease__r.LeaseStatus__c , &apos;D&apos;) || ISPICKVAL(CurrentLease__r.LeaseStatus__c , &apos;K&apos;) || ISPICKVAL(CurrentLease__r.LeaseStatus__c , &apos;M&apos;)), 
		true, 
		false))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Create Inspection Report</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CurrentLeaseExpiryDate__c</fullName>
        <formula>CurrentLease__r.LeaseEndDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Lease Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CurrentLease__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Lease</label>
        <referenceTo>Contract__c</referenceTo>
        <relationshipLabel>Spaces (Current Lease)</relationshipLabel>
        <relationshipName>CurrentLease</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SpaceType</valueSetName>
        </valueSet>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/SpaceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Shop</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Kiosk</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Office Suite</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Store Room</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Seating</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sundry Property</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Garage / Parking</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sundry</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Space Bank</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Common Mall</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>Re-design</label>
    </customValue>
    <customValue>
        <fullName>Seating License</fullName>
        <isActive>false</isActive>
        <label>Seating License</label>
    </customValue>
    <customValue>
        <fullName>Sundry Site</fullName>
        <isActive>false</isActive>
        <label>Sundry Site</label>
    </customValue>
    <masterLabel>Space Type</masterLabel>
</GlobalValueSet>

classes/CreateInspectionBatchTest.cls
/*
*       author: Clark Marie Garde
*       created date: June 8, 2018
*       description: Test class for CreateInspectionBatch
*
*/
@isTest
public class CreateInspectionBatchTest {
    
    @TestSetup private static void testSetup() {
        Map<String, Schema.RecordTypeInfo> accountRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(CONSTANTS.ACCOUNT);
        List<Property__c> propertyList = new List<Property__c>();
        Property__c propertyRecord = new Property__c();
        Account account = new Account();
        List<Space__c> spaceList= new List<Space__c>();
        Space__c spaceRecord = new Space__c();
        Account accountRecord = new Account();
        List<Contract__c> contrList= new List<Contract__c>();
        List<Contract__c> contrRecord = new List<Contract__c>();
        List<Pricebook2> pricebookList = new List<Pricebook2>();
        
        //CREATE PRICEBOOK
        pricebookList = TestDataFactory.createPricebook(10);
        database.insert(pricebookList);
        pricebookList = [SELECT Id, CurrencyIsoCode FROM Pricebook2];
        
        //CREATE PROPERTY
        propertyList = TestDataFactory.createProperty(10, pricebookList[0]);
        database.insert(propertyList);
        propertyRecord = [SELECT Id FROM Property__c LIMIT 1];
        
        //CREATE Account
        account = TestDataFactory.createAccount(20, propertyRecord.id, accountRecordTypeMapByName.get(CONSTANTS.GROUP_LEVEL).getRecordTypeId());
        database.insert(account);
        accountRecord = [SELECT Id, Name FROM Account];
        
        //CREATE Contract
        contrList = TestDataFactory.createContract(20, account);
        
        for(Contract__c con : contrList){
          con.LeaseEndDate__c = Date.today().addMonths(9);
        }
        database.insert(contrList);
        system.debug('contracttt' + contrList); 
        contrRecord = [SELECT Id, Name, Account__c FROM Contract__c limit 1];
        
        //CREATE Space
        spaceList = TestDataFactory.createSpace(20, account, propertyList[0], contrRecord[0]);
        Database.insert(spaceList);
        spaceRecord = [SELECT Id, Name,CreateInspectionReport__c FROM Space__c LIMIT 1];
        
    }
    
    public static testMethod void getSpaceDetails() {
        Space__c spaceRec = [SELECT Type__c,CurrentLease__r.LeaseStatus__c,CurrentLeaseExpiryDate__c,Id,CurrentLease__c,CreateInspectionReport__c from Space__c WHERE CurrentLease__c!=null LIMIT 1];
        spacerec.Type__c = '3';
        TriggerHandler.bypass('SpaceTriggerHandler');
        TriggerHandler.bypass('ContractTriggerHandler');
        database.update(spacerec);
        List<Contract__c> contractList = [SELECT LeaseStatus__c,Id, Property__c, Name, Property__r.Name, Space__c, Space__r.Name,
                                            Space__r.CurrentLease__c, Account__r.Name, LeaseEndDate__c, Account__c, 
                                            Account__r.ParentId, Opportunity__c
                                          FROM Contract__c 
                                          WHERE Id =: spaceRec.CurrentLease__c AND AutoInspectionReportCreated__c=false 
                                          LIMIT 1];

        List<Case> caseToCreate = new List<Case>();
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SCG_SYS_ADM LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        database.insert(testUser);
        system.runAs(testUser){
            Test.startTest();
            caseToCreate = CaseBL.CreateInspectionforContract(contractList);
            database.insert(caseToCreate);      
            CreateInspectionBatch inspectionBatch = new CreateInspectionBatch(); 
            Id batchId = Database.executeBatch(inspectionBatch);
            
            contractList[0].LeaseEndDate__c = contractList[0].LeaseEndDate__c.addDays(1);
            database.update(contractList);
            batchId = Database.executeBatch(inspectionBatch);
            
            contractList[0].LeaseEndDate__c = contractList[0].LeaseEndDate__c.addDays(1);
            database.update(contractList);
            batchId = Database.executeBatch(inspectionBatch);
            
            Test.stopTest();
        }
        
        System.assertEquals(true, caseToCreate <> null);
        
    }
}