objects/Contract__c.object
<CustomObject>
    <description>&lt;CON&gt; - Represents a contract signed with a retailer. Either lease, Commercial lease, license agreement</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts (Account)</relationshipLabel>
        <relationshipName>Contracts1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LeaseStatus__c</fullName>
        <label>Lease Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                    <label>Assigned</label>
                </value>
                <value>
                    <fullName>B</fullName>
                    <label>Assigned - Holdover</label>
                </value>
                <value>
                    <fullName>C</fullName>
                    <label>Assigned - after Renewal</label>
                </value>
                <value>
                    <fullName>D</fullName>
                    <label>Future - D&amp;C</label>
                </value>
                <value>
                    <fullName>E</fullName>
                    <label>Expired</label>
                </value>
                <value>
                    <fullName>F</fullName>
                    <label>Future Lease</label>
                </value>
                <value>
                    <fullName>H</fullName>
                    <label>Holdover</label>
                </value>
                <value>
                    <fullName>I</fullName>
                    <label>Extension of lease term</label>
                </value>
                <value>
                    <fullName>K</fullName>
                    <label>Lockout</label>
                </value>
                <value>
                    <fullName>M</fullName>
                    <label>Marketing Fund</label>
                </value>
                <value>
                    <fullName>N</fullName>
                    <label>New Merchant (Current)</label>
                </value>
                <value>
                    <fullName>O</fullName>
                    <label>New Merchant (Cur) - Holdover</label>
                </value>
                <value>
                    <fullName>R</fullName>
                    <label>New Lease (Renewal)</label>
                </value>
                <value>
                    <fullName>U</fullName>
                    <label>New Lease (Renewal) - Holdover</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ABNSearchController.cls
public class ABNSearchController {
    @AuraEnabled
    public static LightningResponse getABNDetails(String service, String searchValue){
        LightningResponse res = new LightningResponse();
        ABNLookupHelper.ABNsearchResultWrapper abnWrap;
        
        if((searchValue != null && service != null && !searchValue.containsWhitespace())){
            abnWrap = ABNLookupHelper.getABNSearchResult(service, searchValue);
            
            if(!String.isEmpty(abnWrap.message)){
                res.status = Constants.FAILED;
                res.message = abnWrap.message;
            }
        } else {
            res.status = Constants.FAILED;
            res.message = 'Invalid ABN or ACN';
        }
        
        if(Constants.SUCCESS.equalsIgnoreCase(res.status)){
            res.returnValue = JSON.serialize(abnWrap);
        }
        system.debug('RESULT: '+ res);
        return res;
    }
    
    @AuraEnabled
    public static LightningResponse getNZBNDetails(String searchValue){
        LightningResponse res = new LightningResponse();
        ABNLookupHelper.NZBNsearchResultWrapper nzbnWrap = new ABNLookupHelper.NZBNsearchResultWrapper();
        
        if(searchValue != null && !searchValue.containsWhitespace()){
            nzbnWrap = ABNLookupHelper.getNZBNSearchResult(searchValue);
        } else {
            res.status = Constants.FAILED;
            res.message = 'Invalid NZBN';
        }
        
        if(Constants.SUCCESS.equalsIgnoreCase(res.status)){
            res.returnValue = JSON.serialize(nzbnWrap);
        }
        return res;
    }
    @AuraEnabled
    public static LightningResponse isaccountvalidtoupdatedetails(String accountRecordId){
        LightningResponse res = new LightningResponse();
        Set<String> inactivecontractStatus=new Set<String>();
        inactivecontractStatus.add('Expired');
        
        if(accountRecordId!=null&&String.isNotBlank(accountRecordId)){
            Map<Id,Account> allchildaccountMap=new Map<Id,Account>([Select id from Account where parentId =: accountRecordId OR TechGrandParentId__c=: accountRecordId]); 
            Set<Id> accountIdset=new Set<Id>();
            accountIdset.addAll(allchildaccountMap.keySet());
            List<Contract__c> activecontractscount=[Select id from contract__c where Account__c in: accountIdset];
            List<AggregateResult> result=[Select count(id) totalactivecontracts from contract__c where Account__c in: accountIdset AND LeaseStatus__c NOT IN: inactivecontractStatus];
            Integer activecontractscountInt=0;
            if(!result.isEmpty()&&result.size()>0){
                activecontractscountInt=Integer.ValueOf(result[0].get('totalactivecontracts'));
            }
            
            res.returnValue=String.valueOf(activecontractscountInt);
            System.debug('INSIDE CONTROLLER '+ res.returnValue);
        }
        return res;
    }
}