objects/Contract__c.object
<CustomObject>
    <description>&lt;CON&gt; - Represents a contract signed with a retailer. Either lease, Commercial lease, license agreement</description>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipName>Leases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lease</fullName>
                </value>
                <value>
                    <fullName>License Agreement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OpportunityClause__c.object
<CustomObject>
    <description>&lt;OPC&gt; - Represents a clause applied to a deal.</description>
    <fields>
        <fullName>EffectiveFromDate__c</fullName>
        <label>Effective From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ClauseType</valueSetName>
        </valueSet>
    </fields>
    <label>Opportunity Clause</label>
    <nameField>
        <label>Opportunity Clauses Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Clauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PrecedentClause__c.object
<CustomObject>
    <description>&lt;PRC&gt; - Represents the link between clauses and agreed clauses for an account at National level.</description>
    <fields>
        <fullName>CurrentMaximumThreshold__c</fullName>
        <label>Current Maximum Threshold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CurrentMinimumThreshold__c</fullName>
        <label>Current Minimum Threshold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PromoPercentage__c</fullName>
        <label>Promo Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ClauseType</valueSetName>
        </valueSet>
    </fields>
    <label>Precedent Clause</label>
    <nameField>
        <label>Clause Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Precedent Clauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>ApplicableOutgoings__c</fullName>
        <label>Applicable Outgoings</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>OutgoingProducts</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PriceBook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Properties (PriceBook)</relationshipLabel>
        <relationshipName>PropertiesPriceBook</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PropertyCity__c</fullName>
        <label>Property City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PropertyShortName__c</fullName>
        <label>Property Short Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>ApplicableOutgoings__c</fullName>
        <formula>IF(ISPICKVAL(Property__r.Country__c, &apos;New Zealand&apos;),
(CASE(TEXT(Type__c), 
&quot;1&quot;, &quot;Air Con;Council Rates;Land Tax;Water Rates;Operating Expenses;Waste;Food Court;Cafe Court;Rubbish&quot;,
&quot;2&quot;, &quot;Air Con;Council Rates;Land Tax;Water Rates;Operating Expenses;Waste;Food Court;Cafe Court;Rubbish&quot;,
&quot;&quot;)),
(CASE(TEXT(Type__c), 
&quot;1&quot;, &quot;Air Con;Council Rates;Land Tax;Water Rates;Sunday Trade - Air Con;Sunday Trade;Operating Expenses;Emergency Levy;Cleaning&quot;, 
&quot;2&quot;, &quot;Council Rates;Land Tax;Water Rates;Sunday Trade;Operating Expenses;Emergency Levy;Cleaning&quot;, 
&quot;&quot;)))</formula>
        <inlineHelpText>These are defaulted outgoings based on the Property.</inlineHelpText>
        <label>Applicable Outgoings</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumberOfProducts__c</fullName>
        <label>Number of Products</label>
        <summaryForeignKey>SpaceProduct__c.Space__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RentableArea__c</fullName>
        <label>Rentable Area</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SpaceProductsApplies__c</fullName>
        <formula>If( NumberOfProducts__c &gt;0,true,false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>When this box is ticked, the list of Space Products is visible in the &quot;Related&quot; Tab.</inlineHelpText>
        <label>Space Products Applies</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>At Risk</fullName>
                </value>
                <value>
                    <fullName>Held</fullName>
                </value>
                <value>
                    <fullName>Trading</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SpaceType</valueSetName>
        </valueSet>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SpaceProduct__c.object
<CustomObject>
    <description>&lt;SPP&gt; - Represents a products delated to the Space where Space product values is different to property. This caters for space level outgoings eg. Council rates, Air Con</description>
    <fields>
        <fullName>CalculationMethod__c</fullName>
        <description>Drives the price calculation.</description>
        <label>Calculation Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>Percentage</fullName>
                </value>
                <value>
                    <fullName>PSM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EffectiveFromDate__c</fullName>
        <description>The Date from which this Product becomes or became available for use for any Opportunity related to the Space.</description>
        <label>Effective From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Percentage__c</fullName>
        <description>Store the applicable percentage value if the price is calculated based on a percentage (based on the selected &quot;Calculation Method&quot;)</description>
        <inlineHelpText>Provide a percentage if the calculation method is percentage.</inlineHelpText>
        <label>Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <description>The Property to which this Space Product applies. This field is defaulted based on the selected Space.</description>
        <formula>Space__r.Property__r.Name</formula>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <description>The Space to which the Space Product applies.</description>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipLabel>Space Products</relationshipLabel>
        <relationshipName>SpaceProducts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Space Product</label>
    <nameField>
        <displayFormat>SPP - {0000}</displayFormat>
        <label>Space Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Space Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Australia</fullName>
        <default>true</default>
        <label>Australia</label>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

globalValueSets/OutgoingProducts.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Air Con</fullName>
    </customValue>
    <customValue>
        <fullName>Cafe Court</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaning</fullName>
    </customValue>
    <customValue>
        <fullName>Council Rates</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Levy</fullName>
    </customValue>
    <customValue>
        <fullName>Food Court</fullName>
    </customValue>
    <customValue>
        <fullName>Land Tax</fullName>
    </customValue>
    <customValue>
        <fullName>Operating Expenses</fullName>
    </customValue>
    <customValue>
        <fullName>Rubbish</fullName>
    </customValue>
    <customValue>
        <fullName>Sunday Trade - Air Con</fullName>
    </customValue>
    <customValue>
        <fullName>Sunday Trade</fullName>
    </customValue>
    <customValue>
        <fullName>Waste</fullName>
    </customValue>
    <customValue>
        <fullName>Water Rates</fullName>
    </customValue>
    <customValue>
        <fullName>Sunday Trade - Operating Expenses</fullName>
        <isActive>false</isActive>
        <label>Sunday Trade - Operating Expenses</label>
    </customValue>
    <description>Fields to maintain outgoing products name</description>
    <masterLabel>Outgoing Products</masterLabel>
</GlobalValueSet>

globalValueSets/SpaceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Shop</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Kiosk</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Office Suite</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Store Room</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Seating</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sundry Property</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Garage / Parking</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sundry</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Space Bank</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Common Mall</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>Re-design</label>
    </customValue>
    <customValue>
        <fullName>Seating License</fullName>
        <isActive>false</isActive>
        <label>Seating License</label>
    </customValue>
    <customValue>
        <fullName>Sundry Site</fullName>
        <isActive>false</isActive>
        <label>Sundry Site</label>
    </customValue>
    <masterLabel>Space Type</masterLabel>
</GlobalValueSet>

classes/RentUtilityTest.cls
@isTest
private class RentUtilityTest
{
    @TestSetup 
    private static void testSetup() {
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(SecurityController.class.getName());
        Map<String, Schema.RecordTypeInfo> accountRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(CONSTANTS.ACCOUNT);   
        Map<String, Schema.RecordTypeInfo> precclasueRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(CONSTANTS.PRECEDENT_CLAUSE_API);
        Pricebook2 pricebookRecord = new Pricebook2();
        List<Product2> productList = new List<Product2>();
        List<Property__c> propertyList = new List<Property__c>();
        PrecedentClause__c precRecord = new PrecedentClause__c();
        List<Account> accountList = new List<Account>();
        List<PricebookEntry> pricebookEntryList = new List<PricebookEntry>();
        List<PricebookEntry> pricebookEntryList2 = new List<PricebookEntry>(); 
        OpportunityLineItem OpportunityLineItemRecord = new OpportunityLineItem ();
        //CREATE PRICEBOOK
        pricebookRecord = TestDataFactory.createPricebook();
        try {
            database.insert(pricebookRecord);
        } catch (Exception e) {
            errorHandler.createError(e);
        }
        
        try {
            pricebookRecord = [SELECT Id FROM Pricebook2 LIMIT 1];
        } catch (Exception e) {
            pricebookRecord = NULL;
        }
        
        
        //CREATE PRODUCT
        productList.add(TestDataFactory.createProduct(CONSTANTS.OPP_LINEITEM_BASERENT_NET, Constants.RENT));
        productList.add(TestDataFactory.createProduct('Promotion Fund', CONSTANTS.PROMO_MARKETING));
        productList.add(TestDataFactory.createProduct(Constants.PRODUCT_RENT_REVIEW, CONSTANTS.RECOVERIES_GROSS));
        productList[0].dealtype__c = 'Gross';
        productList[0].ProductCode = CONSTANTS.OTG;
        productList[0].SpaceBillingCategory__c = 'NA';
        productList[0].OutgoingsCategory__c = 'Air Con';
        
        productList[1].dealtype__c = 'Gross';
        productList[1].SpaceBillingCategory__c = 'NA';
        productList[1].ProductCode = CONSTANTS.OTG;
        productList[1].OutgoingsCategory__c = 'Council Rates';  
        
        productList[2].dealtype__c = 'Gross';
        productList[2].SpaceBillingCategory__c = 'NA';
        productList[2].OutgoingsCategory__c = 'Council Rates';  
        productList[2].ProductCode = CONSTANTS.OTG;
        
        try {
            database.insert(productList);
        } catch (Exception e) {
            errorHandler.createError(e);
        }
        
        try {
            productList = [SELECT Id FROM Product2];
        } catch (Exception e) {
            productList = NULL;
        }
        
        //System.debug('Product List ' + productList);
        
        //CREATE PRICEBOOK ENTRY
        pricebookEntryList.addAll(TestDataFactory.createStandardPriceBookEntry(1, productList[1]));
        pricebookEntryList.addAll(TestDataFactory.createStandardPriceBookEntry(1, productList[0]));
        try {
            database.insert(pricebookEntryList);
        } catch (Exception e) {
            errorHandler.createError(e);
        }
        
        pricebookEntryList2.addAll(TestDataFactory.createStandardPriceBookEntry(1, productList[1]));
        pricebookEntryList2.addAll(TestDataFactory.createStandardPriceBookEntry(1, productList[0]));
        pricebookEntryList2[1].pricebook2id = pricebookRecord.id;
        pricebookEntryList2[0].pricebook2id = pricebookRecord.id; 
        try {
            database.insert(pricebookEntryList2);
        } catch (Exception e) {
            errorHandler.createError(e);
        }        
        
        //CREATE PROPERTY
        propertyList = TestDataFactory.createProperty(1);
        propertyList[0].PriceBook__c = pricebookRecord.id;
        propertyList[0].ApplicableOutgoings__c = 'Air Con;Council Rates;Land Tax;Water Rates;Sunday Trade - Air Con;Sunday Trade;Operating Expenses;Emergency Levy';
        try {
            database.insert(propertyList);
        } catch (Exception e) {
            errorHandler.createError(e);
        }
        
        try {
            propertyList = [SELECT Id FROM Property__c];
        } catch (Exception e) {
            propertyList = NULL;
        }
        
        //CREATE ACCOUNT
        accountList.addAll(TestDataFactory.createAccountBulk(1, propertyList[0].Id, accountRecordTypeMapByName.get(CONSTANTS.PROPERTY_BASED).getRecordTypeId()));
        try {
            database.insert(accountList);
        } catch (Exception e) {
            errorHandler.createError(e);
        }        
        
        Profile profileRec;
        try {
            profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SYSTEM_ADMINISTRATOR LIMIT 1];
        } catch (Exception e) {
            profileRec = NULL;
        }
        
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        List<OpportunityLineItem> opportunityLineItemList = new List<OpportunityLineItem>();
        List<Opportunity> opportunityList = new List<Opportunity>([SELECT Id FROM Opportunity]);
        
        List<Contract__c> contrList = new List<Contract__c>();
        List<Space__c> spaceLst = TestDataFactory.createSpace(1, propertyList[0]);
        for(Space__c spaceRec : spaceLst){
            spaceRec.type__c = '2';
            spaceRec.RentableArea__c = 12;
        }
        
        try {
            database.insert(spaceLst);
        } catch (Exception e) {
            errorHandler.createError(e);
        }           
        
        List<SpaceProduct__c> spaceProductList = TestDataFactory.createSpaceProduct(1,spaceLst[0], CONSTANTS.RENT, productList[0]);
        //System.debug('Space Product Before' + spaceProductList);
        
        try {
            database.insert(spaceProductList);
        } catch (Exception e) {
            errorHandler.createError(e);
        }              
        
        try {
            spaceLst = [SELECT Id, ApplicableOutgoings__c, NumberOfProducts__c, SpaceProductsApplies__c FROM Space__c];
        } catch (Exception e) {
            spaceLst = NULL;
        }           
        
        contrList = TestDataFactory.createContract(1, accountList[0]);
        for(Contract__c contractRec : contrList){
            contractRec.Space__c = spaceLst[0].id;
        }
        database.insert(contrList);
        //CREATE PRECEDENT CLAUSE
        precRecord = TestDataFactory.createPrecedentClause(1, accountList[0].Id, precclasueRecordTypeMapByName.get(CONSTANTS.NATIONAL_AGREEMENTS).getRecordTypeId());
        precRecord.PromoPercentage__c = 0;
        try {
            database.insert(precRecord);
        } catch (Exception e) {
            errorHandler.createError(e);
        }
        
        try {
            precRecord = [SELECT Id, PromoPercentage__c, CurrentMinimumThreshold__c, CurrentMaximumThreshold__c FROM PrecedentClause__c];
        } catch (Exception e) {
            precRecord = NULL;
        }          
        
        
        //CREATE OPPORTUNITY
        opportunityList = TestDataFactory.createOpportunity(1, accountList[0].Id, precRecord);
        for(Opportunity opp : opportunityList){
            opp.pricebook2id = pricebookRecord.id;
            opp.property__c = propertyList[0].id;
            opp.space__c = spaceLst[0].id;
            opp.DealType__c = 'Gross';
            opp.CurrencyIsoCode = 'AUD';
            opp.AnnualMinimumRent__c = 2000;
            opp.PercentageRentIncluded__c = true;
            opp.ProposedStartDate__c = system.today();
            opp.ProposedRentCommencementDate__c = system.today();
            opp.RentInAdvance__c = 1000;
            opp.SecurityDeposit__c = 1000;
            opp.PromoLevyIncluded__c = 'Yes';
            opp.NationalAgreement__c = precRecord.Id;
            //opp.UsageClause__c
            opp.StageName = Constants.UNDERSTAND_NEGOTIATE;
        }
        
        try {
            database.insert(opportunityList);
        } catch (Exception e) {
            system.debug('Exception: '+e.getMessage());
            system.debug('Exception: '+e.getLineNumber());
            errorHandler.createError(e);
        }        
        
        //Create Usage clause
        opportunityList = [SELECT Id, TermYr__c, ProposedStartDate__c, NationalAgreement__r.PromoPercentage__c, NationalAgreement__r.CurrentMinimumThreshold__c, NationalAgreement__r.CurrentMaximumThreshold__c FROM Opportunity];
        List<OpportunityClause__c> oppClauseRecordsList = new List<OpportunityClause__c>();
        oppClauseRecordsList = TestDataFactory.createOpportunityClause(1,opportunityList[0]);
        try {
            database.insert(oppClauseRecordsList);
        } catch (Exception e) {
            system.debug('Exception: '+e.getMessage());
            system.debug('Exception: '+e.getLineNumber());
            errorHandler.createError(e);
        }  
        
        //Update Opportunity with stage Issue Lease.
        Opportunity opp1 = opportunityList[0];
        opp1.StageName = Constants.OPPORTUNITYSTAGE_ISSUE_LEASE;
        
        try {
            database.update(opportunityList);
        } catch (Exception e) {
            system.debug('Exception: '+e.getMessage());
            system.debug('Exception: '+e.getLineNumber());
            errorHandler.createError(e);
        }  
        
        //Update Precedent Clause for promo percentage = 0
        precRecord.PromoPercentage__c = 80;
        try {
            database.update(precRecord);
        } catch (Exception e) {
            system.debug('Exception: '+e.getMessage());
            system.debug('Exception: '+e.getLineNumber());
            errorHandler.createError(e);
        }  
        
        
        Opportunity opp2 = opportunityList[0];
        opp2.Description = 'test';
        try {
            database.update(opportunityList);
        } catch (Exception e) {
            system.debug('Exception: '+e.getMessage());
            system.debug('Exception: '+e.getLineNumber());
            errorHandler.createError(e);
        }  
        
        opportunityLineItemRecord = TestDataFactory.createOpportunityLineItem(1, opportunityList[0], productList[0], pricebookEntryList2[0] );
        opportunityLineItemRecord.Flexi_Rent__c = false;
        opportunityLineItemRecord.CalculationMethod__c = CONSTANTS.SP_PERCENTAGE;
        opportunityLineItemRecord.AmortizedRent__c = 10000;
        opportunityLineItemRecord.Percentage__c = 2;
        opportunityLineItemRecord.EffectiveFromDate__c = date.today();
        opportunityLineItemList.add(opportunityLineItemRecord);
        try {
            database.insert(opportunityLineItemList);
        } catch (Exception e) {
            errorHandler.createError(e);
        }
        
        Property__c propertyRecord = new Property__c();
        propertyRecord.Name = 'Test Property';
        propertyRecord.PropertyShortName__c = 'ABC';
        propertyRecord.Country__c = 'New Zealand';
        propertyRecord.PropertyCity__c = 'Newmarket';
        propertyRecord.CurrencyIsoCode = 'NZD';
        insert propertyRecord;
        
        List<Account> accountList1 = new List<Account>(); 
        accountList1.addAll(TestDataFactory.createAccountBulk(1, propertyRecord.Id, accountRecordTypeMapByName.get(CONSTANTS.PROPERTY_BASED).getRecordTypeId()));
        try {
            database.insert(accountList1);
        } catch (Exception e) {
            //errorHandler.createError(e);
        }
        
        List<Opportunity> opportunityList1 = new List<Opportunity>();
        opportunityList1 = TestDataFactory.createOpportunity(accountList1);
        for(Opportunity opp : opportunityList1){
            //opp.pricebook2id = pricebookRecord.id;
            opp.property__c = propertyRecord.id;
            //opp.space__c = spaceLst[0].id;
            opp.DealType__c = 'Gross';
            opp.CurrencyIsoCode = 'AUD';
            opp.AnnualMinimumRent__c = 2000;
        }
        
        try {
            database.insert(opportunityList1);
        } catch (Exception e) {
            //errorHandler.createError(e);
        }        
        
    }
    
    private static testMethod void testGetRentInfoNZProperty(){
        List<Opportunity> oppList = [Select Id, AnnualMinimumRent__c, NZProperty__c, PromoLevyIncluded__c, DealType__c, NationalAgreement__r.PromoPercentage__c,NationalAgreement__r.CurrentMinimumThreshold__c,NationalAgreement__r.CurrentMaximumThreshold__c, NationalAgreement__r.Status__c 
                                     from Opportunity LIMIT 10];
        
        for(Opportunity opp : oppList){
            opp.NationalAgreement__c = null;
            opp.PromoLevyIncluded__c = 'Yes';
            opp.DealType__c = 'Semi Gross';
        }
        	
        Test.startTest();
        TriggerHandler.clearAllBypasses();
        Database.update(oppList);
        RentUtility.getRentInfo(oppList);
        Test.stopTest();
    }
    
    private static testMethod void testGetRentInfoNZProperty1(){
        Map<String, Schema.RecordTypeInfo> accountRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(CONSTANTS.ACCOUNT);
        
        List<Opportunity> oppList = [Select Id, AnnualMinimumRent__c, NZProperty__c, PromoLevyIncluded__c, DealType__c, NationalAgreement__r.PromoPercentage__c,NationalAgreement__r.CurrentMinimumThreshold__c,NationalAgreement__r.CurrentMaximumThreshold__c, NationalAgreement__r.Status__c 
                                     from Opportunity WHERE Property__r.Country__c = 'New Zealand' LIMIT 10];
        
        for(Opportunity opp : oppList){
            opp.NationalAgreement__c = null;
            opp.PromoLevyIncluded__c = 'Yes';
            opp.DealType__c = 'Semi Gross';
        }
        
        Test.startTest();
        TriggerHandler.clearAllBypasses();
        Database.update(oppList);
        RentUtility.getRentInfo(oppList);
        Test.stopTest();
    }
}