objects/Contract__c.object
<CustomObject>
    <description>&lt;CON&gt; - Represents a contract signed with a retailer. Either lease, Commercial lease, license agreement</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts (Account)</relationshipLabel>
        <relationshipName>Contracts1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipName>Leases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PropertyTeam__c.object
<CustomObject>
    <description>&lt;PRT&gt; - Represents a internal team working for the property eg. Centre Manager, Facility Manager, RDM, Leasing Executive, Development Leasing Executive</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You should only select Third party type accounts.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ACCThirdParty</value>
            </filterItems>
            <infoMessage>You can only select Third party type accounts.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Property Team (Account)</relationshipLabel>
        <relationshipName>Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <formula>IF(AND(!TeamMember__r.IsActive, RecordType.DeveloperName=&apos;PRT_InternalTeamMember&apos;),false,IF(ISBLANK(EndDate__c),
IF(StartDate__c &lt;= TODAY(),TRUE,FALSE),
(AND(StartDate__c &lt;= TODAY(),
TODAY() &lt;= EndDate__c))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Property Team</relationshipLabel>
        <relationshipName>Property_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RoleType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TeamMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Property_Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property Team</label>
    <nameField>
        <displayFormat>PRT-{0000}</displayFormat>
        <label>Property Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CurrentLeaseExpiryDate__c</fullName>
        <formula>CurrentLease__r.LeaseEndDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Lease Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CurrentLease__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Lease</label>
        <referenceTo>Contract__c</referenceTo>
        <relationshipLabel>Spaces (Current Lease)</relationshipLabel>
        <relationshipName>CurrentLease</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/RoleType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accounts Receivable Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Administration Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Architectural Technician</fullName>
    </customValue>
    <customValue>
        <fullName>Asset General Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Centre Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Chief Operating Officer</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Leasing Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Leasing General Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Leasing Regional Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Property Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Retail Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate Legal</fullName>
    </customValue>
    <customValue>
        <fullName>D&amp;C Special Project Coordinator</fullName>
    </customValue>
    <customValue>
        <fullName>Development Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Development Finance Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Director LARS &amp; NZ Development</fullName>
    </customValue>
    <customValue>
        <fullName>Facilities Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Filing Clerk</fullName>
    </customValue>
    <customValue>
        <fullName>Fitout Contributions Admin</fullName>
    </customValue>
    <customValue>
        <fullName>General Manager Leasing</fullName>
    </customValue>
    <customValue>
        <fullName>General Manager Retail Design</fullName>
    </customValue>
    <customValue>
        <fullName>GM of Corporate Accounting</fullName>
    </customValue>
    <customValue>
        <fullName>GM Retail Admin &amp; Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Group General Manager - LARS</fullName>
    </customValue>
    <customValue>
        <fullName>Group Renewal Admin Team</fullName>
        <label>Group Renewal Team</label>
    </customValue>
    <customValue>
        <fullName>Leasing Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Leasing Finance Analyst</fullName>
    </customValue>
    <customValue>
        <fullName>Project Regional Manager - LARS</fullName>
    </customValue>
    <customValue>
        <fullName>Project Retail Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>Project Retail Design Manager</fullName>
    </customValue>
    <masterLabel>Role Type</masterLabel>
</GlobalValueSet>

classes/CreateInspectionfromSpaceController.cls
public class CreateInspectionfromSpaceController {
    public class Response{
        @AuraEnabled
        public String status;
        @AuraEnabled
        public String message;
        @AuraEnabled
        public String returnValue;
        
        public Response(){
            this.status ='Success';
            this.message = '';
            this.returnValue = '';
        }
    }
    public class createinspectionwrapper{
        public space__c spaceRecord;
        public Date dueDate;
        public Id recordTypeId;
        public id ownerId;
        public string subject;
    }
    @AuraEnabled
    public static Response getspacedetails(id spaceId){
        Response responsedetails=new Response();
        Space__c spaceRecord;
        try {
            spaceRecord=[SELECT Id,Name,CurrentLease__c,CurrentLease__r.Account__c,CurrentLease__r.Name,CurrentLease__r.Id,Property__r.Name,CurrentLease__r.Account__r.Name,CurrentLeaseExpiryDate__c,CurrentLease__r.Account__r.ParentId,CurrentLease__r.Opportunity__c from Space__c where id =:spaceId];
        } catch (Exception e) {
            spaceRecord = NULL;
        }
        
        Map<String,AccountTeamMember> accountteamMap=new Map<String,AccountTeamMember>();
        Map<String,PropertyTeam__c> rolepropertyTeamMap=new Map<String,PropertyTeam__c>();
        Set<Id> accountids=new Set<Id>();
        accountids.add(spaceRecord.CurrentLease__r.Account__c);
        accountids.add(spaceRecord.CurrentLease__r.Account__r.ParentId);
        
        for(AccountTeamMember memberRecod: [Select id,TeamMemberRole,UserId from AccountTeamMember where AccountId =:accountids AND TeamMemberRole=:Constants.TEAM_ROLE_RDAM AND Account.RecordType.Name=:Constants.GROUP_LEVEL]){
            accountteamMap.put(memberRecod.TeamMemberRole,memberRecod);
        }  
        for(PropertyTeam__c propertyteam: [Select id,Role__c,TeamMember__c from PropertyTeam__c where Property__c =: spaceRecord.Property__c AND  Active__c=true AND Role__c=:Constants.TEAM_ROLE_RDM AND TeamMember__r.IsActive=true]){
            rolepropertyTeamMap.put(propertyteam.Role__c,propertyteam);
        }
        
        Id ownerid=userinfo.getUserId();
        if(accountteamMap.containskey(Constants.TEAM_ROLE_RDAM)){
            ownerid=accountteamMap.get(Constants.TEAM_ROLE_RDAM).UserId;
        }else if(rolepropertyTeamMap.containskey(Constants.TEAM_ROLE_RDM)){
            ownerid=rolepropertyTeamMap.get(Constants.TEAM_ROLE_RDM).TeamMember__c;
        }
        createinspectionwrapper wrapper=new createinspectionwrapper();
        wrapper.ownerId=ownerid;
        wrapper.spaceRecord=spaceRecord;
        wrapper.dueDate=System.today().addDays(2);
        //if(spaceRecord.CurrentLease__r.Account__c!=null){
        //  wrapper.subject=spaceRecord.Property__r.Name+' - '+spaceRecord.Name+' - '+spaceRecord.CurrentLease__r.Account__r.Name+' - Inspection Report'; 
        //}else{
        wrapper.subject=spaceRecord.Property__r.Name+' - '+spaceRecord.Name+' - Inspection Report'; 
        //}
        wrapper.recordTypeId=Schema.SObjectType.Case.getRecordTypeInfosByName().get(CONSTANTS.INSPECTION_REPORT).getRecordTypeId();
        
        try {
            responsedetails.returnValue = JSON.serialize(wrapper);
        } catch (Exception e) {
            responsedetails.returnValue = NULL;
        }
        return responsedetails;
    }
    
    //RPP-10876 - START 
    @AuraEnabled
    public static Boolean isIRCaseRaisedEarlier(Id spaceId){
        Boolean checkResult = false;
        list<Case> caseList =[SELECT Id, Space__c, CreatedDate 
                              FROM Case 
                              WHERE CreatedDate = LAST_N_DAYS:60
                              AND Space__c =: spaceId
                              AND RecordType.Name =: Constants.CASE_RECORDTYPE_INSPECTIONREPORT];
        if(caseList.size() > 0){
            checkResult = true;  
        }
        return checkResult;
    }
    //RPP-10876 - END
    
    //added below method to implement RPP-10876 
    @AuraEnabled
    public static void getselectOptions(Id caseId, String reason, String description ) {
        Case cases =[SELECT Id, Other_Reason__c, New_IR_Case_Reason__c, Subject, Status, 
                     Priority, DueDate__c, Contract__c 
                     FROM Case 
                     WHERE Id =: caseId 
                     LIMIT 1];
        if(reason == 'Other'){
            cases.Other_Reason__c = description; 
        }
        cases.New_IR_Case_Reason__c = reason;
        update cases;
    }
}