objects/Contract__c.object
<CustomObject>
    <description>&lt;CON&gt; - Represents a contract signed with a retailer. Either lease, Commercial lease, license agreement</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts (Account)</relationshipLabel>
        <relationshipName>Contracts1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AutoInspectionReportCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field get updated when 9 month expiry inspection report is created.</description>
        <label>Auto Inspection Report Created ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LeaseEndDate__c</fullName>
        <label>Lease End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LeaseType__c</fullName>
        <label>Lease Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OB</fullName>
                    <label>Advertiser</label>
                </value>
                <value>
                    <fullName>AP</fullName>
                    <label>Apartment</label>
                </value>
                <value>
                    <fullName>AS</fullName>
                    <label>AREF Speculative Lease</label>
                </value>
                <value>
                    <fullName>BA</fullName>
                    <label>Brand Alliance</label>
                </value>
                <value>
                    <fullName>EN</fullName>
                    <label>Cinemas Intencity Video Games</label>
                </value>
                <value>
                    <fullName>CO</fullName>
                    <label>Commercial Office</label>
                </value>
                <value>
                    <fullName>DB</fullName>
                    <label>Digital Business</label>
                </value>
                <value>
                    <fullName>ID</fullName>
                    <label>Industrial</label>
                </value>
                <value>
                    <fullName>LL</fullName>
                    <label>Land Lease</label>
                </value>
                <value>
                    <fullName>MJ</fullName>
                    <label>Major</label>
                </value>
                <value>
                    <fullName>MF</fullName>
                    <label>Marketing Fund</label>
                </value>
                <value>
                    <fullName>MM</fullName>
                    <label>Mini-Major</label>
                </value>
                <value>
                    <fullName>NR</fullName>
                    <label>Non-Retail</label>
                </value>
                <value>
                    <fullName>OF</fullName>
                    <label>Office</label>
                </value>
                <value>
                    <fullName>OL</fullName>
                    <label>On-Line</label>
                </value>
                <value>
                    <fullName>OA</fullName>
                    <label>Operating Agreement</label>
                </value>
                <value>
                    <fullName>RS</fullName>
                    <label>Restaurant</label>
                </value>
                <value>
                    <fullName>RT</fullName>
                    <label>Retail - Specialty</label>
                </value>
                <value>
                    <fullName>SR</fullName>
                    <label>Storeroom licence</label>
                </value>
                <value>
                    <fullName>SB</fullName>
                    <label>Sub Lease</label>
                </value>
                <value>
                    <fullName>SL</fullName>
                    <label>Sundry Debtor</label>
                </value>
                <value>
                    <fullName>SP</fullName>
                    <label>Sundry Property</label>
                </value>
                <value>
                    <fullName>SO</fullName>
                    <label>Sundry Property - other</label>
                </value>
                <value>
                    <fullName>TW</fullName>
                    <label>Tenancy Works</label>
                </value>
                <value>
                    <fullName>TS</fullName>
                    <label>Trade Show Booth</label>
                </value>
                <value>
                    <fullName>VS</fullName>
                    <label>Vacant Shop Casual Lease</label>
                </value>
                <value>
                    <fullName>WH</fullName>
                    <label>Warehouse / Storage</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipName>Leases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>CreateInspectionReport__c</fullName>
        <formula>IF( DAY( TODAY() ) = 31 &amp;&amp; MONTH( TODAY() ) = 10 &amp;&amp;  
    CurrentLeaseExpiryDate__c  &gt; ADDMONTHS( TODAY() ,9) &amp;&amp; CurrentLeaseExpiryDate__c &lt;= ADDMONTHS( TODAY() , 11) &amp;&amp; 
	(ISPICKVAL(Type__c, &apos;1&apos;)||ISPICKVAL(Type__c, &apos;2&apos;)) &amp;&amp; 
	NOT( ISPICKVAL(CurrentLease__r.LeaseStatus__c , &apos;E&apos;) || ISPICKVAL(CurrentLease__r.LeaseStatus__c , &apos;F&apos;) || 
        	ISPICKVAL(CurrentLease__r.LeaseStatus__c , &apos;D&apos;) || ISPICKVAL(CurrentLease__r.LeaseStatus__c , &apos;K&apos;) || ISPICKVAL(CurrentLease__r.LeaseStatus__c , &apos;M&apos;)), 
	true , 
	IF( CurrentLeaseExpiryDate__c = ADDMONTHS( TODAY() ,9) &amp;&amp;
	   (MONTH(CurrentLeaseExpiryDate__c) != 8 &amp;&amp; MONTH(CurrentLeaseExpiryDate__c) != 9) &amp;&amp;
	   (ISPICKVAL(Type__c, &apos;1&apos;)||ISPICKVAL(Type__c, &apos;2&apos;)) &amp;&amp; 
	    NOT(ISPICKVAL(CurrentLease__r.LeaseStatus__c , &apos;E&apos;) || ISPICKVAL(CurrentLease__r.LeaseStatus__c , &apos;F&apos;) || ISPICKVAL(CurrentLease__r.LeaseStatus__c , &apos;D&apos;) || ISPICKVAL(CurrentLease__r.LeaseStatus__c , &apos;K&apos;) || ISPICKVAL(CurrentLease__r.LeaseStatus__c , &apos;M&apos;)), 
		true, 
		false))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Create Inspection Report</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CurrentLease__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Lease</label>
        <referenceTo>Contract__c</referenceTo>
        <relationshipLabel>Spaces (Current Lease)</relationshipLabel>
        <relationshipName>CurrentLease</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CreateInspectionBatch.cls
global class  CreateInspectionBatch implements Database.Batchable<sObject>, Database.Stateful, Schedulable{
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        
        if(Test.isRunningTest()){
            return Database.getQueryLocator([SELECT Id,CurrentLease__c from Space__c where CurrentLease__c!=null]);
        }
        
        return Database.getQueryLocator([SELECT Id,CurrentLease__c,
                                         //added below filter to implement RPP-10876
                                         (SELECT Id, CreatedDate
                                          FROM Cases__r
                                          WHERE RecordType.Name =: Constants.CASE_RECORDTYPE_INSPECTIONREPORT 
                                          AND CreatedDate != LAST_N_DAYS:60 )
                                         FROM Space__c 
                                         WHERE CurrentLease__c != NULL 
                                         AND CreateInspectionReport__c = true
                                         //added below filter to implement RPP-10999
                                         AND CurrentLease__r.LeaseType__c !=: Constants.CON_LEASE_TYPE_MAJOR]);
        
        //return Database.getQueryLocator([SELECT Id,CurrentLease__c from Space__c where CurrentLease__c!=null and CreateInspectionReport__c = true and property__c = 'a0a2O0000004dBOQAY']);
    }
    
    global void execute(SchedulableContext sc){
        CreateInspectionBatch schedulableBatch = new CreateInspectionBatch();
        Database.executeBatch(schedulableBatch);
    }
    
    global void execute(Database.BatchableContext BC, List<Space__c> spaceList){
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(CreateInspectionBatch.class.getName());
        
        List<Case> createInspectionList=new List<Case>();
        TriggerHandler.bypass('CaseTriggerHandler');
        Set<Id> contractIdSet=new Set<Id>();
        
        if(spaceList.size()>0&&!spaceList.isEmpty()){
            for(Space__c spaceRecord: spaceList){
                contractIdSet.add(spaceRecord.CurrentLease__c);
            }
        }
        
        List<Contract__c> contractList = new List<Contract__c>();
        Map<Id,Contract__c> contractMap = new Map<Id,Contract__c>([SELECT Id, Property__c, Name,Property__r.Name, Space__c,
                                                                   Space__r.Name, Space__r.CurrentLease__c, Account__r.Name,
                                                                   LeaseEndDate__c, Account__c, Account__r.ParentId, Opportunity__c 
                                                                   FROM Contract__c 
                                                                   WHERE Id IN: contractIdSet 
                                                                   AND AutoInspectionReportCreated__c = FALSE]);
        contractList.addAll(contractMap.Values());
        
        if(contractList.size()>0&&!contractList.isEmpty()){
            createInspectionList = CaseBL.CreateInspectionforContract(ContractList);
            List<Contract__c> contractsToupdateList = new List<Contract__c>();
            
            if(createInspectionList.size() > 0 && !createInspectionList.isEmpty()){
                List<Database.SaveResult> saveResultList = Database.Insert(createInspectionList, false); 
                system.debug('saveResultList ' + createInspectionList );  //added
                Integer counter = 0;
                
                for(Database.SaveResult saveResult : saveResultList){
                    system.debug('saveResultList ' + saveResult ); //added
                    
                    if(saveResult.isSuccess()){
                        system.debug('----  inside the if to make autoInsRepCr =true ---- ' );  //added
                        
                        Contract__c contracttoupdate = new Contract__c();
                        //contracttoupdate.AutoInspectionReportCreated__c=true;
                        contracttoupdate.Id = createInspectionList[counter].Contract__c;
                        contracttoupdate.AutoInspectionReportCreated__c = true;
                        
                        system.debug('AutoInspectionReportCreated__c >>>> '+contracttoupdate.AutoInspectionReportCreated__c); //added
                        
                        if(!contractsToupdateList.contains(contracttoupdate)){
                            contractsToupdateList.add(contracttoupdate);
                        }
                        system.debug('contractsToupdateList >>> '+contractsToupdateList);
                    }
                    for(Database.Error err : saveResult.getErrors()) {
                        errorHandler.createError(err, createInspectionList[counter].Id);
                        System.debug('ERROR IN CreateInspectionBatch: '+ err);
                    }
                    
                    counter++;
                }                
                errorHandler.save();
                
                if(contractsToupdateList.size() > 0 && !contractsToupdateList.isEmpty()){
                    system.debug(' UPDATE here '); //added
                    update contractsToupdateList;
                }
            }
        }
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
}