objects/Contract__c.object
<CustomObject>
    <description>&lt;CON&gt; - Represents a contract signed with a retailer. Either lease, Commercial lease, license agreement</description>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipName>Leases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Reduced ROLO</fullName>
                </value>
                <value>
                    <fullName>No ROLO</fullName>
                </value>
                <value>
                    <fullName>Over payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lease</fullName>
                </value>
                <value>
                    <fullName>License Agreement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>PriceBook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Properties (PriceBook)</relationshipLabel>
        <relationshipName>PropertiesPriceBook</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PropertyTeam__c.object
<CustomObject>
    <description>&lt;PRT&gt; - Represents a internal team working for the property eg. Centre Manager, Facility Manager, RDM, Leasing Executive, Development Leasing Executive</description>
    <fields>
        <fullName>Active__c</fullName>
        <formula>IF(AND(!TeamMember__r.IsActive, RecordType.DeveloperName=&apos;PRT_InternalTeamMember&apos;),false,IF(ISBLANK(EndDate__c),
IF(StartDate__c &lt;= TODAY(),TRUE,FALSE),
(AND(StartDate__c &lt;= TODAY(),
TODAY() &lt;= EndDate__c))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Property Team</relationshipLabel>
        <relationshipName>Property_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RoleType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TeamMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Property_Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property Team</label>
    <nameField>
        <displayFormat>PRT-{0000}</displayFormat>
        <label>Property Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BillingCategory__c</fullName>
        <description>Billing category to identify the bill code.</description>
        <inlineHelpText>For Finance Use Only.</inlineHelpText>
        <label>Billing Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SpaceBillingCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SpaceType</valueSetName>
        </valueSet>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/RoleType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accounts Receivable Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Administration Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Architectural Technician</fullName>
    </customValue>
    <customValue>
        <fullName>Asset General Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Centre Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Chief Operating Officer</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Leasing Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Leasing General Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Leasing Regional Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Property Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Retail Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate Legal</fullName>
    </customValue>
    <customValue>
        <fullName>D&amp;C Special Project Coordinator</fullName>
    </customValue>
    <customValue>
        <fullName>Development Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Development Finance Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Director LARS &amp; NZ Development</fullName>
    </customValue>
    <customValue>
        <fullName>Facilities Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Filing Clerk</fullName>
    </customValue>
    <customValue>
        <fullName>Fitout Contributions Admin</fullName>
    </customValue>
    <customValue>
        <fullName>General Manager Leasing</fullName>
    </customValue>
    <customValue>
        <fullName>General Manager Retail Design</fullName>
    </customValue>
    <customValue>
        <fullName>GM of Corporate Accounting</fullName>
    </customValue>
    <customValue>
        <fullName>GM Retail Admin &amp; Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Group General Manager - LARS</fullName>
    </customValue>
    <customValue>
        <fullName>Group Renewal Admin Team</fullName>
        <label>Group Renewal Team</label>
    </customValue>
    <customValue>
        <fullName>Leasing Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Leasing Finance Analyst</fullName>
    </customValue>
    <customValue>
        <fullName>Project Regional Manager - LARS</fullName>
    </customValue>
    <customValue>
        <fullName>Project Retail Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>Project Retail Design Manager</fullName>
    </customValue>
    <masterLabel>Role Type</masterLabel>
</GlobalValueSet>

globalValueSets/SpaceBillingCategory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>NR</fullName>
        <label>Non Retail</label>
    </customValue>
    <customValue>
        <fullName>PE</fullName>
        <label>External Precinct</label>
    </customValue>
    <customValue>
        <fullName>ATM</fullName>
    </customValue>
    <customValue>
        <fullName>EX</fullName>
        <label>Car Park - External</label>
    </customValue>
    <customValue>
        <fullName>PM</fullName>
        <label>Car Park - Permanent</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Car Park - Internal</label>
    </customValue>
    <customValue>
        <fullName>VL</fullName>
        <label>Car Park - Valet</label>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
        <default>true</default>
        <label>Not Applicable</label>
    </customValue>
    <description>Space Billing Category</description>
    <masterLabel>Space Billing Category</masterLabel>
</GlobalValueSet>

globalValueSets/SpaceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Shop</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Kiosk</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Office Suite</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Store Room</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Seating</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sundry Property</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Garage / Parking</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sundry</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Space Bank</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Common Mall</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>Re-design</label>
    </customValue>
    <customValue>
        <fullName>Seating License</fullName>
        <isActive>false</isActive>
        <label>Seating License</label>
    </customValue>
    <customValue>
        <fullName>Sundry Site</fullName>
        <isActive>false</isActive>
        <label>Sundry Site</label>
    </customValue>
    <masterLabel>Space Type</masterLabel>
</GlobalValueSet>

classes/PostChatterToCaseInvocTest.cls
/*
* @author:              Sidney Garcia
* @description:         Test class for PostChatterToCaseInvoc
*/
@isTest
public class PostChatterToCaseInvocTest {
    @TestSetup private static void testSetup() {
        Map<String, Schema.RecordTypeInfo> accountRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(CONSTANTS.ACCOUNT);
        Map<String, Schema.RecordTypeInfo> caseRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(CONSTANTS.OBJECT_CASE);
        Map<String, Schema.RecordTypeInfo> propTeamRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(CONSTANTS.PROPERTYTEAM);
         Id internalTeamRecTypeId;
        Map<String,Schema.RecordTypeInfo> propertyTeamRecordTypeMap = RecordTypeUtil.getAllRecordTypesByName('PropertyTeam__c');
        Product2 productRecord;
        List<Property__c> propertyList = new List<Property__c>();
        List<Account> accountList = new List<Account>();
        List<Account> tempAccountList = new List<Account>();
        List<Opportunity> opportunityList = new List<Opportunity>();
        List<contact> contactList = new list<contact>();
        List<case> caseList = new list<case>();
        List<User> testUserList = new List<User>();
        PropertyTeam__c propTeam = new PropertyTeam__c();
        Profile profileRec = [SELECT Id, UserLicense.Name FROM Profile WHERE Name = :CONSTANTS.SCG_SYS_ADM LIMIT 1];
        
        System.debug('profile rec ' + profileRec.UserLicense.Name);
        for(Integer i = 0; i < 20; i++){
            testUserList.add(TestDataFactory.createUniqueTestUser('Test ' + i, 'User 1 ' + i, profileRec.Id));
            testUserList[i].IsActive = true;
            
        }
        database.insert(testUserList);
        System.debug('Test User Profile ' + testUserList[0].ProfileId);
        
        //CREATE PRODUCT
        productRecord = TestDataFactory.createProduct(Constants.PRODUCT_RENT_REVIEW, Constants.RENT);
        insert productRecord;
        
        List<Pricebook2> priceBookList = TestDataFactory.createPricebook(1);
        Database.insert(priceBookList);
        Pricebook2 priceBookRec = [SELECT Id, CurrencyIsoCode FROM Pricebook2 LIMIT 1];
        //System.debug('Pricebook rec ' + priceBookRec);
        
        Property__c property = TestDataFactory.createProperty(1)[0];
        property.PriceBook__c = priceBookRec.Id;
        Database.insert(property);
        
        //CREATE ACCOUNT
        accountList.addAll(TestDataFactory.createAccountBulk(1, property.Id, accountRecordTypeMapByName.get(CONSTANTS.PROPERTY_BASED).getRecordTypeId()));
        database.insert(accountList);
        //System.debug('Account List ' + accountList);
        //CREATE OPPORTUNITY
        accountList = [SELECT Id, Property__c, Name FROM Account LIMIT 1];
        opportunityList = TestDataFactory.createOpportunity(accountList);
        //System.debug('Opportunity List' + opportunityList);
        database.insert(opportunityList);
        
        List<Contract__c> contrList = new List<Contract__c>();
        List<Space__c> spaceLst = TestDataFactory.createSpace(1, property);
        spaceLst[0].type__c = '1';
        spaceLst[0].BillingCategory__c = 'NA';
        database.insert(spaceLst);
        spaceLst = [SELECT Id, Type__c FROM Space__c];
        contrList = TestDataFactory.createContract(1, accountList[0]);
        contrList[0].space__c = spaceLst[0].id;
        database.insert(contrList);
        
        //CREATE ACCOUNTTEAMMEMBER
        List<AccountTeamMember> AccTeamMemberList = new List<AccountTeamMember>();
        AccountTeamMember AccTeamMemberRec = TestDataFactory.createAccountTeamMember(accountList[0].id, testUserList[0].id);
        AccTeamMemberList.add(AccTeamMemberRec);
        database.insert(AccTeamMemberList);
        
        Contract__c contractRec = [SELECT Id, Space__c, Property__c, RecordTypeId from Contract__c LIMIT 1];
        
        Id recordTypeId = caseRecordTypeMapByName.get(CONSTANTS.LEASE_AREA_VARIATION).getRecordTypeId();
        
        Set<string> CaseRecordtypeNames = new set<string>();
        CaseRecordtypeNames.add(CONSTANTS.RETAIL_DESIGN_INSTRUCTION);
        CaseRecordtypeNames.add(CONSTANTS.UPDATE_PROMOTIONAL_ALLOWANCE);
        CaseRecordtypeNames.add(CONSTANTS.MISCELLANEOUS_SERVICE);
        CaseRecordtypeNames.add(CONSTANTS.VARIANCE_TO_RENT_COMMENCEMENT);
        CaseRecordtypeNames.add(CONSTANTS.REQUEST_FOR_REFUND);
        CaseRecordtypeNames.add(CONSTANTS.CONDUCT_MARKET_REVIEW);
        CaseRecordtypeNames.add(CONSTANTS.LEASE_AREA_VARIATION);
        CaseRecordtypeNames.add(CONSTANTS.MANAGE_BANK_GUARANTEE);
        CaseRecordtypeNames.add(CONSTANTS.SURRENDER_A_LEASE);
        CaseRecordtypeNames.add(CONSTANTS.TERMINATE_A_LEASE);
        CaseRecordtypeNames.add(CONSTANTS.ASSIGN_OF_A_LEASE);
        CaseRecordtypeNames.add(CONSTANTS.TRADING_NAME_CHANGE);
        CaseRecordtypeNames.add(CONSTANTS.CREDIT_NOTE);
        CaseRecordtypeNames.add(CONSTANTS.CENTRE_TEAM);
        CaseRecordtypeNames.add(CONSTANTS.LEASING_FINANCE);
        CaseRecordtypeNames.add(CONSTANTS.MISCELLANEOUS_LEASE);
        CaseRecordtypeNames.add(CONSTANTS.ANCILLARY_TAX_INVOICE);
       
        for(String caseRecTypeName : CaseRecordtypeNames){
           case caseRec = TestDataFactory.CreateCase(accountList[0], caseRecordTypeMapByName.get(caseRecTypeName).getRecordTypeId(), contractRec.Id);
            caseRec.UnexpiredFitoutAmount__c = 28.50;
            caseRec.Space__c = contractRec.Space__c;
            if(CaseRecTypeName == CONSTANTS.MISCELLANEOUS_LEASE){ 
                caseRec.Type = CONSTANTS.CASE_TYPE_LV18MISCELLANEOUS;
                if(String.isBlank(caseRec.SubType__c)){
               		caseRec.SubType__c = CONSTANTS.CASE_SUBTYPE_LEASING_FINANCE;
                }
            }else if(CaseRecTypeName == CONSTANTS.MANAGE_BANK_GUARANTEE){
                caseRec.Type = CONSTANTS.CASE_TYPE_LV04BANK_GUARANTEE;
                if(String.isBlank(caseRec.SubType__c)){
               		caseRec.SubType__c = CONSTANTS.CASE_SUBTYPE_TRANSFER;
                }
            }else if(CaseRecTypeName == CONSTANTS.CENTRE_TEAM){
                caseRec.Type = CONSTANTS.CASE_TYPE_LV10CENTRE;
                if(String.isBlank(caseRec.SubType__c)){
               		caseRec.SubType__c = CONSTANTS.CASE_SUBTYPE_BAD_DEBIT_WRITE_OFF;
                }
                
            }else if(CaseRecTypeName == CONSTANTS.LEASING_FINANCE){
                caseRec.Type = CONSTANTS.CASE_TYPE_LV11LEASING_FINANCE;
                if(String.isBlank(caseRec.SubType__c)){
               		caseRec.SubType__c = CONSTANTS.CASE_SUBTYPE_BILLING_OF_PERCENT_RENT;
                }
                
            }else if(CaseRecTypeName == CONSTANTS.TERMINATE_A_LEASE){ 
                caseRec.Type = CONSTANTS.CASE_TYPE_LV05TERMINATION;
                if(String.isBlank(caseRec.SubType__c)){
               		caseRec.SubType__c = CONSTANTS.CASE_SUBTYPE_PRE_EXPIRY_OF_LEASE;
                }
            }else if(CaseRecTypeName == CONSTANTS.UPDATE_PROMOTIONAL_ALLOWANCE){ 
                
                caseRec.origin = CONSTANTS.CASE_ORIGIN_DEVELOPMENT;
            }
				
            caseList.add(caseRec);
        }
        
        case caseScentreRec1 = TestDataFactory.CreateCase(accountList[0], caseRecordTypeMapByName.get(CONSTANTS.CENTRE_TEAM).getRecordTypeId(), contractRec.Id);
        caseScentreRec1.UnexpiredFitoutAmount__c = 28.50;
        caseScentreRec1.Space__c = contractRec.Space__c;
        if(String.isBlank(caseScentreRec1.SubType__c)){
            caseScentreRec1.SubType__c = CONSTANTS.CASE_SUBTYPE_HOARDING;
        }
        
        case caseScentreRec2 = TestDataFactory.CreateCase(accountList[0], caseRecordTypeMapByName.get(CONSTANTS.CENTRE_TEAM).getRecordTypeId(), contractRec.Id);
        caseScentreRec2.UnexpiredFitoutAmount__c = 28.50;
        caseScentreRec2.Space__c = contractRec.Space__c;
        if(String.isBlank(caseScentreRec2.SubType__c)){
            caseScentreRec2.SubType__c = CONSTANTS.CASE_SUBTYPE_MAILBOX_CHARGES;
        }
        
        case caseScentreRec3 = TestDataFactory.CreateCase(accountList[0], caseRecordTypeMapByName.get(CONSTANTS.MISCELLANEOUS_LEASE).getRecordTypeId(), contractRec.Id);
        caseScentreRec3.UnexpiredFitoutAmount__c = 28.50;
        caseScentreRec3.Space__c = contractRec.Space__c;
        if(String.isBlank(caseScentreRec3.SubType__c)){
            caseScentreRec3.SubType__c = CONSTANTS.CASE_SUBTYPE_CENTRE;
        }
        
        caseList.add(caseScentreRec1);
        caseList.add(caseScentreRec2);
        caseList.add(caseScentreRec3);
        database.insert(caseList);
        caseList = [SELECT Id, Subtype__c FROM Case];
        
        //CREATE PROPERTY TEAM
        Property__c propRec = [SELECT Id FROM Property__c LIMIT 1];
        propTeam = TestDataFactory.createPropertyTeam(propRec.Id, CONSTANTS.TEAM_ROLE_GMLEASING, UserInfo.getUserId(), propTeamRecordTypeMapByName.get(CONSTANTS.PRT_INTERNAL_TEAM_MEMBER).getRecordTypeId());
        TriggerHandler.clearAllBypasses();
        database.insert(propTeam);
    }
    
    public static testMethod void testPostChatterToCase(){
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SCG_SYS_ADM LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        PropertyTeam__c propTeam = [SELECT property__c,id,teammember__c, teammember__r.IsActive,role__c, Active__c from propertyteam__c WHERE teammember__r.IsActive = true];
        System.debug('Property Team ' + propTeam);
        List<Case> caseList = [SELECT Id FROM CASE LIMIT 20];
        //System.debug('Case ' + caseList);
        List<Id> caseIDList = new List<Id>();
        
        for(Case caseRec : caseList){
            caseIDList.add(caseRec.Id);
        }
        
        System.runAs(testUser) {
            
            Test.startTest();
            
            PostChatterToCaseInvoc.postChatterToCase(caseIDList);
            Test.stopTest();
        }
        List<CaseFeed> caseFeedList = [SELECT ID, ParentId, Body from CaseFeed where Id in :caseIDList];
        System.assertEquals(true, caseFeedList <> null);
    }
}