objects/CovidCaseVisibilitySetting__mdt.object
<CustomObject>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <inlineHelpText>Please include API name with &quot;__c&quot;.</inlineHelpText>
        <label>Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Ready_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Ready Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SectionAndUserAccessOnCovidCase__c</fullName>
        <label>Section And User Access On Covid Case</label>
        <referenceTo>SectionAndUserAccessOnCovidCase__mdt</referenceTo>
        <relationshipName>CovidCaseVisibilitySetting</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Sort_Number__c</fullName>
        <label>Sort Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Covid Case Visibility Setting</label>
    <pluralLabel>CovidCaseVisibilitySetting</pluralLabel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PropertyTeam__c.object
<CustomObject>
    <description>&lt;PRT&gt; - Represents a internal team working for the property eg. Centre Manager, Facility Manager, RDM, Leasing Executive, Development Leasing Executive</description>
    <fields>
        <fullName>Active__c</fullName>
        <formula>IF(AND(!TeamMember__r.IsActive, RecordType.DeveloperName=&apos;PRT_InternalTeamMember&apos;),false,IF(ISBLANK(EndDate__c),
IF(StartDate__c &lt;= TODAY(),TRUE,FALSE),
(AND(StartDate__c &lt;= TODAY(),
TODAY() &lt;= EndDate__c))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Property Team</relationshipLabel>
        <relationshipName>Property_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TeamMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Property_Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property Team</label>
    <nameField>
        <displayFormat>PRT-{0000}</displayFormat>
        <label>Property Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SectionAndUserAccessOnCovidCase__mdt.object
<CustomObject>
    <fields>
        <fullName>Show_by_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this checkbox, if this section needs to be displayed to all users.</inlineHelpText>
        <label>Show by Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sort_Number__c</fullName>
        <label>Sort Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Section and User Access on Covid Case</label>
    <pluralLabel>SectionAndUserAccessOnCovidCases</pluralLabel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CovidCasePageController.cls
public class CovidCasePageController {
        
    @AuraEnabled
    public static Map<String, List<CovidCaseVisibilitySetting__mdt>> getFieldsToShow(Id recordId){
        Boolean iSectionAccessible = checkSectionAccess(recordId);
        
        Map<String, List<CovidCaseVisibilitySetting__mdt>> sctionNamevsMetadataRecords = new Map<String, List<CovidCaseVisibilitySetting__mdt>>();
        
        List<SectionAndUserAccessOnCovidCase__mdt> parentMetadata = [SELECT MasterLabel, DeveloperName, Sort_Number__c, Show_by_Default__c, 
                                                                     (SELECT MasterLabel, DeveloperName, Field_API_Name__c, Sort_Number__c, 
                                                                      Is_Ready_Only__c, Is_Required__c, SectionAndUserAccessOnCovidCase__c, SectionAndUserAccessOnCovidCase__r.MasterLabel
                                                                      FROM CovidCaseVisibilitySetting__r) 
                                                                     FROM SectionAndUserAccessOnCovidCase__mdt
                                                                     ORDER BY Sort_Number__c];
        
        
       
        Map<String, Map<Integer, CovidCaseVisibilitySetting__mdt>> parentVsChildMap = new  Map<String, Map<Integer, CovidCaseVisibilitySetting__mdt>>();
        CovidCasePageController obj = new CovidCasePageController();
        for(SectionAndUserAccessOnCovidCase__mdt mdtParent : parentMetadata){
            System.debug('iSectionAccessible: '+iSectionAccessible+', Show_by_Default__c: '+mdtParent.Show_by_Default__c);
            if(!iSectionAccessible && !mdtParent.Show_by_Default__c)
                    continue;
            
            for(CovidCaseVisibilitySetting__mdt mdtChild : mdtParent.CovidCaseVisibilitySetting__r){
                Integer childSortNumber = (Integer) mdtChild.Sort_Number__c;
                
                if(parentVsChildMap.containsKey(mdtParent.MasterLabel)){
                    parentVsChildMap.get(mdtParent.MasterLabel).put(childSortNumber, mdtChild);
                }else{                    
                    parentVsChildMap.put(mdtParent.MasterLabel, new Map<Integer, CovidCaseVisibilitySetting__mdt>());
                    parentVsChildMap.get(mdtParent.MasterLabel).put(childSortNumber, mdtChild);
                }
            }
        }
        
        for(SectionAndUserAccessOnCovidCase__mdt mdtParent : parentMetadata){
            System.debug('iSectionAccessible: '+iSectionAccessible+', Show_by_Default__c: '+mdtParent.Show_by_Default__c);
            if(!iSectionAccessible && !mdtParent.Show_by_Default__c)
                    continue;
            
            for(Integer index = 0; index <= parentVsChildMap.get(mdtParent.MasterLabel).size(); index++){
                if(!parentVsChildMap.get(mdtParent.MasterLabel).containsKey(index))
                    continue;
                
                CovidCaseVisibilitySetting__mdt mdtChildRec = parentVsChildMap.get(mdtParent.MasterLabel).get(index);
                System.debug('mdtChildRec : '+mdtChildRec );
                if(sctionNamevsMetadataRecords.containsKey(mdtParent.MasterLabel)){
                    sctionNamevsMetadataRecords.get(mdtChildRec.SectionAndUserAccessOnCovidCase__r.MasterLabel).add(mdtChildRec);
                }else{                    
                    sctionNamevsMetadataRecords.put(mdtParent.MasterLabel, new List<CovidCaseVisibilitySetting__mdt>());
                    sctionNamevsMetadataRecords.get(mdtChildRec.SectionAndUserAccessOnCovidCase__r.MasterLabel).add(mdtChildRec);
                }            
            }
        }
        
        
        
        return sctionNamevsMetadataRecords;
    }
    
    /*@AuraEnabled
    public static List<CovidCaseVisibilitySetting__mdt> getRequiredFields(){
        List<CovidCaseVisibilitySetting__mdt> reqFields = new List<CovidCaseVisibilitySetting__mdt>();
        
        for(CovidCaseVisibilitySetting__mdt fields : [SELECT MasterLabel, Is_Required__c, Field_API_Name__c FROM CovidCaseVisibilitySetting__mdt]){
        	if(fields.Is_Required__c)
                reqFields.add(fields);
        }
            
        return reqFields;
        
    }*/
    
    @AuraEnabled
    public static Boolean checkSectionAccess(Id recordId){
        
        Boolean isDataAccessibleToLogggedInUser = FALSE;
        List<Profile> sysAdminProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' OR Name = 'SCG-SysAdm'];
        Case cs = [SELECT Id, TECH_Is_National_Account__c, Space__c, Space__r.Property__c, OwnerId FROM Case WHERE Id = :recordId];

        if((UserInfo.getProfileId() == sysAdminProfile[0].Id || UserInfo.getProfileId() == sysAdminProfile[1].Id || UserInfo.getUserId() == cs.OwnerId) && !Test.isRunningTest())
            return TRUE;
        
        
        if(UserInfo.getName() == 'John Papagiannis' || UserInfo.getName() == 'Andrew Hulls' || UserInfo.getName() == 'Courtney Kingston')
            return TRUE;
        
        if(cs.TECH_Is_National_Account__c){
            for(CaseTeamMember csMem : [SELECT MemberId, ParentId, Parent.Property__c, Parent.Account.Is_National_Account__c FROM CaseTeamMember WHERE ParentId = :recordId]){
                
                if(UserInfo.getUserId() == csMem.MemberId)
                    isDataAccessibleToLogggedInUser = TRUE;
            }    
        }else{
            for(PropertyTeam__c propTeams : [SELECT Id, TeamMember__c FROM PropertyTeam__c WHERE Property__c = :cs.Space__r.Property__c AND Active__c = TRUE]){
                
                if(UserInfo.getUserId() == propTeams.TeamMember__c)
                    isDataAccessibleToLogggedInUser = TRUE;
            }
        }
        
        return isDataAccessibleToLogggedInUser;
    }
    
    @AuraEnabled
    public static String getCaseRecordType(){
        return Schema.SObjectType.Case.getRecordTypeInfosByName().get(Constants.LVI_COVID19).getRecordTypeId();
	}
    
    @AuraEnabled
    public static Boolean isCaseLocked(Id caseId){
        return Approval.isLocked(caseId);
    }
}