objects/OpportunityClause__c.object
<CustomObject>
    <description>&lt;OPC&gt; - Represents a clause applied to a deal.</description>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Clauses</relationshipLabel>
        <relationshipName>Opportunity_Clauses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RiskApplies__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This flag is ticked if there is a risk applied Clause associated with this space. Please contact Retail Admin for any questions.</inlineHelpText>
        <label>Risk Applies?</label>
        <type>Checkbox</type>
    </fields>
    <label>Opportunity Clause</label>
    <nameField>
        <label>Opportunity Clauses Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Clauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OpportunityClauseBL.cls
public class OpportunityClauseBL {
    /** 
    * @Author: Lean Flores
    * @Para: Set<Id> Opportunity Id set, Opportunities to update ClauseSummary
    * @Desc: Contains SOQL queries. Use only when ClauseSummary__c update is needed
    */ 
    public static void updateOpportunityClauseSummary(Set<Id> oppIdSet) {
        Map<Id,List<String>> oppClauseSummaryMap = new Map<Id,List<String>>();
        
        for(OpportunityClause__c riskClause: [SELECT Id, Name, Opportunity__c FROM OpportunityClause__c WHERE RiskApplies__c=true AND Approved__c=false AND Opportunity__c IN:oppIdSet]) {
            if (oppClauseSummaryMap.containsKey(riskClause.Opportunity__c)) {
                oppClauseSummaryMap.get(riskClause.Opportunity__c).add(riskClause.Name);
            } else {
                oppClauseSummaryMap.put(riskClause.Opportunity__c, new List<String>{riskClause.Name});
            }
        }
        
        List<Opportunity> oppsToUpdate = [SELECT Id FROM Opportunity WHERE Id IN:oppIdSet];
        
        if (oppsToUpdate.size() > 0) {
            for (Opportunity opp : oppsToUpdate) {
                opp.ClauseSummary__c = '';
                if (oppClauseSummaryMap.containsKey(opp.Id)){
                    opp.ClauseSummary__c = String.join(oppClauseSummaryMap.get(opp.Id), ', ');
                }
                
            }
        
            Database.update(oppsToUpdate);
        }
    }
    
}