objects/OpportunityClause__c.object
<CustomObject>
    <description>&lt;OPC&gt; - Represents a clause applied to a deal.</description>
    <fields>
        <fullName>LeasingComment__c</fullName>
        <inlineHelpText>Please provide reasons why this clause is required on an Opportunity.</inlineHelpText>
        <label>Leasing Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Clauses</relationshipLabel>
        <relationshipName>Opportunity_Clauses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Clause</label>
    <nameField>
        <label>Opportunity Clauses Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Clauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RiskOpportunityClauseController.cls
public class RiskOpportunityClauseController {
	@AuraEnabled
	public static LightningResponse getOpportunityClause(Id opportunityId){
		LightningResponse res = new LightningResponse();
		ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(RiskOpportunityClauseController.class.getName());
		List<OpportunityClause__c> opportunityClauseList = new List<OpportunityClause__c>();
		
		try{
			opportunityClauseList = [SELECT Id, Name, LeasingComment__c
									 FROM OpportunityClause__c
									 WHERE Opportunity__c =: opportunityId];
									 
			res.returnValue = JSON.serialize(opportunityClauseList);
		} catch(Exception e){
			errorHandler.createError(e);
			res.status = Constants.SUCCESS;
			res.message = e.getMessage();
		}
		
		errorHandler.save();
		
		return res;
	}
	
	@AuraEnabled
	public static Boolean canUpdate(Opportunity opportunity){
		Boolean canUpdate = false;
		
		Profile prof = DatabaseSOQLBank.getProfile(UserInfo.getProfileId());
		
		if(opportunity.OwnerId == UserInfo.getUserId() || Constants.SYSTEM_ADMINISTRATOR.equalsIgnoreCase(prof.Name)){
			canUpdate = true;
		}
		
		return canUpdate;
	}
	
	@AuraEnabled
	public static LightningResponse updateOpportunityClause(String oppClauseListJSON){
		LightningResponse res = new LightningResponse();
		ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(RiskOpportunityClauseController.class.getName());
		List<OpportunityClause__c> opportunityClauseList;
		
		if(oppClauseListJSON != '' && oppClauseListJSON != null){
			opportunityClauseList 
				= (List<OpportunityClause__c>) JSON.deserialize(oppClauseListJSON, List<OpportunityClause__c>.class);
		}
			
		if(opportunityClauseList != null && opportunityClauseList.size() > 0){
			try{
				Database.update(opportunityClauseList);
			} catch(Exception e){
				errorHandler.createError(e);
			}
		}
		
		return res;
	}
}