objects/OpportunityClause__c.object
<CustomObject>
    <description>&lt;OPC&gt; - Represents a clause applied to a deal.</description>
    <fields>
        <fullName>EffectiveToDate__c</fullName>
        <label>Effective To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ClauseType</valueSetName>
        </valueSet>
    </fields>
    <label>Opportunity Clause</label>
    <nameField>
        <label>Opportunity Clauses Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Clauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PrecedentClause__c.object
<CustomObject>
    <description>&lt;PRC&gt; - Represents the link between clauses and agreed clauses for an account at National level.</description>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EffectiveToDate__c</fullName>
        <label>Effective To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Nil_Holdover_Increase__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag used to promo increases should not be automatically added in case of Holdover</description>
        <label>Nil Holdover Increase</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ClauseType</valueSetName>
        </valueSet>
    </fields>
    <label>Precedent Clause</label>
    <nameField>
        <label>Clause Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Precedent Clauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Neel 03042018: Added</description>
        <label>Description</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SpaceType</valueSetName>
        </valueSet>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/SpaceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Shop</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Kiosk</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Office Suite</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Store Room</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Seating</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sundry Property</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Garage / Parking</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sundry</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Space Bank</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Common Mall</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>Re-design</label>
    </customValue>
    <customValue>
        <fullName>Seating License</fullName>
        <isActive>false</isActive>
        <label>Seating License</label>
    </customValue>
    <customValue>
        <fullName>Sundry Site</fullName>
        <isActive>false</isActive>
        <label>Sundry Site</label>
    </customValue>
    <masterLabel>Space Type</masterLabel>
</GlobalValueSet>

classes/PrecedentClauseTriggerHandlerTest.cls
/* 
*@author:               Kyle Tan
*@description:          Test class for the PrecedentClauseTriggerHandler class
*/
@isTest
private class PrecedentClauseTriggerHandlerTest {
    
    //testSetup
    @TestSetup private static void testSetup() {
        Map<String, Schema.RecordTypeInfo> accountRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(CONSTANTS.ACCOUNT);
        Property__c propertyRecord = new Property__c();
        Account accountRecord = new Account(); 
        List<Property__c> propertyList = new List<Property__c>();
        List<Account> accountList = new List<Account>();
        List<Account> tempAccountList = new List<Account>();
        List<Opportunity> opportunityList = new List<Opportunity>();
        PrecedentClause__c precedentClauseRecord = new PrecedentClause__c();   
        List<PrecedentClause__c> precedentClauseList = new List<PrecedentClause__c>();
        List<Pricebook2> priceBookList = new List<Pricebook2>();
        List<Space__c> spaceLst = new List<Space__c>();
        Product2 productRecord;
        List<Account> parentAccList = new List<Account>();
        Account account = new Account();
        Contact conRec = new Contact();
        
        
        //CREATE PRODUCT
        productRecord = TestDataFactory.createProduct(Constants.PRODUCT_RENT_REVIEW, Constants.RENT);
        insert productRecord;
        
        //CREATE PRICEBOOK
        pricebookList = TestDataFactory.createPricebook(10);
        database.insert(pricebookList);
        pricebookList = [SELECT Id, CurrencyIsoCode FROM Pricebook2];
        
        //CREATE PROPERTY
        propertyList = TestDataFactory.createProperty(10, pricebookList[0]);
        database.insert(propertyList);
        Property__c propRec = [SELECT Id FROM Property__c LIMIT 1];
        //CREATE ACCOUNT
        accountList = TestDataFactory.createAccountBulk(10, 
                                                        propertyRecord.Id, 
                                                        accountRecordTypeMapByName.get(CONSTANTS.GROUP_LEVEL).getRecordTypeId());
        database.insert(accountList);
        tempAccountList = [SELECT Id 
                            FROM Account 
                            WHERE ParentId = null 
                            AND RecordTypeId = :accountRecordTypeMapByName.get(CONSTANTS.GROUP_LEVEL).getRecordTypeId() 
                            LIMIT 10];
        accountList = new List<Account>();
        for(Integer counter = 0; counter < 10; counter++) {
            accountRecord = TestDataFactory.createAccountwithParent(counter, 
                                                                    null, 
                                                                    accountRecordTypeMapByName.get(CONSTANTS.PROPERTY_BASED).getRecordTypeId(), 
                                                                    tempAccountList.get(counter).Id);
            accountList.add(accountRecord);
        }
        database.insert(accountList);
        
        //CREATE OPPORTUNITY
        accountList = [SELECT Id, Account.Property__c FROM Account WHERE ParentId != null LIMIT 100];
        
        opportunityList = TestDataFactory.createOpportunity(accountList);
        
        database.insert(opportunityList);
        
        //CREATE PRECEDENT CLAUSE
        accountList = [SELECT Id 
                        FROM Account 
                        WHERE ParentId = null 
                        AND RecordTypeId = :accountRecordTypeMapByName.get(CONSTANTS.GROUP_LEVEL).getRecordTypeId() 
                        LIMIT 10];

        for(Integer counter = 0; counter < 10; counter++) {
            precedentClauseRecord = TestDataFactory.createPrecedentClause(counter, accountList.get(counter).Id);
            precedentClauseList.add(precedentClauseRecord);
        }
        
        database.insert(precedentClauseList);
    }
    
    /* 
*@author:          Kyle Tan
*@description:     inserts precedent clause
*/
    public static testMethod void uponInsertTest() {
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SYSTEM_ADMINISTRATOR LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        Map<String, Schema.RecordTypeInfo> accountRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(CONSTANTS.ACCOUNT);
        PrecedentClause__c precedentClauseRecord = new PrecedentClause__c();
        List<PrecedentClause__c> precedentClauseList = new List<PrecedentClause__c>();
        List<Account> accountList = new List<Account>();
        List<OpportunityClause__c> opportunityClauseList = new List<OpportunityClause__c>();
        
        accountList = [SELECT Id 
                       FROM Account 
                       WHERE ParentId = null 
                       AND RecordTypeId = :accountRecordTypeMapByName.get(CONSTANTS.GROUP_LEVEL).getRecordTypeId() 
                       LIMIT 10];
        
        for(Integer counter = 0; counter < 10; counter++) {
            if(counter < 8) {
                precedentClauseRecord = TestDataFactory.createPrecedentClause(counter, accountList.get(counter).Id);
            } else {
                precedentClauseRecord = TestDataFactory.createPrecedentClause(counter, accountList.get(counter - 1).Id);
            }
            precedentClauseList.add(precedentClauseRecord);
        }
        
        System.runAs(testUser) {
            
            Test.startTest();
            
            database.insert(precedentClauseList);
            precedentClauseList = [SELECT Id FROM PrecedentClause__c LIMIT 1];
            database.delete(precedentClauseList);
            
            Test.stopTest();
        }
        
        opportunityClauseList = [SELECT Id FROM OpportunityClause__c LIMIT 10];
        system.assertEquals(opportunityClauseList.size(), 10);
    }
    
    /* 
*@author:          Kyle Tan
*@description:     updates precedent clause
*/
    public static testMethod void uponUpdateTest() {
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SYSTEM_ADMINISTRATOR LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        Map<String, Schema.RecordTypeInfo> accountRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(CONSTANTS.ACCOUNT);
        
        List<PrecedentClause__c> precedentClauseList = [SELECT Id, Type__c, Name, Description__c, 
                                                                Comments__c, EffectiveToDate__c 
                                                                FROM PrecedentClause__c 
                                                                LIMIT 10];
        List<Account> accountList = new List<Account>();
       
        OpportunityClause__c opportunityClauseRecord = new OpportunityClause__c();
        List<OpportunityClause__c> opportunityClauseList = new List<OpportunityClause__c>();
        
        System.runAs(testUser) {
            
            Test.startTest();
            
            for(PrecedentClause__c tempPrecedentClauseRecord : precedentClauseList) {
                tempPrecedentClauseRecord.Description__c = 'Test Change Description';
                tempPrecedentClauseRecord.Comments__c = 'Test Change Comments';
                tempPrecedentClauseRecord.EffectiveToDate__c = date.today() + 1;
                tempPrecedentClauseRecord.Nil_Holdover_Increase__c = false;
            }
            
            Database.update(precedentClauseList);
            
            System.debug('UPDATE  ' + precedentClauseList);
            
            Test.stopTest();
            
        }
        for(PrecedentClause__c precedentClauseRecord : [SELECT Id, Description__c, Comments__c, EffectiveToDate__c 
                                                            FROM PrecedentClause__c 
                                                            LIMIT 10]) {
                                                                system.assertEquals('Test Change Description', precedentClauseRecord.Description__c);
                                                                system.assertEquals('Test Change Comments', precedentClauseRecord.Comments__c);
                                                            }
        
    }
    
}