objects/PrecedentClause__c.object
<CustomObject>
    <description>&lt;PRC&gt; - Represents the link between clauses and agreed clauses for an account at National level.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Precedent Clauses</relationshipLabel>
        <relationshipName>PrecedentClauses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ClauseType</valueSetName>
        </valueSet>
    </fields>
    <label>Precedent Clause</label>
    <nameField>
        <label>Clause Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Precedent Clauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CreateUsageClauseInvocable.cls
/**
 * @author:					Kyle Tan
 * @desc:					creates usage clause to the parent account created from lead convertion
 **/
public class CreateUsageClauseInvocable {

    @InvocableMethod
    public static void createUsageClause(List<Account> parentAccountList) {
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(OpportunityTriggerHandler.class.getName());
        if(parentAccountList != null && parentAccountList.size() > 0) {
            Set<String> convertedLeadSet = new Set<String>();
            Map<Id, Lead> leadMap = new Map<Id, Lead>();
            for(Account accountRecord :parentAccountList) {
                convertedLeadSet.add(accountRecord.TechConvertedLeadId__c);
            }
            if(convertedLeadSet != null && convertedLeadSet.size() > 0) {
                try {
                    leadMap = new Map<Id, Lead>([SELECT Id, Usage__c FROM Lead]);
                } catch(Exception e) {
                    leadMap = null;
                }
                if(leadMap != null && leadMap.size() > 0) {
                    List<PrecedentClause__c> precClauseList = new List<PrecedentClause__c>();
                    PrecedentClause__c precClauseRec = new PrecedentClause__c();
                    Map<String, Schema.RecordTypeInfo> precedentClauseRecordTypeMapByName  = RecordTypeUtil.getAllRecordTypesByName(Constants.PRECEDENT_CLAUSE_API);
                    for(Account accountRecord :parentAccountList) {
                        if(leadMap.containsKey(accountRecord.TechConvertedLeadId__c) &&
                           String.isNotBlank(leadMap.get(accountRecord.TechConvertedLeadId__c).Usage__c)) {
                            precClauseRec.Name = Constants.PERMITTED_USE;
                            precClauseRec.Account__c = accountRecord.Id;
                            precClauseRec.Type__c = Constants.USAGE;
                            precClauseRec.Status__c = Constants.ACTIVE;
                            precClauseRec.Description__c = leadMap.get(accountRecord.TechConvertedLeadId__c).Usage__c;
                            precClauseRec.RecordTypeId = precedentClauseRecordTypeMapByName.get(Constants.NATIONAL_PRECEDENT_CLAUSES).getRecordTypeId();
                            precClauseList.add(precClauseRec);
                        }
                    }
                    if(precClauseList != null && precClauseList.size() > 0) {
                        try {
                            database.insert(precClauseList);
                        } catch (Exception e) {
                            errorHandler.createError(e);
                        }
                        errorHandler.save();                        
                    }
                }
            }
        }
    }
}