objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PropertyMaps__c.object
<CustomObject>
    <fields>
        <fullName>Floor__c</fullName>
        <label>Floor</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Floor</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Property Maps</relationshipLabel>
        <relationshipName>PropertyMaps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>Property Maps</label>
    <nameField>
        <label>Property Maps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>FloorPlanURL__c</fullName>
        <label>Floor Plan URL</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MainFloor__c</fullName>
        <label>Main Floor</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Floor</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Floor.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>0001</fullName>
    </customValue>
    <customValue>
        <fullName>0002</fullName>
    </customValue>
    <customValue>
        <fullName>0003</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <customValue>
        <fullName>13</fullName>
    </customValue>
    <customValue>
        <fullName>14</fullName>
    </customValue>
    <customValue>
        <fullName>15</fullName>
    </customValue>
    <customValue>
        <fullName>16</fullName>
    </customValue>
    <customValue>
        <fullName>160</fullName>
    </customValue>
    <customValue>
        <fullName>17</fullName>
    </customValue>
    <customValue>
        <fullName>18</fullName>
    </customValue>
    <customValue>
        <fullName>19</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>22</fullName>
    </customValue>
    <customValue>
        <fullName>23</fullName>
    </customValue>
    <customValue>
        <fullName>24</fullName>
    </customValue>
    <customValue>
        <fullName>25</fullName>
    </customValue>
    <customValue>
        <fullName>26</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>50</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>6&amp;7</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <masterLabel>Floor</masterLabel>
</GlobalValueSet>

classes/PropertyMapsBL.cls
/**
 *  @author:        Kyle Tan
 *  @description:   Contains business logic from PropertyMapsTriggerHandler
 **/
public without sharing class PropertyMapsBL {
    
    /**
     * @author:			Kyle tan
     * @desc:			update the FloorPlanURL__c field of the spaces of the property
     **/
    public static List<Space__c> updateSpaceFloorPlanURL(Map<Id, List<Space__c>> propertySpaceMap, PropertyMaps__c propMapRecord) {
        List<Space__c> spaceList = new List<Space__c>();
        String tempURL = null;
        if(propertySpaceMap.containsKey(propMapRecord.Property__c)) {
            for(Space__c spaceRec :propertySpaceMap.get(propMapRecord.Property__c)) {
                if(spaceRec.MainFloor__c != null && propMapRecord.Floor__c != null 
                   && spaceRec.MainFloor__c.equalsIgnoreCase(propMapRecord.Floor__c)) {
                       if(String.isNotEmpty(propMapRecord.URL__c) && propMapRecord.URL__c.contains(Constants.SVG)) {
                           system.debug('hey-->' + spaceRec.MainFloor__c + '-' + propMapRecord.Floor__c);
                           tempURL = propMapRecord.URL__c.replace(Constants.SVG, Constants.PNG);
                           spaceRec.FloorPlanURL__c = tempURL;
                           spaceList.add(spaceRec);
                       }
                   }
            }
        }
        return spaceList;
    }

}