objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PropertyMaps__c.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Property Maps</relationshipLabel>
        <relationshipName>PropertyMaps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>Property Maps</label>
    <nameField>
        <label>Property Maps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PropertyMapsTriggerHandler.cls
/**
* Class PropertyMapsTriggerHandler
*
* Trigger Handler for the PropertyMaps__c SObject. This class implements the ITrigger
* interface to help ensure the trigger code is bulkified and all in one place.
*/
public without sharing class PropertyMapsTriggerHandler extends TriggerHandler implements ITrigger {
    private Map<Id, List<Space__c>> propertySpaceMap = new Map<Id, List<Space__c>>();
    private List<Space__c> spaceToUpdateList = new List<Space__c>();
    
    // Constructor
    public PropertyMapsTriggerHandler()
    {
    }
    
    public void bulkBefore()
    {

        if(Trigger.isInsert || Trigger.isUpdate) {
        }
        
        if(Trigger.isInsert) {
        }
        
        if(Trigger.isUpdate) {
        }
        
    }
    
    public void bulkAfter()
    {
        if(Trigger.isInsert || Trigger.isUpdate) {
            Set<Id> propertyIdSet = new Set<Id>();
            PropertyMaps__c oldPropMapRec = new PropertyMaps__c();
            for(PropertyMaps__c propMapRec :(List<PropertyMaps__c>) Trigger.new) {
                if(Trigger.isInsert) {
                    propertyIdSet.add(propMapRec.Property__c);
                }
                if(Trigger.isUpdate) {
                    oldPropMapRec = (PropertyMaps__c)Trigger.oldMap.get(propMapRec.Id);
                    if(propMapRec.URL__c != oldPropMapRec.URL__c) {
                        propertyIdSet.add(propMapRec.Property__c);
                    }
                }
            }
            // START : KT RPP-5580 8-2-18
            if(propertyIdSet != null && propertyIdSet.size() > 0) {
                propertySpaceMap = DatabaseSOQLBank.getSpacesOfProperty(propertyIdSet);
            }
            // END : KT RPP-5580 8-2-18
            if(Trigger.isInsert) {
            }
            if(Trigger.isUpdate) {
            }
        }
    }
    
    public void beforeInsert(SObject so)
    {
    }
    
    public void beforeUpdate(SObject oldSo, SObject so)
    {
    }
    
    public void beforeDelete(SObject so)
    {
    }
    
    public void afterInsert(SObject so)
    {
        PropertyMaps__c newPropMap = (PropertyMaps__c)so;
        
        // START : KT RPP-5580 8-2-18
        spaceToUpdateList.addAll(PropertyMapsBL.updateSpaceFloorPlanURL(propertySpaceMap, newPropMap));
        // END : KT RPP-5580 8-2-18
    }
    
    public void afterUpdate(SObject oldSo, SObject so)
    {
        PropertyMaps__c newPropMap = (PropertyMaps__c)so;
        PropertyMaps__c oldPropMap = (PropertyMaps__c)oldSo;
        
        // START : KT RPP-5580 8-2-18
        if(newPropMap.URL__c != oldPropMap.URL__c) {
            spaceToUpdateList.addAll(PropertyMapsBL.updateSpaceFloorPlanURL(propertySpaceMap, newPropMap));
        }
        // END : KT RPP-5580 8-2-18
    }
    
    public void afterDelete(SObject so)
    {
    }
    
    public void andFinally()
    {
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(PropertyMapsTriggerHandler.class.getName());
        
        // START : KT RPP-5580 8-2-18
        if(spaceToUpdateList != null && spaceToUpdateList.size() > 0) {
            try {
                database.update(spaceToUpdateList, false);
            } catch(Exception e){
                errorHandler.createError(e);
            }
        }
        // END : KT RPP-5580 8-2-18
        errorHandler.save();
    }

}