objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PropertyMaps__c.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Property Maps</relationshipLabel>
        <relationshipName>PropertyMaps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Property Maps</label>
    <nameField>
        <label>Property Maps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PropertyMapsControllerTest.cls
/*
* @author:              Miguel Paguio
* @description:         Test class for PropertyMapsController
*/
@isTest
public class PropertyMapsControllerTest {
    @TestSetup private static void testSetup(){
        Map<String, Schema.RecordTypeInfo> accountRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(CONSTANTS.ACCOUNT);
        List<Property__c> propertyList = new List<Property__c>();
        List<Account> accountList = new List<Account>();
        List<Account> tempAccountList = new List<Account>();
        List<PropertyMaps__c> propertyMapsList = new List<PropertyMaps__c>();
        List<Space__c> spaceList = new List<Space__c>();
        List<User> userList = new List<User>();
        List<Pricebook2> priceBookList = new List<Pricebook2>();
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SCG_RETAIL_ADMIN LIMIT 1];
        
        //Create Price Book
        priceBookList = TestDataFactory.createPricebook(1);
        database.insert(priceBookList);
        
        //CREATE PROPERTY
        propertyList = TestDataFactory.createProperty(1, priceBookList[0]);
        database.insert(propertyList);
        
        //CREATE PROPERTYMAPS
        propertyMapsList = TestDataFactory.createPropertyMaps(1, propertyList.get(0).Id);
        Database.insert(propertyMapsList);
        
        //CREATE ACCOUNT
        accountList.addAll(TestDataFactory.createAccountBulk(1, propertyList.get(0).Id, accountRecordTypeMapByName.get(CONSTANTS.GROUP_LEVEL).getRecordTypeId()));
        database.insert(accountList);
        
        //CREATE SPACE
        /**for(Integer counter = 0; counter < 10; counter++){
spaceList = TestDataFactory.createSpace(5, propertyList.get(counter));   
}**/
        spaceList = TestDataFactory.createSpace(1, propertyList.get(0));
        Database.insert(spaceList);
        
        for(Integer i = 0; i < 10; i++){
            User testUser = TestDataFactory.createUniqueTestUser(CONSTANTS.TEST_FNAME + ' ' + i, CONSTANTS.TEST_LNAME + ' ' + i, profileRec.Id);
            userList.add(testUser);
        }
        Database.insert(userList); 
    }
    
    public static testMethod void getPropertyMapsByPropertyTest() {
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SYSTEM_ADMINISTRATOR LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        
        List<Property__c> propRec = [SELECT Id FROM Property__c];
        List<PropertyMaps__c> propMaps = [SELECT Id FROM PropertyMaps__c LIMIT 1];
        System.runAs(testUser){
            
            Test.startTest();          
            propMaps = PropertyMapsController.getPropertyMapsByProperty(propRec.get(0).Id);            
            Test.stopTest();   
        }
        
        System.assertEquals(true, propMaps <> null);
    }
    
    public static testMethod void getImageSpaceIdAndLevelTest() {
        
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SYSTEM_ADMINISTRATOR LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        
        List<Property__c> propRec = [SELECT Id FROM Property__c];
        List<PropertyMaps__c> propMaps = [SELECT Id FROM PropertyMaps__c LIMIT 1];
        List<Space__c> spaceRec = [SELECT Id FROM Space__c];
        String testProp = '';
        
        System.runAs(testUser){
            Test.startTest();          
            testProp = PropertyMapsController.getImageSpaceIdAndLevel('0', spaceRec.get(0).Id);            
            Test.stopTest(); 
        }
        
        
        System.assertEquals(true, testProp <> '');
    }
    
    public static testMethod void getPropertyMapBySpaceTest() {
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SYSTEM_ADMINISTRATOR LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        
        List<Property__c> propRec = [SELECT Id FROM Property__c];
        List<PropertyMaps__c> propMaps = [SELECT Id FROM PropertyMaps__c LIMIT 1];
        List<Space__c> spaceRec = [SELECT Id FROM Space__c];
        String testProp = '';
        System.runAs(testUser){
            Test.startTest();          
            testProp = PropertyMapsController.getPropertyMapBySpace(spaceRec.get(0).Id);            
            Test.stopTest();   
        }
        
        System.assertEquals(true, testProp <> null);
        
    }
    
    
    public static testMethod void getImageByPropertyAndLevelTest() {
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SYSTEM_ADMINISTRATOR LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        
        List<Property__c> propRec = [SELECT Id FROM Property__c];
        List<PropertyMaps__c> propMaps = [SELECT Id FROM PropertyMaps__c LIMIT 1];
        String testProp = '';
        
        System.runAs(testUser){
            Test.startTest();          
            testProp = PropertyMapsController.getImageByPropertyAndLevel('0', propRec.get(0).Id);            
            Test.stopTest();   
        }
        
        System.assertEquals(true, testProp <> '');
    }
    
    public static testMethod void getSpacesAndImageByPropertyTest() {
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SYSTEM_ADMINISTRATOR LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        
        List<Property__c> propRec = [SELECT Id FROM Property__c];
        List<PropertyMaps__c> propMaps = [SELECT Id FROM PropertyMaps__c LIMIT 1];
        String testProp = '';
        System.runAs(testUser){
            
            Test.startTest();          
            testProp = PropertyMapsController.getSpacesAndImageByProperty('0', propRec.get(0).Id);            
            Test.stopTest();   
        }
        System.debug('check');
        System.assertEquals(true, testProp <> '');
    }
    
   
}