objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>PropertyStatus__c</fullName>
        <label>Property Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TriggerFactoryTest.cls
/*
* author: Alyana Navarro
* created date: October 10, 2018
* description: Test class for TriggerFactory
*/

@isTest
public class TriggerFactoryTest {
    
    @isTest
    private static void testCreateAndExecuteHandler() {
        List<Pricebook2> pricebookList = new List<Pricebook2>();
        List<Property__c> propertyList = new List<Property__c>();
        
        //CREATE PRICEBOOK
        pricebookList = TestDataFactory.createPricebook(10);
        database.insert(pricebookList);
        pricebookList = [SELECT Id, CurrencyIsoCode FROM Pricebook2];
        
        //CREATE PROPERTY
        propertyList = TestDataFactory.createProperty(10, pricebookList[0]);
        database.insert(propertyList);
        
        //UPDATE PROPERTY
        for(Property__c prop : propertyList){
            prop.PropertyStatus__c = 'Inactive';
        }
        TriggerHandler.clearBypass('PropertyTriggerHandler');
        database.update(propertyList);
        
        //DELETE PROPERTY
        TriggerHandler.clearBypass('PropertyTriggerHandler');
        database.delete(propertyList);
    }
}