objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TechDispatchedTimeStamp__c</fullName>
        <label>Tech_DispatchedTimeStamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TechDispatchedVersion__c</fullName>
        <label>Tech_DispatchedVersion</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TechEventVersionSame__c</fullName>
        <formula>TechAcknowledgeVersion__c  =  TechDispatchedVersion__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tech_EventVersionSame</label>
        <type>Checkbox</type>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CustomIterable.cls
global class CustomIterable implements Iterable<SObject>, Iterator<SObject>{ 
   
   public Iterator<SObject> iterator() { return this; }
   
   List<SObject> sobjs {get; set;} 
   Integer i {get; set;} 
   public CustomIterable(){ 
       sobjs = new List<SObject>();
       //Add space
       List<Space__c> spaces = [SELECT Id, TechDispatchedVersion__c, TechDispatchedTimeStamp__c FROM Space__c WHERE TechEventVersionSame__c = FALSE ORDER BY Property__c Limit 10000]; 
       if (spaces.size() > 0) {
           for( Space__c space : spaces ) {
               sobjs.add(space);
           }   
       }
       //Add accounts
       List<Account> accounts = [SELECT Id, TechDispatchedVersion__c, TechDispatchedTimeStamp__c FROM Account WHERE TechEventVersionSame__c = FALSE Limit 10000];
       if (accounts.size() > 0) {
           for( Account account : accounts ) {
               sobjs.add(account);
           }   
       }
       //Add contact
       List<Contact> contacts = [SELECT Id, TechDispatchedVersion__c, TechDispatchedTimeStamp__c FROM Contact WHERE TechEventVersionSame__c = FALSE Limit 10000];
       if (contacts.size() > 0) {
       		for( Contact contact : contacts ) {
           		sobjs.add(contact);
       		}    
       }
       
       //Add opportunity TechEventVersionSame__c 
       List<Opportunity> oppos = [SELECT Id, TechDispatchedVersion__c, TechDispatchedTimeStamp__c FROM Opportunity WHERE TechEventVersionSame__c = FALSE Limit 10000];
       if (oppos.size() > 0) {
           for( Opportunity oppo : oppos ) {
               sobjs.add(oppo);
           }   
       }
       //Add case
       List<Case> cases = [SELECT Id, RecordTypeId, Status, TechDispatchedVersion__c, TechDispatchedTimeStamp__c, JDESentStatus__c FROM Case WHERE TechEventVersionSame__c = FALSE Limit 10000];
       List<Case> validCases = CaseBL.caseEventCriteriaCheck(cases);
       if (validCases.size() > 0) {
       	   for( Case caseRecord : validCases ) {
               sobjs.add(caseRecord);
           }   
       }
       //Add task
       List<Task> tasks = [SELECT Id, taskType__c, Status, TechDispatchedVersion__c, TechDispatchedTimeStamp__c, WhatId FROM Task WHERE TechEventVersionSame__c = FALSE Limit 10000];
       if (tasks.size() > 0) {
           for( Task task : tasks ) {
               sobjs.add(task);
           }
       }
       i = 0; 
   }   
   global boolean hasNext(){ 
       if(i >= sobjs.size()) 
           return false; 
       else 
           return true; 
   }    
   global SObject next(){ 
       if(i == sobjs.size()){ i++; return null;} 
       i=i+1; 
       return sobjs[i-1]; 
   } 
}