objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PropertyTeam__c.object
<CustomObject>
    <description>&lt;PRT&gt; - Represents a internal team working for the property eg. Centre Manager, Facility Manager, RDM, Leasing Executive, Development Leasing Executive</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Property Team</relationshipLabel>
        <relationshipName>Property_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RoleType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TeamMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Property_Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property Team</label>
    <nameField>
        <displayFormat>PRT-{0000}</displayFormat>
        <label>Property Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/RoleType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accounts Receivable Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Administration Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Architectural Technician</fullName>
    </customValue>
    <customValue>
        <fullName>Asset General Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Centre Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Chief Operating Officer</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Leasing Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Leasing General Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Leasing Regional Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Property Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Retail Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate Legal</fullName>
    </customValue>
    <customValue>
        <fullName>D&amp;C Special Project Coordinator</fullName>
    </customValue>
    <customValue>
        <fullName>Development Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Development Finance Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Director LARS &amp; NZ Development</fullName>
    </customValue>
    <customValue>
        <fullName>Facilities Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Filing Clerk</fullName>
    </customValue>
    <customValue>
        <fullName>Fitout Contributions Admin</fullName>
    </customValue>
    <customValue>
        <fullName>General Manager Leasing</fullName>
    </customValue>
    <customValue>
        <fullName>General Manager Retail Design</fullName>
    </customValue>
    <customValue>
        <fullName>GM of Corporate Accounting</fullName>
    </customValue>
    <customValue>
        <fullName>GM Retail Admin &amp; Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Group General Manager - LARS</fullName>
    </customValue>
    <customValue>
        <fullName>Group Renewal Admin Team</fullName>
        <label>Group Renewal Team</label>
    </customValue>
    <customValue>
        <fullName>Leasing Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Leasing Finance Analyst</fullName>
    </customValue>
    <customValue>
        <fullName>Project Regional Manager - LARS</fullName>
    </customValue>
    <customValue>
        <fullName>Project Retail Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>Project Retail Design Manager</fullName>
    </customValue>
    <masterLabel>Role Type</masterLabel>
</GlobalValueSet>

classes/CancelledOppChatterInvocable.cls
global class CancelledOppChatterInvocable {
    
    @InvocableMethod
    public static void postChatterToPropTeam(List<Id> oppIdList) {
        Map<String, Schema.RecordTypeInfo> oppRecordTypeMapByDeveloperName = RecordTypeUtil.getAllRecordTypesByDeveloperName(CONSTANTS.OPPORTUNITY);
        Set<String> teamRolesToNotify = new Set<String>{ 
            	Constants.TEAM_ROLE_AT,
                Constants.TEAM_ROLE_RDC,
                Constants.TEAM_ROLE_RDM, 
                Constants.TEAM_ROLE_RMR_DESIGN, 
                Constants.TEAM_ROLE_RMR_DELIVERY,
                Constants.TEAM_ROLE_RA
                };
                
		Map<Id, List<Id>> propTeamMembersByOppMap = new Map<Id, List<Id>>();
        
        Map<Id, Opportunity> oppMap = new Map<Id, Opportunity>([SELECT Id, Name, RecordURL__c, Property__c, RecordTypeId FROM Opportunity WHERE Id IN:oppIdList]);
		Set<Id> propIdSet = new Set<Id>();
        Map<Id, Map<String, PropertyTeam__c>> propTeamMembersMap = new Map<Id, Map<String, PropertyTeam__c>>();
        List<ChatterPostUtil.chatterNotificationWrapper> chatterList = new List<ChatterPostUtil.chatterNotificationWrapper>();
        
        for (Opportunity opp : oppMap.values()) {            
            if (opp.Property__c != null) {
                propIdSet.add(opp.Property__c);    
            }
        }
        
        propTeamMembersMap = DatabaseSOQLBank.getPropertyTeamByProperty(propIdSet);
        Id retailOppRecTypeId = oppRecordTypeMapByDeveloperName.get(Constants.OPP_RETAIL_LEASING_API_NAME).getRecordTypeId();
        
        
        for (Opportunity opp : oppMap.values()) {            			
            System.debug('propTeamMembersMap.containsKey(opp.Property__c) '+propTeamMembersMap.containsKey(opp.Property__c) );
            System.debug(opp.RecordTypeId +' '+retailOppRecTypeId);
            if (propTeamMembersMap.containsKey(opp.Property__c) && opp.RecordTypeId == retailOppRecTypeId) {
                
                Set<Id> teamMembersToMention = new Set<Id>();
                
                for (PropertyTeam__c propTeam : propTeamMembersMap.get(opp.Property__c).values()) {
                    if (teamRolesToNotify.contains(propTeam.Role__c)) {
                        teamMembersToMention.add(propTeam.TeamMember__c);
                    }
                }
                
                
                chatterList.add(ChatterPostUtil.ChatterPostGeneric(
                    Label.ChatterCancelledOppGeneric,
                    opp.Id,
                    new List<String>(),
                    teamMembersToMention,
                    opp.Id
                ));
                
            }
            
        }
        
        if (chatterList.size() > 0) {
            ChatterPostUtil.chatterpostBulk(chatterList);
        }
            
    }
}