objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>BillingCategory__c</fullName>
        <description>Billing category to identify the bill code.</description>
        <inlineHelpText>For Finance Use Only.</inlineHelpText>
        <label>Billing Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SpaceBillingCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SpaceType</valueSetName>
        </valueSet>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/SpaceBillingCategory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>NR</fullName>
        <label>Non Retail</label>
    </customValue>
    <customValue>
        <fullName>PE</fullName>
        <label>External Precinct</label>
    </customValue>
    <customValue>
        <fullName>ATM</fullName>
    </customValue>
    <customValue>
        <fullName>EX</fullName>
        <label>Car Park - External</label>
    </customValue>
    <customValue>
        <fullName>PM</fullName>
        <label>Car Park - Permanent</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Car Park - Internal</label>
    </customValue>
    <customValue>
        <fullName>VL</fullName>
        <label>Car Park - Valet</label>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
        <default>true</default>
        <label>Not Applicable</label>
    </customValue>
    <description>Space Billing Category</description>
    <masterLabel>Space Billing Category</masterLabel>
</GlobalValueSet>

globalValueSets/SpaceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Shop</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Kiosk</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Office Suite</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Store Room</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Seating</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sundry Property</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Garage / Parking</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sundry</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Space Bank</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Common Mall</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>Re-design</label>
    </customValue>
    <customValue>
        <fullName>Seating License</fullName>
        <isActive>false</isActive>
        <label>Seating License</label>
    </customValue>
    <customValue>
        <fullName>Sundry Site</fullName>
        <isActive>false</isActive>
        <label>Sundry Site</label>
    </customValue>
    <masterLabel>Space Type</masterLabel>
</GlobalValueSet>

classes/ACRTriggerHandlerTest.cls
/**
* @author:         Kyle Tan
* @description:    Test Class for ACRTriggerHandler
**/
@isTest
private class ACRTriggerHandlerTest {
    
    @testSetup
    private static void testSetup(){
        List<Account> accountList = new List<Account>();
        List<Property__c> propertyList = new List<Property__c>();
        List<Pricebook2> pricebookList = new List<Pricebook2>();
        List<Opportunity> oppList = new List<Opportunity>();
        Contact contactRec = new Contact();
        List<Contact> contactList = new List<Contact>();
        List<Space__c> spaceList = new List<Space__c>();
        
        //CREATE PRICEBOOK
        pricebookList = TestDataFactory.createPricebook(10);
        database.insert(pricebookList);
        pricebookList = [SELECT Id, CurrencyIsoCode FROM Pricebook2];
        
        //CREATE PROPERTY 
        propertyList = TestDataFactory.createProperty(10, pricebookList[0]);
        database.insert(propertyList);
        propertyList = [SELECT Id FROM Property__c LIMIT 1];
        
        accountList = TestDataFactory.createAccountBulk(1, propertyList[0].Id, RecordTypeUtil.getAllRecordTypesByName(CONSTANTS.ACCOUNT).get(Constants.PROPERTY_BASED).getRecordTypeId());
        database.insert(accountList);
        accountList = [SELECT Id, Property__c FROM Account LIMIT 1];
        
        for(Account acc : accountList){
            contactRec = TestDataFactory.createContact('Test Name', accountList[0]);
            
            contactList.add(contactRec);
        }
        
        database.insert(contactList);
        
        //CREATE SPACE
        spaceList = TestDataFactory.createSpace(1, propertyList[0]);
        spaceList[0].type__c = '1';
        spaceList[0].BillingCategory__c = 'NA';
        database.insert(spaceList);
        
        spaceList = [SELECT Id, Type__c FROM Space__c];
        oppList = TestDataFactory.createOpportunity(1, accountList[0], propertyList, spaceList);
        AccountContactRelation acrRec = [SELECT Id, IsActive FROM AccountContactRelation Limit 1];
        System.debug('ACR REC ===== ' + acrRec);
        for(Opportunity opp : oppList){
            opp.JDESentStatus__c = 'Ready';
            opp.PrimaryContact__c = contactRec.Id;
        }
        
        database.insert(oppList);
        
        oppList = [SELECT Id, AccountId,JDESentStatus__c, PrimaryContact__c FROM Opportunity];
        System.debug('Oppplist ==== ' + oppList);
        
        
    }
    
    /**
* @author:         Kyle Tan
* @description:    Test Method for inserting an Account Contact Relationship
**/
    private static testMethod void testInsertACR() {
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SYSTEM_ADMINISTRATOR LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        AccountContactRelation ACRRec = [SELECT ID FROM AccountContactRelation LIMIT 1];
        
        System.debug('Acr REc ==== ' + ACRRec);
        system.runAs(testUser) {
            test.startTest();
            ACRTriggerHandler acrhandler = new ACRTriggerHandler();
            
            List<Opportunity> oppList = [SELECT Id FROM Opportunity LIMIT 200];
            List<Account> accountList = [SELECT Id, Property__c FROM Account LIMIT 200];
            List<Property__c> propertyList = [Select Id FROM Property__c LIMIT 200];
            List<Space__c> spaceList = [SELECT Id FROM Space__c LIMIT 200];
            Contact contactRec = [SELECT Id FROM Contact LIMIT 1];
            oppList = TestDataFactory.createOpportunity(1, accountList[0], propertyList, spaceList);
            for(Opportunity opp : oppList){
                opp.JDESentStatus__c = 'Ready';
                opp.PrimaryContact__c = contactRec.Id;
            }
            database.insert(oppList);
            for(Opportunity opp : oppList){
                opp.JDESentStatus__c = 'Processing';
            }
            TriggerHandler.clearAllBypasses();
            database.update(oppList);
            
            acrhandler.beforeUpdate(ACRRec, ACRRec);
            acrhandler.beforeDelete(ACRRec);
            acrhandler.afterUpdate(ACRRec, ACRRec);
            acrhandler.afterDelete(ACRRec);
            
            //TODO: put some value on acEvents or satisfy the conditon for conW.sendEvent
            
            test.stopTest();
        }
    }
    
    @isTest
    private static void testRDIContactCount(){
        AccountContactRelation ACRRec = [SELECT ID,AccountId, Roles FROM AccountContactRelation LIMIT 1];
        ACRRec.Roles = Label.Applicable_RDI_Contact_Roles.split(',')[0];
        Test.startTest();
        update ACRRec;
        Test.stopTest();
        Account acc = [SELECT Id, No_of_RDI_Applicable_Contact_Relation__c FROM Account WHERE Id =: ACRRec.AccountId];
        System.assert(acc.No_of_RDI_Applicable_Contact_Relation__c != null);
    }
    
}