objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>JDEPropertyNumber__c</fullName>
        <externalId>true</externalId>
        <label>JDE Property Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PropertyMaps__c.object
<CustomObject>
    <fields>
        <fullName>Floor__c</fullName>
        <label>Floor</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Floor</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Property Maps</relationshipLabel>
        <relationshipName>PropertyMaps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>URI__c</fullName>
        <label>URI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>Property Maps</label>
    <nameField>
        <label>Property Maps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>CurrentLeaseRiskApplied__c</fullName>
        <formula>CurrentLease__r.Opportunity__r.RiskApplies__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This flag is ticked if there is a risk applied Clause associated with this Space. Please contact Retail Admin for any questions.</inlineHelpText>
        <label>Current Lease Risk Applied</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CurrentRent__c</fullName>
        <formula>CurrentLease__r.CurrentRent__c</formula>
        <label>Current Rent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CurrentRetailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Neel 03042018: Updated FieldLabel and FieldName</description>
        <label>Current Retailer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Spaces (Current Tenant)</relationshipLabel>
        <relationshipName>LeasedSpace</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MainFloor__c</fullName>
        <label>Main Floor</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Floor</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RentableArea__c</fullName>
        <label>Rentable Area</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UnitNo__c</fullName>
        <formula>TEXT(Type__c) &amp; &quot;-&quot; &amp;  Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unit No</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UsableArea__c</fullName>
        <inlineHelpText>Equals the rentable area.</inlineHelpText>
        <label>Usable Area</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Floor.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>0001</fullName>
    </customValue>
    <customValue>
        <fullName>0002</fullName>
    </customValue>
    <customValue>
        <fullName>0003</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <customValue>
        <fullName>13</fullName>
    </customValue>
    <customValue>
        <fullName>14</fullName>
    </customValue>
    <customValue>
        <fullName>15</fullName>
    </customValue>
    <customValue>
        <fullName>16</fullName>
    </customValue>
    <customValue>
        <fullName>160</fullName>
    </customValue>
    <customValue>
        <fullName>17</fullName>
    </customValue>
    <customValue>
        <fullName>18</fullName>
    </customValue>
    <customValue>
        <fullName>19</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>22</fullName>
    </customValue>
    <customValue>
        <fullName>23</fullName>
    </customValue>
    <customValue>
        <fullName>24</fullName>
    </customValue>
    <customValue>
        <fullName>25</fullName>
    </customValue>
    <customValue>
        <fullName>26</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>50</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>6&amp;7</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <masterLabel>Floor</masterLabel>
</GlobalValueSet>

classes/PropertyMapsController.cls
public class PropertyMapsController {
	
    public class PropertyMapsBLWrapper {
        public String imageUrl;
        public List<Space__c> spaces;
        List<PropertyMaps__c> propertyMaps;
        public String level;
    }
    /**
     * @Author: Chen Chen
     * @Parameter: propertyId, current property Id
     * @Description: Get all the property maps belonging to this property
	 */
    @TestVisible 
    private static List<PropertyMaps__c> getPropertyMapsByProperty(Id propertyId) {
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(PropertyMapsController.class.getName());
        List<PropertyMaps__c> propertyMaps = new List<PropertyMaps__c>();
        try{
            propertyMaps = [Select Id, Name, Floor__c, URL__c, URI__c From PropertyMaps__c Where Property__c =: propertyId ORDER BY Floor__c ASC];
        } catch(Exception e) {
            errorHandler.createError(e);
        }
        
        errorHandler.save();
        return propertyMaps;
    }
    
    /**
     * @Author: Chen Chen
     * @Parameter: level current request level of the property, propertyId current property Id
     * @Description: Get image url by level and property Id
	 */
    public static String getImageByPropertyAndLevel(String level, Id propertyId) {
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(PropertyMapsController.class.getName());
        String imageUrl = '';
        System.debug('level ' + level + ' propertyId ' + propertyId);
        List<PropertyMaps__c> propertyMaps = new List<PropertyMaps__c>();
        try{
            propertyMaps = [Select Id, Floor__c, URL__c, URI__c From PropertyMaps__c Where Property__c =: propertyId And Floor__c =: level];
        } catch(Exception e) {
            errorHandler.createError(e);
        }
        if (propertyMaps.size() > 0 && propertyMaps.size() == 1) {
            System.debug('imageUrl ' + imageUrl);
            imageUrl = propertyMaps.get(0).URL__c;
        }
        errorHandler.save();
        return imageUrl;
    }
    
    /**
     * @Author: Chen Chen
     * @Parameter: level current request level of the property, spaceId current space Id
     * @Description: Get image url by level and space Id
	 */
    @TestVisible 
    private static String getImageSpaceIdAndLevel(String level, Id spaceId) {
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(PropertyMapsController.class.getName());
        String imageUrl = '';
        List<Space__c> space = new List<Space__c>();
        try{
            space = [Select Id, Property__c From Space__c Where Id =: spaceId];
        } catch(Exception e) {
            errorHandler.createError(e);
        }
        if (space.size() == 1) {
            imageUrl = getImageByPropertyAndLevel(level, space.get(0).Property__c);
        }
        errorHandler.save();
        return imageUrl;
    }
    
    /**
     * @Author: Chen Chen
     * @Parameter: level current request level of the property, spaceId current property Id
     * @Description: Get PropertyMapsBLWrapper by level and property Id
	 */
    
    @AuraEnabled
    public static String getSpacesAndImageByProperty(String level, Id propertyId) {
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(PropertyMapsController.class.getName());
        String imageUrl;
        List<PropertyMaps__c> getFloor = [Select id, Floor__c From PropertyMaps__c where Property__c  = :propertyId limit 1];
        if (getFloor.size() > 0 && level == 'initial') {
            level = getFloor.get(0).Floor__c; 
        }
        List<PropertyMaps__c> propertyMaps = new List<PropertyMaps__c>();
        List<Space__c> spaces = new List<Space__c>();
        try {
            imageUrl = getImageByPropertyAndLevel(level, propertyId);
        } catch(Exception e) {
            errorHandler.createError(e);
        }
        try{
            propertyMaps = getPropertyMapsByProperty(propertyId);
        } catch(Exception e) {
            errorHandler.createError(e);
        }
        try {
            spaces = [Select Id, Name, UnitNo__c, CurrentRetailer__c, CurrentRetailer__r.Name, CurrentRent__c, CurrentLeaseRiskApplied__c, RentableArea__c, UsableArea__c, Property__r.JDEPropertyNumber__c From Space__c Where MainFloor__c =: level And Property__c = :propertyId];
        } catch(Exception e) {
            errorHandler.createError(e);
        }
        PropertyMapsBLWrapper pmWrapper = new PropertyMapsBLWrapper();
        pmWrapper.imageUrl = imageUrl;
        pmWrapper.spaces = spaces;
        pmWrapper.propertyMaps = propertyMaps;
        pmWrapper.level = level;
        System.debug('pmWrapper ' + pmWrapper);
        errorHandler.save();
        return JSON.serialize(pmWrapper);
    }
    
    @AuraEnabled
    public static String getPropertyMapBySpace(Id spaceId) {
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(PropertyMapsController.class.getName());
        String imageUrl = '';
        List<Space__c> spaces = new List<Space__c>();
        List<PropertyMaps__c> maps = new List<PropertyMaps__c>();
        try{
            spaces = [Select Id, Property__c, MainFloor__c From Space__c Where Id =: spaceId];
        } catch(Exception e) {
            errorHandler.createError(e);
        }
        if (spaces.size() == 1) {
            String propertyId = spaces.get(0).Property__c;
            String level = spaces.get(0).MainFloor__c;
            try{
                maps = [Select Id, URI__c, URL__c From PropertyMaps__c Where Floor__c =: level and Property__c =: propertyId];
            } catch(Exception e) {
                errorHandler.createError(e);
            }
            if (maps.size() == 1) {
                imageUrl = maps.get(0).URL__c;
            }
        }
        errorHandler.save();
        return imageUrl;
    }
}