objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>PriceBook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Properties (PriceBook)</relationshipLabel>
        <relationshipName>PropertiesPriceBook</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>OccupancyStatus__c</fullName>
        <description>This lists the status of the property being leased.</description>
        <label>Occupancy Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 - Vacancy</fullName>
                </value>
                <value>
                    <fullName>2 - Leasing Issues</fullName>
                </value>
                <value>
                    <fullName>3 - LBNT (Leased but not trading)</fullName>
                </value>
                <value>
                    <fullName>4 - Held Vacancies</fullName>
                </value>
                <value>
                    <fullName>5 - Trading New Retailers</fullName>
                </value>
                <value>
                    <fullName>6 - Expiring Leases</fullName>
                </value>
                <value>
                    <fullName>7 - Holdovers</fullName>
                </value>
                <value>
                    <fullName>8 - Project Shops</fullName>
                </value>
                <value>
                    <fullName>9 - Trading</fullName>
                </value>
                <value>
                    <fullName>10 - Inactive</fullName>
                </value>
                <value>
                    <fullName>1- Vacancy</fullName>
                    <isActive>false</isActive>
                    <label>1- Vacancy</label>
                </value>
                <value>
                    <fullName>9 - Closed Shops</fullName>
                    <isActive>false</isActive>
                    <label>9 - Closed Shops</label>
                </value>
                <value>
                    <fullName>Achieved</fullName>
                    <isActive>false</isActive>
                    <label>Achieved</label>
                </value>
                <value>
                    <fullName>Closed Shops</fullName>
                    <isActive>false</isActive>
                    <label>Closed Shops</label>
                </value>
                <value>
                    <fullName>Expiring Leases</fullName>
                    <isActive>false</isActive>
                    <label>Expiring Leases</label>
                </value>
                <value>
                    <fullName>Held Vacancies</fullName>
                    <isActive>false</isActive>
                    <label>Held Vacancies</label>
                </value>
                <value>
                    <fullName>Holdovers</fullName>
                    <isActive>false</isActive>
                    <label>Holdovers</label>
                </value>
                <value>
                    <fullName>LBNT (Leased but not trading)</fullName>
                    <isActive>false</isActive>
                    <label>LBNT (Leased but not trading)</label>
                </value>
                <value>
                    <fullName>Leasing Issues</fullName>
                    <isActive>false</isActive>
                    <label>Leasing Issues</label>
                </value>
                <value>
                    <fullName>Project Shops</fullName>
                    <isActive>false</isActive>
                    <label>Project Shops</label>
                </value>
                <value>
                    <fullName>Trading New Retailers</fullName>
                    <isActive>false</isActive>
                    <label>Trading New Retailers</label>
                </value>
                <value>
                    <fullName>Vacancy</fullName>
                    <isActive>false</isActive>
                    <label>Vacancy</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>At Risk</fullName>
                </value>
                <value>
                    <fullName>Held</fullName>
                </value>
                <value>
                    <fullName>Trading</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SpaceType</valueSetName>
        </valueSet>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/SpaceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Shop</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Kiosk</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Office Suite</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Store Room</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Seating</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sundry Property</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Garage / Parking</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sundry</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Space Bank</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Common Mall</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>Re-design</label>
    </customValue>
    <customValue>
        <fullName>Seating License</fullName>
        <isActive>false</isActive>
        <label>Seating License</label>
    </customValue>
    <customValue>
        <fullName>Sundry Site</fullName>
        <isActive>false</isActive>
        <label>Sundry Site</label>
    </customValue>
    <masterLabel>Space Type</masterLabel>
</GlobalValueSet>

classes/ContentBLTest.cls
/*
* @author:              Sidney Garcia
* @description:         Test class for ContentBL
*/
@isTest
public class ContentBLTest {
    @TestSetup private static void testSetup() {
        Property__c testProperty = new Property__c();
        List<Account> accountList = new List<Account>();
        Account accountRecord = new Account();
        Map<String, Schema.RecordTypeInfo> accountRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(CONSTANTS.ACCOUNT);
        List<Opportunity> opportunityList = new List<Opportunity>();
        Opportunity opportunityRecord = new Opportunity();
        List<Space__c> spaceList = new List<Space__c>();
        Product2 productRecord;
        
        //CREATE PRODUCT
        
        productRecord = TestDataFactory.createProduct(Constants.FEES_CHARGES, Constants.FEES_CHARGES);
        productRecord.SpaceBillingCategory__c = 'NA';
        insert productRecord;
        
        
        Id pricebookId = Test.getStandardPricebookId();
        
        //CREATE PROPERTY
        testProperty = TestDataFactory.createPropertyRecord();
        testProperty.PriceBook__c = pricebookId;
        database.insert(testProperty);
        
        //CREATE SPACE
        spaceList = TestDataFactory.createSpace(10, testProperty);
        
        for(Space__c spaceRec : spaceList){
            spaceRec.OccupancyStatus__c = Constants.SPACE_OCCUPANCYSTATUS_TRADING;
            spaceRec.Status__c = Constants.SPACE_STATUS_TRADING;
            spaceRec.Type__c = '2';
        }
        
        database.insert(spaceList);
        
        //CREATE ACCOUNT
        for(Integer counter = 0; counter < 5; counter++) {
            accountRecord = TestDataFactory.createAccount(counter, testProperty.Id, accountRecordTypeMapByName.get(CONSTANTS.PROPERTY_BASED).getRecordTypeId());
            accountList.add(accountRecord);
        }
        database.insert(accountList);
        accountList = [SELECT Id, Property__c FROM Account LIMIT 5];
        Contact contactRecord = TestDataFactory.createContact(CONSTANTS.TEST_FNAME, accountList[0]);
        insert contactRecord;
        
        //CREATE Opportunity
        opportunityList = TestDataFactory.createOpportunity(10, accountList[0]);
        for(Opportunity opp : opportunityList){
            opp.Space__c = spaceList[0].Id;
        }
        insert opportunityList;
        
        List<ContentDocumentLink> conDocLinkList = new List<ContentDocumentLink>();
        ContentDocumentLink conDLRecord = new ContentDocumentLink();
        
        ContentVersion cv=new Contentversion();
        cv.title='ABC';
        cv.PathOnClient ='test';
        Blob b = Blob.valueOf('Unit Test Attachment Body');
        cv.versiondata=EncodingUtil.base64Decode('Unit Test Attachment Body');
        cv.DocumentCategory__c = 'Plans';
        cv.DocumentType__c = Constants.LEASE_PLAN;
        Database.insert(cv);
        
        ContentVersion conVer = new ContentVersion();
        conVer = [SELECT Id, title, ContentDocumentId FROM ContentVersion WHERE Id =: cv.Id];
        
        conDLRecord.ContentDocumentId = conVer.ContentDocumentId;
        conDLRecord.LinkedEntityId = opportunityList[0].Space__c;
        conDLRecord.ShareType = 'V';
        conDLRecord.Visibility = 'AllUsers';
        
        insert conDLRecord;
    }
    public static testMethod void testCreateContentDocumentLink(){
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SCG_SYS_ADM LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser(CONSTANTS.TEST_FNAME, CONSTANTS.TEST_LNAME, profileRec.Id);
        List<Opportunity> oppList = [SELECT Id, Space__c, Type FROM Opportunity LIMIT 10];
        List<ContentDocumentLink> conDocLinkList = new List<ContentDocumentLink>();
        System.runAs(testUser) {
            Test.startTest();
            conDocLinkList = ContentBL.createContentDocumentLink(oppList, 'Opportunity');
            Test.stopTest();
        }
        
        System.assert(conDocLinkList <> null);
        
    }
}