objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ChatterForSDICTaskCompletionTest.cls
@isTest
public class ChatterForSDICTaskCompletionTest {
     @testSetup
    public static void testSetup(){
      TestDataFactory.testSetupMeathod();
        
    }
    
     @isTest static void chatterPostToProprtyTeamTest(){
        test.startTest();
         List<Id> lisId =new List<Id>() ;
         List<Task> taskList = [SELECT Id, WhatId, Opportunity__r.Space__r.Property__c FROM Task];
         lisId.add(taskList[0].Id);
         lisId.add(taskList[1].Id);
        ChatterForSDICTaskCompletion.chatterPostToProprtyTeam(lisId);
        test.stopTest(); 
         
         System.assert(true);
    }
    
    @isTest static void chatterPostToProprtyTeamTest1(){
        test.startTest();
         List<Id> lisId =new List<Id>() ;
         List<Task> taskList = [SELECT Id, WhatId, Case__r.Space__r.Property__c FROM Task];
         lisId.add(taskList[0].Id);
         ChatterForSDICTaskCompletion.chatterPostToProprtyTeam(lisId);
        test.stopTest(); 
         System.assert(true);
    }
    
   
}