objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>JDEPropertyNumber__c</fullName>
        <externalId>true</externalId>
        <label>JDE Property Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_Of_Space_Groups__c</fullName>
        <label>No. Of Space Groups</label>
        <summaryFilterItems>
            <field>SpaceGroup__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>SpaceGroup__c.ParentSpace__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <description>Parent
Child</description>
        <label>Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Relationship</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RentableArea__c</fullName>
        <label>Rentable Area</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>At Risk</fullName>
                </value>
                <value>
                    <fullName>Held</fullName>
                </value>
                <value>
                    <fullName>Trading</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SpaceType</valueSetName>
        </valueSet>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SpaceBudgetAndForecast__c.object
<CustomObject>
    <description>&lt;SBF&gt; - Represents approved annualised amount for budget for CY and JV FY and forecast periods</description>
    <fields>
        <fullName>Batch_Process_Status_Reason__c</fullName>
        <label>Batch Process Status Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Batch_Process_Status__c</fullName>
        <label>Batch Process Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Not Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BudgetedDealType__c</fullName>
        <label>Budgeted Deal Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Net</fullName>
                </value>
                <value>
                    <fullName>Semi Gross</fullName>
                </value>
                <value>
                    <fullName>Gross</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <inlineHelpText>The effective date is the year the budget relates to.</inlineHelpText>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ModelType__c</fullName>
        <label>Model Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Budget</fullName>
                </value>
                <value>
                    <fullName>JV Budget</fullName>
                </value>
                <value>
                    <fullName>Forecast</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <formula>Space__r.Property__r.Name</formula>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipLabel>Space Budget and Forecast</relationshipLabel>
        <relationshipName>Space_Budget_and_Forecast</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Space Budget and Forecast</label>
    <nameField>
        <label>Space Budget and Forecast Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Space Budget and Forecast</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SpaceGroup__c.object
<CustomObject>
    <description>&lt;SPG&gt; - Represents a grouping of spaces eg. Sales Precinct, Development Project</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ChildSpace__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Child Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipLabel>Space Groups (Child Space)</relationshipLabel>
        <relationshipName>Space_Groups2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <inlineHelpText>This is the achieved date of the first child Space.</inlineHelpText>
        <label>Effective Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ParentSpace__c</fullName>
        <label>Parent Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipLabel>Space Groups (Parent Space)</relationshipLabel>
        <relationshipName>Space_Groups3</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <formula>ChildSpace__r.Property__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SpaceGroupNumber__c</fullName>
        <description>Same group number for the group saved.</description>
        <inlineHelpText>This is the unique identifier for the reconfiguration group.</inlineHelpText>
        <label>Space Group Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Reconfiguration - Split</fullName>
                </value>
                <value>
                    <fullName>Reconfiguration - Merge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Space Group</label>
    <nameField>
        <label>Space Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Space Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Relationship.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Parent</fullName>
    </customValue>
    <customValue>
        <fullName>Child</fullName>
    </customValue>
    <customValue>
        <fullName>-None-</fullName>
        <default>true</default>
        <label>-None-</label>
    </customValue>
    <masterLabel>Relationship</masterLabel>
</GlobalValueSet>

globalValueSets/SpaceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Shop</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Kiosk</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Office Suite</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Store Room</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Seating</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sundry Property</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Garage / Parking</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sundry</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Space Bank</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Common Mall</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>Re-design</label>
    </customValue>
    <customValue>
        <fullName>Seating License</fullName>
        <isActive>false</isActive>
        <label>Seating License</label>
    </customValue>
    <customValue>
        <fullName>Sundry Site</fullName>
        <isActive>false</isActive>
        <label>Sundry Site</label>
    </customValue>
    <masterLabel>Space Type</masterLabel>
</GlobalValueSet>

classes/SpaceManagementBatchHelper.cls
/*------------------------------------------------------------------------------------
Author:      Aakash Soor
Company:     Arxxus Technology Partners
Description: This is a helper class for SpaceManagementBatch Class
Test Class:  
History
Date            Author             Comments
--------------------------------------------------------------------------------------
04-12-2019      Aakash Soor        Initial Release
--------------------------------------------------------------------------------------*/
public without sharing class SpaceManagementBatchHelper{

    public Set<Id> getParentSpaceIds(List<SpaceBudgetAndForecast__c> spaceBudgets, Set<Id> processedSpaceIds){
        Set<Id> parentSpaceIds = new Set<Id>();

        for(SpaceBudgetAndForecast__c sbf : spaceBudgets){
            if(sbf.Space__c != null
                && !processedSpaceIds.contains(sbf.Space__c)) 
            parentSpaceIds.add(sbf.Space__c);
        }
        return parentSpaceIds;
    }

    public String getQuery(){
        Set<String> spaceFieldsToQuery = new Set<String>();
        Set<String> spaceBudgetFieldsToQuery = new Set<String>();
        Set<String> spaceGroupFieldsToQuery = new Set<String>();

        spaceFieldsToQuery.add('Id');
        spaceFieldsToQuery.add('Name');
        spaceFieldsToQuery.addAll(new Set<String>(Label.SpaceReconfig_BudgetToSplit.split(Constants.SEMICOLON)));
        spaceFieldsToQuery.add('Type__c');
        spaceFieldsToQuery.add('Property__c');
        spaceFieldsToQuery.add('Property__r.JDEPropertyNumber__c');
        spaceFieldsToQuery.add('RentableArea__c');
        spaceFieldsToQuery.add('CurrencyIsoCode');
        spaceFieldsToQuery.add('No_Of_Space_Groups__c');
        spaceFieldsToQuery.add('Status__c'); 
        spaceFieldsToQuery.add('Active__c'); 

        spaceBudgetFieldsToQuery.add('Id');
        spaceBudgetFieldsToQuery.addAll(new Set<String>(Label.SpaceReconfig_BudgetSplitFields.split(Constants.SEMICOLON)));
        spaceBudgetFieldsToQuery.add('ModelType__c');
        spaceBudgetFieldsToQuery.add('BudgetedDealType__c');
        spaceBudgetFieldsToQuery.add('EffectiveDate__c');

        spaceGroupFieldsToQuery.add('Id');
        spaceGroupFieldsToQuery.add('Active__c');
        spaceGroupFieldsToQuery.add('ChildSpace__c');
        spaceGroupFieldsToQuery.add('SpaceGroupNumber__c');

        String query = 'SELECT ' + String.join(new List<String>(spaceFieldsToQuery),',');
        query = query + ', (SELECT ' 
                        + String.join(new List<String>(getSpaceParentFields(spaceFieldsToQuery,'ChildSpace__r')),',')
                        + ','
                        + String.join(new List<String>(spaceGroupFieldsToQuery),',') 
                        +' FROM Space_Groups3__r)';
        query = query + ', (SELECT ' + String.join(new List<String>(spaceBudgetFieldsToQuery),',') +' FROM Space_Budget_and_Forecast__r WHERE Space__r.Active__c = true AND Space__r.Relationship__c = \''+ Constants.SPACE_REL_PARENT +'\' AND Batch_Process_Status__c IN (\'New\',\'Pending\') ORDER BY EffectiveDate__c,CreatedDate DESC)';
        query = query + ' FROM Space__c WHERE ID IN: parentSpaceIds';

        system.debug('query------------'+query);
        return query;
    }

    private Set<String> getSpaceParentFields(Set<String> spaceFieldsToQuery, String lookupAPIName) {
        Set<String> parentFields = new Set<String>();
        for(String field : new List<String>(spaceFieldsToQuery)){
            parentFields.add(lookupAPIName + '.' +field);
        }
        return parentFields;
    }

    public Map<String, List<SpaceBudgetAndForecast__c>> updateSpaceBudgetBatchStatus(List<SpaceBudgetAndForecast__c> spaceBudgetList){
        Map<String, List<SpaceBudgetAndForecast__c>> spaceBudgetMap = new Map<String, List<SpaceBudgetAndForecast__c>>{
                                                                                'Pending' => new List<SpaceBudgetAndForecast__c>(),
                                                                                'NotProcessed' => new List<SpaceBudgetAndForecast__c>(), 
                                                                                'All' => new List<SpaceBudgetAndForecast__c>()};
        for(SpaceBudgetAndForecast__c sbf : spaceBudgetList){
            if(sbf.Space__r.No_Of_Space_Groups__c > 0){
                sbf.Batch_Process_Status__c = 'Pending';
                spaceBudgetMap.get('Pending').add(sbf);
            }else{
                sbf.Batch_Process_Status__c = 'Not Processed';
                sbf.Batch_Process_Status_Reason__c = 'No Reconfiguration found.';
                spaceBudgetMap.get('NotProcessed').add(sbf); 
            }
            spaceBudgetMap.get('All').add(sbf);
        }
        return spaceBudgetMap;
    }

    public Map<Decimal, SpaceManagementController.SpaceBudgetWrapper> prepareSpaceBudgetWrapper(List<Space__c> parentSpaces, Map<String,String> budgetFieldApiNameVsModelType){
        Map<Decimal, SpaceManagementController.SpaceBudgetWrapper> sbWrappers = new Map<Decimal, SpaceManagementController.SpaceBudgetWrapper>();
        SpaceManagementController.SpaceBudgetWrapper sbWrapper;
        Map<Id,List<Space__c>> propertyVsSpaces = new Map<Id,List<Space__c>>();
        Map<String,Schema.SObjectField> spaceObjectSchema = Schema.SObjectType.Space__c.fields.getMap();
        Set<Decimal> invalidGroupNumbers = new Set<Decimal>(); 

        for(Space__c space : parentSpaces){
            system.debug('space.No_Of_Space_Groups__c-------------'+space.No_Of_Space_Groups__c);
            if(space.No_Of_Space_Groups__c > 0){
                Decimal groupNumber = 0;
                sbWrapper = new SpaceManagementController.SpaceBudgetWrapper();
                system.debug('space.Space_Groups3__r-------------'+space.Id+'----------'+space.Space_Groups3__r.size());
                for(SpaceGroup__c spaceGrp : space.Space_Groups3__r){
                    groupNumber = spaceGrp.SpaceGroupNumber__c;

                    if(!spaceGrp.Active__c
                        || !space.Active__c
                       	|| spaceGrp.ChildSpace__c == null
                        || !spaceGrp.ChildSpace__r.Active__c
                       	|| invalidGroupNumbers.contains(groupNumber)){
                        invalidGroupNumbers.add(groupNumber);
                        sbWrappers.remove(groupNumber);
                        continue;
                    }
                    if(sbWrappers.containsKey(groupNumber)){
                        sbWrapper = sbWrappers.get(groupNumber);
                    }
                    system.debug('spaceGrp.ChildSpace__r---------'+spaceGrp.ChildSpace__c+'------------'+spaceGrp.ChildSpace__r);
                    sbWrapper.childSpaces.put(spaceGrp.ChildSpace__c,spaceGrp.ChildSpace__r);
                }
				
                if(!invalidGroupNumbers.contains(groupNumber)){ 
                    sbWrapper.property = space.Property__r;
                    sbWrapper.property.Id = space.Property__c;
                    sbWrapper.parentSpaces.put(space.Id,space);
                    for(String budgetField : budgetFieldApiNameVsModelType.keySet()){
                        if(spaceObjectSchema.containsKey(budgetField)){
                            for(SpaceBudgetAndForecast__c sbf : space.Space_Budget_and_Forecast__r){
                                if(budgetFieldApiNameVsModelType.get(budgetField) == sbf.ModelType__c){
                                    space.put(budgetField,sbf.Id);
                                    sbWrapper.spaceBudgetMap.put(sbf.Id,sbf);
                                }
                            }
                        }
                    }
                    System.debug('sbWrapper---------------'+sbWrapper);
                    sbWrappers.put(groupNumber,sbWrapper);
                }
            }
            
        }
        return sbWrappers;
    }

    public Map<Id,Space__c> updateSpaceWithLatestBudget(List<SpaceBudgetAndForecast__c> spaceBudgetForLinking, 
                                                                Map<String,String> budgetFieldApiNameVsModelType, 
                                                                Map<String,Schema.SObjectField> spaceObjectSchema){
        Map<Id,Space__c> spacesToUpdate = new Map<Id,Space__c>();

        if(!spaceBudgetForLinking.isEmpty()){
            for(String budgetField : budgetFieldApiNameVsModelType.keySet()){
                if(spaceObjectSchema.containsKey(budgetField)){
                    for(SpaceBudgetAndForecast__c sbf : spaceBudgetForLinking){
                        if(budgetFieldApiNameVsModelType.get(budgetField) == sbf.ModelType__c
                          	&& sbf.Id != null){
                            if(spacesToUpdate.containsKey(sbf.Space__c)){
                                Space__c space = spacesToUpdate.get(sbf.Space__c);
                                space.put(budgetField,sbf.Id);
                                spacesToUpdate.put(space.id,space);
                            }else{
                                Space__c space = new Space__c();
                                space.Id = sbf.Space__c;
                                space.put(budgetField,sbf.Id);
                                spacesToUpdate.put(space.id,space);
                            }
                            
                        }
                    }
                }
            }
        }
        return spacesToUpdate;
    }

    @AuraEnabled
    public static string checkLatestBatchStatus(){

        List<AsyncApexJob> sMJobs = [SELECT Id, ApexClass.Name, NumberOfErrors, Status , CompletedDate
                                    FROM AsyncApexJob 
                                    WHERE JobType = 'BatchApex'
                                    AND ApexClass.Name = 'SpaceManagementBatch'
                                    ORDER BY CreatedDate DESC
                                    LIMIT 1];
        
        if(sMJobs.isEmpty()) return null;

        return JSON.serialize(sMJobs);
    } 

    @AuraEnabled
    public static string runSpaceManagementBatch(){

        SpaceManagementBatch spaceMagBatch = new SpaceManagementBatch();
        Id batchprocessid = Database.executeBatch(spaceMagBatch);

        AsyncApexJob sMJob = [SELECT Id, Status, JobItemsProcessed, TotalJobItems, NumberOfErrors, CompletedDate 
                            FROM AsyncApexJob WHERE ID =: batchprocessid ];
        return JSON.serialize(sMJob);
    }
}