objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PropertyTeam__c.object
<CustomObject>
    <description>&lt;PRT&gt; - Represents a internal team working for the property eg. Centre Manager, Facility Manager, RDM, Leasing Executive, Development Leasing Executive</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Property Team</relationshipLabel>
        <relationshipName>Property_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Property Team</label>
    <nameField>
        <displayFormat>PRT-{0000}</displayFormat>
        <label>Property Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>MainFloor__c</fullName>
        <label>Main Floor</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Floor</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SpaceType</valueSetName>
        </valueSet>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Floor.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>0001</fullName>
    </customValue>
    <customValue>
        <fullName>0002</fullName>
    </customValue>
    <customValue>
        <fullName>0003</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <customValue>
        <fullName>13</fullName>
    </customValue>
    <customValue>
        <fullName>14</fullName>
    </customValue>
    <customValue>
        <fullName>15</fullName>
    </customValue>
    <customValue>
        <fullName>16</fullName>
    </customValue>
    <customValue>
        <fullName>160</fullName>
    </customValue>
    <customValue>
        <fullName>17</fullName>
    </customValue>
    <customValue>
        <fullName>18</fullName>
    </customValue>
    <customValue>
        <fullName>19</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>22</fullName>
    </customValue>
    <customValue>
        <fullName>23</fullName>
    </customValue>
    <customValue>
        <fullName>24</fullName>
    </customValue>
    <customValue>
        <fullName>25</fullName>
    </customValue>
    <customValue>
        <fullName>26</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>50</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>6&amp;7</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <masterLabel>Floor</masterLabel>
</GlobalValueSet>

globalValueSets/SpaceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Shop</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Kiosk</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Office Suite</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Store Room</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Seating</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sundry Property</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Garage / Parking</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sundry</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Space Bank</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Common Mall</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>Re-design</label>
    </customValue>
    <customValue>
        <fullName>Seating License</fullName>
        <isActive>false</isActive>
        <label>Seating License</label>
    </customValue>
    <customValue>
        <fullName>Sundry Site</fullName>
        <isActive>false</isActive>
        <label>Sundry Site</label>
    </customValue>
    <masterLabel>Space Type</masterLabel>
</GlobalValueSet>

classes/OpportunityRejectApprovalTest.cls
/**
 * @author:         Kyle Tan
 * @desc:           Test class for OpportunityRejectApproval
 **/
@IsTest
private class OpportunityRejectApprovalTest {

    public static testMethod void rejectApprovalFromOpportunityTest() {
        TriggerHandler.bypass('OpportunityTriggerHandler');
        TriggerHandler.bypass('PropertyTriggerHandler');
        TriggerHandler.bypass('AccountTriggerHandler');
        TriggerHandler.bypass('SpaceTriggerHandler');
        TriggerHandler.bypass('TaskTriggerHandler');
        //Create Price Book
        List<Pricebook2> priceBookList = new List<Pricebook2>();
        priceBookList = TestDataFactory.createPricebook(1);
        database.insert(priceBookList);
        
        //Create Property
        List<Property__c> propertyList = new List<Property__c>();
        propertyList = TestDataFactory.createProperty(1, priceBookList[0]);
        database.insert(propertyList);
        
        //Create Account
        Map<String, Schema.RecordTypeInfo> accountRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(Constants.ACCOUNT);
        List<Account> accountList = new List<Account>();
        accountList = TestDataFactory.createAccountBulk(1, propertyList[0].Id, accountRecordTypeMapByName.get(Constants.PROPERTY_BASED).getRecordTypeId());
        database.insert(accountList);
        
        //Create Space
        List<Space__c> spaceList = new List<Space__c>();
        spaceList = TestDataFactory.createSpace(2, propertyList[0]);
        spaceList[1].Type__c = '4';		// Prince 4/25; Space Type: Store Room
        spaceList[1].MainFloor__c = '1';	
        spaceList[0].MainFloor__c = '1';	
        database.insert(spaceList);
        
        //Create User
        List<User> userList = new List<User>();
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :Constants.SCG_SYS_ADM LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('Pablo', 'Escobar', profileRec.Id);
        userList.add(testUser);
        User testUser2 = TestDataFactory.createUniqueTestUser('John', 'Watson', profileRec.Id);
        userList.add(testUser2);
        database.insert(userList);
        
        //Create Opportunity
        Map<String, Schema.RecordTypeInfo> oppRecordTypeMapByName = RecordTypeUtil.getAllRecordTypesByName(Constants.OPPORTUNITY);
        List<Opportunity> oppList = new List<Opportunity>();
        oppList = TestDataFactory.createOpportunity(1, accountList[0], propertyList[0], spaceList[0]);
        oppList[0].RecordTypeId = oppRecordTypeMapByName.get(Constants.OPP_RETAIL_LEASING).getRecordTypeId();
        oppList[0].RMLARS__c = userList[1].Id;
        //oppList[0].ApprovalStatus__c = 'Final Approval Rejected';
        database.insert(oppList);
        
		// --- 4/16/19
		// Create Property Team
		Map<String, Schema.RecordTypeInfo> propTeamRecordTypeByDevName = RecordTypeUtil.getAllRecordTypesByDeveloperName(Constants.PROPERTY_TEAM_API);
        Schema.RecordTypeInfo internalTeamMember = propTeamRecordTypeByDevName.get(Constants.PRT_INTERNAL_TEAM_MEMBER_API);
        PropertyTeam__c propertyTeam = TestDataFactory.createPropertyTeam(propertyList[0].Id, Constants.TEAM_ROLE_REV_ADMIN, userList[0].Id, internalTeamMember.getRecordTypeId());
        propertyTeam.StartDate__c = date.today().addYears(-1);
        propertyTeam.EndDate__c = date.today().addYears(1);        
        database.insert(propertyTeam);   
        
        // --- 4/22/19
        // Create Task
        Task opptyTask = new Task();
        opptyTask.Opportunity__c = oppList[0].Id;
        opptyTask.WhatId = oppList[0].Id;
        opptyTask.Status = Constants.COMPLETED;
        opptyTask.TaskType__c = Constants.TASK_TYPE_INSTRUCT_SOLICITOR;
        database.insert(opptyTask);
        // ---
    
        Map<Id, Opportunity> oppMap = new Map<Id, Opportunity>([SELECT SpecialityLeaseType__c,ApprovalStatus__c,RecordTypeId,RMLARS__c,Id FROM Opportunity order by createddate desc limit 1]);
        List<Id> oppListId = new List<Id>();
        oppListId.addAll(oppMap.keySet());
        //system.assertnotequals(oppMap.values(),oppMap.values());
        //Create Approval Process
        Approval.ProcessSubmitRequest approvalRequest = new Approval.ProcessSubmitRequest();
        approvalRequest.setComments('Submitting request for approval.');
        approvalRequest.setObjectId(oppListId[0]);
        approvalRequest.setProcessDefinitionNameOrId('RetailInitialApproval_v2');
        
        system.runAs(testUser) {
            Approval.ProcessResult result = Approval.process(approvalRequest);   
            OpportunityRejectApproval.rejectApprovalFromOpportunity(oppListId);
        }
    }
}