objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>HoldingCompaniesName__c</fullName>
        <description>This field is used to store conactinated holding company name from propery ownership records.</description>
        <label>Holding Companies Name</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Tech_ConcatenatedAccountACN__c</fullName>
        <label>Tech_ConcatenatedAccountACN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tech_ConcatenatedHoldingCompanyName__c</fullName>
        <label>Tech_ConcatenatedHoldingCompanyName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PropertyOwnership__c.object
<CustomObject>
    <description>&lt;POW&gt; - Represents ownership of a property with JV partners and bank guarantee entities</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Property Ownerships</relationshipLabel>
        <relationshipName>Property_Ownerships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HoldingCompanyName__c</fullName>
        <label>Holding Company Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Property Ownerships</relationshipLabel>
        <relationshipName>Property_Ownerships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Trust</fullName>
                </value>
                <value>
                    <fullName>JV</fullName>
                </value>
                <value>
                    <fullName>Head Lease / Managed Centre</fullName>
                </value>
                <value>
                    <fullName>Managed Centre</fullName>
                </value>
                <value>
                    <fullName>Bank Guarantee Entity</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property Ownership</label>
    <nameField>
        <displayFormat>PRO-{0000}</displayFormat>
        <label>Property Ownership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Ownerships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PropertyOwnershipBL.cls
public class PropertyOwnershipBL {
    
    /*
     *  @author:        Kyle Tan
     *  @parameters:    propertyIdSet       - contains the property of the property ownership records
     *  @description:   This method populates the Tech_ConcatenatedHoldingCompanyName__c and Tech_ConcatenatedAccountACN__c
     *                  of the property.It would contain the concatenated HoldingCompanyName__c and Accounts ACN of all of its 
     *                  property ownership that has the type as 'Bank Guarantee Entity'.
     */
    public static Map<Id, Property__c> buildPropertyToUpdateMap(Set<Id> propertyIdSet){
        System.debug('propertyIdSet' + propertyIdSet.size());
        Map<Id, List<PropertyOwnership__c>> propertyChildMap = new Map<Id, List<PropertyOwnership__c>>();
        Map<Id, Property__c> propertyToUpdateMap = new Map<Id, Property__c>();
        Integer propertyOwnershipSize = 0;
        Integer counter = 0;
        String conHoldingCompanyName='';
        String conAccountACN;
        
        propertyToUpdateMap = new Map<Id, Property__c>(DatabaseSOQLBank.getProperty(propertyIdSet));
        
        for(PropertyOwnership__c propertyOwnershipRec : DatabaseSOQLBank.getPropertyOwnership(propertyIdSet)) {
            if(propertyChildMap.containsKey(propertyOwnershipRec.Property__c)) {
                propertyChildMap.get(propertyOwnershipRec.Property__c).add(propertyOwnershipRec);
            } else {
                propertyChildMap.put(propertyOwnershipRec.Property__c, new List<PropertyOwnership__c>{propertyOwnershipRec});
            }
        }
        
        for(Id propertyChildMapId : propertyChildMap.keySet()) {
            propertyOwnershipSize = propertyChildMap.get(propertyChildMapId).size();
            for(PropertyOwnership__c propertyOwnershipRec : propertyChildMap.get(propertyChildMapId)) {
                counter++;
                if(String.isNotBlank(propertyOwnershipRec.HoldingCompanyName__c)) {
                    if(String.isEmpty(conHoldingCompanyName)) {
                        conHoldingCompanyName = propertyOwnershipRec.HoldingCompanyName__c;
                    } else if(counter == propertyOwnershipSize) {
                        conHoldingCompanyName = conHoldingCompanyName + Constants.BLANK_SPACE + Constants.CONCATENATE_AND +  propertyOwnershipRec.HoldingCompanyName__c;
                    } else {
                        conHoldingCompanyName = conHoldingCompanyName + Constants.COMMA + propertyOwnershipRec.HoldingCompanyName__c;
                    }
                }
                if(String.isNotBlank(propertyOwnershipRec.Account__r.ACN__c)) {
                    if(propertyOwnershipRec.Type__c == CONSTANTS.BANK_GUARANTEE_ENTITY){
                        if(String.isEmpty(conAccountACN)) {
                            conAccountACN = propertyOwnershipRec.Account__r.Name + Constants.DASH + propertyOwnershipRec.Account__r.ACN__c;
                        } else if(counter == propertyOwnershipSize) {
                            conAccountACN = conAccountACN + Constants.BLANK_SPACE + Constants.CONCATENATE_AND + propertyOwnershipRec.Account__r.Name + Constants.DASH + propertyOwnershipRec.Account__r.ACN__c;
                        } else {
                            conAccountACN = conAccountACN + Constants.COMMA + propertyOwnershipRec.Account__r.Name + Constants.DASH + propertyOwnershipRec.Account__r.ACN__c;
                        }
                    }
                }
            }
            propertyToUpdateMap.get(propertyChildMapId).Tech_ConcatenatedHoldingCompanyName__c = conHoldingCompanyName;
			propertyToUpdateMap.get(propertyChildMapId).HoldingCompaniesName__c = conHoldingCompanyName;
            propertyToUpdateMap.get(propertyChildMapId).Tech_ConcatenatedAccountACN__c = conAccountACN;
            conHoldingCompanyName = '';
        }
        
        return propertyToUpdateMap;
    }
}