objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>PropertyState__c</fullName>
        <label>Property State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/copyPropertyStateOnOpportunityBatch.cls
global class copyPropertyStateOnOpportunityBatch implements Database.Batchable<sObject>, Database.Stateful {
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT ID, Space__c, Property__c, Space__r.Property__r.PropertyState__c FROM Opportunity WHERE Space__c != null'
        );
    }
    
    global void execute(Database.BatchableContext bc, List<Opportunity> scope){
        List<Opportunity> oppListToUpdate = new List<Opportunity>();
        for(Opportunity opp : scope){
            if(opp.Space__c != null && opp.space__r.Property__c != null && opp.space__r.Property__r.PropertyState__c != null)
            {
                opp.Tech_PropertyState__c = opp.Space__r.Property__r.PropertyState__c;
                oppListToUpdate.add(opp);
            }
        }
        update oppListToUpdate;
    }
    
    global void finish(Database.BatchableContext bc){
        
    }   
}