objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <fields>
        <fullName>PropertyOwnershipType__c</fullName>
        <label>Property Ownership Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>OwnershipType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>At Risk</fullName>
                </value>
                <value>
                    <fullName>Held</fullName>
                </value>
                <value>
                    <fullName>Trading</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SpaceType</valueSetName>
        </valueSet>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/OwnershipType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Fully Owned</fullName>
    </customValue>
    <customValue>
        <fullName>JV Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Managed</fullName>
    </customValue>
    <masterLabel>Ownership Type</masterLabel>
</GlobalValueSet>

globalValueSets/SpaceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Shop</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Kiosk</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Office Suite</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Store Room</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Seating</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Sundry Property</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Garage / Parking</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Sundry</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Space Bank</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Common Mall</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>Re-design</label>
    </customValue>
    <customValue>
        <fullName>Seating License</fullName>
        <isActive>false</isActive>
        <label>Seating License</label>
    </customValue>
    <customValue>
        <fullName>Sundry Site</fullName>
        <isActive>false</isActive>
        <label>Sundry Site</label>
    </customValue>
    <masterLabel>Space Type</masterLabel>
</GlobalValueSet>

classes/CreateForecastOpportunity.cls
public class CreateForecastOpportunity {
    
    public static void checkSpaceCriteria(List<Space__c> spaceList){
        Map<Id, List<Account>> propertyIdVsAccount = new Map<Id, List<Account>>();
        List<Opportunity> forecastOpptysToCreate = new List<Opportunity>();
        Set<Id> propertyId = new Set<Id>();
        Set<Id> spaceIds = new Set<Id>();
        
        List<User> migrationUser = DatabaseSOQLBank.getdataMigrationUser();
        
        for(Space__c spc : spaceList){
            spaceIds.add(spc.Id);
            propertyId.add(spc.Property__c);                
        }
        
        for(Account forecastPropertyAccs : DatabaseSOQLBank.getForecastAccountForProperty(propertyId)){
            if(propertyIdVsAccount.containsKey(forecastPropertyAccs.Property__c)){
                propertyIdVsAccount.get(forecastPropertyAccs.Property__c).add(forecastPropertyAccs);
            }else{
                propertyIdVsAccount.put(forecastPropertyAccs.Property__c, new List<Account>());
                propertyIdVsAccount.get(forecastPropertyAccs.Property__c).add(forecastPropertyAccs);
            }
        }
        
        Id oppCommId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Commercial Leasing').getRecordTypeId();
        Id oppRetId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Retail Leasing').getRecordTypeId();
        
        for(Space__c spc : spaceList){
            if(spc.Status__c == Constants.SPACE_STATUS_INACTIVE || spc.Status__c == Constants.SPACE_STATUS_HELD){
                continue;
            }else if(spc.Type__c != '1' && spc.Type__c != '2' && spc.Type__c != '3'){
                continue;
            }else{
                Id accountId;
                
                System.debug('propertyIdVsAccount: '+propertyIdVsAccount);
                if(propertyIdVsAccount.size() == 0 || propertyIdVsAccount.get(spc.Property__c).size() == 0)
                    continue;
                
                if(propertyIdVsAccount.get(spc.Property__c).size() == 1){
                    accountId = propertyIdVsAccount.get(spc.Property__c)[0].Id;
                }else if(propertyIdVsAccount.get(spc.Property__c).size() > 1){
                    for(Account acc : propertyIdVsAccount.get(spc.Property__c)){
                        if(acc.Property__r.PropertyOwnershipType__c == Constants.MANAGED)
                            accountId = acc.Id;
                    }
                }
                
                Opportunity newForecastOppty = new Opportunity();
                newForecastOppty.Name = 'Test 1';
                newForecastOppty.Space__c = spc.Id;
                newForecastOppty.Property__c = spc.Property__c;
                newForecastOppty.AccountId = accountId;
                newForecastOppty.StageName = Constants.UNDERSTAND_NEGOTIATE;
                newForecastOppty.DealType__c = Constants.DEALTYPE_SEMI_GROSS;
                newForecastOppty.BestBet__c = FALSE;
                newForecastOppty.CloseDate = Date.newInstance(Date.today().year(), 12, 31);
                newForecastOppty.ProposedHandoverDate__c = Date.newInstance(Date.today().year(), 12, 31);
                newForecastOppty.OwnerId = migrationUser[0].Id;
                newForecastOppty.Created_from_Space_Creation__c = TRUE;
                
                if(spc.Type__c == '1' || spc.Type__c == '2')
                    newForecastOppty.RecordTypeId = oppRetId;
                else if(spc.Type__c == '3')
                    newForecastOppty.RecordTypeId = oppCommId;
                
                forecastOpptysToCreate.add(newForecastOppty);                
            }
        }
        
        if(forecastOpptysToCreate.size() > 0)
            Database.insert(forecastOpptysToCreate, FALSE);
    }
}