objects/Property__c.object
<CustomObject>
    <description>&lt;PRO&gt; - Used to capture the list of Scentre Group Shopping Centres</description>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PropertyMaps__c.object
<CustomObject>
    <fields>
        <fullName>Floor__c</fullName>
        <label>Floor</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Floor</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Property Maps</relationshipLabel>
        <relationshipName>PropertyMaps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>Property Maps</label>
    <nameField>
        <label>Property Maps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>MainFloor__c</fullName>
        <label>Main Floor</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Floor</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Floor.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>0001</fullName>
    </customValue>
    <customValue>
        <fullName>0002</fullName>
    </customValue>
    <customValue>
        <fullName>0003</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <customValue>
        <fullName>13</fullName>
    </customValue>
    <customValue>
        <fullName>14</fullName>
    </customValue>
    <customValue>
        <fullName>15</fullName>
    </customValue>
    <customValue>
        <fullName>16</fullName>
    </customValue>
    <customValue>
        <fullName>160</fullName>
    </customValue>
    <customValue>
        <fullName>17</fullName>
    </customValue>
    <customValue>
        <fullName>18</fullName>
    </customValue>
    <customValue>
        <fullName>19</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>22</fullName>
    </customValue>
    <customValue>
        <fullName>23</fullName>
    </customValue>
    <customValue>
        <fullName>24</fullName>
    </customValue>
    <customValue>
        <fullName>25</fullName>
    </customValue>
    <customValue>
        <fullName>26</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>50</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>6&amp;7</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <masterLabel>Floor</masterLabel>
</GlobalValueSet>

classes/PropertyMapsTriggerHandlerTest.cls
/**
 * @author:			Kyle Tan
 * @desc:			Test class for PropertyMapsTriggerHandler
 **/
@isTest
private class PropertyMapsTriggerHandlerTest {

    @testSetup
    private static void testSetup() {
        //Create Price Book
        List<Pricebook2> priceBookList = new List<Pricebook2>();
        priceBookList = TestDataFactory.createPricebook(1);
        database.insert(priceBookList);
        
        //Create Property
        List<Property__c> propertyList = new List<Property__c>();
        propertyList = TestDataFactory.createProperty(1, priceBookList[0]);
        database.insert(propertyList);
        
        //Create Space
        List<Space__c> spaceList = new List<Space__c>();
        spaceList = TestDataFactory.createSpace(1, propertyList[0]);
        spaceList[0].MainFloor__c = '1';
        database.insert(spaceList);
    }
    
    /**
     * @author:			Kyle Tan
     **/
    @isTest
    private static void insertPropertyMaps() {
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SCG_SYS_ADM LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        List<Property__c> propertyList = new List<Property__c>([SELECT Id FROM Property__c]);
        List<PropertyMaps__c> propertyMapsList = new List<PropertyMaps__c>();
        propertyMapsList.addAll(TestDataFactory.createPropertyMaps(1, propertyList[0].Id));
        system.runAs(testUser) {
            test.startTest();
            database.insert(propertyMapsList);
            test.stopTest();
        }
    }
    
    /**
     * @author:			Kyle Tan
     **/
    @isTest
    private static void updatePropertyMaps() {
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SCG_SYS_ADM LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        List<Property__c> propertyList = new List<Property__c>([SELECT Id FROM Property__c]);
        List<PropertyMaps__c> propertyMapsList = new List<PropertyMaps__c>();
        propertyMapsList.addAll(TestDataFactory.createPropertyMaps(1, propertyList[0].Id));
        database.insert(propertyMapsList);
        propertyMapsList = [SELECT Id, URL__c FROM PropertyMaps__c];
        propertyMapsList[0].URL__c = 'test@email.com.svg';
        propertyMapsList[0].Floor__c = '1';
        system.runAs(testUser) {
            test.startTest();
            TriggerHandler.clearAllBypasses();
            database.update(propertyMapsList);
            TriggerHandler.clearAllBypasses();
            database.delete(propertyMapsList[0]);
            test.stopTest();
        }
    }
    
    /**
     * @author:			Kyle Tan
     **/
    @isTest
    private static void deletePropertyMaps() {
        Profile profileRec = [SELECT Id FROM Profile WHERE Name = :CONSTANTS.SCG_SYS_ADM LIMIT 1];
        User testUser = TestDataFactory.createUniqueTestUser('John', 'Doe', profileRec.Id);
        List<Property__c> propertyList = new List<Property__c>([SELECT Id FROM Property__c]);
        List<PropertyMaps__c> propertyMapsList = new List<PropertyMaps__c>();
        propertyMapsList.addAll(TestDataFactory.createPropertyMaps(1, propertyList[0].Id));
        database.insert(propertyMapsList);
        propertyMapsList = [SELECT Id FROM PropertyMaps__c];
        system.runAs(testUser) {
            test.startTest();
            TriggerHandler.clearAllBypasses();
            database.delete(propertyMapsList[0]);
            test.stopTest();
        }
    }
}