objects/Space__c.object
<CustomObject>
    <description>&lt;SPA&gt; - Represents a space that is leased to a retailer ie. Shop, Office, Kiosk or a space configured for a future purpose such as splits and mergers</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_Of_Space_Groups__c</fullName>
        <label>No. Of Space Groups</label>
        <summaryFilterItems>
            <field>SpaceGroup__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>SpaceGroup__c.ParentSpace__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <description>Parent
Child</description>
        <label>Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Relationship</valueSetName>
        </valueSet>
    </fields>
    <label>Space</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SpaceBudgetAndForecast__c.object
<CustomObject>
    <description>&lt;SBF&gt; - Represents approved annualised amount for budget for CY and JV FY and forecast periods</description>
    <fields>
        <fullName>Batch_Process_Status_Reason__c</fullName>
        <label>Batch Process Status Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Batch_Process_Status__c</fullName>
        <label>Batch Process Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Not Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <inlineHelpText>The effective date is the year the budget relates to.</inlineHelpText>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ModelType__c</fullName>
        <label>Model Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Budget</fullName>
                </value>
                <value>
                    <fullName>JV Budget</fullName>
                </value>
                <value>
                    <fullName>Forecast</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <label>Space</label>
        <referenceTo>Space__c</referenceTo>
        <relationshipLabel>Space Budget and Forecast</relationshipLabel>
        <relationshipName>Space_Budget_and_Forecast</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Space Budget and Forecast</label>
    <nameField>
        <label>Space Budget and Forecast Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Space Budget and Forecast</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SpaceBudgetFieldModelType__mdt.object
<CustomObject>
    <description>This metadata will contain the mapping of Space Budget field on Space object with their business Meaning.
This will also store the Space Budget fields on space which are required for splitting and merging.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Space_Budget_Field_API_Name__c</fullName>
        <description>This field will store the API name of the space budget field on Space.</description>
        <label>Space Budget Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SpaceBudgetFieldModelType</label>
    <pluralLabel>SpaceBudgetFieldModelTypes</pluralLabel>
</CustomObject>

globalValueSets/Relationship.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Parent</fullName>
    </customValue>
    <customValue>
        <fullName>Child</fullName>
    </customValue>
    <customValue>
        <fullName>-None-</fullName>
        <default>true</default>
        <label>-None-</label>
    </customValue>
    <masterLabel>Relationship</masterLabel>
</GlobalValueSet>

classes/SpaceManagementBatch.cls
/*------------------------------------------------------------------------------------
Author:      Aakash Soor
Company:     Arxxus Technology Partners
Description: This batch class is responsible for creating budget records for child spaces
Test Class:  
History
Date            Author             Comments
--------------------------------------------------------------------------------------
04-12-2019      Aakash Soor        Initial Release
--------------------------------------------------------------------------------------*/
global without sharing class SpaceManagementBatch implements Database.Batchable<sObject>, Database.Stateful{

    public Set<Id> processedSpaceIds = new Set<Id>();
    public static SpaceManagementBatchHelper helper = new SpaceManagementBatchHelper();
    public static Map<String,String> budgetFieldApiNameVsModelType = new Map<String,String>();
    public static Map<String,Schema.SObjectField> spaceObjectSchema = Schema.SObjectType.Space__c.fields.getMap();

    global SpaceManagementBatch(){}
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([SELECT Id, Space__c, Space__r.Active__c, Space__r.Relationship__c, EffectiveDate__c,ModelType__c,
                                                Space__r.No_Of_Space_Groups__c
                                         FROM SpaceBudgetAndForecast__c 
                                         WHERE Space__r.Active__c = true
                                         AND Space__r.Relationship__c !=: Constants.SPACE_REL_CHILD
                                         AND Batch_Process_Status__c IN ('New','Pending')
                                         ORDER BY EffectiveDate__c,CreatedDate DESC]);   
    }

    global void execute(Database.BatchableContext BC, List<SpaceBudgetAndForecast__c> spaceBudgetList){
        ErrorHandlerUtil errorHandler = new ErrorHandlerUtil(SpaceManagementBatch.class.getName());
        Map<Id,Space__c> spacesToUpdate = new Map<Id,Space__c>();
        Map<Id,SpaceBudgetAndForecast__c> statusUpdateSpaceBudgets = new Map<Id,SpaceBudgetAndForecast__c>();
        Set<Id> parentSpaceIds;
        List<SpaceBudgetAndForecast__c> childSpaceBudgetToInsert = new List<SpaceBudgetAndForecast__c>();
        List<SpaceBudgetAndForecast__c> spaceBudgetForLinking = new List<SpaceBudgetAndForecast__c>();

        for(SpaceBudgetFieldModelType__mdt sbfm : [SELECT MasterLabel, Space_Budget_Field_API_Name__c
                                                    FROM SpaceBudgetFieldModelType__mdt
                                                    WHERE Active__c = true]){
            budgetFieldApiNameVsModelType.put(sbfm.Space_Budget_Field_API_Name__c, sbfm.MasterLabel);
        }
        
        Map<String, List<SpaceBudgetAndForecast__c>> spaceBudgetMap =  helper.updateSpaceBudgetBatchStatus(spaceBudgetList);
        
        try{
            update spaceBudgetMap.get('All');
            if(!spaceBudgetMap.get('NotProcessed').isEmpty()) spaceBudgetForLinking = spaceBudgetMap.get('NotProcessed');

            if(!spaceBudgetMap.get('Pending').isEmpty()){

                String query = helper.getQuery();

                parentSpaceIds = helper.getParentSpaceIds(spaceBudgetMap.get('Pending'), processedSpaceIds);
                processedSpaceIds.addAll(parentSpaceIds);
                List<Space__c> parentSpaces = Database.Query(query);

                Map<Decimal, SpaceManagementController.SpaceBudgetWrapper> sbWrappers = helper.prepareSpaceBudgetWrapper(parentSpaces, budgetFieldApiNameVsModelType);

                for(SpaceManagementController.SpaceBudgetWrapper sbWrapper : sbWrappers.values()){
                    childSpaceBudgetToInsert.addAll(SpaceManagementController.createSpaceBudget(sbWrapper));
                    spacesToUpdate.putAll(sbWrapper.parentSpaces);
                }

                List<Database.SaveResult> saveResults = Database.insert(childSpaceBudgetToInsert,false);
                Integer count = 0;
                Set<Id> processedParentSpaceIds = new Set<Id>();
                for(Database.SaveResult saveResult : saveResults){    
                    if(!saveResult.isSuccess()){
                        for(SpaceManagementController.SpaceBudgetWrapper sbWrapper : sbWrappers.values()){
                            if(sbWrapper.childSpaces.containsKey(childSpaceBudgetToInsert[count].Space__c)){
                                for(SpaceBudgetAndForecast__c sbf : sbWrapper.spaceBudgetMap.values()){
                                    sbf.Batch_Process_Status__c = 'Failed';
                                    sbf.Batch_Process_Status_Reason__c = JSON.serialize(saveResult.getErrors()).left(255);
                                    if(!statusUpdateSpaceBudgets.containsKey(sbf.Id)) statusUpdateSpaceBudgets.put(sbf.Id,sbf);
                                    processedParentSpaceIds.add(sbf.Space__c);
                                }
                                break;
                            }
                        }
                    }else{
                        Set<Id> parentSpaceIdTemp = new Set<Id>(processedParentSpaceIds);
                        for(SpaceManagementController.SpaceBudgetWrapper sbWrapper : sbWrappers.values()){
                            parentSpaceIdTemp.retainAll(sbWrapper.parentSpaces.keySet());
                            if(parentSpaceIdTemp.isEmpty()
                                && sbWrapper.childSpaces.containsKey(childSpaceBudgetToInsert[count].Space__c)){
                                for(SpaceBudgetAndForecast__c sbf : sbWrapper.spaceBudgetMap.values()){
                                    if(!statusUpdateSpaceBudgets.containsKey(sbf.Id)){
                                        sbf.Batch_Process_Status__c = 'Success';
                                        statusUpdateSpaceBudgets.put(sbf.Id,sbf);
                                    }
                                }
                                break;
                            }
                        }
                    }    
                    count++;
                }
            }
			
            spaceBudgetForLinking.addAll(childSpaceBudgetToInsert);
            spacesToUpdate.putAll(helper.updateSpaceWithLatestBudget(spaceBudgetForLinking, budgetFieldApiNameVsModelType, spaceObjectSchema));

            TriggerHandler.bypass('SpaceTriggerHandler');
            if(!spacesToUpdate.isEmpty()) update spacesToUpdate.values();
            if(!statusUpdateSpaceBudgets.isEmpty()) update statusUpdateSpaceBudgets.values();
        }catch(Exception e){
            system.debug('Exception------'+e.getLineNumber()+'--------'+e.getStackTraceString());
            errorHandler.createError(e);
        }

        errorHandler.save();
    }
    
    global void finish(Database.BatchableContext BC){}
}